java_console/io/src/main/java/com/rusefi/io/LinkManager.java

With this changes JC is reconnecting after the 5s timeout (as planned???)

Java Console reconnection fixing (by issue #3305)

---

.github/workflows/build-firmware.yaml

This should satisfy #3739
@rusefillc Note that I didn't use the bash script you wrote. This allows us to do the "dice roll" before checking out the repo.

Randomly skip firmware build jobs

---

firmware/config/boards/proteus/connectors/black23.yaml
misc/pinout-gen/pinout.html
misc/pinout-gen/script.js
misc/pinout-gen/style.css

https://github.com/rusefi/rusefi_documentation/issues/196
This requires both board_url and title values in the yaml.
The board_url must be in a yaml file that also has the title.
Result:

Pinout link

---

firmware/controllers/engine_cycle/rpm_calculator.cpp

With this option on, we get stuck in cranking mode.
#3815

fix always instant rpm option

---

firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp
firmware/tunerstudio/rusefi.input

Raw map and ego gauges

---

firmware/config/boards/hellen/hellen128/connectors/main.yaml

Added RevC aux test points.
Corrected minor typos

Hellen128yaml update

---

firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp
firmware/controllers/algo/algo.mk
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_state.h
firmware/controllers/algo/fuel/dfco.cpp
firmware/controllers/algo/fuel/dfco.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
firmware/tunerstudio/rusefi.input

No logic change yet, just refactoring code in to its own place.
#3820

refactor decel fuel cut

---

firmware/controllers/algo/fuel/dfco.cpp
firmware/integration/rusefi_config.txt
unit_tests/tests/ignition_injection/test_fuelCut.cpp

dfco checks driver throttle intent

---

firmware/controllers/trigger/trigger_central.h

#3806
fix bug caused by 9f5188bf305a2327f957548759e9606f9b3cccfa

fix engineMovedRecently

---

firmware/controllers/sensors/frequency_sensor.cpp
firmware/controllers/sensors/frequency_sensor.h
firmware/init/sensor/init_flex.cpp
firmware/init/sensor/init_turbocharger_speed_sensor.cpp
firmware/init/sensor/init_vehicle_speed_sensor.cpp
unit_tests/tests/sensor/test_frequency_sensor.cpp

VSS looks pretty noisy on logs like this, let's filter it!

vss and flex are filtered

---

firmware/controllers/algo/engine.h
firmware/controllers/algo/wall_fuel.cpp
firmware/controllers/algo/wall_fuel.h
unit_tests/tests/ignition_injection/test_fuel_wall_wetting.cpp

extract calculation of alpha/beta out of the per-injection logic and move it to the asynchronous periodic logic

extract logic from wall wetting AE

---

firmware/console/binary/output_channels.txt
firmware/controllers/algo/accel_enrichment.cpp
firmware/tunerstudio/rusefi.input

log more tps accel data

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/math/speed_density.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Add a mode to do charge temperature estimation based on a table, instead of linear interpolation.

table for tcharge interpolation

---

simulator/Makefile

the simulator is gigantic, 2/3 of a bundle 😮

make the simulator smaller

---

firmware/controllers/actuators/main_relay.cpp
firmware/util/containers/type_list.h

fix delayedShutoffRequested `aggregate` magic

delayedShutoffRequested

---

firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/engine_parts.h
firmware/integration/rusefi_config.txt
unit_tests/tests/trigger/test_trigger_decoder.cpp

Whatever this was supposed to do we clearly don't need since startup is really good these days.

dead StartupFuelPumping

---

firmware/config/boards/hellen/alphax-2chan/board_configuration.cpp
firmware/config/boards/proteus/board_configuration.cpp
firmware/hw_layer/ports/stm32/stm32_common.cpp
firmware/hw_layer/ports/stm32/stm32f4/mpu_util.cpp

fix https://github.com/rusefi/alphax-2chan/issues/22
Tested with both TJA1051 and TJA1442.

fix f4 standby

---

firmware/CHANGELOG.md
firmware/hw_layer/sensors/lps25.cpp
firmware/hw_layer/sensors/lps25.h
firmware/tunerstudio/rusefi.input

LPS22 is nearly the same as LPS25, easy to support both by identifying at runtime.

support lps22

---

java_console/ui/src/main/java/com/camick/RXTextUtilities.java
java_console/ui/src/main/java/com/rusefi/etb/StandardTestSequence.java
java_console/ui/src/main/java/com/rusefi/livedata/LiveDataParserPanel.java
java_console/ui/src/main/java/com/rusefi/sensor_logs/BinarySensorLog.java
java_console/ui/src/main/java/com/rusefi/tools/ConsoleTools.java
java_console/ui/src/main/java/com/rusefi/ui/ChartRepository.java
java_console/ui/src/main/java/com/rusefi/ui/FuelTunePane.java
java_console/ui/src/main/java/com/rusefi/ui/engine/EngineSnifferPanel.java
java_console/ui/src/main/java/com/rusefi/ui/engine/EngineSnifferStatusPanel.java
java_console/ui/src/main/java/com/rusefi/ui/light/InternetStatus.java
java_console/ui/src/main/java/com/rusefi/ui/light/LightweightGUI.java

Code cleanup items recommended by intellij. Part 1.

push the "inspect code" button in intellij

---

firmware/config/boards/core8/board.h
firmware/config/boards/core8/board.mk
firmware/config/boards/core8/board_configuration.cpp
firmware/config/boards/core8/compile_core8.bat

added board config files

---

firmware/controllers/can/can_dash.cpp

Based on AIM can protocol
https://www.aimtechnologies.com/support/racingecu/AiM_CAN_101_eng.pdf
FIxed TPS, CLT, IAT, Batt V values
Tested on real device and updated 4 values shows correct data.

AIM dash TPS, CLT,IAT, and Batt V fix

---

firmware/controllers/can/can_dash.cpp

Moved multiplier/divider to scaled_channel factor

Moved multiplier/divider to scaled_channel factor

---

misc/actions/pinouts-create.sh
misc/jenkins/generate_pinouts/gen_upload_pinouts.sh

Fail to generate pinout if there is no connector ID

---

firmware/tunerstudio/rusefi.input

TS: disable ignition and injector test according to cylindersCount

---

firmware/controllers/bench_test.cpp

Do not pass strings as arguments where possible
Do not use strings as temp variables to store floats

Bench test clean

---

firmware/config/stm32f4ems/efifeatures.h

We have memory available, let's blow it on LUAAAAAAA!

embiggen lua space

---

firmware/tunerstudio/rusefi.input

https://github.com/rusefi/rusefi/commit/bd90fe86bb3c69a3f5a45d21e442247def4f533f

please test TS before push TS changes

---

firmware/console/binary/output_channels.txt
firmware/controllers/bench_test.cpp
firmware/tunerstudio/rusefi.input

This is preparation to implement TS dialog where user can define on time, off time and iteration count for injector test.

Test bench: implement injector test for dead time calculation

---

firmware/console/binary/output_channels.txt
firmware/console/binary_log/binary_logging.cpp

- log cut reasons
- log wall fuel amount

sd log tweaks

---

firmware/controllers/can/can_listener.h
unit_tests/tests/test_can_rx.cpp
unit_tests/tests/tests.mk

carve off a piece of #4000, write tests!

break out acceptFrame, test CanListener

---

java_console/io/src/test/java/com/rusefi/native_/JniUnitTest.java
unit_tests/engine_test_helper.cpp

gtest in library is hard

---

firmware/controllers/core/error_handling.h
firmware/controllers/math/engine_math.cpp
firmware/controllers/math/engine_math.h
firmware/controllers/trigger/decoders/trigger_nissan.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/hw_layer/pin_repository.cpp
firmware/util/efilib.h

mostly around signed vs. unsigned comparisons

warnings cleanup

---

firmware/console/binary/output_channels.txt
firmware/console/binary_log/log_fields_generated.h
firmware/controllers/actuators/alternator_controller.cpp
firmware/controllers/actuators/boost_control.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/vvt.cpp
firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/limp_manager.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
firmware/util/math/efi_pid.cpp
firmware/util/math/efi_pid.h

- better boost controller logging
- scaled channels for PID status (saves space)
- remove dead MAP cam fields
- fix signed/unsigned and limits for a few channels
- add boost PID state
- pass pid_status_s as a ref instead of ptr
- add units/limits to some channels

output channel tweaks

---

firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp

don't get afr raw if no sensor exists

---

firmware/console/status_loop.cpp
firmware/controllers/algo/algo.mk
firmware/controllers/algo/engine.h
firmware/controllers/algo/gear_detector.cpp
firmware/controllers/algo/gear_detector.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_gear_detector.cpp
unit_tests/tests/tests.mk

progress on #3779:
- Compute gear ratio using existing wheel size field
- Make an engine module for gear detection
- Unit test gear ratio computation
- UI improvements:

Gear detection improvements

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/buttonshift.cpp
firmware/controllers/buttonshift.h
firmware/controllers/controllers.mk
firmware/controllers/engine_controller.cpp
firmware/controllers/gear_controller.cpp
firmware/controllers/gear_controller.h
firmware/controllers/simple_tcu.cpp
firmware/controllers/simple_tcu.h
firmware/controllers/tc_4l6x.cpp
firmware/controllers/tc_4l6x.h
firmware/controllers/tcu.cpp
firmware/controllers/tcu.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

I'm PRing this before continuing work because I've never built something with selectable classes before, and I'm not sure if this is the proper way to architect it.

Add interface for selecting GearController and TransmissionController classes

---

firmware/config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml

pin selection for VVT pin missing from TS.

VVT TS Pin missing

---

firmware/controllers/algo/gear_detector.cpp
unit_tests/tests/test_gear_detector.cpp

Validate gear detection parameters.
#3779

gear detection validation

---

firmware/controllers/sensors/frequency_sensor.cpp
firmware/controllers/sensors/frequency_sensor.h
firmware/init/sensor/init_aux_speed_sensor.cpp
firmware/init/sensor/init_flex.cpp
firmware/init/sensor/init_turbocharger_speed_sensor.cpp
firmware/init/sensor/init_vehicle_speed_sensor.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/sensor/test_frequency_sensor.cpp

- adjust FrequencySensor so we can adjust filter parameter after construction
- Write a better tooltip
- Use a uint8_t instead of float

make the vss fliter parameter work again

---

firmware/integration/rusefi_config.txt
firmware/rusefi.cpp
firmware/tunerstudio/rusefi.input

Review would be appreciated, this reflects my workflow, but it might not reflect everyone's.

overhaul some docs surrounding rusefi_config.txt

---

firmware/console/binary/tunerstudio_io.cpp

does this assert fail?

---

firmware/console/binary/output_channels.txt
firmware/controllers/buttonshift.h
firmware/controllers/engine_controller.cpp
firmware/controllers/gear_controller.cpp
firmware/controllers/gear_controller.h
firmware/controllers/simple_tcu.h
firmware/controllers/system/efi_gpio.h
firmware/controllers/tc_4l6x.cpp
firmware/controllers/tc_4l6x.h
firmware/controllers/tcu.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Added pressure control solenoid PWM % curves - currently only the steady state is used
Fixed gear gauge issue
Fixed class init bug
Added frequency field for TCC PWM solenoid
Added some fields for 3-2 solenoid
Moved some tables out of engine_configuration_s
Made fields only be visible if they're used by the selected gear or transmission controller

TCU features and fixes

---

.github/workflows/hardware-ci.yaml

hw ci calls gen_config_board.sh

---

firmware/integration/rusefi_config.txt

missed e85 cranking autoscale

---

firmware/controllers/sensors/frequency_sensor.cpp
firmware/init/sensor/init_input_shaft_speed_sensor.cpp
firmware/init/sensor/init_vehicle_speed_sensor.cpp
firmware/util/math/biquad.cpp
unit_tests/tests/sensor/test_frequency_sensor.cpp

fix vss/iss filter parameter validation

---

firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/airmass/speed_density_airmass.cpp
firmware/controllers/algo/defaults/default_fuel.cpp
firmware/controllers/algo/defaults/default_ignition.cpp
firmware/controllers/algo/fuel/injector_model.cpp
firmware/controllers/engine_cycle/knock_logic.cpp
firmware/controllers/math/closed_loop_fuel.cpp
firmware/controllers/math/closed_loop_fuel_cell.cpp
firmware/controllers/math/engine_math.cpp
firmware/integration/rusefi_config.txt
unit_tests/tests/ignition_injection/test_fuel_math.cpp
unit_tests/tests/ignition_injection/test_injector_model.cpp
unit_tests/tests/ignition_injection/test_multispark.cpp
unit_tests/tests/test_knock.cpp
unit_tests/tests/test_stft.cpp

there are more like #4105 
fixes #4067

more missing autoscale

---

firmware/config/boards/hellen/cypress/rusefi_hw_enums.h
firmware/config/boards/kinetis/rusefi_hw_enums.h
firmware/config/boards/subaru_eg33/rusefi_hw_enums.h
firmware/controllers/algo/rusefi_hw_enums.h
firmware/integration/rusefi_config.txt
java_console/ui/src/test/java/com/rusefi/FullServerTest.java
unit_tests/tests/test_cpp_memory_layout.cpp

Code generator was improved in master, making pin two byte should be a trivial affair now

2 byte pin index #4097

---

firmware/config/boards/hellen/hellen72/connectors/main.yaml

options port

---

firmware/controllers/algo/engine.cpp

clarify doesTriggerImplyOperationMode

---

firmware/console/binary/serial_can.cpp
firmware/controllers/can/can_dash.cpp
firmware/controllers/can/can_verbose.cpp
firmware/controllers/can/obd2.cpp
firmware/controllers/can/rusefi_wideband.cpp
firmware/controllers/lua/lua_hooks.cpp
firmware/controllers/sensors/can_sensor.h
firmware/hw_layer/drivers/can/can_msg_tx.cpp
firmware/hw_layer/drivers/can/can_msg_tx.h

introducing concept of "CAN use-case categoty" for us to facilitate code navigation and runtime statistics

CAN category

---

firmware/controllers/trigger/trigger_central.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

part of #4152, related to #4099

cam phase resolution rpm limit

---

unit_tests/tests/tests.mk
unit_tests/tests/trigger/test_trigger_decoder_2.cpp

Pull out just the tests from #4164

Proper decoder testing

---

firmware/controllers/system/timer/single_timer_executor.cpp

remove suspicious cast that could maybe cause an overflow

---

firmware/controllers/system/timer/single_timer_executor.cpp

use correct timestamp

---

firmware/config/boards/proteus/board.mk
firmware/controllers/sensors/vr_pwm.cpp

Make vr threshold work properly on Proteus.

proteus-friendly VR threshold logic

---

firmware/config/boards/core8/connectors/main.yaml

YAML updates

---

firmware/hw_layer/ports/stm32/stm32_common.cpp

pwm uses correct channels

---

firmware/controllers/trigger/decoders/trigger_universal.cpp

improved with data from real car

honda trigger sync ratio

---

firmware/controllers/trigger/trigger_central.cpp
firmware/hw_layer/digital_input/trigger/trigger_input.h
firmware/hw_layer/digital_input/trigger/trigger_input_exti.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_icu.cpp

Don't need to paste this logic everywhere, just do it once.
simplify #3032

consolidate trigger bail-out logic

---

firmware/controllers/settings.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/integration/rusefi_config.txt

remove dead useOnlyFirstChannel

---

java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/ArrayLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/BitGroupLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/ScalarLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/StringLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/StructLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/StructNamePrefixer.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/UnionLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/UnusedLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/outputs/CStructWriter.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/outputs/TsMetadata.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/outputs/TsWriter.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/parsing/Struct.java
java_tools/configuration_definition/src/test/java/com/rusefi/test/newParse/LayoutTest.java
java_tools/configuration_definition/src/test/java/com/rusefi/test/newParse/NewParseHelper.java

Mostly test the layout logic by looking at the TS output.

test new parser TS layout

---

firmware/integration/LiveData.yaml
java_tools/configuration_definition/.idea/runConfigurations/UsagesReader.xml
java_tools/configuration_definition/src/main/java/com/rusefi/ReaderState.java
java_tools/configuration_definition/src/main/java/com/rusefi/ldmp/UsagesReader.java

Let's use yaml like it was intended, instead of parsing an array (?)

use yaml like you're supposed to

---

firmware/controllers/sensors/sensor.h
firmware/init/sensor/init_tps.cpp

rewrite tps init, check if your primary/secondary sensors are too similar

---

firmware/config/boards/hellen/hellen72/board_configuration.cpp

used Hellen121 as example and assigned pins.

ETB hardcode pins

---

firmware/config/boards/hellen/hellen72/board_configuration.cpp

per recommendation, moved to override

move etb from default to override

---

firmware/integration/rusefi_config.txt
java_tools/configuration_definition/src/main/java/com/rusefi/ConfigDefinition.java
java_tools/configuration_definition/src/main/java/com/rusefi/PinoutLogic.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/ParseState.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/ScalarLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/layout/StringLayout.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/parsing/FieldOptions.java
java_tools/configuration_definition/src/main/java/com/rusefi/newparse/parsing/StringField.java

- Use double instead of float to avoid loss of precision
- Fix some config file inconsistencies that cause output differences
- Yaml parser supports new parser
- Parse enum bit count correctly

new parser TS output fixes, config file fixes

---

firmware/controllers/algo/engine.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

add option to force o2 heating

---

firmware/config/boards/hellen/alphax-2chan/board_configuration.cpp
firmware/config/boards/hellen/alphax-4chan/board_configuration.cpp
firmware/config/boards/hellen/harley81/board_configuration.cpp
firmware/config/boards/hellen/hellen-gm-e67/board_configuration.cpp
firmware/config/boards/hellen/hellen-nb1/board_configuration.cpp
firmware/config/boards/hellen/hellen121nissan/board_configuration.cpp
firmware/config/boards/hellen/hellen121vag/board_configuration.cpp
firmware/config/boards/hellen/hellen128/board_configuration.cpp
firmware/config/boards/hellen/hellen154hyundai/board_configuration.cpp
firmware/config/boards/hellen/hellen64_miataNA6_94/board_configuration.cpp
firmware/config/boards/hellen/hellen72/board_configuration.cpp
firmware/config/boards/hellen/hellen81/board_configuration.cpp
firmware/config/boards/hellen/hellen88bmw/board_configuration.cpp
firmware/config/boards/hellen/hellenNA8_96/board_configuration.cpp
firmware/config/boards/hellen_meta.h

hellen SD card presets

---

misc/pinout-gen/script.js

This should fix https://github.com/rusefi/rusefi_documentation/issues/221

always scroll when pin is clicked

---

firmware/console/binary/output_channels.txt

get rid of extra quotes in output_channels.txt

---

firmware/config/boards/hellen/hellen154hyundai/board_configuration.cpp
firmware/config/boards/hellen/hellen72/board_configuration.cpp
firmware/controllers/algo/engine_state.txt

detect SD card
https://github.com/rusefi/hellen-NB2-issues/issues/36

use detected hellen board type on h72

---

firmware/controllers/core/fsio_impl.h
firmware/integration/rusefi_config.txt

We have the space and users might want it, why not give them more space?

more generous script table axis limits

---

.github/workflows/build-firmware.yaml
firmware/Makefile
firmware/controllers/core/error_handling.cpp
firmware/controllers/core/error_handling.h
firmware/hw_layer/backup_ram.h
firmware/hw_layer/ports/cypress/backup_ram.cpp
firmware/hw_layer/ports/kinetis/backup_ram.cpp
firmware/hw_layer/ports/stm32/backup_ram.cpp
firmware/hw_layer/ports/stm32/stm32f4/STM32F4.ld
firmware/hw_layer/ports/stm32/stm32f4/cfg/mcuconf.h
firmware/hw_layer/ports/stm32/stm32f7/STM32F7.ld
firmware/hw_layer/ports/stm32/stm32f7/cfg/mcuconf.h
firmware/hw_layer/ports/stm32/stm32h7/STM32H743xI.ld
firmware/main_hardfault.c
firmware/main_hardfault_asm.S
firmware/rusefi.cpp

maybe helps us figure out #4322

Write hard faults to backup ram, print on next boot

---

firmware/CHANGELOG.md
firmware/config/engines/mazda_miata_1_6.cpp
firmware/config/engines/mazda_miata_na8.cpp
firmware/config/engines/mazda_miata_vvt.cpp
firmware/controllers/actuators/idle_thread.h
firmware/controllers/actuators/idle_thread_io.cpp
firmware/controllers/settings.cpp
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_idle_controller.cpp

Force 0 PID offset and remove the UI for it since this function is fulfilled by the open loop tables instead.
#4336

remove idle offset

---

firmware/console/binary/ts_can_channel.cpp
firmware/console/binary/tunerstudio_io_serial_ports.cpp
firmware/console/ethernet_console.cpp
firmware/console/status_loop.cpp
firmware/console/usb_console.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/vvt.cpp
firmware/controllers/bench_test.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/gauges/malfunction_indicator.cpp
firmware/controllers/lua/lua.cpp
firmware/controllers/sensors/software_knock.cpp
firmware/controllers/system/periodic_task.h
firmware/controllers/system/thread_controller.h
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/drivers/can/can_hw.cpp
firmware/hw_layer/drivers/serial/serial_hw.cpp
firmware/hw_layer/mass_storage/mass_storage_init.cpp
firmware/hw_layer/microsecond_timer/microsecond_timer.cpp
firmware/hw_layer/stepper.cpp
firmware/util/loggingcentral.cpp
misc/stm32f1_test_project/timer/microsecond_timer.cpp

piece of #4327, just rename Start -> start

Start -> start

---

firmware/Makefile
firmware/controllers/bench_test.cpp
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/stm32/stm32_common.cpp
firmware/tunerstudio/rusefi.input

Similar to "Reset to DFU", but uses different seed

Add "Reset to OpenBLT" button

---

.github/workflows/build-android.yaml

master is red,
we have two separate issues

branches are green,

---

firmware/controllers/actuators/boost_control.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

boost control thresholds

---

firmware/controllers/algo/obd_error_codes.h
firmware/controllers/bench_test.cpp
firmware/controllers/sensors/sensor_checker.cpp
firmware/controllers/sensors/sensor_checker.h
firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h

We have diag for gpiochip outputs, let's use it for something!
Encapsulate `getDiag` in to `OutputPin`.

report injector, ignition faults

---

firmware/console/binary/serial_can.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/core/error_handling.cpp
firmware/controllers/tc_4l6x.cpp
firmware/hw_layer/drivers/gpio/l9779.cpp
firmware/hw_layer/drivers/gpio/tle8888.cpp

- fix some warnings that it seems to be unable to find with link-time-optimization turned on (maybe it can detect that they're actually impossible conditions?)
- Break in to debugger in case of panic, more useful to diagnose what happened instead of wondering why your board is boot looping.

misc fixes

---

firmware/CHANGELOG.md
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h
unit_tests/tests/trigger/test_cam_vvt_input.cpp
unit_tests/tests/trigger/test_real_cranking_nissan_vq40.cpp

resolve VVT phase using every tooth, not just sync point

---

.github/workflows/build-firmware.yaml
.github/workflows/gen-configs.yaml
firmware/tunerstudio/upload_ini.sh

I'm unable to actually test this, @rusefillc want to try it first?
#4454

upload ini from firmware build

---

firmware/controllers/actuators/vvt.cpp
unit_tests/tests/actuators/test_vvt.cpp

fix inverted vvt

---

firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp
firmware/hw_layer/digital_input/digital_input_exti.cpp
firmware/hw_layer/digital_input/digital_input_exti.h

Might help narrow down trigger issues. #4459 etc

log missed exti events

---

firmware/console/binary/output_channels.txt
firmware/controllers/actuators/idle_state.txt
firmware/controllers/actuators/idle_thread.cpp

typo, coasting bit was actually cranking

fix idle typo, move bit to idle state

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.txt
firmware/tunerstudio/rusefi.input

etb rev limit indicator

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
unit_tests/mocks.h
unit_tests/tests/test_idle_controller.cpp

https://github.com/rusefi/rusefi/issues/3940

[DRAFT] Air by rpm taper

---

firmware/controllers/algo/fuel/dfco.cpp
firmware/controllers/algo/fuel/dfco.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/ignition_injection/test_fuelCut.cpp

dfco delay

---

firmware/config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml

ETB PINOUT

---

firmware/tunerstudio/rusefi.input

Rearrange gauges and categories.

Tunerstudio cleanup

---

firmware/controllers/core/state_sequence.cpp
firmware/controllers/core/state_sequence.h
firmware/controllers/lua/lua_hooks.cpp
firmware/controllers/lua/script_impl.cpp
firmware/controllers/lua/script_impl.h
firmware/controllers/trigger/decoders/trigger_structure.cpp
unit_tests/tests/ignition_injection/test_fuel_map.cpp
unit_tests/tests/lua/test_lua_with_engine.cpp

This is c++ in 2022, we have more expressive solutions than returning a magic constant

remove some uses of EFI_ERROR_CODE

---

firmware/controllers/algo/defaults/default_fuel.cpp
firmware/controllers/algo/fuel/injector_model.cpp
firmware/integration/rusefi_config.txt

Set a limit in TS, detect impossible value, and set a reasonable default.
#4503

handle bad fuel reference pressure config

---

firmware/controllers/algo/engine.h
firmware/controllers/algo/fuel/fuel_computer.h

@mck1117 can you please help? why does this red?

I am sure that's not magic

---

firmware/tunerstudio/rusefi.input

bug from #4492 @dron0gus FYI
this indicator must be EXACTLY like this
This is why this guy couldn't get the critical error: https://rusefi.com/forum/viewtopic.php?p=46203#p46203

fix critical error readout

---

firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h

We can see logic state of coils and injectors in MLV
I belive that would help troubleshoot stuff like #4477

Engine Sniffer into TS data logs fix #4535

---

firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h

reset instant RPM in case of cam resync

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary_log/binary_logging.cpp
firmware/console/status_loop.cpp
firmware/controllers/actuators/ac_control.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/engine_controller_misc.cpp
firmware/controllers/gauges/lcd_controller.cpp
firmware/controllers/lua/lua_hooks_util.cpp
firmware/controllers/math/pid_auto_tune.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/development/rfi_perftest.cpp
firmware/hw_layer/microsecond_timer/microsecond_timer.cpp
firmware/hw_layer/sensors/gps_uart.cpp
firmware/util/efitime.cpp
firmware/util/efitime.h
firmware/util/util.mk
java_console/ui/resources/c_sources/ac_control.cpp
unit_tests/global_mocks.cpp
unit_tests/tests/test_pid_auto.cpp

No logic change. Only refactor.

time routines refactor

---

firmware/config/stm32f4ems/efifeatures.h
firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp
firmware/controllers/algo/runtime_state.cpp

resurrect EFI_CLOCK_LOCKS

---

.vscode/launch.json

Now we get threads view in vscode! Thanks @dron0gus!

set rtos mode in launch config

---

firmware/CHANGELOG.md
firmware/console/binary/output_channels.txt
firmware/controllers/actuators/gppwm/gppwm_channel.h
firmware/controllers/algo/advance_map.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

For example, if you wanted to do flex fuel timing add:
#289
#3114
#3776
#3778
#4057

add ignition adder tables

---

firmware/tunerstudio/rusefi.input

wbo fault code indicator

---

firmware/config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml

I was unsure on how to proceed with the actual pin id and how duplicates would effect it.  I added this to https://github.com/rusefi/very-serious-business/issues/228 but received no answer and appear to have been removed.  Im pushing anyhow.

yaml update for NA6 MCU144

---

firmware/hw_layer/hardware.cpp
firmware/hw_layer/ports/stm32/stm32f4/cfg/mcuconf.h
firmware/hw_layer/rtc_helper.cpp
firmware/hw_layer/rtc_helper.h

code formatting, cleanup, unnecessary static variables, etc
#4556

rtc cleanup

---

firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/engine_cycle/spark_logic.h
firmware/util/efilib.cpp
firmware/util/efilib.h

tear off trivial part of #4513

plumbing for 4513

---

firmware/config/boards/microrusefi/connectors/main.yaml
misc/actions/pinouts-create.sh

This is to fix https://github.com/rusefi/rusefi_documentation/issues/236

Pinout order

---

firmware/integration/rusefi_config.txt

130 psi of boost for everyone!
Someone on Facebook with a humongous engine needs more than 400kPa MAP (!!!).

up the kPa table axis limits

---

firmware/config/engines/honda_k_dbc.cpp
firmware/controllers/trigger/decoders/trigger_honda.cpp
unit_tests/tests/trigger/test_real_k20.cpp

fix K series exhaust cam sync params #3405

k20 exhaust cam sync

---

firmware/controllers/trigger/trigger_emulator_algo.cpp

also invert trigger stim if you have trigger input inverted

---

firmware/console/binary/bluetooth.cpp
firmware/console/binary/tunerstudio.cpp

https://github.com/rusefi/rusefi/issues/4583

Bluetooth hang

---

firmware/Makefile

cherry picking -fno-inline-functions

gcc10 preparation -fno-inline-functions

---

firmware/config/stm32f4ems/efifeatures.h
firmware/hw_layer/drivers/drivers.mk
firmware/hw_layer/drivers/sent/sent.cpp
firmware/hw_layer/drivers/sent/sent.h
firmware/hw_layer/drivers/sent/sent_hw_icu.cpp
firmware/hw_layer/drivers/sent/sent_hw_icu.h
firmware/hw_layer/hardware.cpp

This PR just adds decoder and ICU-based driver code, but does not enables SENT on any of boards.

SENT core decoder and ICU driver

---

firmware/controllers/engine_controller.cpp
firmware/controllers/settings.cpp
firmware/hw_layer/adc/adc_subscription.cpp
firmware/hw_layer/adc/adc_subscription.h
java_console/ui/src/main/java/com/rusefi/ui/RecentCommands.java

fix #2517 by doing fewer confusing things

consolidate analog vs. temp info commands

---

firmware/controllers/can/can_verbose.cpp
firmware/controllers/can/rusEFI_CAN_verbose.dbc

can dbc update

---

firmware/hw_layer/adc/adc_subscription.cpp

Sensor: unregister on the fly fix #4683

Adc unregister

---

firmware/config/boards/microrusefi/connectors/main.yaml
firmware/hw_layer/drivers/sent/readme.md
firmware/hw_layer/drivers/sent/sent_hw_icu.cpp

fixes https://github.com/rusefi/rusefi/issues/4685

SENT fixes

---

firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h

constify efi_gpio, use size_t

---

firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp
firmware/controllers/algo/airmass/maf_airmass.cpp
firmware/controllers/algo/airmass/maf_airmass.h
firmware/controllers/sensors/sensor_type.h
firmware/init/sensor/init_maf.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Eventually we will operate each bank as its own fueling math, but for now we can just sum all MAF sensors and assume that you have balanced the banks with throttles or a balance tube.
progress on #3680
related #4677

dual MAF sensors

---

firmware/hw_layer/digital_input/trigger/trigger_input.cpp

No reason not to re-register/unregister every time, it's cheaper to just do it than try and debounce.
#4706

fix rpm registration

---

firmware/controllers/actuators/idle_state.txt
firmware/controllers/actuators/idle_thread.cpp

See https://github.com/rusefi/rusefi/issues/4720

idle_state: rename useIacTableForCoasting -> isIacTableForCoasting

---

firmware/tunerstudio/rusefi.input

TS: target lambda and target AFR gauges: fix layout

---

firmware/tunerstudio/rusefi.input

Idle position from Extra 2 to Idle category
idle AC adders to AC dialog
Fan idle adders to Fan dialog

TS UI suggestions by ELDominio

---

misc/pinout-gen/script.js

Handle yams with no info section

---

firmware/console/lwipopts.h
firmware/controllers/thread_priority.h

Set these in the correct spot (and to the correct values!)

lwip thread priorities

---

firmware/hw_layer/ports/cypress/backup_ram.cpp

for https://github.com/rusefi/rusefi/pull/4738#issuecomment-1306111813

fix BACKUP_FLASH_ADDR assertion semantic

---

firmware/provide_gcc.sh

via https://github.com/rusefi/build_support/pull/5
for https://github.com/rusefi/rusefi/pull/4680#issuecomment-1307961836

use build_support ARM GCC 11.3 toolchain

---

firmware/setup_linux_environment.sh

for https://github.com/rusefi/rusefi/issues/4766

fix setup_linux_environment.sh

---

firmware/hw_layer/drivers/sent/sent.cpp
firmware/hw_layer/drivers/sent/sent_logic.h
unit_tests/tests/sent/test_sent.cpp

Do CRC check for slow channel messages.
Add some helpers.
Update tests.

SENT updates

---

firmware/Makefile
firmware/clean_compile_two_versions.sh

Tweak firmware Makefile, scripting

---

.github/workflows/build-firmware.yaml
firmware/controllers/algo/runtime_state.cpp
firmware/controllers/engine_controller.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_adc.cpp
firmware/hw_layer/hardware.cpp
firmware/hw_layer/pin_repository.h
simulator/Makefile

Ubuntu 22.04 / MinGW GCC 11 exposed a few problems with the code and build, via #4791.

fix simulator build (via MinGW)

---

java_console/models/src/main/java/com/rusefi/stream/LogicdataStreamFile.java

rusEFI console produces invalid .logicdata files #1563

---

firmware/tunerstudio/rusefi.input

ve blend typo, explanation on dialog

---

firmware/console/binary/tunerstudio_impl.h
firmware/controllers/engine_cycle/rpm_calculator.h
firmware/controllers/lua/lua_hooks.cpp
firmware/controllers/lua/value_lookup.h
firmware/hw_layer/sensors/cj125.cpp
firmware/hw_layer/sensors/cj125_logic.h
firmware/util/containers/cyclic_buffer.h
firmware/util/containers/fifo_buffer.h
firmware/util/datalogging.cpp
unit_tests/global.h

MacOS build had a bunch of warnings. This fixes most of them on our side.
We also need to update to latest googletest, since many are from that side and have since been fixed by them.

fix warnings

---

firmware/console/binary/bluetooth.cpp
firmware/console/binary/bluetooth.h
firmware/console/binary/tunerstudio.cpp

Run BT setup from TS thread.
Remove special thread.
Remove bluetooth_cancel command.

Bluetooth jdy33: save some memory

---

firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_toyota.cpp
firmware/controllers/trigger/decoders/trigger_toyota.h

Toyota cam 4-1 can be a plain skipped tooth decoder

---

firmware/console/binary/tooth_logger.cpp
firmware/console/binary/tooth_logger.h
firmware/console/binary/tunerstudio.cpp
firmware/hw_layer/mmc_card.cpp

nonblocking for TS, blocking for SD card

---

firmware/tunerstudio/rusefi.input

fixes this situation (from #4904):

disable TPS secondary min/max w/ inputs

---

.github/workflows/hardware-ci.yaml
.github/workflows/openocd_ci_f4_discovery.cfg
.github/workflows/openocd_ci_proteus.cfg
java_console/autotest/src/main/java/com/rusefi/autotest/ControllerConnectorState.java

Specify serial number of stlink and ECU serial port so that we can run multiple HW CI runners on the same machine.

Hardware CI specifies exact device serial number

---

firmware/tunerstudio/rusefi.input

it already exists in VSS dialog

TS: remove totalGearsCount from Experimental/Broken dialog

---

.github/workflows/sync-wiki.yaml

Should fix https://github.com/rusefi/rusefi_documentation/issues/342

undo changes to both workflows

---

.github/workflows/gen-diffs.yaml

Kidiff generation seems pretty happy now, let's go ahead and fix #3440

Kicad diffs - use ssh, new version of Kidiff

---

firmware/controllers/algo/event_registry.h
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/init/sensor/init_sensors.cpp
unit_tests/tests/trigger/test_real_nb2_cranking.cpp

don't warn if we intentionally skipped this spark

---

firmware/console/binary_log/binary_logging.cpp
firmware/console/binary_log/log_field.cpp
firmware/console/binary_log/log_field.h
firmware/integration/rusefi_config.txt
java_console/models/src/main/java/com/rusefi/core/Sensor.java
java_console/models/src/main/java/com/rusefi/sensor_logs/BinaryLogEntry.java
java_console/ui/src/main/java/com/rusefi/sensor_logs/BinarySensorLog.java
java_tools/configuration_definition/src/main/java/com/rusefi/output/SdCardFieldsContent.java
java_tools/configuration_definition/src/test/java/com/rusefi/test/SdCardFieldsGeneratorTest.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/ConfigField.java
unit_tests/tests/test_binary_log.cpp

Emit v2 MLG format that supports writing a category along with each field.

emit v2 mlg

---

firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/integration/rusefi_config.txt
java_console/autotest/src/main/java/com/rusefi/f4discovery/CommonFunctionalTest.java

renumber airmass mode enum to start at 0

---

.github/workflows/build-firmware.yaml
misc/jenkins/build_working_folder.sh
misc/jenkins/compile_other_versions/prepare_bundle.sh

I haven't tested this yet, but am working on it.

Auto folders fix

---

.github/workflows/build-firmware.yaml

See https://github.com/chuckwagoncomputing/rusefi/actions/runs/4033431627 for example failure and error message.

[LTS] Fail firmware builds if . in branch name

---

java_console/autoupdate/src/main/java/com/rusefi/autoupdate/Autoupdate.java
java_console/shared_io/src/main/java/com/rusefi/core/io/BundleUtil.java

Tested and seems to be working, though I didn't actually flash a board. This should fix #4993.

Make autoupdate work

---

java_tools/configuration_definition/src/main/java/com/rusefi/output/SdCardFieldsContent.java
java_tools/configuration_definition/src/test/java/com/rusefi/test/SdCardFieldsGeneratorTest.java

generate SD log category correctly

---

.github/workflows/build-firmware.yaml
firmware/config/boards/nucleo_f767/board.mk
firmware/config/boards/nucleo_f767/board_configuration.cpp
misc/jenkins/build_working_folder.sh

fix #5033 correctly, let nucleos have their own ini

make nucleo builds normal

---

firmware/CHANGELOG.md
firmware/docs/rusEFI_custom_chibios.md
firmware/hw_layer/ports/stm32/stm32f4/cfg/mcuconf.h
firmware/hw_layer/ports/stm32/stm32f7/cfg/mcuconf.h
firmware/hw_layer/ports/stm32/stm32h7/cfg/mcuconf.h

for #4556, via https://github.com/rusefi/ChibiOS/pull/23

enable LSE (via: LSE max wait patches)

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/tunerstudio/rusefi.input
java_console/ui/src/test/resources/frankenso/mainController.ini

Fixup ETB auto-calib/tune buttons

---

firmware/config/boards/f429-discovery/board.h

define non-zero f429-discovery LSECLK

---

firmware/config/boards/hellen/hellen-honda-k/board_configuration.cpp
firmware/config/boards/hellen/hellen_common.cpp
firmware/config/boards/hellen_meta.h

https://github.com/rusefi/rusefi/issues/5068

[DRAFT] Honda125K PWR-EN pin

---

firmware/config/boards/hellen/alphax-2chan/board_configuration.cpp
firmware/config/boards/hellen_meta.h

https://github.com/rusefi/rusefi/issues/5067

[DRAFT] 2chan rev E SD card config #5067

---

.github/workflows/hardware-ci.yaml
java_tools/.idea/gradle.xml

I *think* this PR will make the workflow run to see if it works.

[HW CI Gradle] remove argument

---

firmware/config/boards/hellen/alphax-8chan/connectors/8chan-A-B.yaml
firmware/config/boards/hellen/alphax-8chan/connectors/8chan-C.yaml
firmware/config/boards/hellen/alphax-8chan/connectors/8chan-D.yaml

https://github.com/rusefi/alphax-8chan/issues/45

8chan Yaml update

---

firmware/controllers/algo/obd_error_codes.h
firmware/controllers/sensors/AemXSeriesLambda.cpp

fire a warning in case of wideband fault

---

firmware/console/binary/serial_can.cpp
firmware/controllers/can/rusefi_wideband.cpp
firmware/controllers/lua/lua_hooks.cpp
firmware/hw_layer/drivers/can/can_msg_tx.cpp
firmware/hw_layer/drivers/can/can_msg_tx.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

support wideband controller on the second CAN bus
fix #5028

wideband on second can

---

.github/workflows/build-firmware.yaml

I am leaving this as draft for now, to make sure it works on my fork.

Daily firmware build

---

firmware/controllers/algo/engine_types.h

order entries by ID and remove disturbing blank lines

---

.github/workflows/build-firmware.yaml

Example release:
https://github.com/chuckwagoncomputing/rusefi/releases/tag/2023-02-24
I also simplified the logic for which steps run, so that I could understand it enough to create this.

Create a nightly release

---

.github/workflows/build-firmware.yaml

I used the wrong event name. I didn't catch it because in testing I replaced it with workflow_dispatch so that I could actually test it without waiting a day.

Fix scheduled firmware build

---

firmware/console/binary_log/log_field.cpp

- ensuring header is zerod
addresses #5145

silence -Wstring-truncation for correct use of strncpy

---

.github/workflows/build-firmware.yaml

This should fix #5104 
I'm not sure how this happened, I think I re-typed the command at some point from memory without actually understanding what the -d parameter did.

Remove stray space

---

java_console/io/src/main/java/com/rusefi/binaryprotocol/BinaryProtocol.java

My JAVA skills are minor and I can't compile it yet in my environment, hence this is a test only

improve error message

---

firmware/config/boards/hellen/alphax-8chan/connectors/8chan-A-B.yaml
firmware/config/boards/hellen/alphax-8chan/connectors/8chan-C.yaml

https://github.com/rusefi/alphax-8chan/issues/80

8chan yaml: VR/Hall all options should be obvious

---

.github/workflows/gen-diffs.yaml
.github/workflows/gen-ibom.yaml
.gitignore
misc/jenkins/InteractiveHtmlBom/run.sh
misc/jenkins/generate_ibom/gen_upload_ibom.sh

As of now, I haven't found any backwards-incompatibility issues.
Related https://github.com/rusefi/hellen121vag/issues/89
This PR also fixes a few other issues that have shown up:
- a bug in Kicad-Diff which gives an error message, but doesn't hurt anything.
- a dumb check for a file that no longer exists
Other tweaks:
- fixed variable name in gen_upload_ibom.sh
- added workflow dispatch to gen_ibom

Upgrade to Kicad 7

---

.github/workflows/gen-diffs.yaml

Errors have now been fixed in @leoheck's fork, let's use it.
We are resetting to a specific commit so if he pushes breaking changes to his master, it won't affect us.

Upstream KiCad-Diff

---

firmware/integration/rusefi_config.txt

This PR contains only settings. The implementation will be added later.
#5214
#5224

RPM soft limit and hysteresis settings #5214, #5224

---

firmware/controllers/algo/engine2.cpp
firmware/controllers/limp_manager.cpp
firmware/controllers/limp_manager.h
unit_tests/tests/test_limp.cpp

May affect the following issues:
https://github.com/rusefi/rusefi/issues/5214
https://github.com/rusefi/rusefi/issues/5224
https://github.com/rusefi/rusefi/issues/5234
https://github.com/rusefi/rusefi/issues/5235
Please re-test the above-mentioned issues.

RPM limit fix and unit-tests 

---

firmware/controllers/limp_manager.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_limp.cpp

https://github.com/rusefi/rusefi/issues/4529

Boost cut pressure hysteresis

---

firmware/config/boards/hellen/alphax-8chan/board_configuration.cpp

https://github.com/rusefi/alphax-8chan/issues/99
https://github.com/rusefi/alphax-8chan/issues/101

Fix 8chan pull-ups/pull-downs

---

.github/workflows/build-firmware.yaml

fix #5300
I haven't tested this yet, wait for the workflow to run on this PR and we'll see if it works.

don't skip firmware builds on PR

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
unit_tests/tests/test_idle_controller.cpp

https://github.com/rusefi/rusefi/pull/5315
https://github.com/rusefi/rusefi/issues/5303

Dashpot for return-to-idle from coasting

---

firmware/config/boards/proteus/compile_proteus_f4.sh
firmware/config/boards/proteus/openblt/oblt_board.mk
firmware/config/boards/subaru_eg33/openblt/main_external_osc.c
firmware/flash_usb.sh
firmware/hw_layer/openblt/blt_conf.h
firmware/hw_layer/openblt/flash_layout.c
firmware/hw_layer/openblt/main_internal_osc.c
firmware/hw_layer/openblt/openblt.mk
firmware/hw_layer/ports/stm32/osc_detector.cpp

USB is not stable with HSI. Reuse osc_detector code in OpenBLT.

Openblt usb on Proteus with OSC detecor

---

.github/workflows/gen-pinouts.yaml

This should fix https://github.com/rusefi/rusefi_documentation/issues/492

Check for password secret before uploading pinout

---

firmware/global.h
firmware/hw_layer/ports/cypress/global_port.h
firmware/hw_layer/ports/kinetis/global_port.h
firmware/hw_layer/ports/stm32/stm32f4/global_port.h
firmware/hw_layer/ports/stm32/stm32f7/global_port.h
firmware/hw_layer/ports/stm32/stm32h7/global_port.h

global_port.h

---

firmware/controllers/lua/lua_hooks.cpp
firmware/init/sensor/init_sensors.cpp
firmware/tunerstudio/rusefi.input

lua getAuxDigital() #4861

---

.github/workflows/check-pinout.yaml

This runs if any files matching connectors/*.yaml have changed.
Fix https://github.com/rusefi/rusefi_documentation/issues/386

Generate changed pinouts on PR

---

java_console/autotest/src/main/java/com/rusefi/HwCiProteus.java

proteus F7 hard fault on "enable self stimulation" #5354

---

firmware/config/boards/proteus/compile_proteus_f7.sh
firmware/config/boards/proteus/compile_proteus_f7_debug.sh
firmware/config/boards/proteus/compile_proteus_f7_hardware_QC_special_build.sh

https://github.com/rusefi/rusefi/issues/5432

compile_proteus_f7_debug.sh

---

firmware/console/binary/tooth_logger.cpp
firmware/controllers/core/big_buffer.cpp

Fixes https://github.com/rusefi/rusefi/issues/5354

bigBuffer should be aligned

---

firmware/config/boards/kinetis/prepend.txt
firmware/integration/rusefi_config.txt

shrinking kinetis
only:kinetis

minor fix: tables are flipped?

---

firmware/console/binary/live_data.cpp
firmware/controllers/actuators/ac_control.h
firmware/controllers/actuators/fan_control.cpp
firmware/controllers/actuators/fan_control.h
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/integration/LiveData.yaml
unit_tests/tests/actuators/test_fan_control.cpp

* fan is engine module
* mockable AC
* mockable AC
* mock AC controller in fan test
* constexpr fan livedata
* isPtr

fan control is engine module

---

firmware/CHANGELOG.md
firmware/controllers/actuators/idle_state.txt
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

A version of https://github.com/rusefi/rusefi/pull/5628 without code-generated stuff

Dev ac idle up proper

---

firmware/config/boards/subaru_eg33/board.mk

Fix bug introduced in f7e6ccd9e266c438ebf55db763589bbde3bd165d

subaru_eg33: LEDs are still active low

---

firmware/controllers/core/error_handling.cpp
firmware/controllers/core/error_handling.h
firmware/controllers/core/log_hard_fault.h

variable shadowing should be avoided #5676

---

firmware/tunerstudio/rusefi.input

Changed the Tuner Studio axis assignment for better readability and understanding for After Start Enrichment.

ASE TS axis

---

firmware/controllers/algo/engine.h
firmware/controllers/engine_controller.h
firmware/controllers/flash_main.cpp
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/mpu_watchdog.h
firmware/hw_layer/ports/stm32/stm32_common.cpp
simulator/simulator/mpu_util.h
simulator/simulator/sim_watchdog.h

Watchdog magic constants refactor

---

firmware/hw_layer/hardware.cpp
firmware/hw_layer/hardware.h
firmware/hw_layer/ports/at32/at32_common.cpp
firmware/hw_layer/ports/cypress/mpu_util.cpp
firmware/hw_layer/ports/kinetis/mpu_util.cpp
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/stm32/mcuconf_common_f4_f7.h
firmware/hw_layer/ports/stm32/stm32_common.mk
firmware/hw_layer/ports/stm32/stm32_reset_cause.cpp
firmware/rusefi.cpp
simulator/simulator/mpu_util.h

+ throw a fatal error if a reset by watchdog is detected.

Detect and print Reset cause for STM32

---

firmware/console/lwipopts.h
firmware/controllers/algo/engine_types.h
firmware/controllers/algo/generated_lookup_engine_configuration.h
firmware/controllers/algo/generated_lookup_meta.h
firmware/controllers/algo/persistent_configuration.h
firmware/controllers/algo/rusefi_types.h
firmware/controllers/core/error_handling.h
firmware/controllers/sensors/converters/thermistor_func.h
firmware/controllers/settings.h
firmware/controllers/tcu/gear_controller.h
firmware/controllers/tcu/tcu.h
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/pch/pch.h
firmware/util/efi_quote.h
firmware/util/efi_scaled_channel.h
firmware/util/efilib.h
firmware/util/loggingcentral.h

custom FW repos code generation process #5817

---

firmware/config/boards/subaru_eg33/board.mk
firmware/config/boards/subaru_eg33/board_configuration.cpp
firmware/config/boards/subaru_eg33/efifeatures.h
firmware/hw_layer/ports/stm32/stm32f7/hw_ports.mk

Please apply this PR **before** https://github.com/rusefi/rusefi/pull/5836

Fix subaru_eg33 for OpenBLT

---

firmware/console/binary_log/binary_logging.cpp
java_tools/configuration_definition_base/src/main/java/com/rusefi/ldmp/LiveDataProcessor.java

https://github.com/rusefi/rusefi/issues/5644

simulator does not compile for pchmura4 on gcc13 #5644

---

firmware/console/binary/output_channels.txt
firmware/controllers/sensors/sensor_checker.cpp
firmware/tunerstudio/rusefi.input

TS: show diagnostic for Injector and Ignition outputs

---

firmware/hw_layer/drivers/gpio/mc33810.cpp

@rusefillc need your help with testing diagnostic of Ignition outputs with onboard IGBT/MOSFET.

mc33810 diagnostic improvements

---

.github/workflows/build-firmware.yaml
firmware/Makefile
firmware/bin/upload_bundle.sh
firmware/config/boards/cypress/config/gen_cypress_config.sh
firmware/config/boards/kinetis/config/gen_kinetis_config.sh
firmware/config/boards/readme.md
firmware/config/boards/subaru_eg33/config/gen_subaru_config.sh
firmware/gen_config_board.sh
firmware/gen_config_common.sh
firmware/gen_signature.sh
firmware/hw_layer/mass_storage/create_ini_image.sh
firmware/hw_layer/mass_storage/create_ini_image_compressed.sh
misc/jenkins/build_working_folder.sh

Move the bundle uploading out of build_working_folder.sh into its own script
standardize SHORT_BOARD_NAME variable

Makeover - Preliminary Fiddling

---

.github/workflows/build-firmware.yaml
misc/jenkins/build_working_folder.sh
misc/jenkins/compile_other_versions/prepare_bundle.sh

It doesn't do anything with it, that's handled in the upload_bundle script

Don't pass LTS to prepare_bundle

---

.github/workflows/hw-ci/build_for_hw_ci.sh
.github/workflows/hw-ci/openocd_wipe_and_flash.sh
firmware/bin/compile.sh
firmware/bundle.mk

I should have done this before, at least before removing common_script.
https://github.com/rusefi/rusefi/issues/5997
Green custom: https://github.com/chuckwagoncomputing/fw-custom-example/actions/runs/7980685757

Create composite bin in Make

---

firmware/bundle.mk

Conditionally set bootloader output for prerequisite only

---

.gitignore
firmware/bundle.mk

This is another attempt at fixing #6014

use workarounds for older versions of Make

---

java_console/autotest/src/main/java/com/rusefi/HwCiProteus.java
java_console/autotest/src/main/java/com/rusefi/f4discovery/PTraceTest.java
java_console/io/src/main/java/com/rusefi/io/commands/PTraceHelper.java
java_console/ui/src/main/java/com/rusefi/PerformanceTraceHelper.java

revive ptrace #5983

---

firmware/controllers/can/can_dash.cpp

https://support.haltech.com/portal/en/kb/articles/haltech-can-ecu-broadcast-protocol

Update can_dash.cpp to match the Haltech standard

---

firmware/bundle.mk
firmware/rusefi_config.mk
java_tools/java_tools.mk

Green custom https://github.com/chuckwagoncomputing/fw-custom-example/actions/runs/8057197376

Makefile for building java tools

---

firmware/bin/upload_bundle.sh

Fix LTS upload folder

---

.github/workflows/build-unit-tests.yaml
firmware/bootloader/Makefile
firmware/bundle.mk
firmware/gen_config_board.sh
firmware/rusefi_config.mk
java_tools/java_tools.mk

This should fix #6064.
This ended up being far less simple than I hoped.
I went with the "install realpath on macOS" route.

Make bootloader depend on configs

---

firmware/rusefi_config.mk
java_tools/java_tools.mk

Make Fields.java a prerequisite of console

---

firmware/rusefi_config.mk

This should fix #6081 and #6082.

Regenerate configs if any config files have changed

---

firmware/gen_config.sh

We ain't surfin today, it's the middle of winter.
I expect this to fix #6090

Fix variable confusion

---

firmware/bundle.mk
firmware/rusefi_config.mk
firmware/rusefi_pch.mk
java_tools/java_tools.mk

In addition to adding some comments, I fixed the paths for CONSOLE_OUT, AUTOUPDATE_OUT, and TPL_OUT.
I don't think they were broken for anything, but better safe than sorry.

Add a few comments and fix some paths

---

java_tools/java_tools.mk

Fix big dumb

---

firmware/bundle.mk

Add post build script target

---

firmware/bundle.mk

Clean deliver folder

---

firmware/bin/upload_bundle.sh

Half of #6168
Demonstration of failure: https://github.com/chuckwagoncomputing/rusefi/actions/runs/8209213190

Add return value of tar command

---

.github/workflows/build-firmware.yaml

Run on master: https://github.com/chuckwagoncomputing/rusefi/actions/runs/8209386783

source meta-info before upload

---

firmware/bootloader/Makefile
firmware/bootloader/openblt_chibios/openblt_can.cpp

https://github.com/rusefi/rusefi/issues/6043

Enable CAN for OpenBLT

---

firmware/gen_config.sh

Fix #6100
Run: https://github.com/chuckwagoncomputing/rusefi/actions/runs/8210121705
Commit: https://github.com/chuckwagoncomputing/rusefi/commit/a6bd10c2c0ba1b15aa2d88b4571c26f5367b1344

Automatically find meta info files for gen config

---

.github/workflows/build-firmware.yaml

Don't use wildcard for bundle upload

---

.github/workflows/build-firmware-windows.yaml
.github/workflows/build-unit-tests-windows.yaml

revive windows builds #6185

---

simulator/Makefile

@chuckwagoncomputing I've removed commit from master for now, preserving it here

include board.mk

---

simulator/Makefile

This doesn't fix all the simulator problems on master, but most of them.
I'll open issues for the remaining ones.

Check for default_tune.cpp

---

.github/workflows/build-firmware.yaml

I don't have a FTP server set up to test this, so I guess we'll just try it.

use META_OUTPUT_ROOT_FOLDER for ini upload

---

.github/workflows/custom-board-build/action.yaml

- removed quotes so bash will do the expansion instead of git
- added more debug statements

Attempt 2 to fix tune push

---

.github/workflows/build-simulator.yaml
.github/workflows/gen-configs.yaml
.github/workflows/set-date.yaml

This is another attempt at #5984

revamp pushing in workflows with pull --rebase

---

java_tools/configuration_definition_base/src/main/java/com/rusefi/ldmp/LiveDataProcessor.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/ldmp/StateDictionaryGenerator.java
java_tools/configuration_definition_base/src/test/java/com/rusefi/ldmp/StateDictionaryGeneratorTest.java

second WBO channel logging #6306

---

firmware/bundle.mk

[explicit zip content instead of filtering stuff out](https://github.com/rusefi/rusefi/commit/4dfcccf401224fe06938d2b5c4b21b206bd0b542)

Going positive

---

.github/workflows/gen-configs.yaml

add missing .ini and .md files

---

firmware/config/boards/hellen/alphax-2chan/board_options.ini
firmware/gen_config_common.sh
firmware/rusefi_config.mk
firmware/tunerstudio/tunerstudio.template.ini

https://github.com/rusefi/rusefi/issues/6352

board_options.ini test for 2chan https://github.com/rusefi/rusefi/issues/6352

---

firmware/tunerstudio/tunerstudio.template.ini

tunerstudio.template: fix one more typo

---

firmware/gen_config_common.sh
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
java_tools/configuration_definition_base/src/main/java/com/rusefi/ReaderStateImpl.java
java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/MetaHelper.java

https://github.com/rusefi/rusefi/issues/6352

Add custom board config, menu, tables

---

firmware/config/boards/at_start_f435/board.mk
firmware/config/boards/m74_9/board.mk
firmware/config/boards/subaru_eg33/board.mk
firmware/config/boards/subaru_eg33/halconf.h

encapsulation of relevant properties and reusable file

serial_flash_support.mk

---

firmware/console/binary/bluetooth.cpp
simulator/generated/simulator_tune.msq
simulator/generated/simulator_tune_BMW_M52.msq
simulator/generated/simulator_tune_HARLEY.msq
simulator/generated/simulator_tune_HELLEN_121_NISSAN_6_CYL.msq
simulator/generated/simulator_tune_HELLEN_154_HYUNDAI_COUPE_BK1.msq
simulator/generated/simulator_tune_HELLEN_154_HYUNDAI_COUPE_BK2.msq
simulator/generated/simulator_tune_HONDA_K.msq
simulator/generated/simulator_tune_HONDA_OBD1.msq
simulator/generated/simulator_tune_HYUNDAI_PB.msq
simulator/generated/simulator_tune_MAVERICK_X3.msq
simulator/generated/simulator_tune_MAZDA_MIATA_NA6.msq
simulator/generated/simulator_tune_MAZDA_MIATA_NA94.msq
simulator/generated/simulator_tune_MAZDA_MIATA_NA96.msq
simulator/generated/simulator_tune_MAZDA_MIATA_NB1.msq
simulator/generated/simulator_tune_MAZDA_MIATA_NB2.msq
simulator/generated/simulator_tune_MERCEDES_M111.msq
simulator/generated/simulator_tune_POLARIS_RZR.msq

Moved changing baud last due to bt module reseting/freaking out.

Bluetooth name change fix and character total reply for at version 

---

firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.h

@mck1117 @rusefillc can you check that I did not break some C++ magic with my dirty hands?

SimplePWM: utilize GpioChip PWM capabilities

---

firmware/controllers/actuators/boost_control.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/gppwm/gppwm.cpp
firmware/controllers/actuators/vvt.cpp
firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/engine_cycle/knock_logic.h
firmware/controllers/lua/script_impl.cpp
firmware/controllers/math/speed_density.cpp
firmware/util/containers/table_helper.h
unit_tests/test_basic_math/test_interpolation_3d.cpp

preparation: giving tables names

Map3D should not be silently return 0 if not initialized #6461

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/generated/rusefi_f407-discovery.ini
firmware/tunerstudio/tunerstudio.template.ini
java_console/inifile/src/main/java/com/opensr5/ini/IniFileReader.java
java_console/inifile/src/test/java/com/opensr5/ini/test/IniFileReaderTest.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/TokenUtils.java

Tables have wrong units on Y-Axis #6479

---

firmware/controllers/algo/launch_control.cpp
firmware/controllers/algo/launch_control.h
unit_tests/tests/launch/test_rpm_condition.cpp

…aunch_control_state panel instead of hidden class field #5610

enhance hysterisis detection: now we use isAfterLaunch indicator on launch_control_state panel instead of hidden class field #5610

---

firmware/hw_layer/drivers/gpio/can_gpio_msiobox.cpp

variable shadowing should be avoided in MSGPIO #5676

---

java_console/autotest/src/main/java/com/rusefi/common/MiscTest.java
java_console/io/src/test/java/com/rusefi/binaryprotocol/test/SerialSandbox.java

EFI_TCU TS connected causes red LED #6543

---

unit_tests/tests/launch/test_ignition_angle_advance.cpp

add references to requirements in test

---

firmware/tunerstudio/tunerstudio.template.ini

disable fields on `Launch Control` if `Enable Launch Control` setting is `false`

---

firmware/config/boards/hellen/hellen154hyundai_f7/board_configuration.cpp
firmware/console/eficonsole.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_adc.cpp
firmware/util/datalogging.h
firmware/util/loggingcentral.h

compile-time enforcement of printf strings

---

firmware/controllers/algo/launch_control.cpp
firmware/controllers/algo/launch_control_state.txt
unit_tests/tests/launch/test_rpm_condition.cpp

see https://github.com/rusefi/rusefi/issues/6566#issuecomment-2166719232 (#6566)

get rid of hysteresis functionality

---

firmware/config/boards/hellen/hellen154hyundai_f7/board_configuration.cpp
firmware/config/boards/subaru_eg33/board_configuration.cpp
firmware/hw_layer/mc33816.cpp
firmware/hw_layer/smart_gpio.cpp
firmware/util/os_util.h

https://github.com/rusefi/rusefi/pull/5394

---

firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/hardware.cpp

ADC: comments and dead code

---

.github/workflows/custom-board-build/action.yaml

see https://github.com/actions/runner/issues/1877#issuecomment-1987226919

enhance displaying of step names in composite action

---

firmware/hw_layer/hardware.cpp
firmware/hw_layer/sensors/hip9011.cpp
firmware/hw_layer/sensors/hip9011.h

Fix lost control of CS pin after settings update.

hip9011: fix reinitialization, typos

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

TS: SPI settings interface layout fixes

---

firmware/config/boards/subaru_eg33/board_configuration.cpp
firmware/config/boards/subaru_eg33/prepend.txt

Depends on https://github.com/rusefi/rusefi/pull/6669

eg33 board: minor default settings fixes

---

java_console/io/src/main/java/com/rusefi/io/DfuHelper.java
java_console/io/src/main/java/com/rusefi/io/UpdateOperationCallbacks.java
java_console/io/src/main/java/com/rusefi/io/can/PCanIoStream.java
java_console/io/src/main/java/com/rusefi/io/tcp/BinaryProtocolProxy.java
java_console/io/src/main/java/com/rusefi/io/tcp/BinaryProtocolServer.java
java_console/io/src/main/java/com/rusefi/ui/StatusConsumer.java
java_console/ui/src/main/java/com/rusefi/maintenance/DfuFlasher.java
java_console/ui/src/main/java/com/rusefi/maintenance/DriverInstall.java
java_console/ui/src/main/java/com/rusefi/maintenance/ExecHelper.java
java_console/ui/src/main/java/com/rusefi/maintenance/MaintenanceUtil.java
java_console/ui/src/main/java/com/rusefi/maintenance/ProgramSelector.java
java_console/ui/src/main/java/com/rusefi/maintenance/StLinkFlasher.java
java_console/ui/src/main/java/com/rusefi/maintenance/UpdateStatusWindow.java
java_console/ui/src/main/java/com/rusefi/tools/CANConnectorStartup.java
java_console/ui/src/main/java/com/rusefi/tools/ConsoleTools.java
java_console/ui/src/main/java/com/rusefi/ui/PcanConnectorUI.java
java_console/ui/src/main/java/com/rusefi/ui/StatusWindow.java
java_console/ui/src/test/java/com/rusefi/binaryprotocol/test/PCanIoProxySandbox.java

Improve ECU reboot waiting

---

firmware/config/boards/hellen/alphax-silver/board_configuration.cpp
firmware/config/boards/hellen/hellen128/board_configuration.cpp
firmware/hw_layer/drivers/i2c/i2c_bb.cpp
firmware/hw_layer/drivers/i2c/i2c_bb.h

AlphaX-Silver:
`2024-07-14_20_05_56_393: EngineState: hellenBoardId=304`

pca9555 support for board type detection

---

firmware/controllers/algo/defaults/default_base_engine.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/limp_manager.cpp
firmware/controllers/limp_manager.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/test_limp.cpp

only:oilPressureProtection submenu

oil pressure protection (while running) #6780

---

java_console/ui/src/main/java/com/rusefi/maintenance/ProgramSelector.java

now we really check that new port appeared after ECU port disappeared

---

java_console/autoupdate/src/main/java/com/rusefi/autoupdate/Autoupdate.java
java_console/shared_io/src/main/java/com/rusefi/core/FileUtil.java

Fix `ZipFile invalid LOC header (bad signature)` error

---

firmware/controllers/actuators/boost_control.cpp
firmware/tunerstudio/tunerstudio.template.ini

Fix boost adders

---

unit_tests/tests/actuators/boost/boost_test_base.cpp
unit_tests/tests/actuators/boost/boost_test_base.h
unit_tests/tests/actuators/boost/test_closed_loop_adders.cpp
unit_tests/tests/actuators/boost/test_open_loop_multipliers.cpp

to prevent bugs like https://github.com/rusefi/rusefi/issues/6424#issuecomment-2294958949 now tests reuse real boost controller from test engine #6424

test enhancement

---

firmware/tunerstudio/tunerstudio.template.ini

according to https://github.com/rusefi/rusefi/issues/6424#issuecomment-2305628356 (closes - #6424)

Rename menu items

---

.github/workflows/build-android.yaml
.github/workflows/build-firmware-proteus-f7-mac.yaml
.github/workflows/build-firmware-windows.yaml
.github/workflows/build-firmware.yaml
.github/workflows/build-simulator.yaml
.github/workflows/build-tsplugin-body.yaml
.github/workflows/build-unit-tests-windows.yaml
.github/workflows/codeql.yml
.github/workflows/gen-configs.yaml

java 17 experiment

---

.github/workflows/build-firmware.yaml
firmware/rusefi_config.mk

Makefile needs to know about these little .ini files?

---

unit_tests/tests/test_util.cpp

just a simple fix to remove compiler warning

Minor: silence compiler warning

---

firmware/console/binary/tunerstudio.cpp

Related to https://github.com/rusefi/ts-issues/issues/99 but does not fix.

TS: report error if Page read/write/crc command is out of range

---

java_console/autoupdate/src/main/java/com/rusefi/autoupdate/Autoupdate.java
java_console/shared_io/src/main/java/com/rusefi/core/io/BundleUtil.java
java_console/ui/src/main/java/com/rusefi/StartupFrame.java

Show current branch name

---

firmware/integration/rusefi_config.txt

fixes #5964, small text update on useSeparateAdvanceForIdle

wrong text in 'Use idle ignition table' tooltip

---

firmware/controllers/algo/engine2.cpp
firmware/controllers/engine_cycle/knock_controller.cpp
firmware/controllers/engine_cycle/knock_logic.h
unit_tests/tests/test_knock.cpp

- knock disable suppression then deceleration

- knock fuel trim + diasble suppression then deceleration 

---

firmware/console/usb_console.cpp
firmware/hw_layer/ports/rusefi_halconf.h

https://github.com/rusefi/rusefi/issues/6595

6595 burn failed

---

firmware/controllers/trigger/decoders/trigger_universal.cpp

different gaps for different wheels
@ElDominio wanna try or should I just merge?

3-0 dies for no reason at idle speeds #7002

---

unit_tests/tests/actuators/test_boost.cpp
unit_tests/tests/controllers/can/test_obd2.cpp
unit_tests/tests/test_limp.cpp

Added more tests for `handleGetDataRequest`, still missing for `handleDtcRequest`, `obdOnCanPacketRx` which are currently unfinished code

more tests on OBD2 code, prep tests for map upper limit change

---

java_tools/ts_plugin/src/main/java/com/rusefi/ts_plugin/KnockAnalyzerTab.java
java_tools/ts_plugin/src/main/java/com/rusefi/ts_plugin/KnockCanvas.java

- spectrum by sensors and cylinders

- knock analyzer plugin improve

---

firmware/bootloader/bootloader_main.cpp

https://github.com/rusefi/rusefi/issues/7069

OpenBLT: Enable an arbitrary pin

---

firmware/controllers/can/can_dash.cpp

Change BMW E46 CAN interval to 10 ms

---

firmware/controllers/sensors/impl/software_knock.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp

modularize knock adc for h7

---

firmware/config/boards/nucleo_f767/board.mk
firmware/hw_layer/ports/stm32/stm32f7/mpu_util.cpp

Flash size usage expanded, config copies moved to new location.

Use 1.5Mb for nucleo767 https://github.com/rusefi/rusefi/issues/6242

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/sensors/tps.cpp
firmware/hw_layer/drivers/sent/sent.cpp
firmware/init/init.h
firmware/init/sensor/init_fluid_pressure.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

Uaefi sent

---

firmware/controllers/lua/lua.cpp

Do not increase if allocation failed

lua: fix heap used accumulator calculation

---

.github/workflows/build-unit-tests.yaml
unit_tests/valgrind.suppressions.txt

This reverts commit 8231adba67128782468b0cc08176723f421e2995.

Revert "only:helping build"

---

unit_tests/test-framework/engine_test_helper.cpp
unit_tests/tests/test_engine_math.cpp
unit_tests/tests/test_hip9011.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

Get rid of GTEST assertion wrappers (assertEqualsM2)

---

.github/workflows/hardware-ci.yaml
.github/workflows/hw-ci/how_to_local_hwci.md

update hardware-ci.yaml for generate config before running tests

---

firmware/console/binary/output_channels.txt
unit_tests/tests/binary_log/test_bit_logger_field.cpp

SD card bit data points #7227

---

firmware/controllers/core/error_handling.cpp
firmware/rusefi_rules.mk

revert #RUSEFI_OPT += -Werror=stringop-truncation #7311

---

java_console/io/src/main/java/com/rusefi/io/can/PCanIoStream.java
java_console/io/src/main/java/com/rusefi/io/tcp/BinaryProtocolProxy.java
java_console/io/src/main/java/com/rusefi/io/tcp/BinaryProtocolServer.java
java_console/io/src/main/java/com/rusefi/ui/StatusConsumer.java
java_console/ui/src/main/java/MassUpdater.java
java_console/ui/src/main/java/com/rusefi/maintenance/DriverInstall.java
java_console/ui/src/main/java/com/rusefi/maintenance/ProgramSelector.java
java_console/ui/src/main/java/com/rusefi/maintenance/StatusWindowAnimation.java
java_console/ui/src/main/java/com/rusefi/maintenance/UpdateStatusWindow.java
java_console/ui/src/main/java/com/rusefi/maintenance/jobs/AsyncJobExecutor.java
java_console/ui/src/main/java/com/rusefi/tools/CANConnectorStartup.java
java_console/ui/src/main/java/com/rusefi/tools/ConsoleTools.java
java_console/ui/src/main/java/com/rusefi/ui/PcanConnectorUI.java
java_console/ui/src/main/java/com/rusefi/ui/StatusWindow.java
java_console/ui/src/main/java/com/rusefi/ui/basic/BasicStartupFrame.java
java_console/ui/src/main/java/com/rusefi/ui/basic/BasicUpdaterPanel.java
java_console/ui/src/main/java/com/rusefi/ui/basic/UpdateCalibrations.java
java_console/ui/src/main/java/com/rusefi/ui/widgets/StatusPanel.java

To enable new functionality environment variable `RUSEFI_USE_STATUS_WINDOW_FOR_JOBS` should have value `false`.

Implement status panel to use instead of status window

---

firmware/controllers/algo/engine_types.h
firmware/controllers/bench_test.cpp
firmware/controllers/core/error_handling.cpp
firmware/ext/FatFS/fatfs.mk
firmware/ext/FatFS/ffconf.h
firmware/ext/FatFS/ffsystem.c
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/mmc_card.h
firmware/tunerstudio/tunerstudio.template.ini

SD: delete reports button

---

firmware/controllers/core/error_handling.cpp
firmware/hw_layer/ports/rusefi_halconf.h

No empty error string on firmwareError()

err handler fixes

---

firmware/config/boards/hellen/alphax-8chan/prepend.txt
firmware/config/boards/hellen/uaefi/prepend.txt
firmware/console/binary/output_channels.txt
firmware/controllers/algo/obd_error_codes.h
firmware/controllers/sensors/sensor_checker.cpp
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

Currently only TLS115 Power Good signal is handled on few Hellen boards.
First step of https://github.com/rusefi/rusefi/pull/7155

Report analog failure to TS and rise OBD code

---

firmware/tunerstudio/tunerstudio.template.ini

Show input value.
Show current position on curve.

TS: rework fuel level dialog

---

firmware/hw_layer/mass_storage/mass_storage_device.cpp

```
$ dd if=B5A4-271B/test.bin of=/dev/zero status=progress
133677568 bytes (134 MB, 127 MiB) copied, 129 s, 1.0 MB/s
262144+0 records in
262144+0 records out
134217728 bytes (134 MB, 128 MiB) copied, 129.408 s, 1.0 MB/s
```

USB MSD/SD final speed-up

---

firmware/config/boards/hellen/alphax-gold/board.mk
firmware/config/boards/hellen/alphax-gold/board_configuration.cpp
firmware/config/boards/hellen/alphax-gold/board_engine_configuration.txt
firmware/config/boards/hellen/alphax-gold/connectors/34pins-3k-A.yaml
firmware/config/boards/hellen/alphax-gold/connectors/34pins-4k-B.yaml
firmware/config/boards/hellen_meta.h

Not tested on real HW. But compiles.

AlphaX-Gold configuration

---

.github/workflows/build-rusEFI-console.yaml
.gitignore
firmware/flash_reboot_dfu.bat
firmware/gen_ptrace_enums.bat
firmware/gen_trigger_images.bat
firmware/get_performance_trace.bat
firmware/reboot_dfu.sh
firmware/reboot_ecu.bat
firmware/run_hw_test.bat
firmware/send_command.bat
java_console/autoupdate/build.gradle
java_console/ts2c_fuelTable.bat
java_console/ui/build.gradle
java_tools/java_tools.mk

this change gets gradle-based file system layout one step closer to Makefile-based user artifact folder structure, this increases the chances of autoupdate development from IDEA
this change works together with https://github.com/rusefi/rusefi/commit/886a9febdac15cf4a736238f8eb028c9a52b2235

Unify staging folder

---

firmware/controllers/sensors/converters/func_chain.h

from first step if value not valid return result value with error code

fix return value

---

firmware/controllers/algo/defaults/default_ignition.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/ignition/ignition_state.cpp
firmware/controllers/algo/ignition/ignition_state.h
firmware/controllers/engine_controller.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

* change curve to table on ign clt correction
* bump FLASH_DATA_VERSION
resolves #7163

IGN CLT Correction as 5x5 table [was 8*2 curve]

---

firmware/controllers/algo/defaults/default_ignition.cpp
firmware/integration/rusefi_config.txt

fix for comment:
https://github.com/rusefi/rusefi/issues/7163#issuecomment-2679705313
now gauge & code works as expected:
[ign_clt_iat_fixes.webm](https://github.com/user-attachments/assets/15b50ada-5c19-4c4f-a1b8-94e8637f9736)
resolves #7501

fix IGN CLT/IAT Correction table issue

---

firmware/integration/rusefi_config.txt

~also simplify `setDefaultIatTimingCorrection` / `setDefaultCltTimingCorrection`~ (discarded)

fix IGN CLT/IAT Correction table issue [float => int16_t with autoscale]

---

firmware/config/engines/mazda/mazda_miata_vvt.cpp
firmware/console/status_loop.cpp
firmware/controllers/algo/defaults/default_base_engine.cpp
firmware/controllers/algo/defaults/default_fuel.cpp
firmware/controllers/algo/engine_configuration.h
firmware/controllers/algo/engine_configuration_defaults.h
firmware/controllers/algo/fuel/batt_lag_corr_curve.h
firmware/controllers/algo/fuel/injector_model.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/math/engine_math.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/test-framework/engine_test_helper.cpp
unit_tests/tests/ignition_injection/test_fuel_map.cpp
unit_tests/tests/ignition_injection/test_fuel_math.cpp
unit_tests/tests/ignition_injection/test_injector_model.cpp
unit_tests/tests/ignition_injection/test_staged_injection.cpp
unit_tests/tests/util/engine_config.cpp
unit_tests/tests/util/engine_config.h
unit_tests/tests/util/test_engine_configuration.cpp
unit_tests/tests/util/test_engine_configuration.h

injector deadtime as table #7511

---

firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/adc/adc_inputs_onchip.cpp

This reverts commit 1ad805e1a8429340982224cd5688f8ed63e8adb1.

Revert "adc: onchip: dead boardAdjustVoltage"

---

firmware/controllers/algo/defaults/default_fuel.cpp
firmware/controllers/algo/engine_configuration_defaults.h

add calibration data for Bosch 02880155868 injector

---

firmware/config/boards/hellen/hellen_common.cpp

Without enabling WBO and spamming CAN bus

hellen_common: board hook to enale SD card only

---

unit_tests/tests/test_idle_controller.cpp

update Idle related test for slider + multiplier to curve change

---

unit_tests/tests/ignition_injection/test_ignition_scheduling.cpp

Spark hardware latency [new test for func]

---

firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/ignition/ignition_state.cpp
firmware/controllers/algo/ignition/ignition_state.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/ignition_injection/test_ignition_scheduling.cpp

Spark hardware latency [TS + integration]

---

firmware/config/boards/proteus/prepend.txt
firmware/config/boards/proteus/prepend_proteus_f4.txt
firmware/config/boards/proteus/prepend_proteus_f7.txt
firmware/config/boards/proteus/prepend_proteus_h7.txt
firmware/gen_config_common.sh
firmware/rusefi_config.mk
java_tools/configuration_definition/src/main/java/com/rusefi/ConfigDefinition.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/ReaderState.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/ReaderStateImpl.java

make prepend.txt optional

---

unit_tests/test-framework/engine_test_helper.cpp
unit_tests/test-framework/test_executor.cpp
unit_tests/tests/ignition_injection/injection_mode_transition.cpp
unit_tests/tests/ignition_injection/test_ignition_scheduling.cpp
unit_tests/tests/test_hpfp_integrated.cpp
unit_tests/tests/trigger/test_coil.cpp
unit_tests/tests/trigger/test_nissan_vq_vvt.cpp
unit_tests/tests/trigger/test_real_4b11.cpp
unit_tests/tests/trigger/test_real_arctic_cat.cpp
unit_tests/tests/trigger/test_real_cas_24_plus_1.cpp
unit_tests/tests/trigger/test_real_ford_coyote.cpp
unit_tests/tests/trigger/test_real_volkswagen.cpp
unit_tests/tests/trigger/test_toyota_3_tooth_cam.cpp

technical debt: NT -> US -> NT in unit test scheduler

---

firmware/integration/rusefi_config.txt

just a minor fix to clarify field description structure

Minor: fix help text in the rusefi_config

---

firmware/controllers/actuators/boost_control.cpp
firmware/controllers/engine_controller.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

related issues:
* #7101
*  #6843

separate boost control open loop axis from closed loop axis

---

firmware/controllers/limp_manager.cpp
firmware/controllers/limp_manager.h
firmware/integration/rusefi_config.txt
unit_tests/tests/test_limp.cpp

Max oil pressure protection

---

firmware/controllers/limp_manager.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/test_limp.cpp

see #7575
- setting moved to curve
- a new window for TunerStudio

Oil pressure protection, part2

---

firmware/config/engines/custom_engine.cpp
firmware/controllers/algo/fuel/injector_model.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

calculated fuel vs fuel pressure compensation table [fixes after test]

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h

idle uses fast callback

---

firmware/controllers/algo/fuel/injector_model.cpp
firmware/tunerstudio/tunerstudio.template.ini

also small comment about units used
see #7594 #7624

Fuel mass compensation should use HP sensor

---

java_console/io/src/main/java/com/rusefi/tools/online/HttpUtil.java
java_console/io/src/testFixtures/java/com/rusefi/proxy/client/LocalApplicationProxy.java
java_console/shared_ui/src/main/java/com/rusefi/tools/online/Online.java

related docs:
https://hc.apache.org/httpcomponents-client-5.4.x/migration-guide/index.html
https://hc.apache.org/httpcomponents-client-5.4.x/migration-guide/preparation.html

HttpClient 5.x [Preparation steps] see #7551

---

java_console/io/src/main/java/com/rusefi/binaryprotocol/BinaryProtocol.java
java_console/io/src/testFixtures/java/com/rusefi/proxy/MockIniFileProvider.java

…e is not reliable via real network? #7617
only:proteus_f7

smaller blocking_factor defect

---

java_console/io/src/main/java/com/rusefi/binaryprotocol/BinaryProtocol.java
java_console/io/src/testFixtures/java/com/rusefi/proxy/MockIniFileProvider.java

TCP proxy is not reliable #7617

---

java_tools/configuration_definition/src/test/java/com/rusefi/test/GetConfigValueConsumerTest.java
java_tools/configuration_definition/src/test/java/com/rusefi/test/OutputsTest.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/ParsingException.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/ReaderStateImpl.java

only:complete line into exception

code generation to validate autoscale #7508

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread_io.cpp
firmware/controllers/engine_controller.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

taper down transition into idle duration should be configurable #7616

---

firmware/config/engines/ford_festiva.cpp
firmware/config/engines/honda_k_dbc.cpp
firmware/config/engines/hyundai.cpp
firmware/config/engines/mazda/mazda_miata_na8.cpp
firmware/config/engines/mazda/mazda_miata_vvt.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/defaults/default_cranking.cpp
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/test_idle_controller.cpp

cranking IAC position should be a curve by engine temperature

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/actuators/test_etb.cpp

DC motor wastegate feed forward 2D table see #7150

---

unit_tests/tests/ignition_injection/test_ignition_state.cpp
unit_tests/tests/tests.mk

TDD for smoother idle threshold timing transition see #7498

---

firmware/controllers/actuators/alternator_controller.cpp
firmware/controllers/actuators/alternator_controller.h
unit_tests/tests/actuators/test_alternator.cpp

alternator uses closed loop controller see #5718

---

unit_tests/tests/actuators/test_vvt.cpp

as side-effect now the coverage of this test indirectly tests the PWM output (since I have to call onFastCallback at least once)

VVT remember state [fix test_vvt.cpp]

---

firmware/controllers/actuators/vvt.cpp
firmware/controllers/actuators/vvt.h
unit_tests/tests/actuators/test_vvt.cpp

VVT remember state

---

.vscode/settings.json
firmware/controllers/lua/examples/Dyno-Dynamics.lua
firmware/controllers/lua/examples/utils-can-dbc.lua
firmware/controllers/lua/examples/utils-print-array.lua

https://github.com/rusefi/rusefi/issues/7714

DynoDynamics message parser

---

firmware/tunerstudio/tunerstudio.template.ini

Touches only ini files, should not affect any FW logic.
From this:
To this:

ETB/EWG UI

---

firmware/controllers/sensors/impl/ego.cpp
firmware/controllers/sensors/impl/ego.h
firmware/init/sensor/init_lambda.cpp
firmware/init/sensor/init_sensors.cpp

related issue: #7717
A bit of tech debt resolved and now it's easier to support N amount of lambda sensors

Lambda1/Lambda2 exp average smoothing [preparation] see #7717

---

firmware/console/status_loop.cpp
firmware/controllers/sensors/impl/ego.cpp
firmware/controllers/sensors/impl/ego.h
firmware/init/sensor/init_lambda.cpp

resolves #7718 
demo on simulator
[afr_smooth.webm](https://github.com/user-attachments/assets/94a9fd0a-204b-4bfe-8411-6144e76bd078)

Lambda1/Lambda2 exp average smoothing see #7718

---

firmware/controllers/algo/engine_configuration_defaults.h
firmware/controllers/algo/ignition/ignition_state.cpp
firmware/controllers/algo/launch_control.cpp
firmware/controllers/algo/shift_torque_reduction_controller.cpp
firmware/controllers/algo/shift_torque_reduction_controller.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/shift_torque_reduction/test_shift_torque_reduction_angle_advance.cpp
unit_tests/tests/util/test_engine_configuration.cpp

new UI: (all X axis are independent)

quick shift scalars to become tables

---

unit_tests/tests/core/test_main_loop.cpp
unit_tests/tests/tests.mk

added new coverage for operators & func
resolves #7764

LoopPeriod operators unit test see #7764

---

firmware/controllers/core/main_loop.cpp
firmware/controllers/core/main_loop.h
firmware/controllers/core/main_loop_controller.h
firmware/controllers/thread_priority.h
firmware/development/perf_trace.h
firmware/hw_layer/adc/adc_subscription.cpp
simulator/simulator/rusEfiFunctionalTest.cpp
unit_tests/tests/core/test_main_loop.cpp
unit_tests/tests/system/test_periodic_thread_controller.cpp

execute critical tasks on one big thread see [preparation] #7760

---

firmware/console/status_loop.cpp
firmware/controllers/sensors/impl/ego.cpp
firmware/controllers/sensors/impl/ego.h
firmware/init/sensor/init_lambda.cpp
firmware/init/sensor/init_sensors.cpp

revert for fix issue:
https://github.com/rusefi/rusefi/issues/7755
will reopen:
https://github.com/rusefi/rusefi/issues/7718

revert SmoothedLambda changes

---

firmware/controllers/thread_priority.h

main_loop: should have highest priority

---

firmware/console/status_loop.cpp
firmware/controllers/sensors/impl/ego.cpp
firmware/controllers/sensors/impl/ego.h
firmware/init/sensor/init_lambda.cpp

Re-added smoothedLambda without the modifications to the ego code
related issue: #7755

fix: can assign o2 input to a duplicate channel see #7755

---

firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
unit_tests/tests/ignition_injection/test_fuel_math.cpp

add tests to getCycleFuelMass see #7567

---

firmware/config/engines/custom_engine.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle_impl.h
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/init/sensor/init_tps.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

ETB: support EWG position sensor calibration

---

firmware/config/boards/hellen/alphax-silver/board_configuration.cpp
firmware/config/boards/hellen/alphax-silver/board_engine_configuration.txt
firmware/config/boards/hellen/alphax-silver/board_options.ini

https://github.com/rusefi/rusefi/issues/7825

7825 silver fatal

---

firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/lua/lua.cpp
firmware/util/cli_registry.cpp
firmware/util/datalogging.cpp
firmware/util/loggingcentral.cpp

std::strlen

---

java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/TableData.java
java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/TuneCanTool.java

new `getParentReference` for use on tests of #7833
related issue: #7832
logs of generated files: https://gist.github.com/FDSoftware/b9a6f8e7122000ee363e9ad7e029b545

TuneCanTool does not produce valid code for GPPWM see #7832

---

firmware/config/boards/kinetis/board_configuration.cpp
firmware/config/boards/prometheus/board_configuration.cpp
firmware/config/engines/bmw_m73.cpp
firmware/config/engines/custom_engine.cpp
firmware/config/engines/honda_k_dbc.cpp
firmware/config/engines/mazda/mazda_miata_1_6.cpp
firmware/config/engines/mazda/mazda_miata_vvt.cpp
firmware/config/engines/nissan_vq.cpp
firmware/config/engines/subaru.cpp
firmware/controllers/algo/defaults/default_cranking.cpp
firmware/controllers/algo/engine_state.txt
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/ignition_injection/injection_mode_transition.cpp
unit_tests/tests/ignition_injection/test_fuel_map.cpp
unit_tests/tests/ignition_injection/test_fuel_math.cpp
unit_tests/tests/ignition_injection/test_odd_firing_engine.cpp
unit_tests/tests/ignition_injection/test_startOfCrankingPrimingPulse.cpp
unit_tests/tests/trigger/test_fasterEngineSpinningUp.cpp
unit_tests/tests/util/injection_crank_helper.h

related issue #7567
TS Diff report:
new UI:

cranking base fuel and cranking coolant multiplier see #7567

---

java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/TuneCanTool.java
java_tools/tune-tools/src/test/java/com/rusefi/tune/TuneCanToolTest.java

resolves #7833 also closes #7832

improve unit test coverage for TuneCanTool see #7833

---

firmware/config/boards/kinetis/board_configuration.cpp
firmware/config/boards/prometheus/board_configuration.cpp
firmware/config/engines/bmw_m73.cpp
firmware/config/engines/custom_engine.cpp
firmware/config/engines/honda_k_dbc.cpp
firmware/config/engines/mazda/mazda_miata_1_6.cpp
firmware/config/engines/mazda/mazda_miata_vvt.cpp
firmware/config/engines/nissan_vq.cpp
firmware/config/engines/subaru.cpp
firmware/controllers/algo/defaults/default_cranking.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/ignition_injection/injection_mode_transition.cpp
unit_tests/tests/util/injection_crank_helper.h

crankingCycleFuelCoef => crankingCycleBaseFuel see #7847

---

firmware/controllers/lua/examples/suzuki_can_dash

Speedo, rpm and clt with sweep startup. 
PB1 pin(BTN1 on uaefi) assigned to CEL

2004-2010 swift can dashboard

---

firmware/console/binary_log/binary_logging.cpp
firmware/console/binary_log/log_field.h

only:unit tests
(cherry picked from commit 44ba3a44d16961031f48186d905e5450be3bca6f)

"smarter" needsEngineOffsetHack, the hack goes deeper?

---

firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/modules/map_averaging/map_averaging.cpp

[2025-05-12_12.02.35.mlg.zip](https://github.com/user-attachments/files/20164772/2025-05-12_12.02.35.mlg.zip)

enable MapAveraging on simulator

---

firmware/controllers/modules/map_averaging/map_averaging.cpp
firmware/controllers/modules/map_averaging/map_averaging.h
unit_tests/tests/controllers/modules/map_averaging/test_map_averaging.cpp

test coverage for window sampling single/multiple cyl

---

firmware/controllers/core/main_loop.cpp
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/hardware.cpp

Part of 01a397094d3305058966c396e553d0fcab95c11d

main_loop: add ADC to main loop

---

firmware/controllers/modules/map_averaging/map_averaging.cpp
firmware/controllers/modules/map_averaging/map_averaging.h
firmware/controllers/trigger/trigger_central.cpp
unit_tests/tests/controllers/modules/map_averaging/test_map_averaging.cpp

* added `mapPerCylinder` / `mapAveragingSamples` vars
~* added new config `useNewMapAveragingAngles` temporary until we finish the transition~
~still WIP, i need to add the new config to TS & try adding a couple of new tests~

Map averager uses onEnginePhase

---

firmware/hw_layer/ports/stm32/stm32_can.cpp

https://github.com/rusefi/rusefi/issues/7997

ports: stm32: add 33Kbit settings

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.h
firmware/integration/ts_protocol.txt
firmware/tunerstudio/tunerstudio.template.ini

TS: pages support: paged write command

---

java_console/io/src/main/java/com/rusefi/core/ISensorHolder.java
java_console/io/src/main/java/com/rusefi/core/SensorCentral.java
java_console/models/src/main/java/com/rusefi/core/Sensor.java

using offsets from .ini file
only:bugfix

only adding blend Y to output_channels.txt breaks HW CI #7838

---

firmware/console/binary/output_channels.txt
java_console/io/src/main/java/com/rusefi/core/ISensorHolder.java
java_console/io/src/main/java/com/rusefi/core/SensorCentral.java
java_console/models/src/main/java/com/rusefi/core/Sensor.java

only adding blend Y to output_channels.txt breaks HW CI

---

firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_state.h

output_channels: move stftCorrection to engine_state.txt

---

firmware/controllers/lua/generated/value_lookup_generated.cpp
firmware/controllers/lua/generated/value_lookup_generated.md
firmware/util/efitime.h

@awpe please document pros and cons, looks like a three line snippet (hack?) is being replaced with a lot of nicely documented magic?

todo: document pros and cons

---

firmware/controllers/math/closed_loop_idle.cpp
firmware/controllers/math/closed_loop_idle.h

readable from https://github.com/libnidsj/rusefi

network: closed_loop_idle 

---

java_console/autoupdate/src/main/java/com/rusefi/autoupdate/Autoupdate.java
java_console/shared_io/src/main/java/com/rusefi/core/FindFileHelper.java
java_console/ui/src/main/java/com/rusefi/maintenance/DfuFlasher.java
java_console/ui/src/main/java/com/rusefi/maintenance/MaintenanceUtil.java
java_console/ui/src/main/java/com/rusefi/maintenance/jobs/StLinkJob.java

removed all references to FIRMWARE_BIN_FILE, replace with function

console to look for all files using pattern, preparation

---

unit_tests/tests/controllers/algo/test_closed_loop_idle.cpp
unit_tests/tests/tests.mk

close_loop_idle

---

java_console/io/src/main/java/com/rusefi/io/CommunicationThreadFactory.java
java_console/io/src/main/java/com/rusefi/io/LinkManager.java
java_console/ui/src/main/java/com/rusefi/SerialPortScanner.java

Fix connection to COM port to restore previous calibrations #8143

---

firmware/config/engines/hyundai.cpp
unit_tests/tests/test_change_engine_type.cpp

this replaces https://github.com/rusefi/rusefi/pull/7891 PR

fix changeEngineType test

---

java_console/io/src/main/java/com/rusefi/io/CommunicationThreadFactory.java
java_console/io/src/main/java/com/rusefi/io/LinkManager.java

now we use `AtomicReference` to improve thread-safety (#8143)

---

firmware/console/binary/live_data.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_state.txt
firmware/controllers/long_term_fuel_trim.cpp
firmware/controllers/long_term_fuel_trim.h
firmware/controllers/long_term_fuel_trim_state.txt
firmware/integration/LiveData.yaml
firmware/tunerstudio/tunerstudio.template.ini

LTFT: UI: activity indicators

---

java_console/autotest/src/main/java/com/rusefi/maintenance/TestTuneMigrationContext.java
java_console/ui/src/main/java/com/rusefi/maintenance/migration/ComposedTuneMigrator.java
java_console/ui/src/main/java/com/rusefi/maintenance/migration/DisplacementIniFieldMigrator.java
java_console/ui/src/test/java/com/rusefi/maintenance/migration/displacement_migration/DisplacementIniFieldMigratorTest.java

implement migration of `displacement` ini field

---

firmware/controllers/actuators/boost_control.cpp
firmware/controllers/actuators/boost_control.h
firmware/controllers/algo/defaults/default_base_engine.cpp
firmware/controllers/modules/fan_control/fan_control.cpp
firmware/controllers/modules/fan_control/fan_control.h

setDefaultConfiguration callbacks for fan and boost modules

---

unit_tests/tests/controllers/can/test_can_wideband.cpp

smoothed lambda on can wbo tests

---

firmware/controllers/sensors/impl/AemXSeriesLambda.cpp

Fix for f6bf55f1dd265d4475afaf0779ac7c9bb850aabb

CAN WBO: ups, filter!

---

firmware/config/engines/mazda/mazda_miata_1_6.cpp
firmware/config/engines/mazda/mazda_miata_base_maps.cpp
firmware/config/engines/mazda/mazda_miata_base_maps.h

part of : https://github.com/rusefi/rusefi/issues/7567 https://github.com/rusefi/rusefi/pull/8178

replace crankingFuelBins on mazda_miata_1_6.cpp for crankingCycleBaseFuel

---

unit_tests/tests/trigger/test_trigger_decoder.cpp

New function to test trigger only, not the entire combo of engine+trigger
related https://github.com/rusefi/rusefi/issues/7964

nissan primera preparation

---

firmware/config/engines/engines.mk
firmware/config/engines/mitsubishi_4G93.cpp
firmware/config/engines/mitsubishi_4G93.h
firmware/controllers/algo/engine_type_e.h
firmware/controllers/algo/engine_type_impl.cpp

related: https://github.com/rusefi/rusefi/issues/7964

remove Mitsubishi 4G93 configs

---

firmware/bin/detect_github.sh

fixing make from inside unit_tests folder

---

unit_tests/tests/test_idle_controller.cpp

add RunningToIdleTransition test see #8206

---

firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/accel_enrichment.h

tpsTpsAccelTable map3d => interpolate3d - see #8202

---

unit_tests/readme.md

add testing notes about most used things

---

firmware/integration/rusefi_config.txt

Map estimation tooltip on table editor see #8210

---

firmware/console/binary/tunerstudio.cpp

better handling of missing TS page

---

firmware/config/boards/hellen/alphax-2chan/board_configuration.cpp
firmware/config/boards/hellen/alphax-4K-GDI/board_configuration.cpp
firmware/config/boards/hellen/alphax-4chan/board_configuration.cpp
firmware/config/boards/hellen/alphax-8chan-revA/board_configuration.cpp
firmware/config/boards/hellen/alphax-8chan/board_configuration.cpp
firmware/config/boards/hellen/alphax-gold/board_configuration.cpp
firmware/config/boards/hellen/alphax-silver-revA/board_configuration.cpp
firmware/config/boards/hellen/alphax-silver/board_configuration.cpp
firmware/config/boards/hellen/hellen154hyundai_f7/board_configuration.cpp
firmware/config/boards/tdg-pdm8/board_configuration.cpp

moved all the boards, one per commit, next-step review the rest of the repositories?
related: #8249

migration from boardInitHardware to custom_board_InitHardware

---

.github/workflows/build-unit-tests.yaml
unit_tests/readme.md
unit_tests/upload_coverage.sh

also fix the new error on the upload of the test coverage, next time i should setup a random server to try this before :c

more test docs [code coverage], see #8226 

---

firmware/util/containers/table_helper.h

resolves https://github.com/rusefi/rusefi/issues/8202

Map3D docs, only:docs

---

Makefile

Clean up after AI... Now IDEs can easily pickup files for index

Master Makefile should be more IDE friendly

---

unit_tests/tests/controllers/test_long_term_fuel_trim.cpp

LTFT testSlowCallbackLoadError

---

java_tools/configuration_definition_base/src/main/java/com/rusefi/TokenUtils.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/output/TsOutput.java

For `formatTemperatureTsInfo` on #8313 I need to use the same for/append logic, so extracted to `tokenUtils`

new function tokensToString on TsOutput.java

---

java_tools/configuration_definition_base/src/main/java/com/rusefi/output/TsOutput.java

same/part of https://github.com/rusefi/rusefi/pull/8313 pr, but separating on small changes, here I only organize code different, I need to call this `writeFieldJob` 2 times for the C/F case, since I need to write the conditional, but don't move the `FieldIterator` size or `tsPosition`, which would happen if I call `writeOneField` recursively

separate "writeOneField" callback from writing scalars/arrays/bits on the final .ini on TsOutput.java

---

java_tools/configuration_definition_base/src/main/java/com/rusefi/ConfigField.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/ConfigFieldImpl.java

Last small bit before #8313 pr

add support for overriding tsInfo in ConfigField and ConfigFieldImpl

---

unit_tests/tests/sensor/test_sensor_init.cpp

initTps ford tps/pps test

---

java_console/ui/src/main/java/com/rusefi/maintenance/CalibrationsHelper.java

Fix migration of disappeared .ini-fields

---

firmware/controllers/bench_test.cpp
firmware/controllers/long_term_fuel_trim.cpp
firmware/controllers/long_term_fuel_trim.h
firmware/tunerstudio/tunerstudio.template.ini

Also "Fill with random" button template added. This one is going to be used for tests.

LTFT: reset button

---

firmware/console/binary/live_data.cpp
firmware/controllers/generated/rusefi_generated_mre-legacy_f4.h
firmware/controllers/long_term_fuel_trim.cpp
firmware/controllers/long_term_fuel_trim.h
firmware/controllers/long_term_fuel_trim_state.txt
firmware/controllers/math/closed_loop_fuel.cpp
firmware/controllers/math/closed_loop_fuel_cell.h
firmware/controllers/math/short_term_fuel_trim_state.txt
firmware/integration/rusefi_config_shared.txt
firmware/tunerstudio/tunerstudio.template.ini

1. TS is requested to refresh LTFT tables every second
2. STFT: indicators showing learning and correction status
3. LTFT: counters showing hits/miss/deadband

LTFT and STFT UI update

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

Resolves: #607
needs: #8313
Migration of all tables/values/curves from "C" to "SPECIAL_CASE_TEMPERATURE", one per commit

migrate all temperature configs to "SPECIAL_CASE_TEMPERATURE" unit

---

firmware/config/engines/mazda/mazda_miata_1_6.cpp
firmware/config/engines/mazda/mazda_miata_na8.cpp
firmware/config/engines/mazda/mazda_miata_vvt.cpp
firmware/config/engines/vw_b6.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
firmware/controllers/actuators/idle_thread_io.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/rusefi_enums.h
unit_tests/tests/controllers/algo/test_closed_loop_idle.cpp
unit_tests/tests/test_idle_controller.cpp

migrate idle mode typedef enum to enum class

---

firmware/config/boards/f407-discovery/board_configuration.cpp
firmware/console/binary/tunerstudio.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/hw_layer/board_overrides.h

new functions & one migration as example, next pr all migrations inside this repo
related #8269

custom_board_ConfigOverrides / custom_board_DefaultConfiguration

---

firmware/controllers/trigger/trigger_central.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_comp.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_exti.cpp
unit_tests/test-framework/logicdata_csv_reader.cpp
unit_tests/tests/trigger/test_real_subaru_ej20g.cpp

WIP: Subaru ej20g separate triggers

---

firmware/hw_layer/sensors/max3185x.cpp

@zed65 can you check that this does not breaks EGT in your setup?

EGT: support max6675

---

java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/MetaHelper.java
java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/TuneCanTool.java
java_tools/tune-tools/src/test/java/com/rusefi/tune/TuneCanToolTest.java

gradle VS idea tests

---

firmware/controllers/can/rusefi_wideband.cpp
firmware/controllers/can/rusefi_wideband.h

Small step of https://github.com/rusefi/rusefi/issues/8222

rusefi_wideband: extract/export helper

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
java_tools/configuration_definition/src/test/java/com/rusefi/test/TsOutputTest.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/output/TsOutput.java

new .ini:
new ui:
related https://github.com/rusefi/rusefi/issues/4788

Freedom psi first implementation

---

firmware/integration/rusefi_config.txt
java_tools/configuration_definition/src/test/java/com/rusefi/test/TsOutputTest.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/output/TsOutput.java

more freedom!
docs + `SPECIAL_CASE_SPEED` now working + test + some fields migrated

imperial units speed progress

---

firmware/config/boards/cypress/board_configuration.cpp
firmware/config/boards/hellen/hellen-112-17/board_configuration.cpp
firmware/config/boards/hellen/hellen-honda-k/board_configuration.cpp
firmware/config/boards/hellen/hellen121nissan/board_configuration.cpp
firmware/config/boards/hellen/hellen88bmw/board_configuration.cpp
firmware/config/boards/hellen/super-uaefi/board_configuration.cpp
firmware/config/boards/hellen/uaefi/board_configuration.cpp
firmware/config/boards/kinetis/board_configuration.cpp
firmware/config/boards/subaru_eg33/board_configuration.cpp
firmware/config/engines/bmw_m73.cpp
firmware/config/engines/custom_engine.cpp
firmware/config/engines/dodge_neon.cpp
firmware/config/engines/ford_festiva.cpp
firmware/config/engines/hyundai.cpp
firmware/config/engines/subaru.cpp
firmware/config/engines/test_engine.cpp
firmware/config/engines/vw.cpp
firmware/console/status_loop.cpp
firmware/controllers/algo/defaults/default_base_engine.cpp
firmware/controllers/algo/defaults/default_ignition.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/controllers/engine_cycle/high_pressure_fuel_pump.cpp
unit_tests/test-framework/engine_test_helper.cpp
unit_tests/tests/ignition_injection/test_fuel_math.cpp
unit_tests/tests/test_engine_math.cpp

Preparing first enum for enum generator

---

firmware/rusefi_rules.mk
unit_tests/mocks.h

Missing override

---

firmware/controllers/algo/defaults/default_base_engine.cpp
firmware/init/sensor/init_maf.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

exp average with code duplication

MAF Filtering #7952

---

java_tools/configuration_definition/src/main/java/com/rusefi/ConfigDefinition.java
java_tools/configuration_definition/src/main/resources/config_definition.options

only passive read

---

java_console/io/src/main/java/com/rusefi/libopenblt/XcpLoader.java

XCPLOADER_CMD_PROGRAM_RESET doesn't respond, its correct

OpenBlt: catch exception at the end, it's ok #8495

---

java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/TuneTools.java
java_tools/tune-tools/src/test/java/com/rusefi/tune/LoadOlderTuneTest.java

Enhance define expansion

---

java_console/ui/src/main/java/com/rusefi/maintenance/migration/BinsIniFieldMigrator.java
java_console/ui/src/main/java/com/rusefi/maintenance/migration/ComposedTuneMigrator.java
java_console/ui/src/main/java/com/rusefi/maintenance/migration/TableAddColumnsMigrator.java
java_console/ui/src/main/java/com/rusefi/maintenance/migration/VeRpmBinsIniFieldMigrator.java
java_console/ui/src/main/java/com/rusefi/maintenance/migration/VeTableExtensionMigrator.java
java_console/ui/src/test/java/com/rusefi/maintenance/migration/VeRpmBinsIniFieldMigratorTest.java
java_console/ui/src/test/java/com/rusefi/maintenance/migration/batt_lag_corr_migration/BattLagCorrMigratorTest.java
java_console/ui/src/test/java/com/rusefi/maintenance/migration/clt_idle_corr_migration/CheckIfOverrideCrankingIacSettingHasDisappearedTest.java

Refactor `VeTableExtensionMigrator` class to reuse code of adding columns to arbitrary table

---

firmware/controllers/actuators/idle_thread.cpp

proper update of ac while compressor

---

firmware/tunerstudio/tunerstudio.template.ini
java_tools/configuration_definition/src/test/java/com/rusefi/test/TsOutputTest.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/output/TsOutput.java

un-doing the change for now, too fragile in terms of existing projects

Please make UI in Freedom Fahrenheit units Celsius PSI KPA #4788

---

java_console/inifile/src/main/java/com/opensr5/ini/IniFileModelImpl.java

BlockingFactor on TCP connection: add a note

---

firmware/controllers/algo/obd_error_codes.h
firmware/controllers/trigger/trigger_central.cpp
unit_tests/tests/trigger/test_real_arctic_cat.cpp
unit_tests/tests/trigger/test_real_ford_coyote.cpp

CUSTOM_PRIMARY_BAD_TOOTH_TIMING_EARLY
CUSTOM_PRIMARY_BAD_TOOTH_TIMING_LATE

trigger central: slice 9007 to 9007/9008 erorrs

---

java_console/ui/src/main/java/com/rusefi/maintenance/CalibrationsHelper.java

add exception logging
