rusefi/rusefi

win32_functional_tests/chconf.h

That should one of the simulator bug (#379)

Missing CHPRINTF_USE_FLOAT in simulator's chconf.h

---

firmware/controllers/algo/accel_enrichment.cpp

If the target fuel was very small, and there was lots of fuel on the wall, you could get an injector pulse of <0.  This will inject no fuel (like a pulse of 0ms would), but will more importantly screw up the estimate for how much fuel is on the wall.  If the pulse went negative, the model would update as though the injector had sucked fuel back in to the tank.

Fix accel enrichment for negative fuel pulse

---

firmware/bootloader/src/dfu.h
firmware/bootloader/src/main.cpp
firmware/config/boards/ST_STM32F4/board.c
firmware/config/boards/ST_STM32F4/board.h
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/engine_configuration.h

The bootloader should set a correct pin state for the board (first of all, the default ignition coils state), otherwise some peripherals would be damaged.

Bootloader set default pin states

---

firmware/console/status_loop.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
firmware/controllers/obd2.cpp
firmware/controllers/trigger/main_trigger_callback.cpp

Alpha-version. Partially tested on mono-injector, the result is close to the real measured consumption. 
The code is nicely integrated into existing 'FuelConsumptionState' dummy class.
Also, it would be great to add 'tsOutputChannels->fuelConsumptionPerHour' to output the value...

Fuel consumption impl. (alpha)

---

firmware/hw_layer/sensors/CJ125.cpp

Oops. Some debug code left...
Call to cjPostState() should be only in status_loop.cpp and only for debugMode==DBG_CJ125.

Fix CJ125 postState() debug output

---

firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/engine_configuration_generated_structures.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/rusefi_generated.h
firmware/controllers/trigger/main_trigger_callback.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.ini
java_console/models/src/com/rusefi/config/Fields.java
unit_tests/test_fuelCut.cpp

This PR solves two problems:
1) When fuel is cut, getInjectionDuration returns zero duration, so that no fuel is injected (as desired).  However, when handleFuelInjectionEvent goes to schedule the opening and closing of the injectors schedules two events very close together (sometimes exactly on top of each other).  These events sometimes get swapped in order of execution by the scheduler, so the injector will STICK OPEN FLOODING THE ENGINE.  I discovered this when driving, and the coasting fuel cut caused my O2 sensors to read full scale rich.
Here's an example of that condition while running on the bench.  Note that it sometimes sticks open, and sometimes doesn't because it's a tossup between whether the opening or closing event gets scheduled first.
This fix for this problem adds a …

Coasting Fuel Cut Fixes

---

simulator/compile.bat
simulator/make_run.bat

"-r, --no-builtin-rules      Disable the built-in implicit rules."
Faster build on some environments.

Simulator make: add -r option

---

firmware/controllers/system/DcMotor.cpp
firmware/controllers/system/DcMotor.h

Adds documentation for DcMotor, this is basically the contents of the PR I was going to submit before @rusefi beat me to the punch :)
Unit tests compile & run fine (though there are no DcMotor tests yet) using `gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)`.  Compiles and runs fine on stm32f4 using `gcc version 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] (GNU Tools for Arm Embedded Processors 7-2018-q3-update)`.  So I'm not sure what russian was running in to earlier with virtual method misbehavior.

Documentation for DcMotor

---

firmware/controllers/algo/aux_pid.cpp
firmware/controllers/alternatorController.cpp
firmware/controllers/electronic_throttle.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/idle_thread.cpp
firmware/controllers/injector_central.cpp
firmware/controllers/malfunction_indicator.cpp
firmware/controllers/math/biquad.cpp
firmware/controllers/system/pwm_generator_logic.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/development/engine_emulator.cpp
firmware/development/wave_analyzer.cpp
firmware/hw_layer/HIP9011.cpp
firmware/hw_layer/accelerometer.cpp
firmware/hw_layer/board_test.cpp
firmware/hw_layer/can_hw.cpp
firmware/hw_layer/microsecond_timer.cpp
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/neo6m.cpp
firmware/hw_layer/sensors/CJ125.cpp
firmware/hw_layer/servo.cpp
firmware/hw_layer/stepper.cpp
firmware/util/listener_array.h

Partial fix for #375 
GCC 8 is way more picky for casting pointers, so we need to make it "forget" the original pointer type by casting to void* first.
Compiles with:
```
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 8-2018-q4-major) 8.2.1 20181213 (release) [gcc-8-branch revision 267074]
```
Tried with/without LTO, softp and hardfp.
Not tested on actual hardware.

Workarounds for GCC 8

---

firmware/Makefile
firmware/config/engines/dodge_neon.cpp
firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/engine_configuration_generated_structures.h
firmware/controllers/algo/rusefi_generated.h
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.ini
firmware/tunerstudio/rusefi.input
firmware/util/efilib.cpp
firmware/util/efilib.h
java_console/autotest/src/com/rusefi/AutoTest.java
java_console/models/src/com/rusefi/config/Fields.java
java_console/ui/src/com/rusefi/ui/SettingsTab.java
unit_tests/Makefile
unit_tests/test.mk
unit_tests/test_basic_math/test_efilib.cpp

Previously, AE used a constant for "amount of fuel sucked from wall in one cycle" when in fact that's not how gasoline works.  There's an amount of gasoline sucked off the wall PER TIME, not PER CYCLE.  This change replaces the per-cycle parameter with a time constant (tau) parameter instead.

Improve wall wetting AE to use time constant

---

firmware/hw_layer/stm32f4/mpu_util.cpp

Setting SPI pins to high speed mode fixes #663.  This isn't required on non-f405/407/415/417 parts, but the vast majority of MCUs running rusEfi are f407.  No negative consequence on chips that don't require the workaround.
Info on the silicon defect can be found in this document, section 2.5.2:
https://www.st.com/content/ccc/resource/technical/document/errata_sheet/0a/98/58/84/86/b6/47/a2/DM00037591.pdf/files/DM00037591.pdf/jcr:content/translations/en.DM00037591.pdf

Implement ST-recommended workaround for #663

---

firmware/hw_layer/hw_layer.mk
firmware/hw_layer/trigger_input.cpp

Use EXTI for trigger inputs.
Tested on custom stm32f765 board using trigger simulation.
Set in halconfig.h
+#define HAL_USE_PAL                            TRUE
+#define PAL_USE_CALLBACKS              TRUE

trigger input: add PAL support

---

firmware/config/engines/custom_engine.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/core/fsio_impl.cpp

The idea is to separate "hardware" (board-dependent) def-config from "software" def-config.
We remove hw fields from setDefaultConfiguration() and move them into a new setDefaultBoardConfiguration() or prepareVoidConfiguration().
Also, we refactor setMinimalPinsEngineConfiguration() and engineType=MINIMAL_PINS: we want to skip setting hardware pins instead of first setting them and then unsetting.
See multiple comments below on what's going on.
Also, we fix FSIO_ANALOG_INPUT_COUNT.

Default config refactor

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/system/dc_motor.cpp
firmware/controllers/system/dc_motor.h

Fix ETB control for two pin H bridges.
Now 2 and 3 pin h-bridges are properly supported, without whacky behavior at low duty cycle in 2-pin mode.
Here's changing direction on two pin mode, to prove it works!

Fix ETB control for 2 pin H-bridge

---

firmware/controllers/system/efi_gpio.cpp
firmware/hw_layer/io_pins.cpp
firmware/hw_layer/pin_repository.cpp
firmware/hw_layer/pin_repository.h
firmware/hw_layer/ports/stm32/stm32_pins.cpp
firmware/hw_layer/ports/stm32/stm32f1/hw_ports.mk
firmware/hw_layer/ports/stm32/stm32f4/hw_ports.mk
firmware/hw_layer/ports/stm32/stm32f7/hw_ports.mk

The idea is to move all STM32-specific GPIO code to ports/stm32/stm32_pins.cpp and isolate PORT_SIZE.
Not tested!

STM32-specific GPIO refactor (stm32_pins.cpp)

---

firmware/Makefile

Improves perf a bit, and saves ~10% `.text` and `.data` space.

Enable link time optimization

---

firmware/hw_layer/AdcConfiguration.h
firmware/hw_layer/adc_inputs.cpp
firmware/hw_layer/hardware.cpp

On ARM Cortex M7, only the CPU can invalidate the CPU cache.  So when DMA writes to SRAM, the CPU doesn't know it should re-read.  This change adds an invalidate to the ADC's sample buffer before reading it, so we force a read from SRAM, actually loading the new values.
Fixes #854

Fix F7 ADC #854

---

firmware/config/boards/nucleo_f767/STM32F76xxI.ld

Move stacks (and heap - which we don't use) to DTCM - this certainly won't hurt performance, and will reduce bus contention (not that we had a problem with that).

Relocate pstack/mstack to DTCM

---

firmware/controllers/system/efi_gpio.cpp

If we set the output state (ie high vs low) before enabling the pin, we prevent a spurrious blip.
This manifested as (and was discovered by) ignition outputs giving a 400ns-1us blip as they were initialized.  This change prevents any such blips from occurring by setting the state of the pin before we actually enable it, so it will immediately do the right thing.

Fix mystery 400ns-1us pulse at MCU startup

---

firmware/console/binary/tunerstudio.cpp

Kill some dead code, convert the main TS handler to a switch, and use `static_assert`.

Tunerstudio.cpp cleanup

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_io.h
firmware/console/console.mk
firmware/console/tooth_logger.cpp
firmware/console/tooth_logger.h
firmware/controllers/trigger/trigger_central.cpp
firmware/tunerstudio/rusefi.input

This change adds support for tooth logging in TS.
Right now it only logs the falling edge of the primary trigger, as this is the useful one if you're diagnosing a VR sensor.  (note that if you have the trigger set to invert, it'll use the rising edge, as then that's the "logical" falling edge).
Also works with self stimulation, since it's in the same path that the real trigger uses.

Implement TS tooth logger

---

firmware/config/boards/nucleo_f767/board.mk

Filesystems other than NTFS (for example, `ext4` on Linux) are case sensitive.

Fix build for case-sensitive filesystems

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/map_averaging.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/sensors/ego.cpp
firmware/controllers/trigger/aux_valves.cpp
firmware/hw_layer/sensors/cj125.cpp
firmware/util/math/interpolation.cpp
firmware/util/math/interpolation.h
unit_tests/afm2mapConverter.cpp
unit_tests/test_basic_math/test_find_index.cpp

Switch `interpolate2d` to use a template parameter for the `size` argument.  Since it's known at compile time, we can use the compiler to make guarantees about the things we're passing in.
This allows for the following:
1) `bins` and `values` must be arrays - not bare pointers
1) The length of the `bins` and `values` arrays must match
2) You can't pass in a length that isn't correct for the bins/values you've passed in (buffer overrun is difficult or impossible).  The compiler will deduce the correct `TSize` value by the arrays that are passed in.
I have some more changes coming that will further leverage this, and clean up table consumption, so we don't have to pass bins/values/name every time.

Template-ize bin/value length for interpolation

---

firmware/console/status_loop.cpp
firmware/controllers/actuators/lcd_controller.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/obd2.cpp
firmware/controllers/sensors/maf.cpp
firmware/controllers/sensors/maf.h
unit_tests/tests/test_engine_math.cpp
unit_tests/tests/test_trigger_decoder.cpp

- Remove maf decoding cache.  It isn't on a particularly hot path, so the negligable performance gains aren't worth it.  Also, chopping down to 0.2 volt increments loses so much resolution that MAF wouldn't actually work very well.
- `getMafVoltage` now gets the voltage at the maf pin
- `getRealMaf` gets the mass flow rate, in kg/hr (TODO: should we do kg/s or g/s instead?
This change makes a negligible change to compiled image size, but saves 1KB (!) of RAM.

Fix some maf logic

---

firmware/integration/rusefi_config.txt

After we fixed PID to properly use `dt`, we don't need so many digits that the string doesn't fit in the text box.
Would you be able to tell that the P-factor is set to 1.5?

Reduce PID significant figures from 7 -> 4

---

firmware/config/engines/bmw_e34.cpp
firmware/config/engines/citroenBerlingoTU3JP.cpp
firmware/config/engines/custom_engine.cpp
firmware/config/engines/dodge_neon.cpp
firmware/config/engines/dodge_ram.cpp
firmware/config/engines/ford_1995_inline_6.cpp
firmware/config/engines/ford_aspire.cpp
firmware/config/engines/ford_festiva.cpp
firmware/config/engines/honda_600.cpp
firmware/config/engines/honda_accord.cpp
firmware/config/engines/mazda_626.cpp
firmware/config/engines/mazda_miata.cpp
firmware/config/engines/mazda_miata_1_6.cpp
firmware/config/engines/mazda_miata_nb.cpp
firmware/config/engines/mazda_miata_vvt.cpp
firmware/config/engines/me7pnp.cpp
firmware/config/engines/mitsubishi.cpp
firmware/config/engines/rover_v8.cpp
firmware/config/engines/toyota_jzs147.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/sensors/thermistors.cpp
firmware/controllers/sensors/thermistors.h
unit_tests/tests/test_sensors.cpp

You can assign a struct just like any other copyable type(int, float, string, etc) - so we don't need a `setThermistorConfiguration` function.
This change also saves 96 bytes of flash, because this change essentially replaces the old function with a (compiler generated) memcpy.

Simplify thermistor config

---

firmware/config/engines/chevrolet_camaro_4.cpp
firmware/controllers/trigger/decoders/trigger_gm.cpp
unit_tests/tests/test_trigger_decoder.cpp

Documentation online said that the teeth are 3 or 12 degrees long.  My car and an oscilloscope says that they're 5 and 10 degrees long (which actually makes more sense).

fix gm 24x decoder

---

firmware/hw_layer/adc_inputs.cpp
firmware/hw_layer/hardware.cpp

We only need to do the cache invalidation if we're actually about to read them, which means we should only do it on complete, not half done.  Same goes for updating ADC subscribers.

low hanging performance fruit

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.h
firmware/console/binary/tunerstudio_configuration.h
firmware/console/status_loop.cpp
firmware/console/tooth_logger.cpp
firmware/controllers/actuators/alternator_controller.cpp
firmware/controllers/actuators/aux_pid.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/scheduling/single_timer_executor.cpp
firmware/controllers/trigger/main_trigger_callback.cpp
firmware/controllers/trigger/spark_logic.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/hw_layer/drivers/gpio/tle8888.c
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/sensors/cj125.cpp
firmware/init/sensor/init_oil_pressure.cpp

After typing it 3 times - I realized we should just move it to the header instead of re-declaring it in every single file.

move extern tsOutputChannels to header

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/trigger/main_trigger_callback.cpp

As shown in #973, both `MainTriggerCallback` and `PeriodicFastCallback` call `GetInjectionDuration`, updating the stored injection duration in the engine state.
The trigger callback calls it for every tooth we actually use (generally all rising or all falling edges).  `GetInjectionDuration` takes about 32us to execute, incurring a 32us cost in every tooth decode interrupt.  On high tooth count triggers, this one call can incur significant CPU cost.  For example, on a 60-2 wheel, it's called 5800 times per second, which amounts to 19% of total CPU load on an STM32F4 at 168MHz.
This change omits the call from MainTriggerCallback, and increases the frequency of the `PeriodicFastCallback` to 200hz to make up for the removal.  Since `PeriodicFastCallback` takes around 100us, this will use a …

Performance improvement: call GetBaseFuel less

---

firmware/console/binary/tunerstudio.cpp
firmware/console/status_loop.cpp
firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/accel_enrichment.h
firmware/controllers/algo/engine.h
firmware/controllers/engine_controller.cpp
firmware/controllers/trigger/main_trigger_callback.cpp
unit_tests/tests/test_fuel_wall_wetting.cpp

Previously, were sharing one state for all cylinders.  This means it would run N times too fast, making the wall wetting parameters wrong.

fix wwae for multi cylinder engines

---

firmware/hw_layer/adc_inputs.cpp

Speed up the slow ADC from 20hz to 200hz, and move channels back to it that needed higher than 20hz speed.  It was really overkill to put those all the way on the 10khz adc (and in fact added some noise), so this change puts them back where they belong.
Related to #976

Increase slow ADC sample rate

---

firmware/config/stm32f7ems/chconf.h
firmware/controllers/core/error_handling.h
firmware/controllers/system/efi_gpio.cpp
firmware/global.h
firmware/util/efilib.h

If you have a header included inside an `extern "C"` block, you need to consider very **very** carefully what you're doing.  Pretty much only function declarations should be inside an `extern "C"`.  No includes, no defines, nothing else.
This change does not alter the compiled binary.

Put back static asserts, fix the mess

---

firmware/util/efilib.h
firmware/util/math/interpolation.h

We use a bit of C++ magic to fix tons of these warnings:
```
util/efilib.h:48:35: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#define cisnan(f) (*(((int*) (&f))) == 0x7FC00000)
^
controllers/error_handling.h:54:59: note: in definition of macro 'efiAssertVoid'
```
Due to the gnu-c++ optimisation, the binary code produced is practically the same as before:
```
87              	@ aliasing-test.cpp:15: 	if (cisnan(oneDegreeUs)) {
88 0010 20309FE5 		ldr	r3, .L6+4	@ tmp118,
89 0014 030050E1 		cmp	r0, r3	@, tmp118
90 0018 0200000A 		beq	.L5	@,
```
But without optimisation it's slightly larger (by 2-3 opcodes), so we leave it as it was for -O0...

cisnan() warnings fix

---

.github/workflows/build-firmware.yaml
.github/workflows/build-simulator.disabled_since_need_32bit_yaml
.github/workflows/build-simulator.yaml
.github/workflows/build-unit-tests.yaml

Build firmware in ci.  This runs both for pushes (ci) and on PRs (gate).
Currently builds firmware for boards [frankenso, mre-f4, mre-f7] and configurations [debug, release].
Edit: also triggers on PR
Edit 2: also fixes simulator build

Add workflow for firmware, fix simulator build, trigger builds on PR

---

firmware/config/engines/dodge_neon.cpp
firmware/config/engines/ford_festiva.cpp
firmware/config/engines/sachs.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/math/speed_density.cpp
firmware/controllers/sensors/map.h
firmware/controllers/settings.cpp
firmware/util/containers/table_helper.cpp
firmware/util/containers/table_helper.h
unit_tests/afm2mapConverter.cpp
unit_tests/engine_test_helper.cpp
unit_tests/tests/test_fuel_map.cpp
unit_tests/tests/test_trigger_decoder.cpp

Don't need to pass length - it's an opportunity for a bug.  Use a `TSize` template parameter to bind the length of the passed array.

Use templated array references

---

firmware/console/binary/tunerstudio.cpp
firmware/development/perf_trace.h

- Use default parameters instead of overloads
- Replace `ScopePerf` implementation when disabled (saves stack space - compiler isn't allowed to rearrange/remove members even if they're unused)

Perf trace housekeeping

---

firmware/config/boards/proteus/board_configuration.cpp
firmware/config/engines/ford_festiva.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/gauges/malfunction_central.cpp
firmware/util/containers/cyclic_buffer.h
firmware/util/efilib.h
firmware/util/math/signal_filtering.c

Saves code and data space by storing constant arrays as arrays, then simply copying them in to place instead of hand setting every element.  The new functions are also useful as they guarantee that you can't overrun the destination array.

copyArray helper

---

firmware/console/binary/tunerstudio.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h

No longer does any logic prod the innards of the ETB controller. Hooray!
~~No longer requires `INJECT_ENGINE_REFERENCE` for `EtbController`!~~ Nope, that was a lie.
Makes naming and conventions more in line with C++ conventions.  That means prefixing member variables with `m_`, and not using `this->` when accessing.
This also fixes the bug that multiple ETBs will overwrite each other's state in the tunerstudio outputs, making the gauges useless.

ETB Encapsulation & C++ Conventions

---

firmware/config/boards/kinetis/chconf.h
firmware/config/stm32f4ems/chconf.h
firmware/config/stm32f7ems/chconf.h
firmware/controllers/global_shared.h

Excerpt from `ChibiOS/os/common/ports/ARMCMx/chcore_v6m.h`:
```
/**
* @brief   Per-thread stack overhead for interrupts servicing.
* @details This constant is used in the calculation of the correct working
*          area size.
* @note    In this port this value is conservatively set to 64 because the
*          function @p chSchDoReschedule() can have a stack frame, especially
*          with compiler optimizations disabled. The value can be reduced
*          when compiler optimizations are enabled.
*/
#if !defined(PORT_INT_REQUIRED_STACK)
#define PORT_INT_REQUIRED_STACK         64
#endif
```
Interrupts are NOT serviced on the stack of the thread that was running when the interrupt occurred.  The only thing that happens on that thread's stack is that its registers are pushed (by …

Make stacks smaller

---

firmware/config/boards/kinetis/chconf.h
firmware/config/stm32f4ems/chconf.h
firmware/config/stm32f7ems/chconf.h
firmware/controllers/engine_controller.cpp
firmware/hw_layer/servo.cpp

Finally got a break in to the debugger under the hardware-in-the-loop test conditions that tripped the stack warning.
The problem is that the servo thread directly calls `scheduleForLater`, which could end up executing events off of the queue.  If the ECU is in self-stimulation mode, one of those events could be firing an emulated trigger event, which could then call a relatively deep call hierarchy (`mainTriggerCallback`, etc) that normally runs on the giant (4k) interrupt stack.
Inspection of the caller tree for `doExecute` reveals that the servo is the only time we do this.  Every other call to `doExecute` is made from an interrupt context.
The short term solution is to simply make that one stack big, instead of all stacks. Longer term solution is to do something different for servo …

Re-shrink stacks

---

firmware/controllers/system/timer/event_queue.cpp

For some reason, dequeuing events from our scheduler queue was a two phase process:
1) move all events that are due to run to their own temporary list
2) execute everything in that list.
I can't come up with a good reason for why we were doing that.
This change simply pops elements off the head one at a time, and executes them, instead of the aforementioned complicated (and slow) logic.
Unit tests pass, but pending testing on real hardware.

DRAFT simplify dequeue logic

---

firmware/console/status_loop.cpp
firmware/controllers/sensors/functional_sensor.cpp
firmware/controllers/sensors/functional_sensor.h
firmware/controllers/sensors/stored_value_sensor.h
firmware/init/sensor/init_oil_pressure.cpp

I had mixed feelings about doing it this way from the beginning - it's a bit weird to have magical side effects, especially when those side effects mutate state from a huge distance away.
It's easier to reason about what's going on when it's explicitly done (set state in the TS output channels struct).

Remove sensor reporting loc

---

firmware/tunerstudio/rusefi.input

Almost nobody has EGT enabled, so we probably shouldn't log it unless the feature is actually enabled.  TS is exerting a lot of effort writing all those zeroes!
note: this is part 1 in a scheme to allow an f4 to log in excess of ~~170hz~~ 205hz

don't log EGT if disabled

---

firmware/tunerstudio/rusefi.input

Same deal as the EGT change.  Doesn't log if you don't have one, but behaves normally otherwise.  Gauges still work, and logging works if the accelerometer is enabled.

only log acc if enabled

---

firmware/tunerstudio/rusefi.input

Add settings to TunerStudio to manually disable logging debug channels & the error list.  These new settings default to "Yes".  That means that unless a user intentionally goes to change the setting, the default behavior **does not change**.
The new settings are normal fields, but only stored in `CurrentTune.msq` without being sent at all to the ECU (in the `[PcVariables]` section of the ini).

add settings to log debug & errors list

---

firmware/config/boards/kinetis/config/controllers/algo/rusefi_generated.h
firmware/console/binary/tunerstudio_configuration.h
firmware/console/binary/tunerstudio_debug_struct.h
firmware/console/status_loop.cpp
firmware/controllers/generated/rusefi_generated.h
firmware/hw_layer/drivers/gpio/tle8888.c
firmware/hw_layer/drivers/gpio/tle8888.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

- Implement `scaled_channel` which allows a scaled output channel (for example, storing quarter-RPM) to be used as though it was a normal float, even though it's backed by a different type.
- Reorder TS output channels in roughly reverse priority order.  Since rarely used channels are at the end, datalogging can be sped up by reading a contiguous block of channels near the beginning that we actually care about (for example, logging up thru `lastErrorCode`, 140 bytes, updates at 210-215hz while datalogging on a debug build on an stm32f4 over USB.  This previously ran at ~90hz).
- This change reduces total output channel size from 356 to 220 bytes
The modifications to `tle8888.h`/`c` were required because that `tunerstudio_configuration.h` now requires c++, so we inject only the debug …

Shrink output channels, use scaling

---

firmware/hw_layer/can_hw.cpp
firmware/hw_layer/can_hw.h

CAN now runs on two threads:
- One that dequeues and processes messages (as fast as it can - dequeue/process loop)
- One that transmits messages (at a defined interval)

Split CAN in to separate threads for rx/tx

---

firmware/controllers/engine_cycle/aux_valves.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/scheduler.h
firmware/controllers/system/timer/signal_executor_sleep.cpp
firmware/hw_layer/servo.cpp
unit_tests/tests/test_signal_executor.cpp

Add a templated constructor so that you don't need a cast, and it verifies that you're passing in the correct type (void* provides no such guarantee, so we have to do it ourselves)

Strongly typed action constructor

---

firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/hw_layer/trigger_input_comp.cpp
firmware/hw_layer/trigger_input_exti.cpp
firmware/hw_layer/trigger_input_icu.cpp
unit_tests/engine_test_helper.cpp
unit_tests/tests/test_cam_vtt_input.cpp
unit_tests/tests/test_miata_na6_real_cranking.cpp

Taking the timestamp long after the interrupt has occurred gives an opportunity for not only a fixed offset error (time elapses between interrupt and timestamp), but also jitter.  The more time that elapses without taking the timestamp, the more time other interrupts could occur (or even different execution time due to branches).
The next work is to inject this timestamp all the way down to listeners - most importantly the logic that schedules ignition events, so that ignition timing is referenced to the actual trigger tooth event, not the trigger tooth event plus however long some logic takes to run (source of both offset error and jitter!).

Inject timestamps in to hwHandleShaftSignal

---

firmware/hw_layer/drivers/gpio/gpio_ext.h
firmware/hw_layer/drivers/gpio/mc33810.c
firmware/hw_layer/drivers/gpio/mc33972.c
firmware/hw_layer/drivers/gpio/tle6240.c
firmware/hw_layer/drivers/gpio/tle8888.c

Not brain_pin_e. Drivers like to see pin number within current
chip.

hw: gpio: use unsigned int as pin number inside gpiochip drives

---

firmware/tunerstudio/rusefi.input

binary data were correct, displayed wrong in TS for negative timing

fix signed ignition timing

---

firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.h

Seems a little silly to convert nt -> us -> nt, doesn't it?

don't use us for pwm calculation

---

firmware/console/status_loop.cpp
firmware/controllers/sensors/tps.cpp
firmware/controllers/sensors/tps.h
firmware/controllers/settings.cpp
unit_tests/tests/test_sensors.cpp

Switch TPS to use 200 "adc counts" per volt, instead of actual ADC counts.  This abstracts the fake ADC counts we give to Tunerstudio away from anything to do with a real ADC.

Rescale TPS

---

firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/engine_cycle/rpm_calculator.h

Return the scheduled timestamp from `scheduleByAngle`, so we can schedule something a fixed time after the first event was scheduled. Removes some duplication of `scheduleByAngle`'s logic in the fuel math.

Simplify fuel math again

---

firmware/controllers/sensors/tps.cpp
firmware/controllers/sensors/tps.h

We never call these functions, they don't need to be exported in the header

tps header cleanup

---

firmware/controllers/algo/engine_configuration.cpp
firmware/init/init.h
firmware/init/sensor/init_oil_pressure.cpp
firmware/init/sensor/init_sensors.cpp
firmware/init/sensor/init_tps.cpp

@960 noted that changing the TPS calibration doesn't take effect until a reboot occurs.  This change reconfigures sensors whenever the configuration changes.

Sensor reconfiguration while running

---

firmware/Makefile
firmware/controllers/core/common_headers.h
firmware/controllers/math/engine_math.cpp
firmware/hw_layer/servo.cpp
firmware/rusefi_rules.mk

Turn back on a bunch of warnings-as-errors we had turned off, even though they never happen.

Stricter compile options

---

firmware/hw_layer/drivers/gpio/tle8888.c

DS is not clear, may be tle8888 clears OE bit in case of error on
output.

tle8888: disable diagnostic for outputs

---

firmware/console/binary/tunerstudio_configuration.h
firmware/util/scaled_channel.h

Split out in to its own header, so we can use it for CAN channels too.

split out scaled channel header

---

firmware/controllers/actuators/dc_motors.cpp
firmware/controllers/actuators/dc_motors.h
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h
firmware/controllers/controllers.mk
firmware/hw_layer/hardware.cpp
unit_tests/tests/test_etb.cpp
unit_tests/tests/test_idle_controller.cpp

Makes sense to reuse the init/config code/storage for h-bridge stepper control, so this needs to get pulled out of the ETB file.

Split out EtbHardware

---

firmware/hw_layer/io_pins.cpp
firmware/hw_layer/pin_repository.cpp

This saves 13kb of flash space.
Calling any non-ChibiOS `printf` function will include the full standard library implementation (so then we have two!), which can also format doubles, so it also pulls in huge software support for doubles. Just the function `_dtoa_r` (double-to-alpha, converts a double to a string) was 3.5KB on an optimized build.

don't use standard sprintf/snprintf

---

firmware/config/boards/nucleo_f746/board.h
firmware/config/boards/nucleo_f767/board.h
firmware/config/boards/st_stm32f4/board.h

We don't need vbus (it's a feature for USB OTG), and this can cause issues if that pin is left floating.

ignore vbus

---

firmware/controllers/can/can_rx.cpp
firmware/controllers/sensors/tps.cpp

needs `EFI_CANBUS_PEDAL` set in `efifeatures.h` to enable it, because we REALLY don't want this enabled for somebody who isn't doing something whacky like running a v12 with two ECUs.

Pedal rx shim

---

firmware/bootloader/src/rusefi_stubs.cpp
firmware/console/console_io.cpp
firmware/controllers/actuators/alternator_controller.cpp
firmware/controllers/actuators/aux_pid.cpp
firmware/controllers/actuators/boost_control.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/gauges/lcd_controller.cpp
firmware/controllers/sensors/ego.cpp
firmware/controllers/settings.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/hw_layer/hardware.cpp
firmware/hw_layer/mc33816_data.c
simulator/simulator/rusEfiFunctionalTest.cpp

This removes a bunch of stuff that the linker was removing because it wasn't actually used in a release build.
This is all fully dead code, or data that didn't actually do anything (data written, never read, sort of thing).

save some ram

---

firmware/config/boards/microrusefi/board_configuration.cpp

As our friends dexter_lab and RecaroRacer on Slack discovered, the MRE default vbatt divider is configured wrong.  The battery voltage code does NOT use the board's analog divider coefficient, so we have to multiply it in manually.  For some reason that was removed in ca1d44a, and I'm not sure why.

Fix mre vbatt

---

firmware/tunerstudio/rusefi.input

1. our fahrenheit support is terrible
2. tunerstudio insists upon defaulting to fahrenheit
3. most of our users probably want celsius anyway (and I've already seen one screenshot where they didn't realize they were set to F)
It turns out if you don't have any `#if CELSIUS` in the ini, then TS doesn't even show the dropdown for units!
Closes #1214.

Goodbye, fahrenheit

---

firmware/config/boards/kinetis/config/controllers/algo/engine_configuration_generated_structures.h
firmware/config/engines/dodge_neon.cpp
firmware/controllers/generated/engine_configuration_generated_structures.h
firmware/hw_layer/adc_inputs.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
firmware/util/util.mk

Fixes #1222: remove old biquad coefficients from config, they're no longer used.
Fixes #1220: Indicates that it's fuel pump and rail, not just rail

TS cleanup pass

---

firmware/console/binary/tunerstudio.cpp
firmware/controllers/actuators/pwm_tester.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/bench_test.cpp
firmware/controllers/bench_test.h
firmware/controllers/controllers.mk
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/gauges/lcd_controller.cpp
firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h
firmware/hw_layer/hardware.cpp
firmware/hw_layer/hip9011.cpp
firmware/hw_layer/io_pins.cpp
simulator/simulator/rusEfiFunctionalTest.cpp
unit_tests/engine_test_helper.cpp
unit_tests/engine_test_helper.h
unit_tests/tests/test_ignition_scheduling.cpp
unit_tests/tests/test_trigger_decoder.cpp

As alluded to by many comments strewn about the firmware, `injector_central` was completely the wrong name. This change fixes that!
Oh, and get rid of the huge pile of `extern EnginePins enginePins;`

Finally rename injector_central to bench_test

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_io.h
firmware/hw_layer/adc_inputs.cpp
firmware/hw_layer/pin_repository.cpp
firmware/tunerstudio/rusefi.input

Turns out, TS has a feature for this.  It took a little bit of reverse engineering an MS3 ini, but it seems to work well.  Here's what it looks like:

Show fatal error text in TS (the right way)

---

firmware/controllers/engine_controller.cpp
firmware/controllers/sensors/function_pointer_sensor.h
firmware/controllers/sensors/functional_sensor.h
firmware/controllers/sensors/proxy_sensor.h
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor.h
firmware/controllers/sensors/sensor_info_printing.cpp
firmware/controllers/sensors/sensors.mk
firmware/init/init.h
firmware/init/sensor/init_sensors.cpp
firmware/util/efilib.h
firmware/util/loggingcentral.h
unit_tests/tests/sensor/mock/mock_sensor.h

- Hook up each sensor printing information about itself (next step is having the functional sensor print out info about the function in question)
- Rename `initSensors` to `initNewSensors` to prevent name collision
- Fix `efilib.h` - it didn't compile if it was the first/only thing included in a file, which somehow flew under the radar for a long time.
- Remove duplicate check from `printAnalogChannelInfo` - it already happens in `printAnalogChannelInfoExt`

Debuggability in the new sensor world

---

firmware/controllers/sensors/converters/func_chain.h
firmware/controllers/sensors/converters/linear_func.cpp
firmware/controllers/sensors/converters/linear_func.h
firmware/controllers/sensors/converters/resistance_func.cpp
firmware/controllers/sensors/converters/resistance_func.h
firmware/controllers/sensors/converters/sensor_converter_func.h
firmware/controllers/sensors/converters/thermistor_func.h
firmware/controllers/sensors/sensor_info_printing.cpp

Looks like this (note new stuff under `TPS 1`):
```
2020-03-30_16_18_33_261: EngineState: confirmation_show_sensors:12
2020-03-30_16_18_33_262: EngineState: Sensor "CLT" is not configured.
2020-03-30_16_18_33_262: EngineState: Sensor "IAT" is not configured.
2020-03-30_16_18_33_262: EngineState: Sensor "Oil Pressure" is not configured.
2020-03-30_16_18_33_263: EngineState: Sensor "TPS 1": Raw value: 0.98 Valid: 1 Converted value -8.16
2020-03-30_16_18_33_388: EngineState:     Linear function slope: 30.44 offset: -38.05 min: -10.0 max: 110.0
2020-03-30_16_18_33_394: EngineState:         raw value 0.98 converts to -8.16
2020-03-30_16_18_33_398: EngineState: Sensor "TPS 1 Primary" is not configured.
2020-03-30_16_18_33_400: EngineState: Sensor "TPS 1 Secondary" is not configured. …
```

Debugging for sensor converter functions

---

firmware/console/status_loop.cpp

Not all boards have an analog channel set for vbatt (proteus, data-over-can, etc)

always show vbatt

---

firmware/controllers/actuators/dc_motors.cpp
firmware/integration/rusefi_config.txt

Unclear if this was ever actually used, and clearly isn't needed for any board with ETB wired in.

remove ETB controlPinMode

---

firmware/controllers/sensors/converters/sensor_converter_func.h
firmware/init/sensor/init_oil_pressure.cpp
unit_tests/tests/sensor/test_sensor_init.cpp

- Fix the bug
- Make the bug impossible via the type system: delete the copy constructor
- Add a test that catches the bug

fix oil pressure sensor

---

firmware/controllers/algo/fuel_math.cpp
unit_tests/tests/test_fuel_map.cpp

This math wasn't properly considering that the mass air flow is distributed between N cylinders.

fix maf fueling

---

firmware/hw_layer/drivers/can/can_msg_tx.cpp
firmware/hw_layer/drivers/can/can_msg_tx.h

Some OEM compat needs different length frames.  Default parameter of 8 to maintain compat with existing stuff.

Allow different length CAN frames

---

firmware/controllers/algo/fuel_math.cpp
firmware/tunerstudio/rusefi.input

PR-ing this now in the spirit of small changes. 
Built upon Matt's last PR to allow the MAF fuelling to be tuned with the VE table. 
MAF air charge fuelling now targets AFR and has correction for air flow inconsistencies like reversion through the MAF. 
Creates a value for "airChargeLoad" which is a standardised VE value and is used as Y axis for the VE table. 
VE table tunes MAF fuel by percentage. 100 = no correction, 80 = 20% less fuel, 120 = 20% more fuel. 
VE table enabled in Tuner studio for LM_REAL_MAF instead of Fuel Table.
Known issues:
Pulse width output is tested ok but does cause the build test to fail due to the change in the maths.
Y axis on VE table does not move in TS, need to change rusefi.input file to solve this for the next PR. 
For now the table works but does not …

Update to Matt's MAF code for VE table tuning. 

---

firmware/console/binary/tunerstudio_configuration.h
firmware/console/status_loop.cpp
firmware/tunerstudio/rusefi.input

Sensors are easier to diagnose when you don't need to get out a multimeter - now we have gauges for them!

Gauges for raw sensors

---

firmware/hw_layer/AdcConfiguration.h
firmware/hw_layer/adc_inputs.cpp

We already keep track of GPIO pin usage - so just recycle that for the ADC.  No need to keep a separate list of ADC pin usage when the only thing we use it for is checking if a pin is already used - `efiSetPadMode` already has that logic.
Bonus: this saves 17*4 = 68 bytes of RAM since now we don't need to keep a table of ADC channel names.

deduplicate ADC pin usage logic

---

firmware/integration/rusefi_config.txt

Was scaled -720 to +720, now scaled 0 to 100.
Fixes #1312

ETB pedal map scale

---

firmware/config/boards/st_stm32f4/board.h

Soon to be merged with F7 board.h
Deduplicate most definitions, as most ports are set to the defaults (all pins input pulldown), only doing something different where necessary.

Simplify F4 board.h

---

firmware/controllers/sensors/converters/func_chain.h
firmware/controllers/sensors/converters/resistance_func.cpp
firmware/controllers/sensors/converters/thermistor_func.cpp
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor.h
firmware/controllers/sensors/stored_value_sensor.h
firmware/util/expected.h
unit_tests/tests/sensor/func_chain.cpp

Slow progress towards #1152 and unit-tested ETB glory!  Other systems needed some way to return value-or-failure, like sensors, so this change extracts that functionality out.
- Based on SensorResult (and in fact SensorResult is now an alias to `expected<float>`)
- Added implicit conversion from `T` to `expected<T>` so you can just `return myValue;` instead of `return {true, myValue};`
- Added `unexpected` helper instead of returning `{false, 0}` which is a bit unwieldy.

add "expected" helper

---

firmware/controllers/sensors/converters/linear_func.cpp
firmware/controllers/sensors/function_pointer_sensor.h
firmware/controllers/sensors/redundant_sensor.cpp
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/stored_value_sensor.h
firmware/util/expected.h
unit_tests/tests/sensor/func_sensor.cpp

This way, `unexpected` isn't locked to only a single templated type, and now works for any `expected<T>`.
Inspiration from [p0323r3](https://github.com/viboes/std-make/blob/master/doc/proposal/expected/p0323r3.pdf).
Plus some consumers I missed the first time around.

Improve unexpected

---

firmware/controllers/math/speed_density.cpp

One or both of CLT/IAT sensors could be failed, so we should handle that appropriately, without spamming the log unnecessarily.

Improve tcharge error handling

---

firmware/controllers/algo/engine.h

Arrays don't get default initialized unless you specifically ask for it.

Fix ETB idle hard fault

---

firmware/tunerstudio/rusefi.input

Now it's zoomed in on the interesting part, and isn't clipped off the bottom left corner.

fix display of etb bias

---

firmware/config/boards/kinetis/OS/os/hal/ports/KINETIS/LLD/PITv2/hal_gpt_lld.h
firmware/config/boards/kinetis/efifeatures.h
firmware/config/boards/kinetis/halconf.h
firmware/config/boards/skeleton/efifeatures.h
firmware/config/stm32f4ems/efifeatures.h
firmware/config/stm32f4ems/halconf.h
firmware/config/stm32f4ems/mcuconf.h
firmware/config/stm32f7ems/halconf.h
firmware/config/stm32f7ems/mcuconf.h
firmware/hw_layer/adc_inputs.cpp
firmware/hw_layer/digital_input_icu.cpp

ADC doesn't need pin outputs, so we can switch it to the basic timer TIM6, where it isn't wasting output pins.  Prep for #1283.

switch ADC to gpt

---

firmware/console/status_loop.cpp
firmware/tunerstudio/rusefi.input

These changes are intended to help improve the "glanceability" of the indicator panel at the bottom of the dash in TS. A ton of indicators of random colors is hard to briefly look at and determine if something is wrong.  A field of all white indicators with a single red one, however, is.
- Things that are "normal" now display white
- Warnings display yellow
- Errors display red
- Things that are on (where on and off are both normal states) display green (fuel pump, fan, etc)
Also change pedal position error logic so that we only indicate pedal error when a pedal is configured but failed.  It's a valid configuration to not have a pedal sensor, so don't error in that case.

Revamp indicator panel in TS

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Problem: While hugely flexible, FSIO is too complex for the average user. Users require an easy way to configure things that are relatively simple like:
- Vary fuel pump duty cycle with engine load
- Engage/disengage supercharger clutch
- PWM cooling fan control: increase duty as temperature increases
- Automatic transmission line pressure control
- Decrease windshield wiper speed with increasing engine load to emulate old vacuum operated wipers while trying to sneak an EFI'd classic in to a stingy Concours d'Elegance
- Light bulb marked `DANGER TO MANIFOLD` that gets brighter with increasing boost pressure
Solution: After a survey of other ECUs functionality, I came up with this.  I tried to strike a balance between both ease of use, and flexibility to support may different scenarios. …

General purpose PWM: configuration fields

---

firmware/config/boards/kinetis/config/controllers/algo/rusefi_generated.h
firmware/console/binary/tunerstudio_configuration.h
firmware/controllers/generated/rusefi_generated.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

In order for automatic tuning/calibration to provide a great experience, we need some way to exfiltrate data from the ECU back up to TunerStudio, and set it in the configuration.
Here's an example of how this works:
```
maintainConstantValue = tpsMax, { (calibrationMode == 1 ) ? calibrationValue : tpsMax }
maintainConstantValue = tpsMin, { (calibrationMode == 2 ) ? calibrationValue : tpsMin }
```
This line tells TunerStudio:
- when `calibrationMode == 1`, copy the value read in from `calibrationValue` to the configuration field `tpsMax`
- Otherwise just pipe `tpsMax` back in to itself (ie, do nothing)
...and likewise for tpsMin, but for mode `2`.
With this simple construct, the ECU can send any number of internally computed configuration fields back to TunerStudio, getting around the …

TS protocol framing for auto tune/calibration features

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_etb.cpp

- Change 'pauseEtbControl' behavior to do all the math, but just not output to the motor.  This makes it more useful for testing, as all the gauges will still be alive.
- Add test for `pauseEtbControl`.
- Update `pauseEtbControl` docs in TS.
- fix `EtbController::onConfigurationChange`: only reset PID if PID parameters changed, not the inverse!
- Change behavior with failed pedal.  We can still drive the throttle, so just pretend the pedal is fully up (closed throttle) when failed.

Minor ETB improvements

---

firmware/bootloader/src/rusefi_stubs.cpp
firmware/config/boards/kinetis/chconf.h
firmware/config/chconf_common.h
firmware/config/stm32f4ems/chconf.h
firmware/config/stm32f7ems/chconf.h
firmware/controllers/engine_controller.cpp
firmware/controllers/engine_controller_misc.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/development/perf_trace.cpp
firmware/development/perf_trace.h
java_console/models/src/com/rusefi/tracing/Entry.java
java_console/models/src/com/rusefi/tracing/JsonOutput.java

- Store a unique ID with every thread, so that perf tracing can distinguish threads
- Trace ISR number and thread ID
- Render ISR number and thread ID in Java converter
- Update process (ISR) names, so they display in `chrome://tracing`
- Consolidate `chconf.h` thread hooks in to `chconf_common.h`
Example:

Perf Trace Improvements

---

firmware/development/perf_trace.cpp

If perf tracing happened while under a global system lock (interrupts disabled, essentially), the perf trace could forcibly do a system unlock (!), leaving code after the trace susceptible to stomping on from other threads and interrupts.

fix perf trace unlock bug

---

firmware/tunerstudio/rusefi.input

- Group trigger inputs with the normal trigger settings
- Move VVT & debugging to its own dialog "Advanced Trigger"
- Limit missing tooth options to reasonable values (maximum teeth 60, maximum missing 10)

Trigger dialog cleanup

---

firmware/config/boards/kinetis/config/controllers/algo/engine_configuration_generated_structures.h
firmware/controllers/actuators/dc_motors.cpp
firmware/controllers/actuators/dc_motors.h
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/generated/engine_configuration_generated_structures.h
firmware/integration/rusefi_config.txt

- Allow DC motor consumer to pick mode (stepper is always 2 pin)
- Add config space for 2 more DC motors
- Remove unused `SimplePwm etbPwmUp`

Support 4 h-bridges

---

firmware/hw_layer/drivers/drivers.mk

This fixes following build issue under linux:
make: *** No rule to make target 'build/obj/.cpp cj125.cpp', needed by 'build/obj/ build/obj/cj125.o'.  Stop.
make: *** Waiting for unfinished jobs....
Introduces in 8d35c35035dd7dc5fd3a149d04a5d3f55b6facca

either newline at end of mk file either no backslash on last line

---

firmware/console/status_loop.cpp
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/mmc_card.h

Don't assume it's always a string, because in the near future it'll be binary.

pass in SD log write length

---

firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/core/error_handling.cpp
firmware/controllers/engine_cycle/aux_valves.cpp
firmware/controllers/flash_main.cpp
firmware/controllers/gauges/tachometer.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/trigger/decoders/trigger_universal.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/hw_layer/adc_inputs.cpp
unit_tests/engine_test_helper.cpp
unit_tests/engine_test_helper.h
unit_tests/tests/trigger/test_trigger_decoder.cpp

For things that are either:
- a bug
- a combination of config settings that will result in undefined or otherwise wrong behavior
We want to trip a fatal error, because there is no (automatic) corrective action the ECU can take to limp along.
The most common cases this covers are things like inconsistent configurations (ex: wrong firing order for cyl count), and clearly invalid configurations (unexpected enum values).
This PR also makes calls to `firmwareError` in unit tests throw an exception (so the test registers as failed), instead of simply calling `exit` which will terminate the process immediately.

switch some firmware warnings to errors

---

firmware/gen_config.bat
firmware/gen_config.conf
firmware/gen_config.sh

All the parameters to be passed to java are now in gen_config.conf.
gen_config.bat just calls gen_config.sh.
It checks whether C:\cygwin or C:\cygwin64 exists. Are there any situation in which one of these would not be true?

Fix #1492 redux

---

.github/workflows/set-date.yaml

This should make it so the set_date workflow only runs on the rusefi/rusefi repo, not forks

Fix set date

---

firmware/console/binary/tunerstudio_outputs.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Previously only supported up to 655.35kg/h of airflow, which is only about 400hp worth of air.  Now we support 4000hp worth of air!

fix maf gauge scaling

---

firmware/controllers/actuators/aux_pid.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/tunerstudio/rusefi.input

Start switching tables over to use the new fuelingLoad channel.

Switch TS tables to use new axes

---

.github/workflows/build-firmware.yaml

For some reason gen_config_board.sh doesn't update changes made to TunerStudioOutputChannels.
If someone else who knows more about ConfigDefinition wants to add that to gen_config_board, go ahead, but for now here is a workaround.

always generate default config

---

firmware/config/boards/kinetis/config/controllers/algo/auto_generated_enums.cpp
firmware/controllers/algo/airmass/alphan_airmass.cpp
firmware/controllers/algo/airmass/alphan_airmass.h
firmware/controllers/algo/algo.mk
firmware/controllers/algo/auto_generated_enums.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/controllers/math/engine_math.cpp
firmware/integration/rusefi_config.txt
unit_tests/tests/test_fuel_map.cpp
unit_tests/tests/test_fuel_math.cpp

part 3 of #1299.
also fix #1455 
Benefits of this over the old time-based fuel map method:
- compensates for injector size
- uses AFR table
- computes usable airmass value (for ignition Y-axis if/when we get there)
Because it is a fundamentally different mode, it gets a new enum value.  The old one will be removed so that we can intentionally cause an error to signal to the user that they need to visit their VE table.

new alphan implementation

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h
firmware/integration/rusefi_config.txt
unit_tests/mocks.h
unit_tests/tests/test_etb.cpp

Implement support for #1637 
Using this requires configuring the ECU like this:
1. Set the primary TPS to the cable-operated throttle's sensor
2. Set the secondary TPS to the mini ETB's position sensor(s)
3. Enable the "use VW ETB idle" bit
4. Use idle control normally, 0% will fully close the mini etb, and 100% idle fully open it.

VW's Whacky ETB Idle

---

firmware/controllers/engine_cycle/map_averaging.cpp
firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/system/timer/event_queue.cpp
unit_tests/global_execution_queue.cpp
unit_tests/global_execution_queue.h

Found while debugging #1632, some tests were spilling state in to others via instances of `scheduling_s` that are statically allocated, and therefore used by multiple tests.
This change adds a flush to clean up those leftover instances, then fixes the behavior of the offending events.

reduce crosstalk between tests

---

.github/workflows/gen-diffs.yaml
hardware/generate_diffs.sh

Problems:
1: Files were going in a 'plots' subdirectory of plots_<board name>, which was not intended
2: Files from previous changes would remain behind and take up disk space without having a index.html to make them usable.
With this change, old files are deleted. To make this happen, I switched from ncftp to lftp.
3: If any .kicad_pcb file changed, diffs were generated and uploaded for all .kicad_pcb files. This was an apparent bug in
KiCad-Diff. I'm using a fork in my own repo for now.

More Kicad Diff changes

---

.github/workflows/sync-wiki.yaml

This requires setting up a Personal Access Token (I think in organization settings?).
Set the token as a Secret for the repository, and call it ACCESS_TOKEN.
This action runs whenever the wiki on this repo is edited, and merges the changes to rusefi_documentation.

Sync wiki to rusefi_documentation.

---

firmware/controllers/bench_test.cpp
firmware/tunerstudio/rusefi.input

- make 2d map values more reasonable (ie, avoid crazy decimals from uneven division)
- reorder items in the fueling menu so they group in to:
- Airflow/airmass
- Fuel model & corrections
- Injection settings (currently just injection phase)
- Enrichments
- Regroup injector hardware, modes, and deadtime in to two dialogs that look like this:

Fuel ts reorder

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.h
firmware/tunerstudio/rusefi.input
java_console/io/src/main/java/com/rusefi/binaryprotocol/BinaryProtocol.java
java_console/io/src/main/java/com/rusefi/binaryprotocol/BinaryProtocolCommands.java

- remove unused zeroes (that were once page offsets)
- actually send offset/length to the CRC command (so that partial CRCs work)
- remove page parameter from all operations since it isn't used

remove unneccessary zeroes from TS protocol

---

firmware/config/boards/proteus/knock_config.h
firmware/controllers/sensors/software_knock.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Some engines have multiple knock sensors.  This change lets you pick which sensor should listen for each cylinder.

Multiple knock sensors

---

firmware/util/expected.h

Should return a `TValue`, not a `float`.
Believe it or not, this is related to #1708

fix expected<T>

---

firmware/util/containers/table_helper.h

defining them in class removes all of the nasty boilerplate like
```
template<int RPM_BIN_SIZE, int LOAD_BIN_SIZE, typename vType, typename kType, typename TValueMultiplier>
float Map3D<RPM_BIN_SIZE, LOAD_BIN_SIZE, vType, kType, TValueMultiplier>::getValue(float xRpm, float y) const
```

define map3d functions in class

---

firmware/console/status_loop.cpp
firmware/controllers/core/error_handling.cpp
firmware/development/engine_sniffer.cpp
firmware/development/logic_analyzer.cpp
firmware/development/sensor_chart.cpp
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/rtc_helper.cpp
firmware/util/datalogging.cpp
firmware/util/datalogging.h
firmware/util/efilib.cpp
firmware/util/loggingcentral.cpp
simulator/simulator/rusEfiFunctionalTest.cpp
unit_tests/tests/test_accel_enrichment.cpp
unit_tests/tests/test_pid_auto.cpp

Lots of functions of the form `myFunc(Logging* logger)` should actually be members of `Logging`.  This change does that!
Changing the `buffer` member to `const` means that it has to be initialized at construction - so it can't be null! Removing runtime checks in favor of compile-time checks is always great.

logging simplification: switch bare functions to member functions

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h
firmware/controllers/engine_controller.cpp
unit_tests/mocks.h
unit_tests/tests/test_etb.cpp

etbs are adults, they can share a single thread between them.  Besides , ChibiOS won't even preempt a thread with the same priority, so they were already sort of running on the same thread.
progress on #1784

two throttles one thread

---

firmware/hw_layer/adc/adc_inputs.cpp

If too many adc channels got enabled, we'd overrun the buffer and cause a hard fault.  Fail gracefully!

guard against ADC buffer overrun

---

firmware/config/boards/proteus/mapping.yaml
firmware/integration/rusefi_config.txt

No reason the HW can't use analog inputs for switch inputs.

add analog inputs to switches

---

firmware/config/boards/hellen/cypress/config/controllers/algo/auto_generated_enums.cpp
firmware/config/boards/hellen/cypress/config/controllers/algo/auto_generated_enums.h
firmware/config/boards/kinetis/config/controllers/algo/auto_generated_enums.cpp
firmware/config/boards/kinetis/config/controllers/algo/auto_generated_enums.h
firmware/config/engines/bmw_e34.cpp
firmware/config/engines/dodge_neon.cpp
firmware/config/engines/ford_festiva.cpp
firmware/config/engines/honda_accord.cpp
firmware/config/engines/me7pnp.cpp
firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/controllers/algo/auto_generated_enums.cpp
firmware/controllers/algo/auto_generated_enums.h
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/controllers/engine_controller.cpp
firmware/controllers/settings.cpp
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/mmc_card.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

This change removes the following config fields:
- `isFastAdcEnabled`: This should be disabled with a `#define` if a board doesn't have this capability.
- `secondTriggerChannelEnabled`: unused, replaced with trigger modes using the proper inputs all by themselves.
- `isTunerStudioEnabled`: this one provides you the potential to "saw off the branch you're sitting on", and lose TS connectivity.  If a board doesn't support TS, just don't define `EFI_TUNER_STUDIO`
- `storageMode`: Unused.

Remove dead & useless config

---

firmware/controllers/core/fsio_core.cpp
firmware/controllers/core/fsio_core.h
unit_tests/tests/test_logic_expression.cpp

- much clearer tests
- move similar operators out to their own functions (reduce duplication!)
- add binary literals (`true`/`false`)
- minor parser cleanup

FSIO refactoring

---

firmware/controllers/core/fsio_core.cpp
firmware/controllers/core/fsio_core.h
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/core/fsio_impl.h
unit_tests/tests/test_logic_expression.cpp

prep for type checking - operations have to be able to fail (ie, return `unexpected`)!

switch FSIO from float to expected<float>

---

firmware/console/binary_log/binary_logging.cpp
firmware/console/binary_log/binary_logging.h
firmware/console/status_loop.cpp

also write the actual header length, instead of assuming it fits in 2k
fixes #1864

Check for sd buffer overrun

---

firmware/controllers/system/timer/pwm_generator_logic.cpp

Dynamic iteration limit means we will do as many cpu cycles as we can without overflowing a 32-bit timer counter.

Fix #1873 - compute dynamic PWM iterationLimit

---

firmware/controllers/system/buffered_file_writer.h
firmware/controllers/system/buffered_writer.h
unit_tests/tests/tests.mk
unit_tests/tests/util/test_buffered_writer.cpp

currently we need a huge buffer that can fit the whole SD log header at once - currently 2300 bytes.  This change adds a class that allows for small and large writes alike to be buffered by a smaller buffer, which is automatically flushed to the underlying medium when its full (or on command).

buffered writer - progress on #1463

---

firmware/Makefile
unit_tests/Makefile
unit_tests/tests/test_pid.cpp

`0.25`: this is a double
`0.25f`: this is a float
Adding this compiler option means these are both actually floats.  We don't have the hardware to process doubles, so it happens instead in software.
For example, the line of code `float instantRpm = (60000000.0 / 360 * US_TO_NT_MULTIPLIER) * angleDiff / time;` compiles to this:
Circled are SOFTWARE EMULATED `double` math operations.  Bad! Slow! So much extra code!
With this option added, it now compiles to this:
As a bonus, this saves ~1k of flash space.

switch to single precision constants

---

firmware/util/common.h

This fix compilation error for Kinetis and Cypress if common.h
is included after platform includes which also defines MIN MAX.

common.h: define MIN and MAX macro only if nod defined yet

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/fuel/injector_model.cpp
firmware/controllers/algo/fuel/injector_model.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/ignition_injection/injection_mode_transition.cpp
unit_tests/tests/ignition_injection/test_startOfCrankingPrimingPulse.cpp
unit_tests/tests/test_fasterEngineSpinningUp.cpp
unit_tests/tests/test_fuel_map.cpp

Convert to duration later in the fueling pipeline.  This means all corrections (cranking, CLT/IAT/duration, etc) are applied as a mass, not as a duration, with injector deadtime added at the very end, after all corrections.
As a side effect, this means the base cranking value is now a mass (milligrams), not a duration (milliseconds), so it's now automatically adjusted by the injector settings, and will soon be adjusted by the fuel pressure too, which will provide better startup performance for GDI, and potentially PFI even without a pump prime!
fixes #1903 by design, not with a hack like #1904 did

convert mass -> duration later in the pipeline

---

firmware/console/status_loop.cpp
firmware/console/status_loop.h
firmware/controllers/actuators/gppwm/gppwm.h
firmware/controllers/actuators/gppwm/gppwm_channel.h
firmware/controllers/actuators/idle_thread.h
firmware/controllers/core/common_headers.h
firmware/controllers/core/engine_ptr.h
firmware/controllers/global_shared.h
firmware/development/engine_sniffer.cpp
unit_tests/global.h
unit_tests/globalaccess.h

Consolidate it all to one spot, with associated forward declarations.  This means header files don't need to include the full `engine.h`.  Should help with compile time a bit, in addition to the "which header should I include" problem.

Move all DECLARE_ENGINE_PTR etc to one place

---

.gitignore
.gitmodules
.vscode/extensions.json
.vscode/launch.json
.vscode/tasks.json

The workflow is now:
1. open vscode
2. press `ctrl-shift-b` to build firmware or unit tests
3. press `f5` to start debugging firmware or unit tests
Only tested on Linux, but probably works on windows too if you have the windows build tools installed.

debugging in vscode 🎉

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_io.cpp
firmware/console/binary/tunerstudio_io.h

use the `crcReadBuffer` as a transmit buffer as well.  This ensures that we compute the CRC and transmit the same data - there's no opportunity for another thread to preempt and change the data between the CRC calculation and transmission.  This might actually net improve performance - it saves two calls to `sr5WriteData`.
fixes #1943

fix CRC errors

---

firmware/hw_layer/mmc_card.cpp

causes a kernel halt if the MMC device changes during an MMC operation, possible when the setting is changed from TS

prevent MMC preemption by TS thread

---

firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/mmc_card.h

don't re-read SD card spi device after boot - it could change mid transaction (TS thread could preempt), which will cause disaster (usually multiple-unlock of the same mutex in `UNLOCK_SD_SPI`

read SD card config exactly once

---

firmware/hw_layer/drivers/gpio/tle8888.c

Enabled pull-down affects analog inputs that shares same pins.
Disable it.
DOTO: enable diagnostic if ouput requested through tle8888_setPadMode

TLE8888: disable diagnostic for OUTPUT8..13

---

firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/global.h
simulator/simulator/global.h
unit_tests/global.h

confirmed that its removal doesn't change the output binary
the functions it'd marked were already getting inlined by the compiler, and these days `inline` is a hint at best, and usually just ignored altogether.

remove ALWAYS_INLINE

---

firmware/controllers/actuators/boost_control.cpp
unit_tests/tests/test_boost.cpp

ignore the closed loop target when in open loop mode

Boost tolerance

---

firmware/console/binary/tunerstudio_outputs.h
firmware/tunerstudio/rusefi.input

added new field to send out Vehicle acceleration based on Vss.
I did not create a new scaled type, i reused the scaled_ms -> we use the same scaling.

introduce vehicle acceleration in TS

---

firmware/hw_layer/adc/AdcConfiguration.h
firmware/hw_layer/adc/adc_inputs.cpp

Bug was introduced in 2312b0ae5755e47b0963586f3ae717537c57da4d when
sample buffer was moved out of class. So sample become adcsample_t*
instead of adcsample_t[] and sizeof returns 4.

ADC: correctly calculate cache invalidate range for STM32F7xxx

---

firmware/controllers/sensors/converters/linear_func.h
firmware/init/sensor/init_tps.cpp
unit_tests/tests/sensor/test_sensor_init.cpp

warn the user that their wiring may be busted if the TPS values are very close together (aka, auto calibrate didn't work)
progress #1954 part 2

require TPS values to be different

---

firmware/controllers/sensors/redundant_sensor.h
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor.h
unit_tests/tests/sensor/redundant.cpp

Add the ability to check whether a sensor is redunant, so the ETB can require dual TPS sensors later

add isRedundant api for sensors

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor.h
unit_tests/tests/test_etb.cpp

And no, it's not configurable, since it's a safety problem.  It's much easier for us to say "sorry, no, redundant is required" instead of allowing janky setups that aren't a real throttle body.  All real throttle bodies have redundant sensors.

Require redundant tps for ETB

---

firmware/console/binary/tunerstudio.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h
firmware/controllers/actuators/electronic_throttle_impl.h
unit_tests/mocks.h
unit_tests/tests/test_etb.cpp

reduce the header include footprint a bit for people who aren't the ETB controller cpp itself

Split ETB in to interface + implementation headers

---

firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h

- unconditionally set physical output pin every time.  Checking whether we need to costs about the same as actually setting the pin (which you'd have to do anyway), so just set the pin and don't bother checking
- re-enable pin state validation
Tested with a logic analyzer that GPIO does indeed still work correctly.
fixes #2006

reduce GPIO complexity & fix #2006

---

firmware/console/status_loop.cpp

we always have a tps2 sensor, but not always a tps2primary, so only show an error if we have the latter

fix tps2 error detection

---

firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.h
firmware/controllers/system/timer/single_timer_executor.cpp

If we're far behind schedule on PWM, skip cycles to catch up instead of executing every single event we missed.  
Trying to catch up will just swamp the scheduler while generating extremely high speed PWM (I measured it at ~50-70khz) that isn't actually doing anything useful.  For example, if you were trying to generate a 60-2 wheel at 6000 rpm, that's 12000 events per second, and if the flash erase + write takes 3 seconds, that leaves you with ~36k events to try and execute once the flash is done, which will be cranked out as fast as the PWM driver can toggle a pin.

force a pwm cycle start (skip cycles) if late

---

firmware/controllers/core/error_handling.cpp

print formatted errors instead of just the format string

format errors in tests

---

java_console/autotest/src/com/rusefi/PwmHardwareTest.java

Using existing hw jumpers we measure idle pin pwm.
Duty is not yet checked, but we do check if we have correct output frequency.

Test Idle PWM 

---

firmware/controllers/actuators/aux_pid.cpp
firmware/controllers/algo/engine.h
firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/hw_layer/sensors/hip9011.cpp
unit_tests/engine_test_helper.cpp

Bug: if you un-initialize a pin, setValue will still work! If you initialize pin A, then set it to "none", then initialize the same pin elsewhere, both users will be able to call setValue and set the same pin!  This causes a problem in particular when reinitializing a pin that's set by a higher priority thread, like the hardware trigger emulator does.
This PR fixes both possibilities:
- Only do the hardware set if `brainPin != GPIO_UNASSIGNED`, which is now always set by `initPin`, and always cleared by `unregister`.
- Guard pin init and de-init with a critical section so that other threads couldn't even set the pin if they tried

Fix gpio reinit race condition

---

firmware/util/timer.cpp

This bug can cause the fuel pump to occasionally blip off if we get a lucky trigger interrupt between taking a timestamp and doing the subtraction.

handle negative timer delta

---

java_console/autotest/src/com/rusefi/IoUtil.java
java_console/models/src/main/java/com/rusefi/core/ISensorCentral.java
java_console/models/src/main/java/com/rusefi/core/SensorCentral.java

this change means you can pass a lambda directly to `addListener` instead of having to keep the lambda around yourself, and call `removeListener` with the right parameters.  Just call `listenerToken.remove()` instead.

use token for sensor listener unsubscribe

---

java_console/autotest/src/com/rusefi/EnduranceTestUtility.java
java_console/autotest/src/com/rusefi/FunctionalTest.java
java_console/autotest/src/com/rusefi/IoUtil.java
java_console/autotest/src/com/rusefi/functional_tests/EcuTestHelper.java
java_console/io/src/main/java/com/rusefi/io/CommandQueue.java
java_console/ui/src/main/java/com/rusefi/ui/RecentCommands.java

The pattern of 
```
send request
wait for response or timeout
```
doesn't actually work, because if the "signal listening thread" action happens elsewhere prior to you starting to listen, you get stuck.  This had the effect of waiting for the timeout (10 seconds for `set engine_type`!) instead of the command actually completing!
This PR changes it to instead
```
start listening for response
send request
wait for completion or timeout
```
which means we actually return immediately upon confirmation of the command as intended.
It also removes the retry timeout, as any connectivity problem that requires a retry indicates a bug, and we should just fail hard so the issue can be diagnosed (besides, the retry mechanism was sort of broken anyway).

fix race condition in CommandQueue, massively speeding up HW CI tests

---

firmware/util/cli_registry.cpp

- send confirmation AFTER completing the command, not before
- simplify printing, removing 200 byte buffer (free ram!)

simplify cli confirmation logic

---

java_console/autotest/src/com/rusefi/TestingUtils.java

we should use junit assertions instead of custom ones, and that starts with `fail()`

use junit fail instead of throw

---

firmware/controllers/core/fsio_core.cpp
firmware/controllers/core/fsio_core.h
firmware/controllers/core/fsio_impl.cpp
unit_tests/tests/test_logic_expression.cpp

related to doing invalid things with fsio, sort of #2058

rename FsioValue to FsioResult

---

firmware/controllers/core/fsio_core.cpp
firmware/controllers/core/fsio_core.h
firmware/controllers/core/fsio_impl.cpp

Unused member.  Saves about 1200 bytes of RAM.

unused fsio ivalue

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/engine2.cpp
firmware/controllers/controllers.mk
firmware/controllers/core/error_handling.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/limp_manager.cpp
firmware/controllers/limp_manager.h
unit_tests/tests/test_limp.cpp
unit_tests/tests/tests.mk

create limp manager, prep for:
- #2125 ETB failure handling
- #1336 ETB deviation detection/response
- #932 limp in case of MAP failure
- #1535 ETB rev limiting
- #455 Rev limit depend on CLT
- #192 configurable limiting strategy
- #187 #413 Disable accel enrich after rev limit
Move rev limit & boost cut logic in to limp manager
This functionality is tested by #2141

create limp manager

---

firmware/controllers/actuators/electronic_throttle.cpp

progress on #2151 
This isn't ideal, but it will at least prevent invalid TPS calibration in case of a failed autocal attempt from being written to the ECU, causing a fatal error on the next boot.

don't write settings if ETB cal didn't work

---

firmware/util/math/biquad.cpp
firmware/util/math/biquad.h

Q = 0.707 was actually causing overshoot on step responses, but 0.54 won't.
Also removes a line of code that was a duplicate of the previous line.

update biquad filter default

---

firmware/controllers/algo/event_registry.h
firmware/controllers/engine_cycle/fuel_schedule.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/trigger/decoders/trigger_structure.cpp

maybe helps the 2003 Neon part of #2207
The bug happens when a trigger change occurs that renders the old fueling schedule invalid, potentially referencing teeth that no longer exist.  This change forces a rebuild of the injection schedule after the trigger pattern changes so that injection scheduling can pick up the new trigger shape.

part of 2217 which may fix 2207

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/core/engine_ptr.h
firmware/controllers/core/state_sequence.h
firmware/controllers/global_shared.h
firmware/controllers/trigger/decoders/trigger_mazda.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/decoders/trigger_universal.cpp
firmware/controllers/trigger/decoders/trigger_vw.cpp
unit_tests/global.h

make better use of `engine_ptr.h` instead of `global.h`

clean up some includes

---

firmware/controllers/actuators/boost_control.cpp
firmware/controllers/actuators/boost_control.h
firmware/controllers/algo/engine.cpp
firmware/hw_layer/hardware.cpp
firmware/tunerstudio/rusefi.input

- boost control was broken after a config apply since the pin was getting reset but is already a `RegisteredOutputPin`
- call boost control from periodic slow instead of as its own task
- improve boost control default settings
- TS UI cleanup

boost fixes

---

firmware/controllers/trigger/decoders/trigger_structure.h
unit_tests/tests/test_fuel_map.cpp

Store eventAngles in a scaled_channel instead of a float, using only half the space.  With the current value of `PWM_PHASE_MAX_COUNT`, this saves 576 bytes.
This reduces the accuracy of trigger events to 1/64th of a degree, which is still more than plenty.  64 * 720 = ~46000 so it won't overflow.

Save more space in the angle cache

---

firmware/controllers/algo/airmass/speed_density_airmass.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

progress on #2244 
- in case of MAP failure, use configured value instead for SD fueling
- TS cleanup so now it looks like this:

Map fallback logic, TS cleanup

---

firmware/console/status_loop.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/engine_cycle/spark_logic.h
firmware/controllers/limp_manager.cpp
firmware/controllers/limp_manager.h

let the limp manager completely handle disabling injection/ignition, either by user selection or by rev limit/boost cut/whatever
also, since apparently the bits for it already exist, allows user selection of whether to limit fuel/spark for rev limit
progress #2244

Limp handles inj/ign disable

---

.github/workflows/gen-docs.yaml
hardware/frankenso/sym-lib-table
misc/jenkins/InteractiveHtmlBom/run.sh

1. Generate iBOMs for all boards with .kicad_pcb files
2. Show netlists for boards with .net files
3. Update InteractiveHtmlBom to get rid of xvfb dependency
4. Switch to official kicad ppa

iBOM improvements

---

firmware/hw_layer/ports/stm32/port_mpu_util.h
firmware/hw_layer/ports/stm32/serial_over_usb/usbcfg.c
firmware/hw_layer/ports/stm32/serial_over_usb/usbcfg.h
firmware/hw_layer/ports/stm32/serial_over_usb/usbconsole.c
firmware/hw_layer/ports/stm32/stm32f4/device_mpu_util.h
firmware/hw_layer/ports/stm32/stm32f7/device_mpu_util.h

- Report the real serial number over USB, so that you can tell multiple ECUs apart when they're connected at the same time.
- Set the USB manufacturer string to "rusEFI LLC"
- Fix the casing on the device name string so the R is lower case in rusEFI
- Set our max power to 200mA which is a little closer to reality than 100mA (there is a very narrow possibility that this well help with the USB stability problems some people see)

USB reports real STM32 Serial Number

---

firmware/hw_layer/hw_layer.mk
firmware/hw_layer/i2c_bb.cpp
firmware/hw_layer/i2c_bb.h

Implement a bit-banged I2C controller for low priority I2C operations.
Bit-banged (as opposed to hardware accelerated) provides several benefits:
- No interrupts required
- No usage of microcontroller resources (particularly DMA channels)
- No operating system locks (any other thread can preempt an operation)
- Smaller code size
- No restriction on pins: can use any two GPIO pins
progress on #2288 and #2281

implement bit-banged I2C driver

---

misc/jenkins/generate_doxygen/gen_upload_docs.sh

-m was added to create the directory if it doesn't exist. For some reason this had the side effect of putting the source directory inside of the target directory, instead of putting the /contents/ of the source directory inside the target directory. To solve this I added a asterisk to get the contents of the source dir rather than the dir itself. However, Windows has a limit on the number of arguments that can be passed to a command that is way too low to handle the number of files that doxygen generates.

try removing -m and glob

---

firmware/hw_layer/ports/stm32/serial_over_usb/usbcfg.c

Convert from a plain CDC device, to a composite device that wraps a CDC device.  Prep for USB mass storage, #140

turn in to a USB composite device

---

firmware/hw_layer/mmc_card.cpp

SD spec says 0-25MHz for slow mode, and 0-50MHz for fast mode.
Increases slow mode to either 10.5MHz or 5.25MHz (depending on which SPI device it is), and fast mode to 42MHz or 21MHz (depending on which SPI device it is).  On an F7 that means 13.5mhz/6.75mhz slow mode and 54MHz/27MHz fast mode, which is pushing it a little bit on SPI1, but will probably be just fine.

increase SD card speed

---

firmware/hw_layer/ports/stm32/serial_over_usb/usbcfg.c

Rename USB endpoints to reflect what they actually do.
Update ChibiOS-Contrib because there have been improvements to the MSD driver in the past few weeks.

Rename USB endpoints, update ChibiOS-Contrib

---

misc/jenkins/generate_doxygen/gen_upload_docs.sh
misc/jenkins/generate_ibom/gen_upload_ibom.sh
misc/jenkins/generate_pinouts/gen_upload_pinouts.sh

It seems my recent pull requests caused the doxygen to be put at html/html. That directory can be deleted after this is merged.
I also took this opportunity to optimize the parameters to the other ncftpput commands, for pinouts and ibom.
The -z flag doesn't seem to be doing anything, but I left it in case it does, but I can't tell.

Fix doxygen 3

---

firmware/hw_layer/ports/stm32/serial_over_usb/usbcfg.c

Length was wrong on these descriptors, causing Windows to get a little bit upset.

fix usb descriptor mistakes

---

firmware/Makefile
firmware/hw_layer/mass_storage/mass_storage.mk
firmware/hw_layer/mass_storage/null_device.cpp
firmware/hw_layer/mass_storage/null_device.h

This is a helper that lets us handle the case when we want to connect USB, but not mount an SD card.

implement null block device

---

firmware/hw_layer/mmc_card.cpp

Rewrite SD card initialization logic in preparation for #140
The following combinations were tested:
- MSD enabled:
- Card present -> mounted to USB
- Card missing/disabled -> null device mounted to USB (windows shows "no media")
- MSD disabled:
- SD present -> logs written to SD
- SD missing/disabled -> nothing done
- SD removed while running -> gracefully stops logging, stops log thread.

rewrite SD initialization

---

firmware/hw_layer/ports/stm32/stm32_common.cpp

Proteus took >30 seconds to detect that no SD card was installed.
see comment in code, progress for #140

fix proteus SD card detection

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/airmass/airmass.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/fuel/injector_model.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/engine_cycle/aux_valves.cpp
firmware/controllers/engine_cycle/map_averaging.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/sensors/ego.cpp
firmware/controllers/sensors/maf.cpp
firmware/hw_layer/sensors/cj125.cpp
firmware/util/math/interpolation.h
unit_tests/test_basic_math/test_find_index.cpp

`msg` parameter of `interpolate2d` was unused, so now it's gone.

remove unused msg parameter

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/core/engine_ptr.h
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/hardware.cpp
firmware/hw_layer/sensors/hip9011.cpp
firmware/rusefi.cpp
simulator/simulator/rusEfiFunctionalTest.cpp
unit_tests/engine_test_helper.cpp
unit_tests/tests/ignition_injection/test_fuel_map.cpp
unit_tests/tests/ignition_injection/test_miata_na6_real_cranking.cpp
unit_tests/tests/trigger/test_all_triggers.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp
unit_tests/tests/trigger/test_trigger_noiseless.cpp

The engine class had a weird home-spun half way to `DECLARE_ENGINE_PTR` solution, this switches it to do the normal thing like everybody else.

use DECLARE_ENGINE_PTR for Engine class

---

firmware/Makefile
firmware/hw_layer/ports/stm32/stm32f4/hw_ports.mk
firmware/hw_layer/ports/stm32/stm32f7/hw_ports.mk
firmware/hw_layer/ports/stm32/stm32h7/hw_ports.mk

the compiler knows some tricks to get better perf on cm4 vs cm7 because of the different pipeline and architecture, so use it!

set MCU type properly

---

firmware/controllers/core/fsio_core.cpp
firmware/controllers/core/fsio_core.h
firmware/controllers/core/fsio_impl.cpp
unit_tests/tests/test_logic_expression.cpp

- saves `sizeof(LEElement*)` = 4 bytes per element.  We have 288 LEElement, for a savings of 1152 bytes of RAM.
- probably improves performance as it just linearly reads through elements, instead of jumping around pointers.
fixes #2181

rework FSIO LEelement

---

firmware/controllers/core/fsio_core.cpp
firmware/controllers/core/fsio_core.h
firmware/controllers/core/fsio_impl.cpp
unit_tests/tests/test_logic_expression.cpp

no need to store a pointer to the program in `LECalculator` when we always pass it in when evaluating.
cleanup from #2374

small fsio cleanup

---

firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/mmc_card.h
firmware/hw_layer/mmc_card_access.cpp

- Fix filesystem object caching on F7/H7 (ie, don't cache it)
- SD driver takes exclusive use of the SPI driver for the full duration of use (which in most cases means forever)

mmc cleanup

---

java_console/autotest/src/com/rusefi/proteus/ProteusAnalogTest.java
java_console/models/src/main/java/com/rusefi/core/Sensor.java

Check that the raw values on CLT/IAT are expected.  In the future an external resistor could be added to fake a sensor and check the full system's operation.

hardware CI for clt/iat inputs

---

firmware/config/engines/test_engine.cpp

5khz pwm was an even multiple of ADC frequency, so we could get aliasing, so try a PWM frequency coprime with the ADC frequency.

maybe make proteus CI more reliable

---

firmware/controllers/engine_controller.cpp
firmware/hw_layer/hardware.cpp
firmware/hw_layer/ports/stm32/serial_over_usb/usbconsole.c
firmware/rusefi.cpp

There were cases where we could bail out of initialization before configuring USB or the MMC card (you have to initialize the MSD driver, or Windows will hang during device enumeration), so this change moves init of USB and MMC very early - just after config read

avoid various "no connect" scenarios

---

firmware/util/math/error_accumulator.cpp
firmware/util/math/error_accumulator.h
firmware/util/util.mk
unit_tests/tests/tests.mk
unit_tests/tests/util/test_error_accumulator.cpp

Implement an error accumulator that can detect errors in control systems, but rejects noise.
Useful for #1336, #932, et al

error accumulator

---

firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/algo/adc_math.h
firmware/hw_layer/ports/cypress/port_mpu_util.h
firmware/hw_layer/ports/kinetis/port_mpu_util.h
firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp
firmware/hw_layer/ports/stm32/stm32_adc_v4.cpp
firmware/hw_layer/ports/stm32/stm32f4/device_mpu_util.h
firmware/hw_layer/ports/stm32/stm32f7/device_mpu_util.h
firmware/hw_layer/ports/stm32/stm32h7/device_mpu_util.h

Clean up ADC defines, oversampling.
Move ADC_MAX_VALUE in to port_mpu_util.h since H7 has a 16 bit ADC.
Enable hardware oversampling on H7, and actually use all 16 bits instead of discarding 4.

ADC cleanup, enable oversampling on H7

---

firmware/console/binary/tunerstudio.cpp
firmware/console/status_loop.cpp
firmware/controllers/core/error_handling.cpp
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/rtc_helper.cpp
firmware/util/loggingcentral.cpp
firmware/util/loggingcentral.h

handful of spots that we could just call `scheduleMsg` - so do that
change signature of swapOutputBuffers to return `const char*`
remove useless SD card warning, not-plugged-in SD card is a valid case that doesn't deserve a warning

logging cleanup before refactor

---

firmware/controllers/algo/fuel/injector_model.cpp
firmware/controllers/sensors/proxy_sensor.h
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor.h
unit_tests/Makefile
unit_tests/tests/ignition_injection/test_injector_model.cpp
unit_tests/tests/sensor/basic_sensor.cpp
unit_tests/tests/sensor/mock/mock_sensor.h

- check that you actually have a pressure sensor configured if you try to use it
- handle negative pressure delta (ie, injectors are trying to flow backwards), as this suggests a failed sensor
fixes #2445

Fuel pressure sensor checks

---

firmware/config/boards/prometheus/efifeatures.h
firmware/config/boards/skeleton/efifeatures.h
firmware/config/boards/subaru_eg33/efifeatures.h
firmware/console/binary/tunerstudio.cpp
firmware/controllers/core/error_handling.cpp
firmware/controllers/core/error_handling.h
firmware/init/sensor/init_tps.cpp

We had no protection against overflowing the error or warning buffers.  If you hit certain errors, it would overflow and stomp whatever memory lay after the error buffer.
This does exactly what was suggested by the todos in code: just use `chvsnprintf` instead of a custom memorystream implementation.
fixes #2331

fix error/warning buffer overflow

---

firmware/controllers/bench_test.cpp
firmware/controllers/can/can.h
firmware/controllers/can/wideband_bootloader.cpp
firmware/tunerstudio/rusefi.input

Problem: you have multiple wideband contollers
Solution: you can now set which physical device gets which logical index!
also updates the controller image to support the new command/message.

Add set wideband index buttons

---

firmware/rusefi.cpp

To avoid 'CRITICAL error: hwTimer not alive' error

Enable trigger stimulation after HW timer initialized

---

firmware/console/status_loop.cpp
firmware/controllers/algo/rusefi_types.h
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/pin_repository.cpp
firmware/rusefi.cpp

Some configurations can cause a no-boot.  This avoids some of them: particularly invalid cylinder counts and invalid trigger shapes.

harden against various no-boot scenarios

---

firmware/hw_layer/ports/rusefi_halconf.h

there are some narrow timing conditions that could cause a stack overflow on the mass storage (context switch during decompression, for example), and devices using compressed ini are already guaranteed tons of memory, so just make the stack bigger.

embiggen mass storage stack

---

firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp

It helps if you sample channel 9 instead of sampling channel 8 twice.

fix stm32 ADC channel 9

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

standardize the UI language to `bank [1, 2] [intake, exhaust]` instead of cryptic index numbers for cam inputs, vvt offset, and modes.

cleanup of VVT ui

---

firmware/controllers/settings.cpp
firmware/hw_layer/hardware.cpp
firmware/hw_layer/hardware.h
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/mmc_card.h
firmware/rusefi.cpp

prep related to #2464, also just general refactoring to make initialization a little less spaghetti
also removes the nearby `getBor` and `setBor` console commands for setting/setting the brownout threshold, which has been set reasonably by `mpu_util` for a long time now, and has no reason to be settable via console.

move some initialization steps earlier

---

firmware/config/stm32h7ems/efifeatures.h
firmware/controllers/flash_main.cpp
firmware/controllers/thread_priority.h

Enable writing H7 flash while the engine is running.  H7 uses dual bank flash, and this change moves the flash write to a low-priority thread (only when enabled) so as to not block any other operations on the ECU.  Behavior for F4/F7 is currently unchanged.
It also moves clearing the `needToWriteConfiguration` flag to *after* the flash write, so the indicator is extinguished in TS once the operation is actually done.

write flash on separate thread for H7

---

firmware/config/engines/mazda_miata_vvt.cpp
firmware/config/engines/vw_b6.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

- remove dead `fuelRailPressure` field, fix corresponding NB miata and VW defaults to use correct config for fixed rail pressure
- Shuffle around some menu options, mostly moving things out of the giant controller menu in to places where they belong
- Write tooltips for multispark
- update language on VVT PID page to match trigger input page
- a little bit of "human proofing" for after start enrichment options so you can't set it to options that makes your engine hard to start

various TS project improvements, dead config fields

---

.github/workflows/sync-wiki.yaml

Apparently double quotes don't work.

Fix sync wiki try numero dos

---

firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/engine_configuration.h
firmware/rusefi.cpp

Fix init order so `RegisteredOutputPin`s are init'd properly at ECU startup.
this was broken by #2481

fix init order

---

firmware/config/boards/hellen/hellen72/board.h

This may solve some transient startup issues with Idle and VVT

Hellen72: Set the default pin states to input-pulldown instead of input-pullup

---

firmware/controllers/actuators/gppwm/gppwm_channel.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/integration/rusefi_config.txt

add a Y axis option that's forced to zero, in case you want to emulate a 1d table instead of a 2d table

gppwm zero option

---

firmware/controllers/bench_test.cpp
firmware/controllers/engine_cycle/fuel_schedule.cpp
firmware/controllers/math/engine_math.cpp

to supress signed vs usigned warnings

use cylinders_count_t in loops through cylinders

---

firmware/controllers/sensors/sensor_type.h

Set explicit values for sensor types, since Lua has no concept of an enum.  These now must stay in the same order so as to not break Lua scripts.

assign specific int values to SensorType

---

firmware/config/stm32f4ems/efifeatures.h
firmware/controllers/lua/lua.cpp

- don't malloc, use a static buffer instead
- enable on F42x ECUs

use static buffer for lua heap, enable on f429

---

misc/jenkins/generate_pinouts/gen_upload_pinouts.sh

This will fix #2609. It's still possible for there to be yaml errors, as we don't check for errors at generation time. The only time an error will show up at generation time is if it prevents getting the file name for the image.

Add check for error

---

firmware/controllers/engine_controller.cpp
firmware/controllers/system/timer/event_queue.cpp
firmware/controllers/system/timer/scheduler.h

This change cuts `sizeof(scheduling_s)` from 24 to 20.  Saves ~750 bytes of memory.
Saves 4 bytes by using the action itself instead of a separate `isScheduled` bit.

pack scheduling_s

---

firmware/controllers/flash_main.cpp
firmware/hw_layer/ports/stm32/stm32f7/STM32F7.ld
firmware/hw_layer/ports/stm32/stm32f7/hw_ports.mk
firmware/hw_layer/ports/stm32/stm32f7/mpu_util.cpp

Previously only supported 2MB STM32F7 devices, so you couldn't actually write your tune to the ECU's flash.
Unfortunately, if a 1MB F7 is in use, the nDBANK option bit _must_ be cleared (ie, set to dual bank mode), otherwise we don't have enough space to store both configuration copies.
This change also now properly supports either option for nDBANK on 2MB devices as well.

Support STM32F7 1MB devices

---

firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_subscription.cpp

- Move pin init to adc subscription, progress towards #2636
- Increase number of available ADC subscription entries, fixes #2632
- Fatal error if we run out of ADC subscription entries would have helped diagnose #2632

move ADC pin initialization

---

firmware/main.cpp
firmware/version_check.h

Fail hard (and obvious) if you tried a compiler that might not work.
fixes #2671

explicit compiler version check

---

firmware/controllers/flash_main.cpp

QC builds didn't fail because they never actually resolve the flash address, which is where the check for a misconfigured device happens
fix #2675

always resolve flash address

---

firmware/controllers/sensors/converters/thermistor_func.cpp
unit_tests/tests/sensor/therm_func.cpp

write a test to make sure ptc thermistors work too
also increases the maximum valid temperature somewhat, since air cooled engines can run HOT

explicitly test PTC thermistors

---

firmware/controllers/algo/airmass/airmass.cpp
firmware/controllers/algo/airmass/airmass.h
firmware/controllers/algo/airmass/alphan_airmass.cpp
firmware/controllers/algo/airmass/alphan_airmass.h
firmware/controllers/algo/airmass/maf_airmass.cpp
firmware/controllers/algo/airmass/maf_airmass.h
firmware/controllers/algo/airmass/speed_density_airmass.cpp
firmware/controllers/algo/airmass/speed_density_airmass.h
firmware/controllers/algo/airmass/speed_density_base.cpp
firmware/controllers/algo/airmass/speed_density_base.h
firmware/controllers/algo/engine.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
unit_tests/mocks.h
unit_tests/tests/ignition_injection/test_fuel_math.cpp

That function can be `const`.  Tangentially related to #2693.
Also breaks out an interface for AirmassModelBase that doesn't have built-in VE logic.

make getAirmass const

---

misc/pinout-gen/script.js

The last fix caused a new bug. If you clicked on a row, the wrong pin was highlighted. This fixes that.
This also tries a new formula for the pin marker text size.

More pinout fixes

---

firmware/hw_layer/drivers/gpio/mc33810.cpp

IGN mode does not want to fire Subaru ignitor

mc33810: set ignition outputs to GP mode

---

firmware/controllers/algo/fuel/fuel_computer.cpp
firmware/controllers/algo/fuel/injector_model.cpp
firmware/hw_layer/drivers/gpio/mc33972.cpp
firmware/hw_layer/drivers/gpio/tle6240.cpp
firmware/hw_layer/drivers/gpio/tle8888.cpp

Address some todos around the code.  All minor.
The lock comments removed are OK because those functions are only ever called from one thread.

Assorted todos

---

java_tools/configuration_definition/src/com/rusefi/ConfigDefinition.java

don't parse in the command line decoding, keep a list and parse afterward

smarter enum file parsing

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Split cranking in to 3 dialogs.
- #2771: Move a few things down to an "advanced" section.
- #2767 clarify IAC cranking correction tooltip/label
- Adds more info to a bunch of cranking-relevant tooltips.

simplify/clarify cranking UI

---

firmware/controllers/actuators/idle_thread.cpp
unit_tests/tests/test_idle_controller.cpp

Found while testing #2745.  Makes getOpenLoop do the right thing in case `overrideCrankingIacSetting` is set to false.
nb: this code path is not currently called by master, but will be after #2745

make the cranking idle implementation match what the UI claims

---

firmware/controllers/actuators/idle_thread.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_idle_controller.cpp

Add config field, implementation, and test for open loop fan/AC idle bump.
Adds an "open loop" section to the idle UI to mirror the implementation in #2745

idle fan/AC open loop bump

---

java_tools/configuration_definition/build.xml

auto generate antlr with compile task, so that simply running `ant` will work

fix dependencies for ConfigDefinition build

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_io.h
firmware/console/console_io.cpp
firmware/console/console_io.h
firmware/console/status_loop.cpp

Some related to https://github.com/rusefi/rusefi/issues/2839 , but does not fix it.
- do not stop "communication" blinking in case TS command executes too long. CRC calculation command previously sometimes cause communication LED to switch to slow blinking for a one period.

TS communication minor fixes

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/controllers/actuators/ac_control.cpp
firmware/controllers/actuators/ac_control.h
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/fan_control.cpp
firmware/controllers/actuators/fan_control.h
firmware/controllers/algo/engine.cpp
firmware/controllers/controllers.mk
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/system_fsio.h
firmware/controllers/system_fsio.txt
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_fan_control.cpp

progress to #2817 
- Adds setting for max RPM
- Adds setting for max CLT (engine overheat protect)
- Adds setting for max TPS (wot AC disable)
- Only enable AC with fan when AC actually on, not just mirroring switch

Move AC logic out of FSIO

---

firmware/controllers/engine_cycle/rpm_calculator.cpp
unit_tests/tests/trigger/test_real_cranking_miata_NA.cpp
unit_tests/tests/trigger/test_real_cranking_miata_na6.cpp

fix #2885 
call movePreSynchTimestamps exactly once, on the first sync

fix instant rpm

---

firmware/config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml

1l and 1r are tied to the same pin and rely on the same id.  removed the id and TS name from 1r and removed pin designation from 1L TS name to avoid confusion.  Now just "Radiator Fan"

1l and 1r fix

---

.github/workflows/build-unit-tests.yaml
unit_tests/run_sharded_tests.sh
unit_tests/tests/test_etb.cpp

Run every unit test individually to test for cross-test-spillage

shard unit tests

---

firmware/rusefi.cpp

Avoids a fatal error at startup if you have ETB idle.

init loops after sensors

---

misc/jenkins/generate_pinouts/gen_upload_pinouts.sh
misc/pinout-gen/append.sh

quick fix
I'm not sure what actually changed. It appears that yq now outputs "null" for a key that's not found, which was one problem, but I'm not sure what changed to cause the main problem.

Fix Pinouts again

---

firmware/config/boards/STM32F407VET6_Mini.bat
firmware/config/boards/hellen/hellen121nissan/board.h
firmware/config/boards/hellen/hellen121vag/board.h
firmware/config/boards/hellen/hellen128/board.h
firmware/config/boards/hellen/hellen64_miataNA6_94/board.h
firmware/config/boards/hellen/hellen72/board.h
firmware/config/boards/prometheus/board.h
firmware/config/boards/subaru_eg33/board.h
firmware/config/boards/subaru_eg33/mcuconf.h
firmware/hw_layer/ports/stm32/mcuconf_common_f4_f7.h
firmware/hw_layer/ports/stm32/osc_detector.cpp
firmware/hw_layer/ports/stm32/stm32_common.mk
firmware/hw_layer/ports/stm32/stm32f4/board.h
firmware/hw_layer/ports/stm32/stm32f4/cfg/mcuconf.h
firmware/hw_layer/ports/stm32/stm32f7/board.h
firmware/hw_layer/ports/stm32/stm32f7/cfg/mcuconf.h

This allows for universal firmware that can detect any (integer mhz) external crystal frequency.

auto detect HSE clock speed

---

firmware/console/eficonsole.cpp
firmware/hw_layer/ports/stm32/osc_detector.cpp

kind ChibiOS forum user had a better idea, to use the RTCPRE and TIM11 to measure HSE instead of doing the LSE double-hop.
https://forum.chibios.org/viewtopic.php?f=3&t=5892&p=40250#p40245

detect clock with TIM11 instead of TIM5

---

firmware/config/boards/microrusefi/connectors/main.yaml
misc/pinout-gen/pinout.html
misc/pinout-gen/script.js

Only the first "title" field is used
Each connector will have its "name" field placed above it

Pinout Title and connector names

---

java_console/autotest/src/com/rusefi/proteus/ProteusAnalogTest.java

added an analog filter in hardware (bodge wires), we should wait longer, but it'll be more accurate now

proteus hw ci: wait longer but be stricter

---

misc/pinout-gen/script.js

This fixes a bug I noticed, where if you click the entry in the info table that shows up when you click a pin, it scrolls to the top of the page and adds the pin info to the first connector's info table.

Fix Pinouts bug

---

java_console/.idea/ant.xml
java_console/autoupdate/src/main/java/com/rusefi/autoupdate/AutoupdateUtil.java

The problem was that none classloader of rusefi_autoupdate contains the path to `rusefi_console.jar` and URLClassLoader which is used to load `rusefi_console.jar` didn't embed in the classloaders hierarchy. Nevertheless, to load icons you use `getResource()` from `Class` this method just resolves resource name according to class package and consequently use its ClassLoader `getResource()` method. Eventually, the path to the `rusefi_console.jar` keeps nowhere after invoking the `Launcher.main` method. Thus, to solve this problem we should someway insert the path for `rusefi_console.jar`.
Solutions:
1. Insert jar's URL to system classloader using Reflection API
2. Embed classloader with jar's URL to the classloaders hierarchy. __Maybe impossible__
3. Use only our custom classloader with …

hotfix 2944: broken icon paths in rusefi_autoupdate

---

firmware/config/boards/proteus/board.mk
firmware/config/stm32f7ems/efifeatures.h
firmware/console/binary/tunerstudio_io.h
firmware/console/binary/tunerstudio_io_serial.cpp
firmware/console/binary/tunerstudio_io_serial_ports.cpp

Needed some minor header adjustments to compile properly with pch.  This was compiling by luck before, and the failure now would still fail even if we just included one header instead of it being a proper pch.

make tunerstudio_io_serial_ports happy with pch

---

firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h
unit_tests/tests/trigger/test_cam_vvt_input.cpp

fix #3070 
The problem was that instant RPM was trying to use `currentCycle.current_index`, which doesn't account for trigger patterns that only cover part of the engine cycle (for example, a crank only trigger).
This looks much better now!
As a bonus, this probably helps #3015, since now symmetrical crank instant RPM /actually/ works, instead of only calculating on one tooth per cycle, which effectively broke instant RPM on symmetrical crank triggers.

instant rpm uses full engine cycle

---

unit_tests/engine_test_helper.cpp
unit_tests/tests/trigger/test_real_cranking_miata_na6.cpp

call `handleShaftSignal` instead of `engine->triggerCentral.handleShaftSignal` in unit tests
fixes #3096

call handleShaftSignal

---

unit_tests/efifeatures.h
unit_tests/tests/test_vehicle_speed.cpp
unit_tests/tests/tests.mk

I has found, what wrapping 
`
CONFIG(vehicleSpeedSensorInputPin) = GPIOA_0;
brain_pin_markUsed(GPIOA_0, "VSS" PASS_ENGINE_PARAMETER_SUFFIX);
engineConfiguration->vehicleSpeedCoef = speedCoef;
`
into function causes big mess and tons of parameters, so i just copy-paste it.
Idk why `brain_pin_markUsed()` dont works, and vehicleSpeed still has `NOT_ASSIGNED`, so i used direct 'CONFIG(vehicleSpeedSensorInputPin) = GPIOA_0;' too.

Unit tests for vehicle speed.cpp #3081

---

firmware/controllers/engine_cycle/rpm_calculator.cpp
unit_tests/tests/ignition_injection/injection_mode_transition.cpp
unit_tests/tests/trigger/test_fasterEngineSpinningUp.cpp

Not much reason to do this - we don't make this check at all for non-instant RPM, so there isn't a reason to do it for instant RPM either.  It could actually hinder starting for an engine that starts quickly - it will give a wrong RPM reading if the engine kicks before a full cycle has completed, increasing engine speed past the cranking threshold before a full cycle (and "normal" RPM reading) is complete.  The wrong RPM will cause events to be scheduled late, possibly hindering engine start, as it means ignition timing will be (possibly significantly) retarded from the set value.

don't "validate instant RPM"

---

firmware/controllers/sensors/map.cpp

Updated Mazda 1 bar to follow measurements.
Files and calibration available at #3184

updated OEM map sensor values for Mazda 1 bar

---

firmware/tunerstudio/rusefi.input

From this:
To this:
Same for few other Idle and Crank related tables.

Rusefi input fixes: make some tables more frienly looking

---

firmware/controllers/sensors/converters/turbocharger_speed_converter.h
firmware/controllers/sensors/frequency_sensor.cpp
firmware/controllers/sensors/frequency_sensor.h
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor_type.h
firmware/init/sensor/init_flex.cpp
firmware/init/sensor/init_turbocharger_speed_sensor.cpp
firmware/init/sensor/init_vehicle_speed_sensor.cpp
unit_tests/tests/sensor/test_frequency_sensor.cpp
unit_tests/tests/sensor/test_turbocharger_speed_converter.cpp

- add sensor type for turbo speed
- output rpm instead of hz
- `FrequencySensor::init` doesn't need msg param, just ask the sensor what it's called
#3243

Turbo sensor

---

firmware/tunerstudio/rusefi.input

rusefi.input: adjust RPM gauge limits
- Low red zone - up to 200
- Low yellow zone - up to Cranking RPM limit
- High yellow zone - from (RPM Hard Limit - 500)
- High red zone - from RPM Hard limit and up to (RPM Hard limit + 2000)
rusefi.input: "deg C" -> "C" on all gauges

Rusefi input cosmetics

---

firmware/controllers/engine_cycle/map_averaging.cpp

Not sure what this was for, but it wasn't doing anything.  Looks like an attempt at a lock-free implementation, but lock free isn't necessary here.  There's so little work to do under lock that the overhead is negligible.

dead code in map avg

---

firmware/controllers/engine_controller.cpp
firmware/controllers/engine_controller.h
firmware/controllers/engine_controller_misc.cpp
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt

Dead mock setters for iat/clt. Superceded long ago by just setting the mock sensor value itself.

dead mock iat/clt

---

firmware/console/status_loop.cpp

`updateTunerStudioState` uses a ton of stack on unoptimized builds, since it doesn't reuse stack space for multiple different locals/scratch work unless you enable optimization.  It will, however, reuse the same stack space if the work is being done by different functions!
When optimization is enabled, this change has almost no impact - all these new functions get inlined, and the stack space reused so very little is used in that case either way.
helps #3302

reduce updateTunerStudioState stack usage

---

firmware/controllers/engine_cycle/map_averaging.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

discussion in #3309, saves 48 bytes of precious memory

shrink multi cylinder map average buffer

---

firmware/console/status_loop.cpp
firmware/controllers/actuators/ac_control.cpp
firmware/controllers/actuators/alternator_controller.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/airmass/airmass.cpp
firmware/controllers/algo/airmass/maf_airmass.cpp
firmware/controllers/algo/airmass/speed_density_airmass.cpp
firmware/controllers/algo/dynoview.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/launch_control.cpp
firmware/controllers/can/can_dash.cpp
firmware/controllers/can/can_verbose.cpp
firmware/controllers/can/obd2.cpp
firmware/controllers/can/rusefi_wideband.cpp
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/map_averaging.cpp
firmware/controllers/gauges/lcd_controller.cpp
firmware/controllers/limp_manager.cpp
firmware/controllers/lua/lua_hooks.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/sensors/map.cpp
firmware/controllers/sensors/sensor.h
firmware/hw_layer/stepper.cpp
unit_tests/tests/sensor/test_sensor_init.cpp
unit_tests/tests/test_logic_expression.cpp

Saves some stack since there's no longer a `SensorResult` temporary required for every call to `Sensor::get` if we're just going to discard it anyway.  Also a handy thing to have anyway.
#3302

add getOrZero

---

.gitmodules

OpenBLT is forked for RusEFI, rusefi_prod brunch is used.

OpenBLT: add as submodule under firmware/ext

---

firmware/controllers/algo/rusefi_types.h
firmware/util/containers/table_helper.h
firmware/util/scaled_channel.h
unit_tests/tests/tests.mk
unit_tests/tests/util/test_scaled_channel.cpp

Disallow scaled_channel for float.  I can't think of a reason to allow it, and it gets in the way
of rounding.
Add separate template param to setTable; let the compiler sort out whether assignment can happen
between TElement and VElement without forcing them to be the same at function call time.

Allow scaled_channel to have both multiplier and divisor

---

firmware/config/engines/vw_b6.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/controllers/engine_cycle/high_pressure_fuel_pump.cpp
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Remove the old algorithm so the diff that includes the new algorithm doesn't intermix unrelated code.
The algorithm is the same one as before, but the configuration is separated out as requested.

Configuration for HPFP control algorithm.

---

.github/workflows/build-unit-tests.yaml
unit_tests/rules.mk
unit_tests/unit_test_rules.mk

- don't emit assembly listings for unit tests (nobody looks at these?), worth about 20%
- disable code coverage unless specified, and specify it in CI runs, worth another 15%
Total improvement: 32% reduction in compile time.
Address sanitizer stays on, since it was only worth about 4% on my machine.
fix #3485

unit test build times

---

firmware/controllers/engine_controller_misc.cpp
firmware/util/efitime.h
unit_tests/tests/test_util.cpp

Saves another 4 instructions / 12 bytes.  It should take less time to run this than to even enter CriticalSectionLocker.

Make getTimeNowNt even faster

---

firmware/Makefile
firmware/bootloader/src/Makefile
firmware/rusefi_pch.mk
simulator/Makefile
unit_tests/tests/test_util.cpp
unit_tests/unit_test_rules.mk

Having to remove the precompiled header when switching from firmware to simulator to unit_tests and
back again is annoying.  Use a directory to store the precompiled header output.  Turn off
precompiled header warnings as GCC still complains even if it finds a valid one eventually.

Compile each project's PCH to a separate file to reduce developer friction

---

firmware/controllers/core/state_sequence.cpp
firmware/controllers/core/state_sequence.h
firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.h
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_emulator_algo.cpp

All it wants is to use the main trigger state, so don't bother copying it.  Instead, change
PwmConfig to take a const pointer to a Multi.*Sequence, then make all the users adapt.  Worse
fallout is that SimplePwm now has its own Multi.*Sequence, but PwmConfig is downgraded to a
pointer, so that's only a net +4 bytes.  And we can make the overhead of Multi.*Sequence much lower
using embedded arrays, which only the caller can do since it knows the maximum size... (for another
day...)
Also remove SimplePwm's 2nd copy of SingleChannelStateSequence.  It served no purpose.
Saves 1992 bytes of BSS and 24 bytes of RAM4 (latter probably due to SimplePwm change)

Don't keep a separate MultiChannelStateSequence for the trigger emulator.

---

firmware/controllers/core/state_sequence.cpp
firmware/controllers/core/state_sequence.h
firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.h
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_emulator_algo.cpp

All it wants is to use the main trigger state, so don't bother copying it.  Instead, change
PwmConfig to take a const pointer to a Multi.*Sequence, then make all the users adapt.  Worse
fallout is that SimplePwm now has its own Multi.*Sequence, but PwmConfig is downgraded to a
pointer, so that's only a net +4 bytes.  And we can make the overhead of Multi.*Sequence much lower
using embedded arrays, which only the caller can do since it knows the maximum size... (for another
day...)
Also remove SimplePwm's 2nd copy of SingleChannelStateSequence.  It served no purpose.
Saves 1992 bytes of BSS and 24 bytes of RAM4 (latter probably due to SimplePwm change)

Don't keep a separate MultiChannelStateSequence for the trigger emulator, version 2.

---

firmware/controllers/core/state_sequence.cpp
firmware/controllers/core/state_sequence.h
firmware/controllers/trigger/decoders/trigger_structure.cpp
unit_tests/tests/trigger/test_nissan_vq_vvt.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

Better than reaching into members that should be private.  I didn't feel like actually making them private though, as one user validates pinStates isn't NULL.

Change users of MultiChannelStateSequence to use the API

---

firmware/Makefile

The compiler was outsmarting us: UNUSED_CCM disappeared entirely (probably because of the *0),
while UNUSED_RAM was helpfully moved to read-only flash.  It's possible making these not static
would have helped, but link time optimization might have gotten rid of them too.
Instead, print BSS and RAM4 totals at the end using the java script.  If java is unable to run,
don't error out the Makefile, just complain a little and move on.  Until the gcc_map_reader
actually works with RAM4, we print it manually.

Print BSS and RAM4 totals at the end of make.

---

firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/controllers/trigger/trigger_simulator.cpp
unit_tests/tests/ignition_injection/test_fuel_map.cpp
unit_tests/tests/trigger/test_miata_na_tdc.cpp
unit_tests/tests/trigger/test_nissan_vq_vvt.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

It will eventually be class to support dynamic universal patterns in addition to ROM-based
tables.

Convert TriggerWaveform::wave to a pointer in preparation for code-defined sequences.

---

simulator/simulator/efifeatures.h

If you give the Lua interpreter no memory, it does not work.
fix #3561

simulator gets a heap

---

firmware/controllers/algo/engine.h
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/engine_configuration.h
firmware/controllers/engine_controller.cpp
firmware/controllers/flash_main.cpp
firmware/controllers/persistent_store.cpp
firmware/controllers/settings.cpp

This allows the compiler to see through the pointer and make accesses faster.
It saves 1336 bytes of text.

Make engine* and friends be const pointers in production.

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/airmass/airmass.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/util/containers/type_list.h
unit_tests/tests/trigger/test_injection_scheduling.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

engineModules.get<FOO>(). becomes modules<FOO>()->
I believe the new API is more conducive to supporting arrays, by doing std::array<T, N> or
std::array<Mockable<T>, N>, with the support of a helper class.

Make the module API more concise.

---

firmware/console/binary_log/log_field.cpp
firmware/console/binary_log/log_field.h

Also move the type field for better packing.  Saves about 500 bytes of flash.
This fixes #3574.

Extend LogField to support scaled_channel divisors.

---

firmware/controllers/trigger/decoders/trigger_mazda.cpp

Zach's car didn't start since he was just outside the sync conditions while cranking.  Tweaks the timing to be a little more generous.
Tested on the car in question using the sync override option.

adjust miata sync conditions

---

firmware/controllers/algo/engine2.cpp
firmware/util/containers/cyclic_buffer.h

This exposed a buffer overrun, so double the size of the buffer (to account for 720 degree engine
cycle vs 360 degree crank events).
Also use proper numeric limits when computing min/max.
Finally, add a lock around the call to cyclic_buffer that actually caused the contention.

Fix potential buffer overrun in cyclic_buffer.

---

firmware/controllers/core/state_sequence.cpp
firmware/controllers/core/state_sequence.h
firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.h
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/controllers/trigger/trigger_simulator.cpp
unit_tests/tests/ignition_injection/test_fuel_map.cpp
unit_tests/tests/trigger/test_miata_na_tdc.cpp
unit_tests/tests/trigger/test_nissan_vq_vvt.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

Most all the users were Multi* anyways, so just improve that:
1. Allow up to 8 waveforms to share one byte per timestamp.  It could be better but this is simple
and gets most of the benefit.
2. Use a wrapper structure to handle reserving space for the arrays.  Makes the interface simpler
and more rigid.  Also saves 4 bytes per Multi*.  Downside is access is now via -> and *,
not . and (nothing).
Saves 224 bytes of BSS, 1832 bytes of RAM4/CCM, 824 bytes of TEXT (yay? but unexpected...), and
costs 26 bytes of RODATA (more yay?)

Drop SingleChannelStateSequence in favor of MultiChannelStateSequenceWithData

---

firmware/controllers/core/fsio_impl.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/lua/lua.cpp
firmware/init/sensor/init_thermistors.cpp

Lua's stack probably doesn't need DMA.  Allows us to group more of our unused RAM together
in one place.

Move LuaThread to CCM, and shuffle a couple items out.

---

firmware/console/status_loop.cpp

SD log has a buffer overflow that we didn't detect because of #3595 and because of #3594

embiggen SD log buffer

---

firmware/config/engines/GY6_139QMB.cpp
firmware/config/engines/dodge_neon.cpp
firmware/controllers/algo/auto_generated_commonenum.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/controllers/engine_cycle/map_averaging.cpp
firmware/integration/rusefi_config.txt

With fast TS, we don't need MAP sensor chart.
#3607

goodbye MAP sensor chart

---

firmware/setup_linux_environment.sh

- newer dependencies
- add current user to `dialout` group so you can access serial ports without root

setup script adjustments

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/controllers/algo/wall_fuel.cpp
firmware/controllers/algo/wall_fuel.h
firmware/tunerstudio/rusefi.input

- Log something actually useful instead of claiming it's milliseconds (it's not)
- Clarify units on wall wetting
- disable WW if either beta or tau is zero

wall fuel tweaks

---

firmware/controllers/actuators/alternator_controller.cpp
firmware/integration/rusefi_config.txt

We don't need industrial PID nonsense for alternator.  It also seems to break alternator debug outputs, which is relevant to https://rusefi.com/forum/viewtopic.php?f=19&t=2226

alternator not industrial pid

---

firmware/console/status_loop.cpp
firmware/console/status_loop.h
firmware/controllers/trigger/trigger_central.cpp

improve engine phase logging by using actual tooth angle, instead of inferring angle from last sync point
this improves accuracy when cranking due to engine speed variation (think: harley cranking with 900cc cylinders)
relevant to #3645

use tooth angle instead of timed angle

---

firmware/controllers/algo/engine.h
firmware/controllers/engine_cycle/fuel_schedule.cpp
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/math/engine_math.h

Fueling and ignition now both use the same math, and incorporate the cylinder offset table. In anticipation of adding a separate small per-cylinder table to set ignition offset, since there's no need to set separate per-cylinder injection offset.
To clarify:
- Existing options become "cylinder offset from even-fire position" which applies to both ignition and injection for that cylinder.  This is for configuring when your crankshaft fires at odd-intervals, like v-twin, some V6, most V10, etc.
- New tables will set per-cylinder ignition-only trim.
probably completes #2501

simplify cylinder phasing calculation

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

We have better tools for this now, no reason to have an option that prints out 1000 messages per second

remove etb status option

---

firmware/controllers/core/state_sequence.h
unit_tests/tests/test_can_serial.cpp

You can't include anything before pch.
You also have to include `<array>` if you intend to use `std::array`.

make macos happy

---

firmware/Makefile
firmware/check.c

Related to https://github.com/rusefi/rusefi/issues/3644

GCC-10 and C++ 2a: supress depricated volatile use errors

---

firmware/hw_layer/drivers/can/can_hw.cpp
firmware/hw_layer/drivers/can/can_hw.h
firmware/hw_layer/ports/cypress/mpu_util.cpp
firmware/hw_layer/ports/kinetis/mpu_util.cpp
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/stm32/stm32_common.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

- Fixes broken H7 from dual CAN (but doesn't make CAN work on the H7).
- Corrects init sequence when using different baud rate on both devices, and when "logical CAN device 1" may be CAND2, not CAND1.
- Only initialize CAN read for devices that are configured
- Adjust UI to show one section for CAN data settings, and one section per CAN hardware (pins, bitrate)

fix dual CAN init, update UI

---

firmware/controllers/engine_cycle/high_pressure_fuel_pump.cpp

According to one of the logs, the I sum was being forced quite negative when the P term went very large due to the error being 46 bar when starting the car.

GDI/HPFP: Don't take P term into account when clamping I.

---

firmware/controllers/actuators/idle_hardware.cpp

This needs additional investigation. But allocating these structs
in CMM cause HardFault

Move out of CMM

---

firmware/controllers/actuators/dc_motors.cpp
firmware/controllers/actuators/dc_motors.h
firmware/controllers/actuators/idle_hardware.cpp
firmware/controllers/actuators/idle_thread.cpp

GP1-GP4 on MRE is now can be used to directly drive 4-wire stepper idle valve.
Do not forget to enable "useTLE8888 stepper" option. This will enable Push-Pull mode for corresponding outputs.
Depends on https://github.com/rusefi/rusefi/pull/3749

Stepper direct push pull driver

---

firmware/hw_layer/drivers/gpio/tle8888.cpp

Some register settings also needs to be changed. Change of direct
drive input is not enought.

TLE8888: do not allow direct gpio drive for Push Pull outputs

---

firmware/hw_layer/drivers/can/can_hw.cpp

Otherwise it will emit strange error if both can are disabled

CAN: do null check first

---

firmware/hw_layer/ports/stm32/mcuconf_common_f4_f7.h

Some board (like stm32f429-disco) with SDRAM need clock to be
enabled in __early_init (before .bss and .data initialization).
So if STM32_HSECLK defined - skip clock detection.

Enable ENABLE_AUTO_DETECT_HSE only if STM32_HSECLK is not defined

---

firmware/config/boards/proteus/board_configuration.cpp
firmware/hw_layer/ports/stm32/port_mpu_util.h
firmware/hw_layer/ports/stm32/stm32_common.cpp
firmware/hw_layer/ports/stm32/stm32f7/mpu_util.cpp

Some boards might need to do special things before going to low-power mode.

per-board pre-low-power handlers

---

firmware/flash_can.sh
firmware/flash_dfu_openblt_only.sh

This adds script to flash OpenBLT bootloader only over DFU.
This adds script to update RusEFI part of FW over can.
You may want to run `dfu_erase.sh` first to test how to flash over can. Then `flash_dfu_openblt_only.sh` to flash bootloader only.
Then connect you CAN adapter, bring can0 interface up and run `flash_can.sh` to test FW update over CAN.

Openblt scripts

---

firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Pretty self explanatory.  Never uses "slow" RPM, always uses instant RPM.
On my v8, this fixes a post-start stumble presumably caused by inaccurate ignition timing (maybe fuel timing too) that happens during the engine's rapid acceleration from cranking to idle (the engine goes from 150 -> 1100 rpm in 0.21 second!).

add option to always use instant RPM

---

firmware/gen_config.sh

maybe fix https://github.com/rusefi/web_backend/issues/138
see how proteus_h7 is missing from this list? https://rusefi.com/online/ini/rusefi/2022/01/20/

add proteus h7 to list

---

.github/workflows/build-firmware.yaml

This is another approach to #3817
This adds the option to run the workflow manually, and if it is run manually, it doesn't skip any jobs.

Don't skip firmware jobs if workflow is run manually

---

firmware/controllers/algo/fuel/dfco.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/ignition_injection/test_fuelCut.cpp

Add conditions to enable/disable decel fuel cut at low speed. Helps with low-speed jerkiness from decel fuel cut in low gears.

vss based dfco

---

firmware/config/boards/hellen/alphax-2chan/connectors/main.yaml

@chuckwagoncomputing is this the right thing to do for pins that have multiple internal functions? These two pins can either be a VR interface, OR two hall inputs. Those functions each use a different STM32 pin.
#3744

alphax 2ch crank hall/vr options

---

firmware/config/boards/hellen/hellen-nb1/prepend.txt
firmware/config/boards/hellen/hellen121nissan/prepend.txt
firmware/config/boards/hellen/hellen121vag/prepend.txt
firmware/config/boards/hellen/hellen128/prepend.txt
firmware/config/boards/hellen/hellen154hyundai/prepend.txt
firmware/config/boards/hellen/hellen64_miataNA6_94/prepend.txt
firmware/config/boards/hellen/hellen72/prepend.txt
firmware/config/boards/hellen/hellen81/prepend.txt
firmware/config/boards/hellen/hellen88bmw/prepend.txt
firmware/config/boards/hellen/hellenNA8_96/prepend.txt
firmware/config/boards/microrusefi/prepend.txt
firmware/config/boards/proteus/prepend.txt
firmware/config/boards/subaru_eg33/prepend.txt
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

- dead `showSdCardWarning`
- hide SD card pinout options on hard wired boards

SD card UI cleanup

---

java_console/models/src/main/java/com/rusefi/waves/EngineReport.java
java_console/models/src/main/java/com/rusefi/waves/RevolutionLog.java
java_console/models/src/test/java/com/rusefi/waves/test/EngineReportTest.java
java_console/ui/src/main/java/com/rusefi/TriggerImage.java
java_console/ui/src/main/java/com/rusefi/ui/engine/EngineSnifferPanel.java
java_console/ui/src/main/java/com/rusefi/ui/engine/EngineSnifferStatusPanel.java
java_console/ui/src/main/java/com/rusefi/ui/engine/UpDownImage.java

- Change layout slightly based on height (don't render too much)
- Slightly improve performance
- Simplify rendering logic for UpDownImage
- Remove gross mouse-over big red text
- Fix line stroke spillage out from dashed lines in to borders of sniffer items
- Render 1 decimal place instead of 2 for angles (who cares about 0.01 degree?)
- Don't overlap row labels (left side) with rendered events

Engine sniffer refinements

---

firmware/config/boards/atlas/board_configuration.cpp
firmware/config/boards/core8/board_configuration.cpp
firmware/config/boards/f407-discovery/board_extra.cpp
firmware/config/boards/f429-discovery/board_configuration.cpp
firmware/config/boards/nucleo_h743/board_configuration.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/integration/rusefi_config.txt

Stepper config should be brain pins, as those are internal to ECU, and are only ever STM32 pin names.
Move/add some config to core8 config overrides.

core 8 overrides and stepper-as-brain-pin

---

firmware/config/boards/core8/board_configuration.cpp

CAN 1 TX and RX pin overwrites were set incorrectly causing error in TS

Fix to CAN 1 bus overwrites. TX and RX pins swaped.

---

java_console/ui/src/main/java/com/rusefi/ui/engine/EngineSnifferPanel.java
java_console/ui/src/main/java/com/rusefi/ui/engine/UpDownImage.java

fix broken engine sniffer due to silent failure of `assertAwtThread`
This also greatly reduces the number of repaints we queue - it's now just one per update, instead of one _per row_ per update.

fix engine sniffer repaint

---

firmware/config/boards/hellen/hellen128/board_configuration.cpp

Tested on Hellen128 revC -> Board id is read correctly.
2022-03-21_23_38_27_832: EngineState: i2c on PB10
2022-03-21_23_38_27_833: EngineState: i2c on PB11
2022-03-21_23_38_27_837: EngineState: BoardID [6300]
[...]
2022-03-21_23_38_28_080: EngineState: ETB Disable on PD13
2022-03-21_23_38_28_084: EngineState: ETB Dir 1 on PC6
2022-03-21_23_38_28_085: EngineState: ETB Enable on PC7

Hellen128 board variant

---

firmware/hw_layer/digital_input/digital_input_exti.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_exti.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_icu.cpp

maybe helps with #4019 
carve off a piece of #3032
Probably actually helps with performance since we don't loop through entries that don't have anything there.

exti uses a queue

---

firmware/config/boards/hellen/hellen-nb1/board_configuration.cpp
firmware/config/boards/hellen/hellenNA8_96/board.mk
firmware/config/boards/hellen/hellenNA8_96/board_configuration.cpp

NA8 was using NB1 board config file, and was overriding trigger input pins so you couldn't change pinout.

fix nb1 vs na8 config

---

firmware/controllers/algo/engine.cpp

@rusefillc this is what I meant by "check raw voltage" #4059
We don't want/need to re-test the thermistor decoding logic, we want to check if the hardware works.

check voltage instead of temperature

---

firmware/console/binary/FragmentEntry.cpp
firmware/console/binary/FragmentEntry.h
firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.h
firmware/console/binary/tunerstudio_commands.cpp
java_tools/configuration_definition/src/main/java/com/rusefi/ldmp/UsagesReader.java
unit_tests/tests/test_scattered_outputs.cpp

- pass around const-friendly `FragmentList` instead of pointer/size
- use `size_t` as appropriate instead of int
- fix overflow bug in case of reading off the end of a fragment list
- improve fragment tests
- remove now-unnecessary `initFragments()`
- simplify `live_data_fragments.cpp` generation
- clearer parameter names for `copyRange`

fragment refactoring

---

firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h

- encapsulate `vvtSyncCounter`
- move `syncEnginePhase`/`hasSynchronizedPhase` inside the "primary" trigger decoder class, VVT doesn't need these.

minor trigger decoder refactoring

---

firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h

Switch vvt sync back to flag. We can just reset the flag when we lose sync, since there may be conditions where we want to spend long periods of time without trying to resync based on cam.

switch back to flag

---

firmware/console/status_loop.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h

A bunch of logic was in `engine.cpp` that really should be part of the trigger decoder itself.
This PR moves it in.
Unblocks #4152 being able to reset the "full sync" flag when we get a trigger error.

move logic in to trigger decoder

---

firmware/controllers/trigger/trigger_decoder.h
unit_tests/run_sharded_tests.sh
unit_tests/tests/trigger/test_trigger_decoder_2.cpp

I dropped this: `!`
Adds tests to verify behavior.
Also increases the number of shards used in `run_sharded_tests.sh` since we have more than 500 tests now.

Fix trigger error indicator

---

firmware/config/boards/hellen/harley81/board.mk
firmware/config/boards/hellen/harley81/board_configuration.cpp
firmware/hw_layer/ports/stm32/mcuconf_common_f4_f7.h
firmware/hw_layer/ports/stm32/stm32_common.cpp

PWM HW timer conflict between VR and ETB consumers
both are using hardware pwm
but trying to use different frequency on timer
so it's running the ETB at 10khz I think

harley pwm fix

---

firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h

Return a result with the current trigger tooth, instead of outside components reaching inside the trigger decoder to find out where we are.
Break out a function for MAP cam decode to improve legibility.

trigger decoder returns a result

---

.gitmodules
firmware/controllers/sensors/AemXSeriesLambda.cpp

Update wideband firmware to a version that uses the new, custom format! That means we're up to date with `master` on the wideband controller, which gets us the new goodness like temperature decoding, versioned messages, and better resolution for things like ESR, temperature, and other debugging parameters.

update wideband firmware

---

firmware/controllers/algo/engine.cpp
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h
unit_tests/tests/trigger/test_trigger_decoder.cpp
unit_tests/tests/trigger/test_trigger_decoder_2.cpp

- don't pass extra parameter to initializeTriggerWaveform that we already have access to
- set `TriggerDecoder`'s name in the constructor, not in `engine.cpp`

Trigger cleanup init

---

firmware/hw_layer/ports/rusefi_halconf.h
firmware/integration/rusefi_config.txt

#4200, this gets us 500hz. I tried even bigger and it didn't get faster, so I'm not sure where the perf went. It doesn't seem to be the ECU since it's pinned at exactly 500.0/499.9.

500 byte blocking factor

---

java_tools/configuration_definition/src/main/java/com/rusefi/ConfigField.java

```
$ ./gen_config.sh | grep RRRR
mkdir: cannot create directory ‘build’: File exists
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='timeConstant', type='uint16_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='deadband', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='minAfr', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='maxAfr', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on ConfigField{name='knockRetardAggression', type='uint8_t', arraySizes=[]}
RRRRRRRRRRRRRRRR Unexpected scale of 0.1 without autoscale on …
```

new autoscale constraint

---

firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_state.h

We never updated `timeSinceCrankingInSecs` if you didn't have a post-crank fuel taper enabled.
fix #4253

fix closed loop fueling if post cranking fuel taper not enabled

---

firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_decoder.cpp
unit_tests/tests/trigger/test_trigger_decoder_2.cpp
unit_tests/tests/trigger/test_trigger_noiseless.cpp

- increment trigger error counter in all cases (answer to the TODO is `yes`)
- small format cleanup
- clarify VVT angle validation logic (because alphax is maybe having an issue with this on hyundai)

trigger tweaks cleanup

---

firmware/CHANGELOG.md
firmware/controllers/lua/lua_can_rx.cpp

Previously the ID could get passed with some garbage in the high bits when processing an 11b frame.

fix lua CAN RX of 11b frames

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_io.h

-reduce timeouts ~~on both sides (may cause disconnect while flashing settings on boards with single bank flash)~~
-do not emit error messages and replies if connection is out of sync
-remove duplicated debug messages

TunerStudio reconnect speedup

---

firmware/controllers/lua/lua_hooks.cpp
firmware/controllers/sensors/sensor.cpp
unit_tests/tests/sensor/basic_sensor.cpp

Detect when we fail to decode a sensor name, and trip an error in Lua if/when that happens.
Also do a soft check in case you really do register two of the same sensor so it doesn't tank the whole ECU.
fix #4368

detect bad Lua sensor name when registering

---

firmware/controllers/actuators/fan_control.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/fuel/dfco.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/engine_cycle/aux_valves.cpp
firmware/controllers/engine_cycle/high_pressure_fuel_pump.cpp
firmware/controllers/sensors/converters/flex_sensor.h
firmware/controllers/sensors/converters/linear_func.cpp
firmware/controllers/sensors/converters/resistance_func.cpp
firmware/controllers/sensors/converters/thermistor_func.cpp
firmware/controllers/sensors/functional_sensor.cpp
firmware/controllers/sensors/redundant_ford_tps.cpp
firmware/controllers/sensors/redundant_sensor.cpp
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor_info_printing.cpp
firmware/controllers/sensors/stored_value_sensor.h
firmware/util/expected.h
unit_tests/tests/sensor/func_sensor.cpp

Instead of just returning "failed", sensors can now return information about the nature of the failure. Timeout, low, high, inconsistent, etc. That way we can better report to the user what happened.

unexpected contains information about why it failed

---

firmware/controllers/math/speed_density.cpp

previous behavior was a bug, was returning 0 when it should return the IAT

correct behavior in case of failed CLT but not failed IAT

---

firmware/controllers/sensors/sensor_checker.cpp

Don't try to report any pins that returned `invalid`, since pins those don't have diag information available.
#4418

ignore invalid diag result when checking ign/inj

---

unit_tests/tests/trigger/test_miata_na_tdc.cpp
unit_tests/tests/trigger/test_quad_cam.cpp
unit_tests/tests/trigger/test_real_cranking_miata_NA.cpp
unit_tests/tests/trigger/test_real_cranking_miata_na6.cpp
unit_tests/tests/trigger/test_real_cranking_nissan_vq40.cpp
unit_tests/tests/trigger/test_real_gm_24x.cpp
unit_tests/tests/trigger/test_real_k24a2.cpp
unit_tests/tests/trigger/test_real_nb2_cranking.cpp
unit_tests/tests/trigger/test_real_volkswagen.cpp
unit_tests/tests/trigger/test_symmetrical_crank.cpp

Progress to #4460.
This is all tweaks to when we get RPM (always instant gets us rpm earlier), and exact RPM numbers that change a little.

enable alwaysInstantRpm in some tests

---

firmware/tunerstudio/rusefi.input

This fixes issue when only GPPWM 4 output Gauge was available.

tunerstudio: GPPWM gauges: unique names, use Note as label

---

firmware/tunerstudio/rusefi.input

I'd like to see something on indicator even it is off.
From this:
to this:

tunerstudio: indicators: no blank indicators in off state

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/obd_error_codes.h
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h
unit_tests/tests/trigger/test_cam_vvt_input.cpp
unit_tests/tests/trigger/test_real_cranking_nissan_vq40.cpp
unit_tests/tests/trigger/test_real_nb2_cranking.cpp
unit_tests/tests/trigger/test_trigger_decoder_2.cpp

Instead of some catch-all trigger warnings, have exactly one warning per type of trigger error: primary or cam, too many or too few teeth.

more granular trigger error messages

---

firmware/CHANGELOG.md
firmware/controllers/limp_manager.cpp
firmware/controllers/limp_manager.h
unit_tests/tests/test_deadband.cpp
unit_tests/tests/test_limp.cpp

Add hysteresis to force the driver to back off, and maybe save components.
#4529

add hysteresis to limp rpm, boost, injector duty

---

firmware/console/binary/tooth_logger.cpp

Ensure we cannot write past the end of the buffer.
fix #4542

simplify and probably fix tooth logger overflow

---

firmware/controllers/algo/engine.cpp

https://stackoverflow.com/questions/68690961/why-does-converting-int-to-float-lose-precision-in-c-programming-language

efiWatchdog: avoid converting time to float

---

firmware/hw_layer/ports/stm32/microsecond_timer_stm32.cpp

Driver sets (period - 1) to ARR (auto-reload register) So we need to set period to (1 << 32) to get maximum 0xffffffff value in ARR. But period is uint32_t.
So set it to 0 and it will ovelap to UINT32_MAX at `pwmp->tim->ARR  = pwmp->period - 1;`
```
859	  pwmp->tim->ARR  = pwmp->period - 1;
(gdb) 
860	  pwmp->tim->CR2  = pwmp->config->cr2;
(gdb) p/x *pwmp
$7 = {state = 0x1, config = 0x80b4b3c, period = 0x0, enabled = 0x0, channels = 0x4, clock = 0x66ff300, tim = 0x40000c00}
(gdb) p/x *pwmp->tim
$5 = {CR1 = 0x0, CR2 = 0x0, SMCR = 0x0, DIER = 0x0, SR = 0x0, EGR = 0x0, CCMR1 = 0x6868, CCMR2 = 0x6868, CCER = 0x0, CNT = 0x0, PSC = 0x1a, ARR = 0xffffffff, RCR = 0x0, CCR = {0x0, 0x0, 0x0, 0x0}, BDTR = 0x0, 
DCR = 0x0, DMAR = 0x0, OR = 0x0, CCMR3 = 0x0, CCXR = {0x0, 0x0}}
```

stm32: microsecond timer: set correct period value

---

firmware/controllers/system/timer/pwm_generator_logic.cpp

fix #4577
possibly related to #4570

pwm iteration limit to avoid float math accuracy loss

---

firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/limp_manager.h
firmware/tunerstudio/rusefi.input

Indicators now show the actual spark/fuel cut reason, not just that its cut. That also means we no longer need to actually send the bit of "cut" vs "not cut", since that logic can be in TS instead of copying bits around on the ECU.

add fuel/spark cut codes to TS indicators

---

firmware/controllers/trigger/trigger_decoder.h

Horrible terrible typo that causes `someSortOfTriggerError` to get stuck `true` forever after an error.

terrible horrible typo

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/trigger/decoders/auto_generated_sync_edge.cpp
firmware/controllers/trigger/decoders/auto_generated_sync_edge.h
firmware/controllers/trigger/decoders/sync_edge.h
firmware/controllers/trigger/decoders/trigger_chrysler.cpp
firmware/controllers/trigger/decoders/trigger_gm.cpp
firmware/controllers/trigger/decoders/trigger_honda.cpp
firmware/controllers/trigger/decoders/trigger_mazda.cpp
firmware/controllers/trigger/decoders/trigger_mercedes.cpp
firmware/controllers/trigger/decoders/trigger_misc.cpp
firmware/controllers/trigger/decoders/trigger_mitsubishi.cpp
firmware/controllers/trigger/decoders/trigger_nissan.cpp
firmware/controllers/trigger/decoders/trigger_renix.cpp
firmware/controllers/trigger/decoders/trigger_rover.cpp
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/decoders/trigger_subaru.cpp
firmware/controllers/trigger/decoders/trigger_suzuki.cpp
firmware/controllers/trigger/decoders/trigger_toyota.cpp
firmware/controllers/trigger/decoders/trigger_universal.cpp
firmware/controllers/trigger/decoders/trigger_vw.cpp
firmware/controllers/trigger/trigger.mk
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/gen_enum_to_string.sh
unit_tests/tests/ignition_injection/test_fuel_map.cpp

Previously there was a constellation of booleans you could set to determine rise/fall/both, with some unclear defaults. Now an enum must be passed to `initialize()` to set which edges are looked at for finding the sync point.

explicitly pass which edges we sync trigger on

---

firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h
firmware/controllers/trigger/trigger_central.txt

- We know when to expect the next tooth
- We know the actual angle of the current tooth
- Store the first thing and check it against the second thing!
Maybe some day this can tell us "your trigger is close enough to sync but you may get unpredictable ignition timing"
We could also in theory nudge the trigger teeth around to match reality. Trigger pattern is "close enough", and it gets fine-tuned by the running engine itself.
I guess related to  #2222

log deviation between actual tooth gap and expected tooth gap

---

firmware/controllers/engine_controller.cpp
firmware/controllers/engine_cycle/prime_injection.cpp
firmware/controllers/engine_cycle/prime_injection.h

- code style
- fix bug where prime reset could only happen once per ECU power cycle (ignition start/run cycles with USB connected didn't re-prime on subsequent starts)
- use `onSlowCallback` instead of calling from `engine_controller.cpp`

minor priming refactor

---

firmware/controllers/trigger/decoders/trigger_chrysler.cpp
firmware/controllers/trigger/decoders/trigger_gm.cpp
firmware/controllers/trigger/decoders/trigger_honda.cpp
firmware/controllers/trigger/decoders/trigger_mazda.cpp
firmware/controllers/trigger/decoders/trigger_misc.cpp
firmware/controllers/trigger/decoders/trigger_mitsubishi.cpp
firmware/controllers/trigger/decoders/trigger_nissan.cpp
firmware/controllers/trigger/decoders/trigger_renix.cpp
firmware/controllers/trigger/decoders/trigger_rover.cpp
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_subaru.cpp
firmware/controllers/trigger/decoders/trigger_suzuki.cpp
firmware/controllers/trigger/decoders/trigger_universal.cpp
firmware/controllers/trigger/decoders/trigger_vw.cpp

Part of #4621: set trigger types that are rising-edge-only. Doesn't change logic yet, as `::Rise` and `::RiseOnly` currently behave the same.

change triggers that need RiseOnly

---

unit_tests/tests/trigger/test_2jz_vvt.cpp

Make 2jz vvt test continue working after #4621, and improve comments while we're at it

make 2jz test happier without use only rise

---

firmware/config/boards/hellen/hellen72/connectors/main.yaml

While diagnosing a users issue with clutch input, i found that the pin changed on the 176 from res3 to D1 at revE.

Added new pin mapping for clutch

---

firmware/util/loggingcentral.cpp

Related to https://github.com/rusefi/rusefi/issues/4651
Wrong symbol can still come from one of arguments, like:
`efiPrintf("This is test %s", "this is wrong char\r\n");`
So check should be done for final buffer.
Also check for '\r' too.
Or just simply replace all not-allowed chars with space.
@rusefillc please cherry-pick at least first patch at this series.

Logging asserts

---

firmware/console/binary/output_channels.txt
firmware/console/binary_log/log_field.h
firmware/controllers/sensors/wideband_state.txt
firmware/development/logic_analyzer.cpp
firmware/integration/rusefi_config.txt

- Allow `LogField` to accept plain integer/float, instead of requiring `scaled_channel`.
- Remove `autoscale` in places where we have 1:1 scaling, using the new logic.
useful for #3985

allow SD logging non-scaled_channel

---

firmware/Makefile
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/lua/luaconf.h
firmware/hw_layer/ports/stm32/stm32f7/hw_ports.mk
firmware/hw_layer/ports/stm32/stm32h7/hw_ports.mk
unit_tests/global.h

- Turn off 16-byte function alignment on MCUs without a cache - saves 1-15 bytes added between functions for alignment
- use `chsnprintf` instead of `snprintf`
- Don't bother with trying to compute the locale-specific decimal point for lua (`lua_getlocaledecpoint`), just use `'.'`.
- Turn on section "sort by alignment", avoids useless fill gaps between linked objects.

build tweaks for size

---

.github/workflows/build-firmware.yaml
.github/workflows/hardware-ci.yaml
firmware/init/sensor/init_sensors.cpp
java_console/autotest/src/main/java/com/rusefi/proteus/ProteusAnalogTest.java

Re-enable proteus CI.
fix #4668
Set the compiler in `$PATH`, so that #4641 can use gcc10 in hardware CI without manually adjusting the hw ci machines (side by side gcc9 + gcc10)

enable proteus, select compiler in script

---

firmware/controllers/settings.cpp
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/decoders/trigger_universal.cpp
firmware/controllers/trigger/decoders/trigger_universal.h
unit_tests/tests/trigger/test_trigger_decoder.cpp

We had two functions that do the same thing. Delete one of them.

simplify initializeSkippedToothTrigger

---

firmware/hw_layer/drivers/sent/sent.cpp

Implement another one CRC check that is compatible with GM throttle.
Use more pulses for Unit time calculation.
Fix debug output.
```
2022-10-23_00_39_41_668: EngineState: ---- SENT ch 0 ----
2022-10-23_00_39_41_669: EngineState: Unit time 275 timer ticks
2022-10-23_00_39_41_669: EngineState: Total pulses 2363816
2022-10-23_00_39_41_670: EngineState: Last fast msg Status 0x0 Sig0 0xAD4 Sig1 0x52B
2022-10-23_00_39_41_670: EngineState: Restarts 0
2022-10-23_00_39_41_670: EngineState: Interval errors 441 short, 7845 long
2022-10-23_00_39_41_672: EngineState: Total frames 248023 with crc error 208 (0.083863192 %)
2022-10-23_00_39_41_672: EngineState: Sync errors 441
2022-10-23_00_39_41_672: EngineState: --------------------
```

SENT fixes

---

firmware/hw_layer/ports/rusefi_halconf.h
firmware/integration/rusefi_config.txt

Goes from 333 -> 500 hz over USB, and gets ~700hz over ethernet on an H7.

750 byte bigger blocking factor

---

firmware/CHANGELOG.md
firmware/config/engines/mazda_miata_1_6.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_idle_controller.cpp

Deadzone on idle timing PD is a trap, as in no real scenario will it help make your idle more stable.
#4729

remove idle timing deadzone

---

firmware/config/boards/prometheus/compile_prometheus_469.sh
firmware/config/boards/prometheus/f405/board.mk
firmware/config/boards/prometheus/f405/config.mk
firmware/config/boards/prometheus/f469/board.mk
firmware/config/boards/prometheus/f469/config.mk
firmware/config/boards/prometheus/prometheus-common-board.mk
firmware/config/boards/prometheus/prometheus-common-config.mk

The check for `USE_BOOTLOADER` is before the `include .../board.mk` in `firmware/Makefile`.  Either that check should be moved lower (and some cleanup from ...) or these fixes incorporated.  `config/boards/subaru_eg33/board.mk` is suspect too (`ifeq ($(USE_BOOTLOADER),yes)`); for one, `Makefile` uses inverted assertion (about `no`) so this condition brittle.
```
No CCACHE_DIR
PROJECT_BOARD: prometheus/f405
PROJECT_CPU:   ARCH_STM32F4
CONFDIR:       ./hw_layer/ports/stm32/stm32f4/cfg
LDSCRIPT:      ./hw_layer/ports/stm32/stm32f4/STM32F4.ld
Compiler Options
arm-none-eabi-gcc -c -mcpu=cortex-m4 -mthumb -DEFI_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE -O2 -ggdb -g -fomit-frame-pointer …
```

fix prometheus build options

---

firmware/config/boards/common_make.sh

non-critical change to avoid these messages from `compile_*.sh` scripts:
```
...
../common_make.sh: line 19: [: =: unary operator expected
...
../common_make.sh: line 37: [: =: unary operator expected
../common_make.sh: line 52: [: =: unary operator expected
...
```

quote USE_OPENBLT to avoid condition error

---

.github/workflows/build-firmware.yaml
firmware/provide_gcc.sh
firmware/setup_linux_environment.sh

for #4759 -- uses some bash variable expansion magic which may prove problematic for certain systems
`provide_gcc.sh` downloads and extracts GCC toolchain and creates a colloquially named `gcc-arm-none-eabi` link for use; this could change to accept a variable for that name instead, but this colloquial name allows to encapsulate this term and avoid having to pass it back or require the use-sites to determine the name (which changes among releases/builds).

factor GCC provision script

---

.github/workflows/build-firmware.yaml
firmware/provide_gcc.sh

target pruned rusEFI ARM GCC 11.3; also fixed up GCC provision script to avoid double decompression (via temporary directory) to speed CI

use rusEFI pruned ARM GCC 11.3

---

.github/workflows/build-firmware.yaml

GHA/build-firmware: pin agents to Ubuntu 20.04

---

simulator/simulator/can/hal_can_lld.cpp

for std::remove -- GCC 12 exposes this issue

simulator: add missing stdc++ include to CAN HAL LLD

---

simulator/Makefile

I stumbled about ChibiOS's `CPPC` vs the standard `CXX`; initially I wanted to support `CXX` pass-through as `CPPC`, but this is intangible as `CXX` is always set: easier to just "get with" using `CPPC` ("be in the know").
`./compile.sh CC=gcc-11 CPPC=g++-11 USE_VERBOSE_COMPILE=yes`
Otherwise, this allows to pass arguments to make via `simulator/compile.sh`, and tidies some indentation that otherwise standardizing on tabs causes problems with make: (`<tab>$(info ...)` is interpreted as a recipe):
```
Makefile:64: *** recipe commences before first target.  Stop.
```
----
Note the firmware jobs will fail due to #4791 (see #4793).

Tweak simulator Makefile, scripting

---

firmware/hw_layer/mass_storage/create_ini_image.sh
firmware/hw_layer/mass_storage/create_ini_image_compressed.sh

e.g. `./gen_default_everything.sh` fails on Debian systems because e.g. `mkfs.fat` is not in regular user's `PATH`
```
hw_layer/mass_storage/create_ini_image.sh: line 26: mkfs.fat: command not found
```

add /usr/sbin to PATH in create_ini_image*.sh

---

firmware/controllers/can/can_dash.cpp
firmware/controllers/settings.cpp
firmware/controllers/settings.h
firmware/hw_layer/rtc_helper.cpp
firmware/hw_layer/rtc_helper.h
java_console/ui/src/main/java/com/rusefi/ui/console/MainFrame.java

for https://github.com/rusefi/rusefi/issues/4662
I have not tested these changes in any way beyond that the builds succeed.
~~Should this concern w/ backward compatibility at all?  E.g. introduce i.e. `CMD_DATE_ISO` and retain `CMD_DATE` for some time?~~ Seemingly no (see below) -- ideally the altered logic will account for this and not cause crashes about mismatches, but may.

avoid ctime, use UTC ISO 8601 for CMD_DATE format

---

firmware/controllers/algo/fuel/fuel_computer.cpp
firmware/controllers/algo/fuel/fuel_computer.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/math/speed_density.cpp
unit_tests/tests/ignition_injection/test_fuel_computer.cpp

We can inline ValueProvider3D and get rid of constructor argument but would that mean wiping out test?

without ValueProvider3D interface how do we mock?

---

firmware/CHANGELOG.md
firmware/controllers/algo/engine_configuration.cpp
firmware/hw_layer/mmc_card.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

I decided to go ahead and make this a config break, since the user may have had some other value set there that produces unpredictable results when converted from ms to hz.
fix #4553

SD logging period -> frequency

---

firmware/controllers/settings.cpp

oopsie; fixes for #4662
```
I 221205 040811.572 [Commands Queue] BinaryProtocol - Sending [set date 2022-12-05T04:08:11.452]
I 221205 040811.653 [communication executor1] MessagesCentral - postMessage EngineState: date_set parsed: 2022-12-05T04:08:11
I 221205 040811.653 [communication executor1] MessagesCentral - postMessage EngineState: confirmation_set date 2022-12-05T04:08:11.452:32
```

firmware: fix ISO date-time parsing

---

firmware/controllers/algo/event_registry.h
firmware/controllers/engine_cycle/high_pressure_fuel_pump.h
unit_tests/engine_test_helper.cpp
unit_tests/engine_test_helper.h
unit_tests/tests/actuators/test_aux_valves.cpp
unit_tests/tests/test_hpfp.cpp

No users of `AngleBasedEventOld` after this, then we can delete the "two implementations" confusion and consolidate to just the new one.

switch hpfp and aux valves to AngleBasedEventNew

---

firmware/tunerstudio/rusefi.input

Is selectively disabling the panels against practice?  Wondering because I guess bits/pins there-in will retain their value if not enabled, which makes unsetting them a hassle.  What's the rusEFI practice around this?

organize ETB H-Bridge No1/2 into panels

---

firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_subscription.cpp
firmware/hw_layer/adc/adc_subscription.h
firmware/init/sensor/init_fluid_pressure.cpp
firmware/init/sensor/init_map.cpp
firmware/init/sensor/init_thermistors.cpp
firmware/init/sensor/init_vbatt.cpp

Prevents the brief window during reconfiguration (ie, when you push the burn button) that sensors are unsubscribed if the channel didn't change.
- only unsubscribe if the new ADC channel is empty (ie, if the sensor is really going away)
- Allow re-subscription of a sensor without unsubscribing it first, even if the ADC channel changes in the process
#4916

adc resubscription of the same sensor

---

firmware/CHANGELOG.md
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/advance_map.h
firmware/controllers/algo/defaults/default_ignition.cpp
firmware/controllers/engine_controller.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/trigger/test_trigger_decoder.cpp

Switch the ignition IAT correction table to use IAT/load instead of IAT/RPM.
This is what the OEMs do - very little RPM dependence, mostly dependent upon load/iat.
Also includes more sensible default values in the table.

improve iat ignition table

---

firmware/controllers/core/error_handling.cpp

We already print out warnings, we don't need to clog the cpu and console log by printing every single time one occurs.
mitigates #4958

don't print "sim_warning %s"

---

.github/workflows/build-android.yaml
.github/workflows/build-firmware.yaml
.github/workflows/build-rusEFI-console.yaml
.github/workflows/build-simulator.yaml
.github/workflows/build-tsplugin-body.yaml
.github/workflows/build-unit-tests.yaml
.github/workflows/gen-configs.yaml
.github/workflows/gen-diffs.yaml
.github/workflows/gen-docs.yaml
.github/workflows/gen-ibom.yaml
.github/workflows/set-date.yaml

Many actions are failing currently, unable to communicate with `azure.archive.ubuntu.com`, for unknown reasons.
```
Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libc6-dev-i386 amd64 2.35-0ubuntu3.1
Could not connect to azure.archive.ubuntu.com:80 (40.119.46.219), connection timed out [IP: 40.119.46.219 80]
```
Some solutions:
1. avoid azure archive, a la https://github.com/actions/runner-images/issues/675#issuecomment-610483420
- `sed -i 's/azure\.//' /etc/apt/sources.list && apt-get update`
2. use a tool to find a suitable mirror, a la https://github.com/actions/runner-images/issues/675#issuecomment-609780588
- `gem install apt-spy2 && apt-spy2 check && apt-spy2 fix && apt-get update`
3. add retryability to apt-get, a la …

GitHub actions use apt-spy2, retry apt-get update

---

firmware/console/binary/tunerstudio.h

I saw a low stack warning on the comms thread in a HW CI run, so give it some more stack.

more stack for TS

---

.github/workflows/build-firmware.yaml
misc/jenkins/build_working_folder.sh
misc/jenkins/compile_other_versions/prepare_bundle.sh

This expects/requires a 'lts' subdirectory of build-server.
How to use:
1. Go to the '[Firmware at GHA](https://github.com/rusefi/rusefi/actions/workflows/build-firmware.yaml)' action
2. Click "Run Workflow"
3. Select your LTS branch (assuming you have a special branch; if not, master works too)
4. Check "LTS Build" toggle
5. Click green "Run Workflow" button
If this workflow isn't to your liking, we can probably find a different way. This just seemed simplest to me.

LTS - one way of doing things

---

firmware/provide_gcc.sh

This enables self-hosted runners to pre-download the arm-none-eabi toolchain at build time.
The script checks the checksum of one of the executables, so that we are sure to be running the correct toolchain version.

Don't download ARM Gnu toolchain if present

---

java_console/autoupdate/src/main/java/com/rusefi/autoupdate/Autoupdate.java
java_console/bin/switch_bundle.sh
java_console/shared_io/src/main/java/com/rusefi/core/io/BundleUtil.java
java_console/shared_io/src/main/java/com/rusefi/core/net/ConnectionAndMeta.java
misc/jenkins/build_working_folder.sh

This will fix #4992 and #4993.
- Removed date from bundle name
- I chose the approach of using the name of the folder rather than putting the info in bundle_name.txt
I chose this because I thought it would be simpler, but the exception to that is switch_bundle.sh, which got a little more complicated - see Caveats below. I'm not set on doing things this way.
- The bundle names are `rusefi.<branch name>.<bundle>`
If the branch is master, then the `<branch name>` is "snapshot".
Examples:
`rusefi.snapshot.proteus_f7`
`rusefi.lts_foo.mre_f4`
- I chose to use `.` instead of `_` because `_` is often used in board names which makes parsing difficult.
- I chose to move `rusefi` to the beginning of the bundle name to make them easier for the end user to find. By this I mean that they'll be together …

[LTS] Put branch in bundle name (please read caveats)

---

.github/workflows/build-android.yaml
.github/workflows/build-firmware.yaml
.github/workflows/build-rusEFI-console.yaml
.github/workflows/build-simulator.yaml
.github/workflows/build-tsplugin-body.yaml
.github/workflows/build-unit-tests.yaml
.github/workflows/gen-configs.yaml
.github/workflows/gen-diffs.yaml
.github/workflows/gen-docs.yaml
.github/workflows/gen-ibom.yaml
.github/workflows/gen-pinouts.yaml
.github/workflows/hardware-ci.yaml
.github/workflows/set-date.yaml

I haven't tested HW-CI, so we for sure need to wait for that.
This will fix #3494. I removed all `submodules: recursive` statements and figured out, largely by trial and error, which submodules were required for which workflows.
I also removed some `fetch-depth: 0` statements. Somewhat counterintuitively, this means that the whole history is checked. The default is to only fetch HEAD.
I also haven't tested:
- gen-ibom (currently broken green)
- gen-docs (only removed fetch-depth)
- set-date (only removed fetch-depth)

Lean submodule fetching (don't merge until all green)

---

firmware/controllers/sensors/ego.cpp
firmware/controllers/sensors/ego.h
firmware/init/sensor/init_lambda.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Initial work on dual ADC wideband support under single calibration (same type controllers)
Have Audi 4.2 v8 and MB m113 NA engines with each bank exhausts merging very far so no option to run single wideband support. I know FW can support dual CAN wideband so would be good to add support for dual ADC wideband based on single calibration set. My core8 ECU has built-in dual 14point7 controllers so they can share the same calibration ranges. 
Done just initial work:
1. TS rusefi.input added EGO 2 panel
2. rusefi_config.txt added hwChannel2 to store input pin
3. updated getAfr in ego.cpp/.h to provide sensor as a parameter to read ADC from 
4. used sensor to read volts from hwChannel or hwChannel2 based on provided sensor type.
5. init_lambda.cpp updated getLambda wrapper to use Lambda1 senor …

dual ADC wideband support

---

firmware/config/boards/proteus/board.mk
firmware/hw_layer/ports/stm32/stm32f7/STM32F7.ld

go back to 512k for #3566 since stm programmer is still not fixed
Os vs O2 performance hit is very small, F7 is plenty fast, and it knocks ~53k off the binary. Probably mostly due to loop unrolling not happening like it does at O2.

build f7 with -Os, fits in 512k

---

.github/workflows/build-android.yaml
.github/workflows/build-firmware.yaml
.github/workflows/build-rusEFI-console.yaml
.github/workflows/build-simulator.yaml
.github/workflows/build-tsplugin-body.yaml
.github/workflows/build-unit-tests.yaml
.github/workflows/gen-configs.yaml
.github/workflows/gen-diffs.yaml
.github/workflows/gen-docs.yaml
.github/workflows/gen-ibom.yaml
.github/workflows/set-date.yaml

re: https://github.com/rusefi/rusefi/pull/5037#issuecomment-1419135471, #4967.
Attempts to resolve issues with `archive.ubuntu.com` mirrors failing, without `apt-spy2`, by adding more mirrors to the `apt` configuration, which sources say will allow apt to use these additional mirrors in the case of failure.

GitHub workflows: more ubuntu-latest mirrors

---

firmware/controllers/algo/rusefi_enums.h
firmware/hw_layer/drivers/can/can_hw.cpp
firmware/integration/rusefi_config.txt

- Add 50kbit/s, 83.33kbit/s, 125kbit/s
- Fix 100kbit on F7
- Fix 100kbit on H7
- tweak 250/500/1000kbit on H7
- reorder CAN bitrate options so they're sorted with the new ones

add 50/83.3/125kbit CAN

---

.github/workflows/gen-pinouts.yaml

Please note that in the current state, the workflow will fail.

use new interactive-pinouts release, error on duplicates

---

firmware/controllers/actuators/gppwm/gppwm.cpp

Fix the GPPWM Y axis display in TS/logs.

gppwm Y axis doesn't work

---

.github/workflows/build-firmware.yaml

To use this mode, put `only:<bundle name>` in your commit message.
There must not be a space between `only:` and the name, and the name is case-sensitive.
Fix #5104

Build only one bundle

---

firmware/hw_layer/drivers/can/can_msg_tx.cpp

bus argument was introduces in 12c899ddcab89ff79a40782bc82d473f90ae6bfc but was ignored.
@mck1117 ping

can msg tx: do not ignore bus argument

---

.github/workflows/build-firmware.yaml

There was an error in the logic, with the result that the "Create Release tag" step never ran. I don't know how it worked at all, but it did fail randomly - e.g. https://github.com/rusefi/rusefi/actions/runs/4272425928
Fixing this revealed an obvious race condition.
I moved the tag and release creation to its own job that runs before the build matrix.

Fix nightly

---

.github/workflows/build-firmware.yaml

It didn't fail on my fork because it was running on a self-hosted runner that already had the repo checked out, d'oh.
The tag-exists-action doesn't need the repo to be checked out.
(I shut down my self hosted runner to test this)

Fix nightly again

---

.github/workflows/build-firmware.yaml

for https://github.com/rusefi/rusefi/issues/5117#issuecomment-1454313413
avoids failing release scheduled runs for non-golden repos, allowing to keep the workflow and associated notifications and avoid spam about unconcerning failures: https://github.com/nmschulte/rusefi/actions/runs/4443042591/jobs/7799915165#step:4:15
please double check my work:
- condition is correct? https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
- concern in all the correct places?

firmware workflow schedule only for rusefi/rusefi

---

firmware/controllers/can/can_dash.cpp

Small edit sending gear over CAN with AIM dashboards, I want it to update with rpm/vss gear calculations. 
From the AIM documentation, it seems like it's supposed to be a signed 16 bit int:
Currently the frame struct is using `scaled_channel<uint16_t, 10>`, so I imagine it should be changed to `scaled_channel<int16_t, 1>`?

set aim dash CAN gear frame to current gear

---

firmware/controllers/trigger/trigger_decoder.cpp
firmware/util/math/efi_pid.cpp

Virtual functions should not be invoked from a constructor or destructor of the same class. Confusingly, virtual functions are resolved statically (not dynamically) in constructors and destructors for the same class. The call should be made explicitly static by qualifying it using the scope resolution operator.

Fix invoking virtual functions from constructors

---

firmware/controllers/algo/nmea.cpp

Accessing an array offset before checking the range means that the program may attempt to read beyond the end of a buffer.

Fix offset used before range check

---

firmware/controllers/algo/engine.h
firmware/controllers/controllers.mk
firmware/controllers/engine_controller.cpp
firmware/controllers/tcu/buttonshift.h
firmware/controllers/tcu/gc_generic.cpp
firmware/controllers/tcu/gc_generic.h
firmware/controllers/tcu/gear_controller.cpp
firmware/controllers/tcu/gear_controller.h
firmware/controllers/tcu/tcu.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

I haven't PR'd this until now because I'm not terribly pleased with how I ended up doing the TS UI, but I can't think of a better way.
Being able to hide the graph by default would be an improvement, but I don't think it's possible.
I also put the transmission settings back in the menu with an "(alpha)" label. If this isn't acceptable, I'm open to suggestions.

Add Transmission range input

---

.github/workflows/build-simulator.yaml

The gen-config workflow only runs on push to master, which is why it doesn't cause errors.

Add check for push to master for simulator workflow

---

firmware/config/boards/common_make.sh

I'm not sure if hex is needed?
There will still be an error for boards that use an OpenBLT composite image. The comments in common_make.sh say not to deliver any format that can confuse users, so I didn't copy the .hex for those boards.
Before:
After:

Reduce missing hex errors

---

.github/workflows/hardware-ci.yaml
java_console/build.xml

running HW CI explicitly without ant junit runner as a step on our ant to gradle migration
expected: this change makes zero functional difference
actual: HW CI does not like this change?

Let's admit it's time to move to gradle #3014

---

.github/workflows/gen-pinouts.yaml

I broke this without realizing it. Before, a leading ./ was required, now it must not be present.

remove leading ./

---

firmware/controllers/can/can_bench_test.cpp

https://github.com/rusefi/rusefi-hardware/issues/228

fix mixed up CLT & IAT in the bench_test_raw_analog CAN packet

---

.gitmodules

A few different things are happening here
* as is https://github.com/ChibiOS/ChibiOS/tree/stable_20.3.x simply does not compile potentially for at least two different reasons
* https://github.com/rusefi/ChibiOS/tree/stable_21.11.x.rusefi is great but merge commits are making history hard to read
* well that reminds me that we kind of should contribute to https://github.com/ChibiOS/ChibiOS see some tickets at https://github.com/rusefi/ChibiOS/issues
* https://github.com/rusefi/ChibiOS/tree/stable_20.3.x.rusefi_clean_history is linear version of stable_21.11.x.rusefi actually let me create a separate migration ticket
https://github.com/rusefi/ChibiOS/tree/stable_20.3.x_rusefi_2023.07.06 is today ChibiOS with https://github.com/rusefi/ChibiOS/tree/stable_20.3.x.rusefi_clean_history commits …

picking fresh Chibios branch 20 via stable_20.3.x_rusefi_2023.07.06

---

firmware/CHANGELOG.md
firmware/config/boards/hellen/hellen121nissan/board_configuration.cpp
firmware/config/engines/custom_engine.cpp
firmware/config/engines/honda_k_dbc.cpp
firmware/controllers/algo/defaults/default_cranking.cpp
firmware/controllers/algo/engine2.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

My LPG-converted engine was not happy with fixed ASE for all temperatures.
That is because while cold it needs lots of fuel after start, but when the LPG evaporator is hot, and I'm using the hot-start feature it's giving too rich mixture.
LPG doesn't get along too well with overly rich mixtures (and cylinder head really hates this!) like petrol does.
I have implemented this as 3D table like in OEM and other Standalone EFI systems do.
Ideally the axis for duration should not be in seconds, but engine cycles... I'm still getting to know how rusEFI works...

After-start enrichment handling more similar to OEM

---

firmware/config/engines/honda_k_dbc.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/defaults/default_cranking.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Thanks to the last tip, I was able to get it to build myself to test on my Lexus
Idle advance is entering slowly now upon starting the car. That can be changed to work always when entering idle by setting m_crankTaperEndTime to 0 below m_timingPid.reset();
For me I did not see reason to do it.
I have fixed both previous feature commits, unfortunately I had to break the TunerStudio again.
Also, it looks to me like the interpolate3d function, or TunerStudio generation swaps X an Y axis, if the axes are of not equal lengths like it was 4x8 instead of 6x6, then the axes are swapped.

ASE and CL Ignition fixes confirmed on the real car

---

firmware/console/eficonsole.cpp
firmware/hw_layer/ports/at32/at32_common.cpp
firmware/hw_layer/ports/at32/at32_common.mk
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/stm32/stm32f4/hw_ports.mk

Now sayHello() knows something about AT32:
```
2023-10-30_12_36_02_598: EngineState: *** rusEFI LLC (c) 2012-2023. All rights reserved.
2023-10-30_12_36_02_598: EngineState: *** rusEFI v20231029@65034
2023-10-30_12_36_02_598: EngineState: *** Chibios Kernel:       6.1.4
2023-10-30_12_36_02_598: EngineState: *** Compiled:     Oct 30 2023 - 12:34:37
2023-10-30_12_36_02_599: EngineState: *** COMPILER=12.2.1 20221205
2023-10-30_12_36_02_599: EngineState: hellenBoardId=0
2023-10-30_12_36_02_599: EngineState: UID=A075EE 3C754000 E808722
2023-10-30_12_36_02_600: EngineState: MCU IDCODE AT32F437ZMT7 in LQFP144 with 4032 KB flash
2023-10-30_12_36_02_600: EngineState: MCU SER_ID AT32F437 rev A
2023-10-30_12_36_02_600: EngineState: MCU F_SEZE 4032 KB
2023-10-30_12_36_02_600: EngineState: …
```

AT32: chip detection, flash detection, sayHello()

---

firmware/controllers/flash_main.cpp

@dron0gus see also https://github.com/rusefi/rusefi/pull/5671
this PR here and https://github.com/rusefi/rusefi/pull/5671 are different in order of operations in the duplicated code.

reducing code duplication - internal flash order of operations

---

firmware/rusefi_rules.mk

RUSEFI_OPT += -Werror=stringop-truncation

# some compilers seem to have this off by default?

---

firmware/bootloader/Makefile

Make it closer to the main Makefile which uses $(BOARDINC)

Add BOARDINC to the bootloader's Makefile

---

.github/workflows/build-firmware.yaml

With this change, re-running a firmware build workflow run will prevent skip-rate and only: from having any effect. This is a little QOL improvement for me. If it will negatively affect your workflow, don't merge it; it's not a big deal at all.

Don't skip firmware build on re-run

---

.github/workflows/build-firmware.yaml
firmware/Makefile
firmware/bootloader/Makefile
firmware/config/boards/common_script.sh

Find the meta-info.env file so we can use it in future commits
Set PROJECT_BOARD to SHORT_BOARD_NAME if it is empty
Add `./` and `../` to BOARD_DIR for firmware and bootloader builds respectively - the path in the workflow matrix doesn't have them. We could do this somewhere else, like common_script.sh, but it's going to end up in the Makefile anyhow, so we might as well put it there now.
Don't pass the variables to make, because when you do that, it overrides any setting of that variable within the makefile, in our case:
- Adding `./` or `../` to BOARD_DIR
- In the future, setting PROJECT_BOARD to SHORT_BOARD_NAME will happen in the makefile

Set env variables in firmware workflow

---

.github/workflows/build-firmware.yaml
.github/workflows/hw-ci/build_for_hw_ci.sh
firmware/bin/find_meta_info.sh
firmware/bin/upload_bundle.sh
firmware/bootloader/Makefile
firmware/config/boards/common_script.sh
firmware/tunerstudio/upload_ini.sh
misc/jenkins/build_working_folder.sh
misc/jenkins/compile_other_versions/compile.sh

Don't call the compile script any more, we can just call common_script.sh directly. This gets rid of most of compile.sh.
Arguments can be removed from calls to scripts in build-firmware.yaml, as they can get those values from the environment variables. Also included are changes in upload_bundle.sh to use the environtment variables instead of the passed arguments.
There's no reason this has to be done in this commit, but I'm out of Github Actions minutes for today and am depending on my own self-hosted runners, which makes splitting up commits take way longer, so I left them in this commit.

Import board-specific meta-info

---

.github/workflows/build-firmware.yaml
.github/workflows/hw-ci/build_for_hw_ci.sh
firmware/clean.bat
firmware/clean.sh
misc/jenkins/compile_other_versions/compile.sh
misc/jenkins/compile_other_versions/compile_and_upload.bat

let Make take care of cleaning, and call common_script directly

get rid of compile and clean scripts

---

firmware/bootloader/Makefile
firmware/bundle.mk
firmware/config/boards/common_script.sh

Ignore invalid PCH warnings in the bootloader Makefile as @racer-coder did in the firmware Makefile in https://github.com/rusefi/rusefi/commit/37da55c9206328bfba2a3bc24ef26d0ad419d1ab
Make coordinates with sub-instances of make to maintain the total number of parallel build threads; we don't even need to use the `-j` option.

Call make bootloader from make

---

.github/workflows/custom-board-build.yaml
firmware/config/boards/common_script_read_meta_env.inc
firmware/gen_config_board.sh
misc/jenkins/build_working_folder.sh

board_dir is relative to custom repo root, and assumed to be at the repo root if it's not passed
shortBoardName is no longer required as that's in the meta-info now

Makeover - custom builds

---

.github/workflows/custom-board-build.yaml

build_working_folder.sh expects META_OUTPUT_ROOT_FOLDER to be relative to the repo root, but gen_config_board.sh expects it to be relative to the firmware directory. So let's just use an absolute path.
Green run: https://github.com/chuckwagoncomputing/fw-custom-example/actions/runs/7949685960/job/21701131321

Use absolute path for generated outputs dir

---

firmware/bundle.mk

I thought the patter rule would work from reading this answer:
https://stackoverflow.com/questions/63928066/what-is-the-canonical-way-to-simulate-grouped-targets-in-older-versions-of-make
I think the kind of pattern rule that would have worked is one that listed both BOOTLOADER_HEX and BOOTLOADER_BIN, but both with a % in them, like `bootloader/blbuild/openblt_%.bin bootloader/blbuild/openblt_%.hex`
I decided to go with another sentinel file instead. It's clearer (to me at least) that it was done that way for a reason. If I see a pattern rule with no prerequisites, I'm likely to think "that's stupid" and change it.

Use sentinel for bootloader

---

firmware/hw_layer/ports/stm32/microsecond_timer_stm32.cpp

To avoid "gap in time" error during debug

Stop microsecond TIM clock when CPU is halted by debuger

---

.github/workflows/build-firmware-windows.yaml
.github/workflows/build-unit-tests-windows.yaml

[setup-mingw](https://github.com/egor-tensin/setup-mingw) has not been maintained in over a year and is currently pretty broken.
This PR switches to the official Cygwin install action. Cygwin bundles more packages and has a large repository for installing more if needed. I expected the extra weight to slow down the workflow, but it looks like it's actually faster because setup-mingw used Chocolatey for installing minGW, which added some overhead.

Use cygwin instead of minGW

---

.github/workflows/build-firmware-windows.yaml
.github/workflows/build-firmware.yaml
.github/workflows/build-unit-tests-windows.yaml
.github/workflows/build-unit-tests.yaml
.github/workflows/custom-board-build.yaml
firmware/Makefile
firmware/bundle.mk
firmware/config/boards/cypress/meta-info.env
firmware/config/boards/kinetis/meta-info.env
firmware/config/boards/subaru_eg33/meta-info-subaru_eg33_f7.env
firmware/config/boards/subaru_eg33/meta-info-subaru_eg33_f7_no_bl.env
firmware/gen_config_board.sh
firmware/rusefi_config.mk
firmware/rusefi_pch.mk

Instead of having hard-coded checks for calling custom gen_config scripts, I have added a variable to the meta-info of those boards that require it.
As of this PR, configs are generated every time make is run. This is not optimal, it's a small-PR stepping stone.
I had to add flock to the call to Gradle in gen_config_board.sh. Eventually, this call will be removed from this file, but it has to stay for now.
Because of this, unit tests on macOS require installing flock.  Flock is a BSD standard system call which Linux has also adopted, but macOS doesn't ship with a command line utility for using it. In linux, the command line tool is a part of the util-linux package. Util-linux is shipped with every linux distro and cygwin.
All the config-related stuff is in a new file, rusefi_config.mk. …

Call gen_config_board with make

---

.github/workflows/build-rusEFI-console.yaml
.github/workflows/build-unit-tests.yaml
unit_tests/unit_test_rules.mk

This prepares unit tests for regenerating configs if they need to be.
Because generating configs requires board meta info, I copied the code that sets the default from firmware/rusefi.mk.
Green custom: https://github.com/chuckwagoncomputing/fw-custom-example/actions/runs/8043683225

Include rusefi_config.mk for unit tests

---

firmware/bin/compile.sh

I found out macOS doesn't have realpath, so this is a workaround for that. I don't have a macOS machine to test this on.

Make compile.sh macOS compatible (hopefully)

---

firmware/gen_config_board.sh

This is extraneous. gen_config.sh builds it, and make builds it now.

don't build config_definition in gen_config_board

---

firmware/rusefi_config.mk

This is necessary because PROJECT in unit tests is "rusefi_test", not "rusefi"

hard coded rusefi_generated_

---

.github/workflows/hw-ci/build_for_hw_ci.sh
firmware/bin/gen_image_board.sh
firmware/gen_config.sh
firmware/gen_config_board.sh
firmware/gen_config_default.sh
firmware/rusefi_config.mk

Previous to this PR, ramdisk headers are always touched, even when no other config files are. Now the ramdisk headers will only be built if the .ini file was touched.
Currently the configs are always re-generated, which prior to this PR also caused most of the firmware to be rebuilt.
A future PR (hopefully next one) will only re-generate configs if one of their input files changed, but we still want to avoid rebuilding the firmware if one of those input files changed in a way that doesn't actually effect the output of config generation.
Because of the .dep issue, I had to do `$(TCPPOBJS): $(RAMDISK)`
I also removed the gen_signature call from gen_config_board, and called it everywhere that call gen_config_board.
Green custom: https://github.com/chuckwagoncomputing/fw-custom-example/actions …

Move ramdisk creation to its own script and make target

---

firmware/rusefi_config.mk

Caveat: SHORT_BOARD_NAME doesn't cover all possible changes. For example, if I build Proteus F7, then build Proteus F7 Debug, it won't actually rebuild. BUNDLE_NAME would be a better specifier, but it's currently only available from the build_firmware GHA workflow. Another option would be to use BOARD_META_PATH, and export it in config.sh.
@rusefillc Let me know what you think.
Fix #6088
Green custom: https://github.com/chuckwagoncomputing/fw-custom-example/actions/runs/8102640677

Use file with short board name to trigger rebuild on target change

---

firmware/hw_layer/hardware.cpp
firmware/hw_layer/ports/at32/at32_spi.cpp
firmware/hw_layer/ports/cypress/mpu_util.cpp
firmware/hw_layer/ports/kinetis/mpu_util.cpp
firmware/hw_layer/ports/stm32/stm32_spi.cpp

Fixes possible out of array bounds introduced in 5af710ff73a0d9cd51e21478b3c665b803613b27

one-based indexing enums is not cool

---

firmware/bundle.mk
firmware/rusefi_config.mk

Also pass the variable to the bootloader sub-make (it doesn't use it yet, but it will.)

Move .target-sentinel to variable

---

firmware/init/sensor/init_sensors.cpp

reconfigureSensors()->initLambda()->registerCanSensor() ...
This cause linked list loop.
Proper solution is to remove AEM sensors from can listener list before inserting them again.
Revert "missing initLambda in reconfigureSensors"
This reverts commit ee20cbd33b114dd05782faf02728f1966216ae9b.

Do not insert aem can listeners to list on each flash write

---

firmware/Makefile
firmware/bootloader/Makefile
firmware/rusefi_config.mk
firmware/target_sentinel.mk

So that bootloader can include it without including whole rusefi_config.mk

move target sentinel rules to separate makefile

---

.github/workflows/build-simulator.yaml

`**/*.h` etc. seem to not be working. On bash this is disabled by default. We will try enabling it with `shopt -s globstar`
This issue has probably always existed, but files other than the .xml files are not always created. It may be happening more often because more things are being rebuilt because one of their prerequisites were updated, I'm not sure.

Try enabling globstar

---

firmware/target_sentinel.mk

This is the brute force way to fix #5990, in lieu of generating deps ahead of time as in #6124.

Rebuild all objects on target change

---

.github/workflows/build-firmware-proteus-f7-mac.yaml
.github/workflows/build-firmware-windows.yaml
.github/workflows/build-firmware.yaml
.github/workflows/build-rusEFI-console.yaml
.github/workflows/build-unit-tests-windows.yaml
.github/workflows/build-unit-tests.yaml
.github/workflows/gen-configs.yaml
.github/workflows/hw-ci/build_for_hw_ci.sh
firmware/Makefile
firmware/docs_enums.mk
firmware/gen_enum_to_string.sh
firmware/gen_live_documentation.sh
unit_tests/unit_test_rules.mk

- call gen_live_documentation if any input files or the jars were updated
- don't build config_definition_base or enum_to_string in gen_live_documentation or gen_enum_to_string because make will do that if needed
- build config_definition_base and enum_to_string in places that are calling gen_live_documentation directly

Call gen_live_documentation.sh from make

---

firmware/tunerstudio/rusefi.input

Why?
Set warning to 110 KMh, red zone from 130.

VSSGauge: why red zone from 4 KMh?

---

firmware/controllers/core/error_handling.h
firmware/controllers/sensors/frequency_sensor.cpp
firmware/controllers/sensors/hella_oil_level.cpp
firmware/controllers/sensors/hella_oil_level.h
firmware/hw_layer/digital_input/digital_input_exti.cpp
firmware/hw_layer/digital_input/digital_input_exti.h
firmware/hw_layer/digital_input/trigger/trigger_input_adc.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_exti.cpp
firmware/init/sensor/init_flex.cpp

Set one of trigger inputs to PD6
Set VSS input to PD6
Get firmware error
Try to fix: set VSS to PD7. Things get even worse - ChibiOS dies on internal assert:
```
#0  chDbgPanic3 (msg=0x8075d64 <__func__.0.lto_priv.14> "_pal_lld_disablepadevent", file=0x8075adc "ChibiOS/os/rt/src/chsys.c", line=201) at ./controllers/core/error_handling.cpp:108
#1  0x08002c6c in chSysHalt (reason=reason@entry=0x8075d64 <__func__.0.lto_priv.14> "_pal_lld_disablepadevent") at ChibiOS/os/rt/src/chsys.c:201
#2  0x08003456 in _pal_lld_disablepadevent (port=<optimized out>, pad=<optimized out>) at ChibiOS/os/hal/ports/STM32/LLD/GPIOv2/hal_pal_lld.c:23
```
This is becase Vss sensor will try to disable exti on pin that it fails to obtain on init.

Vss fixes, efiExtiEnablePin() fixes

---

firmware/config/boards/cypress/config/hellen_cypress_gen_enum_to_string.sh

Fix cypress enum gen

---

.github/workflows/custom-board-build/action.yaml
firmware/bundle.mk

I have royally clogged my GHA pipeline so IDK if this is all good, but it _should_ be.
call `make obfuscated-bundle` to build the obfuscated bundle
expects a POST_BUILD_SCRIPT environment variable
POST_BUILD_SCRIPT is expected to be a shell script which uses `$1` as input bin to construct `$2` output bin.

Add obfuscated bundle target

---

.github/workflows/build-firmware.yaml

This is a funny little `contains()` check because GHA expressions don't have anything like `length()`

Check for empty matrix

---

firmware/controllers/core/error_handling.cpp

To avoid reentrance and infinity error loop
See https://github.com/rusefi/rusefi/pull/5911

firmwareError: set hasFirmwareErrorFlag as soon as possible

---

.github/workflows/custom-board-build/action.yaml

Turns out there isn't a type field for action inputs, so these do nothing and are misleading.

Remove types from custom-board-build inputs

---

.github/workflows/custom-board-build/action.yaml
firmware/bundle.mk
java_tools/java_tools.mk

This adds two inputs to the custom-board-build action, `run_simulator` and `sim_output`
If both `run_simulator` and `push` are true, the .msq and canned-tune/.md files will be pushed to the directory set in `sim_output`.

Build and run simulator for custom boards

---

firmware/bundle.mk
firmware/rusefi_config.mk
simulator/Makefile

This is trying to fix #6206
Also missed a generated file - `engine_configuration_generated_structures_<board>.h`

make simulator depend on config files

---

firmware/rusefi_pch.mk
simulator/Makefile

I tested build times on my laptop:
before: 1:45.05
after: 0:38.71
That after time even includes config generation, which didn't happen before, because the simulator uses a different rules.mk in which ACPPOBJS and TCPPOBJS don't exist, so nothing had CONFIG_FILES as a prerequisite.
Now CPPOBJS has PCHOBJ as a prerequisite, which in turn has CONFIG_FILES as a prerequisite, so configs get generated.

Make simulator build use PCH

---

.github/workflows/hardware-ci.yaml
.github/workflows/hw-ci/openocd_wipe_and_flash.sh
.github/workflows/hw-ci/run_hw_ci.sh
.github/workflows/openocd_ci_f4_discovery.cfg
.github/workflows/openocd_ci_proteus_f4.cfg
.github/workflows/openocd_ci_proteus_f7.cfg

An approach at #6103
expects environment variables:
```
HARDWARE_CI_SERIAL
HARDWARE_CI_STLINK_SERIAL
HARDWARE_CI_VBATT
```
`HARDWARE_CI_SERIAL` is just the serial, not the full path, and will be turned into a full path. This is to avoid needing to install systemd (which creates /dev/serial/by-id symlinks) on the self-hosted docker image. We can get the path manually from the serial in run_hw_ci.sh.
Making this draft PR to test on Matthew's hardware

HW CI multihost

---

simulator/simulator/rusEfiFunctionalTest.cpp

Simulator run was failing on my laptop with GCC 13.
I found this change trying to fix this error for a different compiler:
https://github.com/rusefi/rusefi/commit/61909b2f4ec1cbd831916624940b41fee1d341f4
I think the wrong digit was replaced by mistake - it was replacing the `c`.
```
assertString FAILED
>>>>>>>>>> firmwareError [chprintf test: got a-1.20b-3.400000096X while a-1.20b-3.400000095X]
```

replace correct digit in assert

---

simulator/Makefile

Fix #6195
Green custom: https://github.com/chuckwagoncomputing/fw-custom-paralela/actions/runs/8289357534
Result: https://github.com/chuckwagoncomputing/fw-custom-paralela/commit/4aff60dc17f0982c33b50aff5956b874a1949f85

Include board.mk in Simulator build if BOARD_DIR is set

---

firmware/rusefi.mk
simulator/Makefile

Draft because I have a red custom board with an error I haven't seen before.
https://github.com/chuckwagoncomputing/fw-custom-paralela/actions/runs/8312666260/job/22747852617

Get default tune and include meta output folder

---

firmware/controllers/sensors/impl/AemXSeriesEgt.cpp
firmware/controllers/sensors/impl/AemXSeriesEgt.h
firmware/controllers/sensors/sensors.mk
firmware/init/init.h
firmware/init/init.mk
firmware/init/sensor/init_egt.cpp
firmware/init/sensor/init_sensors.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Same protocol is implemented on RusEFI WBOx2
Currently only 0x000A0305 and 0x000A0306 IDs are supported
These two will be mapped to EGT1 and EGT2

sensors: support AEM X series EGT CAN gauge 

---

.github/workflows/build-simulator.yaml

Attempt at fixing #5984
Also remove redundant config generation.

Only commit msq and canned-tunes md files in simulator commit

---

simulator/Makefile

regardless of boards let's force simulator to be clean?

only:simulator has rules

---

firmware/bundle.mk
simulator/Makefile

It is currently possible to request both simulators with the custom board action. Prior to this PR, this fails because make doesn't know that the .o files need to be rebuilt for whichever version runs second. Even worse, they could run concurrently. This PR fixes both of these issues.

Allow for compiling both Windows and Linux simulators in a single Make run

---

.github/workflows/custom-board-build/action.yaml

This is slightly weird because it's the only thing in the workflow that needs the PROJECT_BOARD variable.
Fix #6263
Green custom: https://github.com/chuckwagoncomputing/fw-custom-paralela/actions/runs/8411292161

Upload openblt bin as artifact

---

.github/workflows/build-firmware.yaml

Fixes this: https://github.com/rusefi/rusefi/actions/runs/8413874239/job/23036744334?pr=6296
Run with both double quote and a single quote in a multi-line commit message: https://github.com/chuckwagoncomputing/rusefi/actions/runs/8414519038

Make matrix generation more resilient to funny commit messages

---

.github/workflows/build-firmware.yaml
.github/workflows/custom-board-build/action.yaml
firmware/Makefile
firmware/bundle.mk
firmware/rusefi_config.mk

Also `make bundle` now only builds the normal bundle, not the autoupdate as well. Use `make bundles` to build both.
Green custom https://github.com/chuckwagoncomputing/fw-custom-paralela/actions/runs/8412769451

Add more Make targets to simplify custom board action

---

firmware/bundle.mk

only renaming entities for readability

Bootloader bin out

---

firmware/controllers/tcu/gc_generic.cpp
firmware/controllers/tcu/gear_controller.cpp
firmware/controllers/tcu/gear_controller.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

The big thing here is changing the type of the tcu_range arrays from uint8 to float, which if I understand correctly requires incrementing FLASH_DATA_VERSION and updating TS_FILE_VERSION. I've never done that before, so I'm not sure if I've done it correctly.
Also adds:
- TS input for automatic shift speeds.
- Option for assumed shift time in the absence of an input speed sensor
- define TCU_RANGE_COUNT instead of having a magic number (And correct bug - it was 9 when it should have been 11)

TCU config stuff

---

.github/workflows/check-pinout.yaml
.github/workflows/gen-pinouts-top-level.yaml
.github/workflows/gen-pinouts.yaml

We went back to Debian for now because yq disappeared from the Alpine repos and I'm to lazy to check if the yq release on GH works on Alpine.

Update to interactive-pinout 2.15

---

firmware/tunerstudio/tunerstudio.template.ini

Duplicate some settings dialogs under this menu.

tunerstudio: add separate menu for CAN and related

---

.github/workflows/build-unit-tests.yaml
.github/workflows/custom-board-build/action.yaml
firmware/bin/gen_image_board.sh
firmware/gen_config_board.sh

#6405
- always use grealpath if it exists
- enable aliases - they're only enabled by default for interactive shells

Fix realpath on macos

---

firmware/rusefi_config.mk

Change of these files currently does not cause regeneration of auto-generated files.
@rusefillc @chuckwagoncomputing

Should rusefi_config.mk track rusefi_hw_*.h files changes?

---

firmware/console/binary/tunerstudio_io.cpp
firmware/console/binary/tunerstudio_io.h

@dron0gus just to confirm, this change is a bugfix, not just refactoring, is that right?

TS: clear naming, isBigPacket() against actual buffer size

---

firmware/Makefile
firmware/config/boards/f407-discovery/board.mk
firmware/config/boards/proteus/board.mk
firmware/config/boards/subaru_eg33/board.mk
firmware/rusefi_rules.mk

#5676
boards with Ethernet fail due to
```
ChibiOS/os/various/lwip_bindings/lwipthread.c: In function 'lwip_thread':
Compiling lwipthread.c
ChibiOS/os/various/lwip_bindings/lwipthread.c:414:20: error: declaration of 'p' shadows a parameter [-Werror=shadow]
414 |       struct pbuf *p;
```
desire is to not do -Werror=shadow for such configurations while having it everywhere else

variable shadowing should be avoided fix #5676

---

firmware/controllers/tcu/gc_auto.cpp
firmware/controllers/tcu/gc_auto.h
firmware/controllers/tcu/gc_generic.cpp
firmware/controllers/tcu/gc_generic.h
firmware/controllers/tcu/gear_controller.cpp
firmware/controllers/tcu/tc_4.cpp
firmware/controllers/tcu/tc_4l6x.cpp
firmware/controllers/tcu/tcu.cpp

gc_auto doesn't use range input pins; gc_generic which inherics gc_auto does.

Tcu crumbs

---

firmware/console/binary/bluetooth.cpp
firmware/console/binary/bluetooth.h

When a baud rate change was requested, we were trying to connect at the new baud rate instead of the current "working" baud rate. This was reporting back to the console as a NAME change failure.
Also moved some code to create a "findBaudIndex" function. This is not necessary but helped me keep things organized.

Bluetooth initialization order bug fix (and housekeeping)

---

firmware/hw_layer/adc/AdcDevice.h
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/hardware.cpp
firmware/hw_layer/ports/cypress/mpu_util.cpp
firmware/hw_layer/ports/kinetis/mpu_util.cpp
firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp
firmware/hw_layer/ports/stm32/stm32_adc_v4.cpp

`AdcToken` is planned to be used for all ADCs.
Only rename. No code logic changes.

ADC: FastAdcToken rename to AdcToken

---

firmware/console/binary/tunerstudio.cpp

Get all livedata with one command with no arguments. Preparation for blockingFactor = infinity.

TS: handle ochGetCommand with no arguments (read all)

---

.github/workflows/custom-board-build/action.yaml
firmware/bin/find_white_label.sh

to fix in GHA `Error: Process completed with exit code 1.` in case when `shared_io.resources/shared_io.properties` doesn't contain `white_label` property
P. S. It's a kind of magic :)

only: extract `Find out white-label` step code into `find_white_label.sh` script

---

firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs_onchip.cpp
firmware/integration/rusefi_config.txt

Out of bounds access to `adcHwChannelMode` was causing incorrect fast ADC selection for value reading.
Fast ADC had no protection of invalid channel read that cause another one out-of-bounds access to samples array and read of random data far behind this array.

Adc fix 13bit

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

`Target(Volts)` setting on `Alternator Settings` area in Tuner Studio), closes #6523

get rid of unused `targetVBatt` setting

---

firmware/Makefile
firmware/bundle.mk

Helps https://github.com/rusefi/rusefi/issues/6289

Add CRC32 support to plain .srec binary

---

firmware/controllers/engine_controller.cpp
firmware/controllers/engine_controller.h
firmware/controllers/sensors/core/sensor.cpp
firmware/controllers/sensors/impl/map.cpp
firmware/controllers/settings.cpp
firmware/controllers/system/efi_gpio.h
firmware/hw_layer/adc/adc_subscription.cpp
firmware/hw_layer/ports/cypress/cypress_common.cpp
firmware/hw_layer/ports/kinetis/kinetis_common.cpp
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/stm32/stm32_adc.cpp
firmware/hw_layer/ports/stm32/stm32_pins.cpp

Do not strcpy from 0x0 to temporally 16 bytes buffer causing surround corruption.

Adc subscription on mux

---

firmware/controllers/algo/engine.h

Otherwise if we have `hasFirmwareError()` `initGearController()` is never called and `engine->gearController` left unitialized and bad.
After TS connection we get hardfault:
```
Program received signal SIGTRAP, Trace/breakpoint trap.
HardFault_Handler_C (sp=<optimized out>) at ./hw_layer/main_hardfault.c:63
63		bkpt();
(gdb) bt
#0  HardFault_Handler_C (sp=<optimized out>) at ./hw_layer/main_hardfault.c:63
#1  <signal handler called>
#2  0x002431f8 in getLiveData<tcu_controller_s> () at ./console/binary/live_data.cpp:29
#3  0x0027b096 in FragmentEntry::get (this=0x200467a4 <fragments+48>) at ./libfirmware/util/include/rusefi/fragments.h:36
#4  copyRange (destination=0x20055077 <usbChannel+15> "", src=..., skip=0, size=532) at ./libfirmware/util/src/fragments.cpp:32
#5  0x0024b7fa in …
```

engine->gearController should be nullptr until initGearController()

---

firmware/controllers/flash_main.cpp
firmware/hw_layer/ports/at32/at32f4/mpu_util.cpp
firmware/hw_layer/ports/cypress/mpu_util.cpp
firmware/hw_layer/ports/kinetis/mpu_util.cpp
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/stm32/stm32f4/mpu_util.cpp
firmware/hw_layer/ports/stm32/stm32f7/mpu_util.cpp
firmware/hw_layer/ports/stm32/stm32h7/mpu_util.cpp
simulator/simulator/framework.cpp
simulator/simulator/mpu_util.h

Fix logic error. Previously we believed that if `EFI_FLASH_WRITE_THREAD` is TRUE we do flashing from thread.
But thread was created only if `(allowFlashWhileRunning() || (EFI_STORAGE_MFS_EXTERNAL == TRUE))`.
With STM32F7 2Mb single bank we ran into situation when `EFI_FLASH_WRITE_THREAD` is TRUE but `allowFlashWhileRunning()` is false. So not thread was created, but `writeToFlashIfPending()` was returning doing nothing.
Now we use same check on thread creation and inside `writeToFlashIfPending()`

Fix saving settings on STM32F7 2Mb single bank

---

firmware/controllers/algo/engine_state.h
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/limp_manager.cpp
firmware/controllers/math/engine_math.cpp
unit_tests/tests/ignition_injection/test_ignition_scheduling.cpp

port of https://github.com/FOME-Tech/fome-fw/pull/479
support wasted spark on odd cylinder count engines, including during startup before the cam position is resolved.
5 cylinder firing wasted spark (every cylinder fires every 360 degrees):
https://github.com/rusefi/rusefi/issues/4195 and also https://github.com/rusefi/rusefi/issues/6662
Also supports odd-fire but even-cylinder engines, as that's the same fundamental problem!
https://github.com/rusefi/rusefi/issues/6868
Here's an odd-fire 2 cyl running in wasted spark:

Odd cylinder engine wasted spark

---

simulator/simulator/boards.cpp
simulator/simulator/framework.cpp
simulator/simulator/rusEfiFunctionalTest.cpp
simulator/simulator/system/signal_executor_sleep.cpp

a few simple fixes to cleanup compilation output
all others modules should be fixed in the same way

Minor: fix 'unused parameter' warning in the simulator

---

simulator/Makefile

the root cause is .os.sentinel generation - it breaks, if $(OS) variable is empty
closes https://github.com/rusefi/rusefi/issues/6337

Fix incremental build of the simulator (linux version)

---

firmware/gen_live_documentation.sh

I cannot build unittests, if  `$META_OUTPUT_ROOT_FOLDER` is empty (in that case this utility tries to find files from the root folder).
Haven't found, why it happens on windows, but on linux works fine, but in either case all other usages of this variable expects that it should ends with slash (lets say https://github.com/rusefi/rusefi/blob/49c6b135073f3286d3aa19fc6e2bc9fc6224edaa/firmware/gen_signature.sh#L13 
or https://github.com/rusefi/rusefi/blob/49c6b135073f3286d3aa19fc6e2bc9fc6224edaa/firmware/gen_config_common.sh#L37 )

Fix building, if META_OUTPUT_ROOT_FOLDER is empty

---

java_tools/enum_to_string/src/main/java/com/rusefi/ToJavaEnum.java

Running build on Windows makes autogenerated files with 'inverted' slashes.
To reduce the number of differences would be better to use the same slashes (since it's in either case just a comments)

Minor: generate the same java enum files on windows as on linux

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle_impl.h
unit_tests/tests/actuators/test_etb.cpp

rather than try to integrate error over time, simply fault if there's been too much error for too long. Up to +-X error is allowed for any period of time, more is allowed for Y seconds.

simpler ETB jam detection #6925

---

firmware/tunerstudio/tunerstudio.template.ini

fixes #6856 
new sensors categories:
- Aux sensors
- Fuel sensors
- Oil sensors
- Chassis sensors
- Turbo sensors
tested on rusefi simulator / TS v3.2.03:

Organize sensor categories in tunerstudio

---

firmware/controllers/trigger/decoders/trigger_vw.cpp

Trigger wheel was mirrored(small tooth on other end of gap). Setting up falling edge trigger in TS gives the same tooth pattern as originally coded with different gap lengths, so only length and gap ratio had to be modified. Tested on working car.

Update trigger_vw.cpp - skoda trigger wheel

---

.vscode/launch.json
firmware/controllers/sensors/impl/AemXSeriesLambda.h
unit_tests/tests/test_can_wideband.cpp

added tests for: #7011, also added the missing preLaunchTask for debug on sim/hw/tests
```
root@dec6eb02fbba:/workspaces/rusefi/unit_tests# build/rusefi_test --gtest_filter=CanWideband.*
Note: Google Test filter = CanWideband.*
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from CanWideband
[ RUN      ] CanWideband.AcceptFrameId0
commonInitEngineController
doInitElectronicThrottle No
getSpeedDensityAirmass map=96.26
Not enough data for unittest_AcceptFrameId0.logicdata
[       OK ] CanWideband.AcceptFrameId0 (0 ms)
[ RUN      ] CanWideband.AcceptFrameId1
commonInitEngineController
doInitElectronicThrottle No
getSpeedDensityAirmass map=96.26
Not enough data for unittest_AcceptFrameId1.logicdata
[       OK ] …
```

new tests on decodeAemXSeries, fixed debug task on vscode

---

firmware/console/binary/tunerstudio.cpp
firmware/integration/ts_protocol.txt
firmware/tunerstudio/tunerstudio.template.ini

But until ochBlockSize is bigger than blockingFactor TS will not use this command and prefer ochGetCommand.
But you can comment out blockingFactor in ini file and get:

TS: implement getCommand that have no params and requests all livedata

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_impl.h

Also fix bug with incorrect data picked in pageValueWrite. Seems pageValueWrite was never used by TS

ts: handle pageValueWrite and pageChunkWrite with one func

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.h
firmware/console/binary/tunerstudio_impl.h
unit_tests/tests/test_tunerstudio.cpp

Initial support for page addressing. This is needed to move scatteredOffsetArray to separate page that is not saved in TS and ECU.

ts: handleWriteChunkCommand() and handlePageReadCommand() now with page

---

firmware/config/stm32f4ems/efifeatures.h
firmware/hw_layer/drivers/drivers.mk
firmware/hw_layer/drivers/gpio/tle9201.cpp
firmware/hw_layer/drivers/gpio/tle9201.h
firmware/hw_layer/smart_gpio.h

Tested on a hw board with TLE9201:
On start:
```
EngineState: TLE9201[0] Detected! (rev=00000021)
EngineState: TLE9201[0] Diag (0000005C):
EngineState: * Outputs disabled.
EngineState: * Open Load
```
During the ETB calibration:
```
EngineState: TLE9201[0] Diag (000000DF):
EngineState: * No failure
```
During the ETB calibration with one wire shorted to the ground:
```
EngineState: TLE9201[0] Diag (000000DE):
EngineState: * Short to GND at OUT1
```

TLE9201 SPI diag support https://github.com/rusefi/rusefi/issues/5058

---

firmware/integration/rusefi_config.txt

- updated load-related configs from hardcoded 1000kpa to MAP_UPPER_LIMIT
- updated MAP_UPPER_LIMIT from 255 kpa to 1000kpa
related issue: https://github.com/rusefi/rusefi/issues/7054

MAP_UPPER_LIMIT, change from uint8 to uint16

---

firmware/controllers/can/can_dash.cpp

0x153 is being sent out by the traction control module. It should not be sent by the ecu because it's causing traction control indicator to blink even when the car is not moving.
See https://www.ms4x.net/index.php?title=CAN_Bus_ID_0x153_ASC1

Remove 0x153 from E46 CAN dash

---

firmware/bootloader/Makefile
firmware/config/boards/readme.md

resolves: #7096
added DEBUG_LEVEL_BLT_OPT to define debug options in the bootloader, small comment in the boards .md to clarify the difference between both variables
cons?: by default now all boards will compile the bootloader with Os (the default option in the makefile)

new env var for openblt debug options, see #7096

---

firmware/hw_layer/drivers/sent/sent.cpp

prior to change we had two completely independent usages of same value

separating two different usages of variable

---

firmware/hw_layer/drivers/sent/sent.cpp
firmware/hw_layer/drivers/sent/sent.h
firmware/hw_layer/drivers/sent/sent_hw_icu.cpp
firmware/hw_layer/drivers/sent/sent_logic.h

Ok, we get decode errors because we lost events from HW.
Now we need to find why.
https://github.com/rusefi/rusefi/issues/7077
```
2024-12-07_00_44_44_072: EngineState: ---- SENT input 1 ---- on 24A - Hall Input 3 / SENT
2024-12-07_00_44_44_073: EngineState: Unit time 354 CPU ticks 1.638888832 uS
2024-12-07_00_44_44_073: EngineState: Pause pulse detected No
2024-12-07_00_44_44_073: EngineState: Total pulses 3528938
2024-12-07_00_44_44_074: EngineState: Last valid fast msg Status 0x0 Sig0 0xAD6 Sig1 0x529
2024-12-07_00_44_44_076: EngineState: HW overflows 102831 
2024-12-07_00_44_44_076: EngineState: Pause pulses 31323 
2024-12-07_00_44_44_080: EngineState: Restarts 2
2024-12-07_00_44_44_081: EngineState: Interval errors 30916 short, 43928 long
2024-12-07_00_44_44_081: EngineState: Total …
```

SENT: count HW timer overcapture events

---

firmware/console/status_loop.cpp
firmware/controllers/sensors/impl/ego.cpp
firmware/controllers/sensors/impl/map.cpp
firmware/hw_layer/adc/adc_external.h
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/adc/adc_inputs_onchip.cpp
firmware/hw_layer/adc/adc_subscription.cpp
firmware/hw_layer/algo/adc_math.h
firmware/hw_layer/drivers/gpio/protected_gpio.cpp
firmware/hw_layer/hardware.cpp
firmware/hw_layer/sensors/hip9011.cpp
simulator/simulator/boards.cpp
simulator/simulator/boards.h
unit_tests/boards.cpp
unit_tests/boards.h

adcGetRawValue() - get raw sample from ADC input, integer
adcGetRawVoltage() - get voltage on MCU ADC input (raw sample multiplied by ADC reference voltage)
adcGetScaledVoltage() - get voltage on ECU pin associated with provided ADC input. All input dividers and multipliers are applied.

ADC: rename helpers

---

java_console/autotest/src/main/java/com/rusefi/HwCiNucleoF7.java
java_console/autotest/src/main/java/com/rusefi/nucleo/NucleoVssHardwareTest.java

* ~docs for running the HW-CI tests without a github runner~ 0cb246e
* ~refactor `f4discovery/VssHardwareLoopTest.java`  with same style as  `common/PwmHardwareTestLogic.java`~  5aeba94
* added `NucleoVssHardwareTest` relevant log => https://gist.github.com/FDSoftware/819524a62d37d5e7abed18b29ef0fbed

Add VSS HW test to F767 suite

---

firmware/tunerstudio/tunerstudio.template.ini

added new Idle gauge, tested on simulator F407, preview:

Add 'Idle Stepper Target Position' as a gauge in Tunerstudio SEE: #7134

---

unit_tests/tests/ignition_injection/test_ignition_scheduling.cpp
unit_tests/tests/ignition_injection/test_odd_firing_engine.cpp
unit_tests/tests/ignition_injection/test_one_cylinder_logic.cpp
unit_tests/tests/ignition_injection/test_startOfCrankingPrimingPulse.cpp
unit_tests/tests/trigger/test_real_bosch_quick_start.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

without `test_fasterEngineSpinningUp.cpp` as this file needs to be treated separately (needs `EXPECT_NEAR` instead of `ASSERT_EQ`)
related issue: #6477

Get rid of GTEST assertion wrappers (EngineTestHelper::assertRpm)

---

unit_tests/tests/trigger/test_fasterEngineSpinningUp.cpp

one case uses EXPECT_NEAR as RPM are: 199.99998474121094, expected 200
related issue: #6477

Get rid of GTEST assertion wrappers (test_fasterEngineSpinningUp.cpp)

---

unit_tests/test-framework/engine_test_helper.cpp
unit_tests/test-framework/unit_test_framework.cpp
unit_tests/test-framework/unit_test_framework.h

also remove new dead code on `unit_test_framework.cpp` 
related issue: #6477

Get rid of GTEST assertion wrappers (assertEqualsM4)

---

firmware/controllers/algo/engine.h
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/gen_live_documentation.sh
java_tools/configuration_definition_base/src/main/java/com/rusefi/ldmp/LiveDataProcessor.java
unit_tests/tests/ignition_injection/test_ignition_scheduling.cpp

* edited test `ignition.trailingSpark`
* removed `enableOverdwellProtection` from `engine.h`
* removed enableOverdwellProtection usage from `spark_logic.cpp`
related issue: #3553
also one test less with the unitTestBusyWaitHack :D

remove legacy enableOverdwellProtection

---

firmware/CHANGELOG.md
firmware/hw_layer/ports/stm32/stm32f7/cfg/halconf.h
firmware/hw_layer/ports/stm32/stm32h7/cfg/halconf.h

enable watchdog for F7/H7
Looks like we leverage stm32 watchdog for over a year now? Should be safe to leverage same for F7.

stm32 own build-in watchdog #1339

---

firmware/hw_layer/mmc_card.cpp

We need 100..400 KHz clock during card initialization. And <=25MHz after.
http://elm-chan.org/docs/mmc/mmc_e.html

SD: calculate clock in runtime

---

firmware/hw_layer/main_hardfault.c

Call to bkpt() with no debuger attached will cause hang. Restart immediately instead.

hardfault: call bkpt() only if debuger is detected

---

firmware/console/eficonsole.cpp
firmware/controllers/core/error_handling.cpp
firmware/controllers/core/error_handling.h
firmware/hw_layer/backup_ram.h
firmware/hw_layer/hardware.cpp
firmware/hw_layer/hardware.h
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/mmc_card_util.cpp
firmware/hw_layer/mmc_card_util.h
firmware/rusefi.cpp
firmware/rusefi_rules.mk

Also:
-report ChibiOS panic message
-use bootCount for boot report file naming
-save few bytes in backup ram by reusing same field for different errors types

error reporting: extract all related code to error_handling

---

firmware/bootloader/bootloader_stubs.cpp
firmware/controllers/core/error_handling.cpp
firmware/controllers/core/error_handling.h
firmware/controllers/core/log_hard_fault.h
firmware/hw_layer/main_hardfault.c

**chibi_fault** command.
What programmer see:
```
chDbgPanic3 (msg=0x8089d60 "operator()", file=0x807bccc "ChibiOS/os/rt/src/chsys.c", line=201) at ./controllers/core/error_handling.cpp:343
343			bkpt();
...
(gdb) bt
#0  chDbgPanic3 (msg=0x8089d60 "operator()", file=0x807bccc "ChibiOS/os/rt/src/chsys.c", line=201) at ./controllers/core/error_handling.cpp:365
#1  0x08002cc8 in chSysHalt (reason=<optimized out>) at ChibiOS/os/rt/src/chsys.c:201
#2  0x0804a58c in operator() (__closure=0x0) at ./controllers/core/error_handling.cpp:114
#3  _FUN () at ./controllers/core/error_handling.cpp:114
#4  0x0803d770 in handleActionWithParameter (current=0x40024000, current@entry=0x20015af4 <consoleActions>, argv=0x8089d60, argv@entry=0x200081d4 <usbConsole+1356>, argc=argc@entry=0)
at …
```

error handing: save some stack on error

---

firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp

First include knock_config.h then use KNOCK_ADC define

stm32: adc v2: fix include order

---

firmware/controllers/core/error_handling.cpp
firmware/controllers/core/error_handling.h
firmware/controllers/core/error_handling_c.h
firmware/hw_layer/ports/rusefi_halconf.h

There is not way to pass '...' argument to another function. We need to switch to va_list first
Fixes bug introduced in 36ee662a34649f5ce94341b6ca9c9937cfb752e7
This should fix incorrect serialization of arguments. Like this:

error_handling: do not pass va_list to variable argument list function

---

firmware/controllers/algo/defaults/default_ignition.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/ignition/ignition_state.cpp
firmware/controllers/algo/ignition/ignition_state.h
firmware/controllers/algo/ignition/ignition_state.txt
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

* added a new table "trailingSparkAngle"
* removed trailingSparkAngle as config on rusefi.txt
* added trailingSparkAngle as variable on ignition state
* bump FLASH_DATA_VERSION
needs test/review from @ElDominio 
resolve: #5248

Make trailing spark angle a 3D table #5248

---

firmware/controllers/sensors/sensor_checker.cpp

TunerStudioOutputChannels *state is used even BOARD_EXT_GPIOCHIPS is zero

sensor_checker: fix visibility of TunerStudioOutputChannels

---

firmware/hw_layer/ports/stm32/stm32_common.cpp

Tested on Nucleo-F767 and STM32CubeIDE debug session.

Activate 'debug freeze' watchdog feature for debug builds https://github.com/rusefi/rusefi/issues/1339

---

firmware/tunerstudio/tunerstudio.template.ini

Was accidentally added back due to bad rebase

tunerstudio.template: no knockBandCustom

---

firmware/controllers/actuators/electronic_throttle.txt

Dead since 3ee894594d405ceac8a98ea5838c3d11c94e9c1d

etb: dead etbIntegralError

---

firmware/hw_layer/mass_storage/mass_storage_device.cpp
firmware/hw_layer/mass_storage/mass_storage_device.h
firmware/hw_layer/mass_storage/mass_storage_init.cpp
firmware/hw_layer/mass_storage/mass_storage_init.h
firmware/hw_layer/mmc_card.cpp

Read using UAEFI before this patch:
```
$ dd if=test.bin of=/dev/zero status=progress
133939712 bytes (134 MB, 128 MiB) copied, 269 s, 498 kB/s
262144+0 records in
262144+0 records out
134217728 bytes (134 MB, 128 MiB) copied, 269.492 s, 498 kB/s
```
Read using UAEFI with blkbuf1 = 2K bytes:
```
$ dd if=B5A4-271B/test.bin of=/dev/zero status=progress
133677568 bytes (134 MB, 127 MiB) copied, 202 s, 661 kB/s
262144+0 records in
262144+0 records out
134217728 bytes (134 MB, 128 MiB) copied, 202.69 s, 662 kB/s
```

SD in MSD: Speed up a bit

---

firmware/controllers/algo/fuel/injector_model.txt
firmware/integration/rusefi_config_shared.txt
firmware/tunerstudio/tunerstudio.template.ini

added the sensor as "pressureCorrectionReference" inside "injector_model_s" struct for future use inside the deadtime curve to table change (https://github.com/orgs/rusefi/projects/37/views/1?pane=issue&itemId=99441931)
For now the value is not updated at any time, the proposed change for it is the following, but I have doubts if it is the ideal place, so I do not include it in the PR
```c++
float InjectorModelWithConfig::getDeadtime() {
switch (getInjectorCompensationMode()) {
case ICM_FixedRailPressure:
pressureCorrectionReference = getFuelReferencePressure();
case ICM_SensedRailPressure: {
auto fps = Sensor::get(SensorType::FuelPressureInjector);
if (!fps) {
pressureCorrectionReference = getFuelReferencePressure();
} else {
pressureCorrectionReference = fps.Value;
}
}
}
return …
```

Expose SensorType::FuelPressureInjector on TS

---

firmware/tunerstudio/tunerstudio.template.ini

at `firmware/controllers/algo/fuel/fuel_computer.cpp`
We are already using fuelingLoad as a parameter, so it's just a phrasing change in TS
```cpp
float FuelComputer::getTargetLambda(float rpm, float load) const {
float target = interpolate3d(
config->lambdaTable,
config->lambdaLoadBins, load,
config->lambdaRpmBins, rpm
);
// Add any blends if configured
for (size_t i = 0; i < efi::size(config->targetAfrBlends); i++) {
auto result = calculateBlend(config->targetAfrBlends[i], rpm, load);
engine->outputChannels.targetAfrBlendParameter[i] = result.BlendParameter;
engine->outputChannels.targetAfrBlendBias[i] = result.Bias;
engine->outputChannels.targetAfrBlendOutput[i] = result.Value;
target += result.Value;
}
return target;
}
```
related issue: #7170
TS Change:
prev:
now:

Y label for AFR blends

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/mocks.h
unit_tests/tests/test_idle_controller.cpp

https://github.com/FOME-Tech/fome-fw/commit/dd67fa58e79183425c38d1f9c516fa3da59581f4 => added comment about diff on `targetRpmAc`
https://github.com/FOME-Tech/fome-fw/commit/1934761cea3c3758dcb48e93c9cb0a1c8a77c73a => change from `interpolateClamped` to `interpolateClampedWithValidation`
https://github.com/FOME-Tech/fome-fw/commit/e2796b2f11273cec397c6f64af7e6f6e482624a7 => as is
https://github.com/FOME-Tech/fome-fw/commit/404bf5c188055ac3acf838219c018d9efd988092 => as is
related issue: #7598

ramp target as you enter idle

---

simulator/simulator/can/hal_can_lld.cpp

works ok now with:
`gcc versión 14.2.1 20240912 (Red Hat 14.2.1-3) (GCC) `
resolves #6650

Simulator won't compile with newer GCC versions #6650

---

firmware/config/boards/hellen/hellen-honda-k/board_configuration.cpp
firmware/config/engines/dodge_neon.cpp
firmware/config/engines/gm_sbc.cpp
firmware/config/engines/honda_k_dbc.cpp
firmware/config/engines/m111.cpp
firmware/controllers/math/engine_math.h

Also updated all the references to `globalTriggerAngleOffset` that were adding the 360°

separate trigger offset from cam being on second phase see #7645

---

firmware/config/engines/hyundai.cpp
firmware/config/engines/mazda/mazda_miata_na8.cpp
firmware/config/engines/mazda/mazda_miata_vvt.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
firmware/controllers/algo/defaults/default_cranking.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/mocks.h
unit_tests/tests/test_idle_controller.cpp

resolves #7670 
UI:
also new max 500 cycles ==> at 1500 rpm == 20s (5000 cycles was the original max value and seems too exaggerated)

cranking iac taper duration should be a curve see #7670

---

firmware/controllers/sensors/impl/software_knock.cpp
firmware/hw_layer/adc/adc_inputs_onchip.cpp
firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp
firmware/hw_layer/ports/stm32/stm32_adc_v4.cpp

Starting new conversion until previous one is not handled cause assert and ChibiOS panic.
ADC_READY and ADC_ERROR are only allowed states to start new conversion.

ADC: knock

---

firmware/console/binary/output_channels.txt
firmware/hw_layer/mmc_card.cpp
firmware/tunerstudio/tunerstudio.template.ini

Also show return values to user.
TODO: store all FatFS returned errors to sd_error

SD card: show formating indicator while formating

---

firmware/Makefile
firmware/bootloader/Makefile
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/controllers.mk
firmware/controllers/engine_controller.cpp
firmware/controllers/modules/generated/engine_modules_generated.h
firmware/controllers/modules/generated/modules_list_generated.h
firmware/controllers/modules/modules.mk
firmware/controllers/modules/tachometer/tachometer.mk
simulator/Makefile
unit_tests/Makefile

Updated the makefiles, removed unused references to `tachometer.h`
now windows safe :D

refactoring: leverage EngineModule more often see #7572

---

.github/workflows/build-unit-tests.yaml

The timeout command will throw an error code 127 if the second build takes more than 30 seconds.

CI coverage to assert that unit test build is incremental see #7748

---

firmware/tunerstudio/tunerstudio.template.ini

This helps aiming when filling Bias table.

TS UI: add etb1DutyCycle as Y OutputChannel on ETB bias curve

---

firmware/config/stm32f4ems/efifeatures.h
firmware/console/binary/output_channels.txt
firmware/hw_layer/adc/AdcDevice.h
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs_onchip.cpp
firmware/hw_layer/ports/at32/at32f4/cfg/mcuconf.h
firmware/hw_layer/ports/stm32/stm32_pwm.cpp

Now ADC is started by timer event without CPU intervention.
This removes 10.000 IRQ/sec.

ADC: timer HW trigger

---

firmware/console/console.mk
firmware/console/eficonsole.h
firmware/controllers/modules/ethernet_console/ethernet_console.cpp
firmware/controllers/modules/ethernet_console/ethernet_console.mk
firmware/controllers/modules/generated/modules_list_generated.h
firmware/controllers/modules/modules.mk
firmware/rusefi.cpp

last pr for resolve #7572, also first example of a optional module :D (ie, not all boards have eth, so the module is removed for those), also some form of progress to https://github.com/rusefi/rusefi/issues/7603 (_per-feature .txt and template.ini provisions_)

refactoring: leverage EngineModule more often [ethernet_console] see #7572

---

firmware/controllers/system/periodic_thread_controller.h
unit_tests/chibios-mock/mock-threads.h

Use previous execution timestamp instead of chVTGetSystemTime()
Use chTimeAddX() helper
From this:
To this:
Average execution period (last PID dT) is closer to 2.0 mS with this fix.
See https://www.chibios.org/dokuwiki/doku.php?id=chibios:documentation:books:rt:kernel_threading "Fixed Intervals 3"
Somehow also relate to main loop https://github.com/rusefi/rusefi/issues/7760

periodic thread controller: be more real-time

---

firmware/tunerstudio/tunerstudio.template.ini

Users usually ignore instructions. Lets see if they can see RED warning.
From:
To:

TS UI: improve ETB calibration dialogs

---

firmware/setup_linux_environment.sh

`libncurses5` and `libncursesw5` seems to be outdated and not present in the common Ubuntu 24.04 repository
Don't know who uses it, and most likely it can be simply removed.
```
$ sudo apt-get install -y build-essential gcc gdb gcc-multilib make openjdk-11-jdk-headless xxd libncurses5 libncursesw5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libncurses5
E: Unable to locate package libncursesw5
```

setup_linux_environment.sh wont work on Ubuntu 24

---

java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/TuneCanTool.java
java_tools/tune-tools/src/test/java/com/rusefi/tune/TuneCanToolTest.java

new output from script:
```c++
// default "cc/min"
engineConfiguration->injectorFlowAsMassFlow = true;
// default "false"
engineConfiguration->enableAemXSeries = true;
// default "false"
engineConfiguration->enableSoftwareKnock = true;
```
resolves #7843

TuneCanTool does not produce valid code for named boolean see #7843

---

java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/MetaHelper.java
java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/TuneCanTool.java
java_tools/tune-tools/src/main/java/com/rusefi/tools/tune/TuneTools.java

resolves #7858
example output:
```
// default "false"
config->testPerBoardBit = true;
// default "Single Tooth"
engineConfiguration->vvtMode[0] = VVT_INACTIVE;
// default 450.0
engineConfiguration->vvtOffsets[0] = 0;
// default 200.0
engineConfiguration->injector.flow = 10;
// default "cc/min"
engineConfiguration->injectorFlowAsMassFlow = true;
// default 250.0
engineConfiguration->gppwm[0].pwmFrequency = 250;
// default 250.0
engineConfiguration->gppwm[1].pwmFrequency = 20;
```

canned tune broken testPerBoardBit see #7858

---

firmware/config/stm32f4ems/efifeatures.h
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp

If `EFI_INTERNAL_SLOW_ADC_BACKGROUND` is enabled slowAdc is continually restarted from `end_cb` conversion end callback.
`readSlowAnalogInputs` is not longer wait for conversion end, it just picks fresh `SLOW_ADC_OVERSAMPLE` samples and does averaging.

ADCv2: irq-driven continuoes conversion in background

---

firmware/console/binary_log/binary_logging.cpp
firmware/console/binary_log/log_field.h

Lets use actual engine object size

unit_tests: binary_logging: 1B is too much for this hack

---

firmware/controllers/modules/map_averaging/map_averaging.cpp

related issue: #7869
now using `samplingStart - currentPhase` as map averager start
detail on time active:
log:
[2025-05-13_01.21.25.mlg.zip](https://github.com/user-attachments/files/20181120/2025-05-13_01.21.25.mlg.zip)
map averager configured as:

fix: "map window averaging does not use crank angle" see #7869

---

firmware/config/boards/f407-discovery/board_configuration.cpp
firmware/config/boards/hellen/hellen154hyundai_f7/board_configuration.cpp
firmware/config/boards/subaru_eg33/board_configuration.cpp
firmware/hw_layer/drivers/gpio/mc33810.cpp
firmware/hw_layer/drivers/gpio/mc33810.h

No SPKDUR event after ignition pulse means misfire.
Duration of SPKDUR = duration of ignition spark.
Detect and measure duration of SPKDUR signal.
Of no SPKDUR detected - rise `PIN_OPEN` diagnostic code for this ignition output.
TODO: export spark duration to TS/logs.

MC33810 SPKDUR support

---

firmware/config/boards/proteus/prepend_proteus_f7.txt
firmware/console/binary/tunerstudio.cpp

We have 64K offset limitation for one settings page. Try not to cross this boundary.
https://github.com/rusefi/rusefi/issues/7840

7840 burn brokes TS on Proteus F7

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/sensors/impl/AemXSeriesLambda.cpp
firmware/controllers/sensors/impl/AemXSeriesLambda.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
unit_tests/tests/controllers/can/test_can_wideband.cpp

Now user can select witch type of WBO is used. So onboard RusEFI WBO can be ignored and external AEM can be used instead.
Autodetection is disabled. User should explicitly define used WBO.
Someone need to test this with AEM.

7048 AEM vs RusEFI WBO

---

firmware/bin/check_manifest_in_jar.sh
firmware/bin/check_manifests_in_bundle.sh
firmware/bin/upload_bundle.sh

Sometimes generated bundles have scanty manifests in .jar files.
We don't know why it happens, but we definitely do not want to upload bundles with broken manifests.
only:uaefi

we definitely do not want to upload bundles with broken manifests

---

firmware/controllers/algo/engine.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini

This dangerous option was replaced with manual WBO type selection
This reverts commit 79cfb0a5f3d1d9c9bcbb38c52c63072bca842fdd
https://github.com/rusefi/rusefi/issues/7870

WBO: Remove Suppress on-board WBO

---

firmware/controllers/bench_test.cpp
firmware/controllers/can/rusefi_wideband.cpp
firmware/controllers/can/rusefi_wideband.h

If non-broadcast hwIndex is passed send extended WB_MSG_SET_INDEX CAN message with HW index in second byte. This type of packet is supported by 2025 WBO FW and allows to address individual WBO depending on its strap pins.

WBO: setWidebandOffset() with hwIndex

---

firmware/console/binary/output_channels.txt
firmware/controllers/algo/engine_types.h
firmware/controllers/algo/rusefi_enums.h
firmware/controllers/bench_test.cpp
firmware/controllers/can/rusefi_wideband.cpp
firmware/tunerstudio/tunerstudio.template.ini

New UI with dropdowns fully replaces "Set Index 0" and "Set Index 1". Someday we should remove these buttons.

RE WBO: individually addressed set CAN index commands and UI

---

firmware/controllers/lua/lua.cpp

Tested on MRE with F427:
```
2025-05-27_16_01_01_537: EngineState: rx total/recent 0 0
2025-05-27_16_01_01_538: EngineState: luaCycle 10us including luaRxTime 3us
2025-05-27_16_01_01_538: EngineState: Lua memory heap usage: 16445 / 65536 bytes = 25.0%
2025-05-27_16_01_01_539: EngineState: confirmation_luamemory:9
```

Lua heap: fix stupid mistake

---

firmware/controllers/lua/lua.cpp

Now also shows ChibiOS heap and memcore statistic.
```
2025-06-01_10_04_21_403: EngineState: rx total/recent 0 0
2025-06-01_10_04_21_404: EngineState: luaCycle 22us including luaRxTime 9us
2025-06-01_10_04_21_404: EngineState: Lua memory heap usage: 16542 / 92000 bytes = 17.9%
2025-06-01_10_04_21_405: EngineState: Common ChibiOS heap: 0 bytes free
2025-06-01_10_04_21_406: EngineState: ChibiOS memcore free size: 52992
```

Luamemory command improvement

---

firmware/tunerstudio/tunerstudio.template.ini

edit for "Rotary" Should only be selectable when "Base engine-> Trigger->Strokes" is set to "Two" #6397

Updated tunerstudio.template.ini for rotary trigger

---

firmware/hw_layer/ports/stm32/stm32f7/STM32F7.ld

1. ram2 is used as no-cached area. So exclude it from ram0. Keeping this are in two memory regions in ld file can cause overlap that will not detected by linker.
2. Also use unused ram from ram0 section for ChibiOS.
These increase amount of memory available for ChibiOS memcore and default heap. And thus to Lua
From:
```
2025-06-02_18_06_04_024: EngineState: Dedicated Lua memory heap usage: 20232 / 92000 bytes = 21.9%
2025-06-02_18_06_04_024: EngineState: Common ChibiOS heap: 0 bytes free
2025-06-02_18_06_04_024: EngineState: ChibiOS memcore: 52992 bytes free
```
To:
```
2025-06-02_17_25_36_509: EngineState: LUA script loaded successfully!
2025-06-02_17_25_36_509: EngineState: Dedicated Lua memory heap usage: 20232 / 92000 bytes = 21.9%
2025-06-02_17_25_36_510: EngineState: Common ChibiOS …
```

Lua heap and stm32f7 ram2

---

firmware/controllers/actuators/electronic_throttle.cpp
unit_tests/tests/actuators/test_etb.cpp
unit_tests/tests/ignition_injection/test_ignition_state.cpp

* Traction control ETB is not fliped, updated the comment & test, both on firmware and TS we have correct X/Y axis (as defined on #6944 screenshot X => vehicle speed; Y => wheel slip)
* added test for tables on `Traction Control Timing drop` and `Traction Control Skip Ignition`
* newer test calculates the end of the table on compile time instated of fixed array length, to prevent more issues like: https://github.com/rusefi/rusefi/pull/7775
relevant TS template section:
```ini
table = tractionEtbTableTbl,  tractionEtb,  "Traction Control ETB drop",	1
xBins		= tractionControlSpeedBins,  vehicleSpeedKph
yBins		= tractionControlSlipBins,  wheelSlipRatio
zBins		= tractionControlEtbDrop
table = tractionTimingTableTbl,  tractionEtb,  "Traction Control Timing drop",	1
xBins		= …
```

Traction control ETB & spark tests

---

.github/workflows/hardware-ci.yaml

we have a problem related to HW-CI and TS signatures:
to reproduce:
* download https://github.com/FDSoftware/rusefi/actions/runs/15635956765 .ini artifact
* see incorrect `signature	= "rusEFI .2025.06.13.stm32f767_nucleo.97654472"`
* download https://github.com/FDSoftware/rusefi/actions/runs/15637107791 .ini with fix:
* see now more nice: `signature	= "rusEFI fix_branch_name.2025.06.13.stm32f767_nucleo.97654472"`

Fix HW-CI .ini & fw signature

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.h
firmware/console/binary/tunerstudio_commands.cpp

One more round of setting pages support.
Move all common code to helpers.
This should simplify adding new settings pages.
Someday we may want to divide big settings blob into chunks for each module and allocate separate page for each chunk.

TS: pages support

---

firmware/controllers/sensors/impl/AemXSeriesLambda.cpp
firmware/controllers/sensors/impl/AemXSeriesLambda.h

Using timeout from StoredValueSensor is not correct as it is not updated on invalidate() call.

CAN WBO: implement its own timeout

---

unit_tests/ci_gcov.sh

While creating the tests for closed_loop_idle.cpp I saw that we had lcov configured for the repository, and that the reports were uploaded to this URL:
https://rusefi.com/docs/unit_tests_coverage/index.html
but it has not been updated since December, searching in the CI, the pipeline always fails with an error similar to this:
```
geninfo: WARNING: ('mismatch') mismatched end line for _ZN29FunctionChain_TestSingle_Test8TestBodyEv at rusefi/unit_tests/tests/sensor/func_chain.cpp:25: 25 -> 40
(use "geninfo --ignore-errors mismatch,mismatch ..." to suppress this warning)
``` 
With `--ignore-errors mismatch` we can patch until we find the exact error that causes it, which changes from file to file depending on the execution of the CI we look at.
now much nicer:

patch lcov since we don't have coverage reports since 2024-12-19

---

firmware/controllers/math/closed_loop_idle.cpp

This pr includes completely optional things
* Converting fabsf to std::abs to simplify and let the compiler decide the ideal override
* comments about the code

closed_loop_idle optional bits

---

firmware/controllers/can/can_listener.h
firmware/controllers/can/can_rx.cpp
firmware/controllers/can/rusefi_wideband.cpp
firmware/controllers/can/rusefi_wideband.h
firmware/controllers/sensors/impl/AemXSeriesLambda.cpp
firmware/controllers/sensors/impl/AemXSeriesLambda.h
firmware/hw_layer/drivers/gpio/can_gpio_msiobox.cpp
unit_tests/tests/controllers/can/test_can_rx.cpp
unit_tests/tests/controllers/can/test_can_wideband.cpp

This allows listener to check CAN bus as well as CAN message ID.
This is needed for ECU with >= 2 CAN buses where same messages with different purpose may exist on different buses.

CanListener: pass CAN bus index to acceptFrame()

---

firmware/controllers/system/efi_gpio.cpp

efiPrintfInternal() has it's own critical section inside. Nesting critical sections is not allowed in ChibiOS and cause "SV#4" halt on ChibiOS 21.11.x.
See _dbg_check_lock() and _dbg_enter_lock().
Not clear why we did not see this fault on currect ChibiOS...
Breakpoint 1, chSysHalt (reason=0x56791e40 "SV#4") at ../firmware/ChibiOS/os/rt/src/chsys.c:209 209	void chSysHalt(const char *reason) {
(gdb) bt
0  chSysHalt (reason=0x56791e40 "SV#4") at ../firmware/ChibiOS/os/rt/src/chsys.c:209
1  0x56584c68 in __dbg_check_lock () at ../firmware/ChibiOS/os/rt/src/chdebug.c:159
2  0x56584a08 in chSysLock () at ../firmware/ChibiOS/os/rt/include/chsys.h:411
3  chSysGetStatusAndLockX () at ../firmware/ChibiOS/os/rt/src/chsys.c:431
4  0x566e0338 in …

efi_gpio: do not efiPrintf() from critical section

---

firmware/controllers/lua/lua_hooks.cpp

It would be a bit clearer to not convert int -> float for a functions that deals only with ints.
Advantages:
- `print(lua_readpin(1,2))` will return `1` but not `1.0000`
- `if lua_readpin(1,2) == 1` should work better (floats comparision is an evil, even if it works in this particular case)

Minor: use integers for return values in LUA hooks

---

firmware/hw_layer/drivers/can/can_msg_tx.cpp

Just a minor code cleanup, all MCU-specific #ifdef magic exists inside CAN_ID() macro

Minor: use existing macro CAN_ID() to get CAN packet id

---

firmware/config/boards/nucleo_f429/board_configuration.cpp
firmware/config/boards/nucleo_h743/board_configuration.cpp
firmware/console/eficonsole.cpp
firmware/hw_layer/board_overrides.h
firmware/main.cpp
simulator/main.cpp

I thought about taking advantage of the fact that we are using more c20, we have std::invoke available to be able to invoke functions without having to write a cast
result:
```
[0us]efiPrintfInternal:msg`*** rusEFI LLC (c) 2012-2024. All rights reserved.`
[0us]efiPrintfInternal:msg`*** rusEFI v20250709@1140675965 now=0`
[0us]efiPrintfInternal:msg`*** Chibios Kernel:       7.0.5`
[0us]efiPrintfInternal:msg`*** Compiled:     Jul  9 2025 - 18:26:56`
[0us]efiPrintfInternal:msg`*** COMPILER=14.2.1 20240912 (Red Hat 14.2.1-3)`
[0us]efiPrintfInternal:msg`custom board hello from simulator`
``` 
If we need to invoke a custom board function or a default one, we can also add something like
```c++
std::invoke(custom_board_boardSayHello.value_or(default_board_boardSayHello));
```
related: #8249

prep: new board override system for boardInitHardware/boardInitHardwareExtra see #8249

---

.github/workflows/build-unit-tests.yaml
unit_tests/ci_gcov.sh

demo here:
https://fdsoftware.github.io/gcovr_demo/
visually are relative the same both, so not much to show, but gcovr introduces a new "decisions" instated of branches in the coverage:
fist are branches, second the decision
https://gcovr.com/en/stable/faq.html#why-does-c-code-have-so-many-uncovered-branches
decision are more readable than branches, see:
vs:
same file on LCOV:
and on GCOVR:
resolves: #8129

LCOV => GCOVR migration

---

firmware/console/status_loop.cpp
firmware/controllers/flash_main.cpp
firmware/controllers/flash_main.h
firmware/controllers/long_term_fuel_trim.cpp
firmware/controllers/long_term_fuel_trim.h
firmware/controllers/long_term_fuel_trim_state.txt
firmware/controllers/storage.cpp
firmware/controllers/storage.h
firmware/controllers/storage_flash.cpp
firmware/controllers/storage_flash.h
firmware/controllers/storage_mfs.cpp
firmware/controllers/storage_mfs.h
firmware/controllers/storage_sd.cpp
firmware/controllers/storage_sd.h
firmware/controllers/thread_priority.h
firmware/hw_layer/mmc_card.cpp
unit_tests/tests/controllers/test_flash.cpp

SD card takes some time to init. Initialization is done from separate thread after engine modules init is done.
We need way to notificate storage users that storage is ready and calibration can be loaded.
Implement such for LTFT.

SD storage: delayed LTFT calibration load on SD card mount

---

firmware/config/boards/at_start_f435/board_storage.cpp
firmware/config/boards/hellen/hellen_common.cpp
firmware/config/boards/microrusefi/board_storage.cpp
firmware/config/boards/subaru_eg33/board_storage.cpp
firmware/controllers/storage.cpp
firmware/controllers/storage.h
firmware/controllers/storage_mfs.cpp

Allow registering/deregistering storages from storage manager thread.
Allow boards to indicate that MFS storage is not ready (powered off on some Hellen boards).
Hellen boards: request MFS storage attach after aux power (used for SD and SPI flash) is enabled.

Storage: async api

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/tunerstudio.template.ini
java_tools/configuration_definition_base/src/main/java/com/rusefi/output/TsOutput.java

new rusefi_config.txt syntax is: 
`float[IAT_CURVE_SIZE] iatFuelCorrBins;;"SPECIAL_CASE_TEMPERATURE", 1, 0, -100, @@CLT_UPPER_LIMIT@@, 2`
Instated of: 
`float[IAT_CURVE_SIZE] iatFuelCorrBins;;"C", 1, 0, -100, @@CLT_UPPER_LIMIT@@, 2`
note the new `SPECIAL_CASE_TEMPERATURE` unit to determine if we are dealing with temperature units
new generated .ini should be like this:
```
#if CELSIUS
iatFuelCorrBins = array, F32, 13740, [16], "C", 1, 0, -100, 250, 2
#else
iatFuelCorrBins = array, F32, 13740, [16], "F", 1.8,17.77777,-148.0,482.0, 2
#endif
``` 
~draft since needs more comments to explain how it works, and I'm afraid I've committed too many sins in this PR (fixed with the last force-push, now i split all in more small commits)~
also maybe `SPECIAL_CASE_TEMPERATURE` not the best name for …

Celsius/ Fahrenheit handling on .ini generator

---

firmware/tunerstudio/tunerstudio.template.ini
java_tools/configuration_definition/src/test/java/com/rusefi/test/TsOutputTest.java
java_tools/configuration_definition_base/src/main/java/com/rusefi/output/TsOutput.java

replace of `#if CELSIUS` (which defaults to fahrenheit in TS), with new "TEMP_UNITS_CELSIUS" (which defaults to Celsius)
settingGroup doesn't support a default value, so I can't give it fancy labels for the user.

custom flag for Celsius/Fahrenheit selector

---

firmware/integration/rusefi_config.txt

Migration of all supported fields without having to change the type/size
some excluded such as:
`uint32_t[VBAT_INJECTOR_CURVE_PRESSURE_SIZE] autoscale battLagCorrPressBins;Injector correction pressure;"kPa", 0.1, 0, 0, 30000, 2`
For these,we would have to use "scale * 0.145038", I can add this to the tsOutput, but I didn't know if I'm going out of scope
related #4788

kpa => SPECIAL_CASE_PRESSURE migration

---

java_tools/configuration_definition_base/src/main/java/com/rusefi/ConfigFieldImpl.java

From:
```
Caused by: com.rusefi.ParsingException: While parsing uint32_t[VBAT_INJECTOR_CURVE_PRESSURE_SIZE] autoscale battLagCorrPressBins;Injector correction pressure;"SPECIAL_CASE_PRESSURE", 0.1, 0, 0, 30000, 2
at com.rusefi.ReaderStateImpl.processField(ReaderStateImpl.java:358)
at com.rusefi.ReaderStateImpl.readBufferedReader(ReaderStateImpl.java:312)
at com.rusefi.ReaderStateImpl.doJob(ReaderStateImpl.java:126)
... 2 more
Caused by: java.lang.NumberFormatException: For input string: "0.1"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
```
to:
```
Caused by: com.rusefi.ConfigFieldImpl$FieldOutOfRangeException: battLagCorrPressBins: incorrect scale for SPECIAL_CASE_* field, use 1 as scale
at …
```

SPECIAL_CASE_* require scale of 1 fix on error throw

---

firmware/controllers/system/thread_controller.h

Why I cannot reproduce this locally?
```
In file included from ../global.h:28,
from ../pch/pch.h:22:
../controllers/system/thread_controller.h: In instantiation of 'class ThreadController<512>':
../controllers/system/periodic_thread_controller.h:36:7:   required from 'class PeriodicController<512>'
36 | class PeriodicController : public ThreadController<TStackSize>
|       ^~~~~~~~~~~~~~~~~~
../controllers/can/can.h:58:31:   required from here
58 | class CanWrite final : public PeriodicController</*TStackSize*/512> {
|                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../ChibiOS/os/various/cpp_wrappers/ch.hpp:1337:21: error: 'chibios_rt::ThreadReference chibios_rt::BaseStaticThread<N>::start(tprio_t) [with int N = 512; tprio_t = long unsigned int]' was hidden …
```

start() was hidden fix?

---

firmware/config/boards/hellen/alphax-8chan/board_configuration.cpp
firmware/config/boards/hellen/uaefi/board_configuration.cpp
firmware/console/status_loop.cpp
firmware/controllers/sensors/impl/ego.cpp
firmware/controllers/sensors/impl/map.cpp
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/adc/adc_subscription.cpp
firmware/hw_layer/algo/adc_math.h
firmware/hw_layer/drivers/gpio/protected_gpio.cpp
simulator/simulator/boards.cpp
unit_tests/adc_inputs.h
unit_tests/boards.cpp

Now we can detect +5VP failure on few Hellen board.
```
2024-12-12_00_34_32_433: EngineState: WARNING: P2125: Sensor fault: AcceleratorPedalPrimary has timed out
2024-12-12_00_34_32_445: EngineState: WARNING: P2130: Sensor fault: AcceleratorPedalSecondary has timed out
2024-12-12_00_34_32_447: EngineState: WARNING: P0641: Analog subsystem fault
2024-12-12_00_34_32_447: EngineState: WARNING: P0106: Sensor fault: Map has timed out
```
Also analog inputs depending on this supply is now reported invalid using `expected`. So sensor (or any other analog input user) can propagate sign of error further.
```
2024-12-12_00_35_21_160: EngineState: fast 649421 samples
2024-12-12_00_35_21_161: EngineState:  F ch[ 0] @ PC0 ADC11 12bit=  13 0.000V input 0.000V INVALID
2024-12-12_00_35_21_161: …
```

Report analog failure to TS and rise OBD code, use TLS115 PG signal on Hellen boards, use `expected` for adc inputs

---

firmware/config/boards/hellen/hellen_common.cpp
firmware/config/boards/microrusefi/board_configuration.cpp

Most of these boards uses REF3033 as Vref+ supply. It is 3.3 with 0.2% acuracy.
Some uses LDO with less acuracy, bit still with 3.3V output.
vccAdc was defined as 3.29V for MRE from the begin of ages. And seems was copy-pasted to Hellen.
Maybe @mck1117 knows some story of this.

Hellen and MRE: adcVcc is 3.3V

---

firmware/controllers/actuators/idle_thread.cpp

we need to compensate ac idle output while crank-to-run is active. compressor doesn't care

fix cranking-to-run idle with AC 

---

firmware/console/binary/output_channels.txt
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/integration/rusefi_config_shared.txt
firmware/tunerstudio/tunerstudio.template.ini

I'm not good in terms, but seems this ration is not ROC.
Just a ration between last and prev injection pulse widths.

Fuel: calculate last injection pulse to previous pulse ratio

---

firmware/controllers/actuators/electronic_throttle.cpp

boardAdjustEtbTarget should be positive if boardAdjustEtbTarget() incresed ETB target.
And vise versa.
Affects only logging.

ETB: boardEtbAdjustment fix sign.

---

firmware/controllers/algo/accel_enrichment.cpp
firmware/tunerstudio/tunerstudio.template.ini

Reuse same timeout as used for Closed Loop Fuel.
Copy indicator and timeout settings to Accel Enrichment dialog.

AE: disable on tuning

---

firmware/config/boards/hellen/uaefi/board.mk
firmware/hw_layer/ports/stm32/stm32h7/cfg/mcuconf_stm32h723.h

stm32h723 is alive on uaefi.
And have some RAM for BIG LUA:
```
2025-10-03_00_15_26_321: EngineState: luaCycle 3us including luaRxTime 1us
2025-10-03_00_15_26_322: EngineState: Lua total heap(s) usage: 15029 / 180552 bytes = 8.3%
2025-10-03_00_15_26_322: EngineState: Common ChibiOS heap: 216 bytes free
2025-10-03_00_15_26_323: EngineState: ChibiOS memcore usage: 18368 / 180552
2025-10-03_00_15_26_324: EngineState: confirmation_luamemory:9
```

uaefi h7: fix for 20MHz HSE oscillator

---

unit_tests/test-framework/engine_test_helper.cpp
unit_tests/test-framework/test_executor.cpp
unit_tests/test-framework/test_executor.h

It does not depend on unitTestTaskPrecisionHack
Fixes CUSTOM_OUT_OF_ORDER_COIL in some tests.
Needs some tests fixing.
This reverts part of https://github.com/rusefi/rusefi/pull/7576/commits/ee4f4e1c81faa925e995b77b624bdc5f473ba680
@FDSoftware can you review this?
https://github.com/rusefi/rusefi/issues/7245

unit_tests: TestExecutor::executeAll always expect time in uS

---

firmware/config/boards/hellen/alphax-gold/board_configuration.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/hw_layer/board_overrides.h

related: #8631
`call_board_override` now supports args :D (and added notes on a few places where we need a minor refactor)
as always only one board migrated and next PR is the rest on individual commits

week override: OnConfigurationChange
