rusefi/rusefi

firmware/controllers/lcd_controller.cpp
win32_functional_tests/Makefile
win32_functional_tests/simulator/global.h

Just the simulator fix this time.

Fixed Posix simulator.

---

firmware/hw_layer/can_hw.cpp

Improved RX8 cluster operation - clt needle, battery and clt lamps

---

firmware/config/stm32f4ems/efifeatures.h
firmware/hw_layer/serial_over_usb/usbconsole.c

UART-DMA compile errors fix

---

firmware/config/stm32f4ems/efifeatures.h
firmware/console/binary/bluetooth.cpp
firmware/console/binary/bluetooth.h
firmware/console/binary/bluetooth_readme.txt
firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.mk
firmware/console/binary/tunerstudio_io.cpp
firmware/console/binary/tunerstudio_io.h

See firmware/console/binary/bluetooth_readme.txt

Bluetooth module setup procedure

---

firmware/controllers/core/interpolation.cpp
firmware/controllers/core/interpolation.h
firmware/controllers/idle_thread.cpp

Iac cranking running taper

---

firmware/controllers/engine_controller.cpp
firmware/controllers/engine_controller.h
firmware/controllers/idle_thread.cpp
firmware/hw_layer/adc_inputs.cpp
firmware/hw_layer/adc_inputs.h
firmware/hw_layer/stepper.cpp
firmware/hw_layer/stepper.h

Use RTC backup register to save Stepper IAC position

---

firmware/hw_layer/backup_ram.cpp
firmware/hw_layer/backup_ram.h
firmware/hw_layer/hw_layer.mk
firmware/hw_layer/stepper.cpp
firmware/hw_layer/stepper.h

 Backup NV-RAM refactor

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Please run gen_config.bat after merge to rebuild all files.

Update config files for the new features (tables) + fixes

---

firmware/hw_layer/flash.c

Tested on STM32F469 with bootloader/ST-Flasher.

Fix flash memory erase for 2Mb MCUs (2 banks)

---

firmware/controllers/math/pid.cpp
firmware/controllers/math/pid.h

See https://rusefi.com/forum/viewtopic.php?f=9&t=1315

New PID with CIC integrator

---

firmware/controllers/sensors/map.cpp

"Fixed baro correction" option using the initial MAP pressure

---

firmware/controllers/trigger/main_trigger_callback.cpp

Impl. primeInjFalloffTemperature

---

firmware/controllers/error_handling.cpp

Needed for Prometheus board with no 'printf' available.

Add an option to print errors as warnings

---

firmware/hw_layer/stepper.cpp

Fix stepper motor

---

firmware/controllers/algo/advance_map.cpp

We need all warmup corrections for fast engine startup.
Tested.

Fix advance corrections for cranking

---

firmware/console/status_loop.cpp
firmware/controllers/algo/rusefi_enums.h

We need to know the real current VE used in formulas.

Fix currentVE display

---

firmware/console/binary/tunerstudio_io.cpp

Fix UART-DMA for ChibiOS4

---

firmware/hw_layer/sensors/CJ125.cpp
firmware/hw_layer/sensors/CJ125.h

Support for CJ125 Wideband controller (alpha version)

---

firmware/controllers/algo/engine_configuration_generated_structures.h
firmware/controllers/algo/rusefi_generated.h
firmware/hw_layer/stepper.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Tested. Requested by @darxfame.
Please run gen_config.bat

Add Option: Force stepper parking every restart

---

firmware/controllers/trigger/main_trigger_callback.cpp

Check if we should skip prime inj.pulse for some reason

---

firmware/tunerstudio/rusefi.input

(recreating a new PR from scratch)

ini04 Add 'Sensor Inputs' panel

---

firmware/tunerstudio/rusefi.input

Attempt to recteate PR using "git add -p" split-staging technique...

ini05 Add 'Device Outputs' and move some pins there

---

firmware/tunerstudio/rusefi.input

There're 4 commits in this PR.
Please try to work on them independently as if it were 4 PRs (via 'git cherry-pick' or something)...
We should decide whether this approach is good for us or not.
Any feedback is strongly encouraged ;)

ini06 Remove redundant ADC inputs & Add a few gauges

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Please run gen_config.bat afterwards!

Coasting Fuel cutoff (initial)

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
unit_tests/main.cpp
unit_tests/test.mk
unit_tests/test_fuelCut.cpp
unit_tests/test_fuelCut.h

Tested.
See https://rusefi.com/forum/viewtopic.php?f=9&t=1354

Coasting Fuel Cut-off - Implementation (basic)

---

firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_structure.cpp
firmware/controllers/trigger/trigger_structure.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/test.mk
unit_tests/test_trigger_decoder.cpp
unit_tests/test_trigger_decoder.h
unit_tests/test_trigger_noiseless.cpp

Experimental function.
Partially tested on a workbench and on a real car (currently only on 60-2 wheel, but not limited to...)
Also see workbench results in attach (no filtering < 40sec, and filtering enabled on > 40 sec). An old coffee-grinder was used as an interference source :smile: 
[2018-04-21_14.10.49.msl.zip](https://github.com/rusefi/rusefi/files/1935849/2018-04-21_14.10.49.msl.zip)

Noiseless trigger decoder

---

firmware/config/boards/Prometheus/board_configuration.cpp
firmware/hw_layer/sensors/CJ125.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
java_tools/enum_to_string/src/com/rusefi/EnumToString.java

Please run gen_config.bat and merge this before other PRs.
Also contains some minor fixes (see commits below).

Prepare for TPS-based Advance and tCharge Modes + Fixes

---

firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/rusefi_types.h
firmware/controllers/core/table_helper.h

Tps-based Advance Table

---

firmware/controllers/trigger/decoders/trigger_mazda.cpp
firmware/controllers/trigger/decoders/trigger_mazda.h

tdc is 0 or 360. i put 0 in for now.

trigger fix

---

firmware/controllers/trigger/trigger_decoder.cpp
unit_tests/engine_test_helper.cpp
unit_tests/engine_test_helper.h

Affected testFasterEngineSpinningUp

Fix unit-tests (timeNowUs=0 & isInitializingTrigger)

---

firmware/console/status_loop.cpp
firmware/controllers/algo/aux_pid.cpp
firmware/controllers/algo/engine_configuration_generated_structures.h
firmware/controllers/alternatorController.cpp
firmware/controllers/electronic_throttle.cpp
firmware/controllers/idle_thread.cpp
firmware/controllers/injector_central.cpp
firmware/controllers/malfunction_indicator.cpp
firmware/controllers/sensors/tps.cpp
firmware/controllers/trigger/aux_valves.cpp
firmware/controllers/trigger/decoders/trigger_gm.cpp
firmware/controllers/trigger/decoders/trigger_honda.cpp
firmware/controllers/trigger/decoders/trigger_mitsubishi.cpp
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/decoders/trigger_universal.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/global.h
firmware/hw_layer/cdm_ion_sense.cpp
firmware/hw_layer/joystick.cpp
firmware/util/cyclic_buffer.h

make it compiled with gcc8.2 without errors.
also kill most annoying warnings

warning cleanup

---

firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/accel_enrichment.h
firmware/controllers/trigger/main_trigger_callback.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_accel_enrichment.cpp

Tested.
Please:
1) run gen_config.bat 
2) re-set broken "tle8888spiDevice" setting.

Tps-accel. fractional mode

---

firmware/hw_layer/pin_repository.cpp
firmware/hw_layer/pin_repository.h

Some modifications that later will be used during external gpio chips integration

Extgpios integration 1

---

firmware/hw_layer/drivers/drivers.mk
firmware/hw_layer/drivers/gpio/mc33972.c
firmware/hw_layer/drivers/gpio/mc33972.h
firmware/hw_layer/drivers/gpio/tle8888.c

* tle8888: fix building for stm32f765
* gpio-chips: add mc33972 driver

gpio chips

---

firmware/config/engines/custom_engine.cpp
firmware/console/binary/tunerstudio_io.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/hw_layer/smart_gpio.cpp
firmware/hw_layer/trigger_input.cpp

This should not break anything.

More config portability: TLE6240, Trigger_input, UART/Serial

---

firmware/config/boards/me7_pnp/!compile-me7_pnp.bat
firmware/config/boards/me7_pnp/board.mk
firmware/config/boards/me7_pnp/board_configuration.cpp
firmware/config/engines/me7pnp.cpp
firmware/hw_layer/can_hw.cpp
firmware/hw_layer/can_hw.h

Please check and test-compile.

Initial engine config, and cleanup.

---

firmware/config/boards/me7_pnp/board_configuration.cpp

New try !
Now I think I've got it right :-)

Fixing build

---

.gitignore
firmware/.vscode/settings.json

- gitignore vscode files
- Add vscode settings file that matches existing repo standards (tabs, mostly)

Better vscode support

---

firmware/hw_layer/drivers/gpio/core.c
firmware/hw_layer/drivers/gpio/mc33972.c
firmware/hw_layer/hardware.cpp
firmware/hw_layer/io_pins.cpp
firmware/hw_layer/pin_repository.cpp
firmware/hw_layer/smart_gpio.cpp

Looks like now no one uses getBrain_pin_e() from auto_generated_enums.cpp

Smart gpios fixes 3

---

firmware/tunerstudio/rusefi.input

TS: Spelling and clarity improvements

---

firmware/console/eficonsole.cpp

`threadinfo` command now spits out stack base, stack free (in bytes), and ticks consumed by the thread.  Stack free space is included for the dedicated interrupt stack.
Here's some example data:
The learning is that `SingleTimerExecutor::scheduleForLater` goes _very_ deep, but the compiler inlines it to hell and back with `-O2` turned on (the giveaway here is that the only thing the servo thread does is schedule stuff, yet it uses a bunch of stack).

Fix threadinfo command #695

---

firmware/console/binary/tunerstudio.cpp
firmware/controllers/injector_central.cpp
firmware/tunerstudio/rusefi.input

MRE doesn't have a hardware reset button.
So now there's one in tunerstudio!
Also, eliminate the pesky degree symbols in the TS ini.

Add "Reset ECU" button

---

firmware/config/stm32f7ems/efifeatures.h
firmware/global.h

It's like the CCM on the f4, but with more f7

Enable DTCM

---

firmware/hw_layer/can_hw.cpp

Add per-MCU (f4 vs f7) CAN settings

---

firmware/bootloader/src/Makefile
firmware/config/engines/custom_engine.cpp
firmware/config/engines/me7pnp.cpp

It seems the bootloader has been broken for a while... So we fix it too!

Small fix for simulator + bootloader

---

firmware/config/engines/custom_engine.cpp
firmware/config/engines/me7pnp.cpp

Hide hardware-specific TLE8888_PIN_* settings under #if (BOARD_TLE8888_COUNT > 0)

Use BOARD_TLE8888_COUNT for more compatibility

---

firmware/hw_layer/drivers/gpio/tle8888.c

As tle8888 suposed to be reset master and reset MCU there is no
flag showing POR reset. So try to poll OE bit.

TLE8888: track reset event by cleared OE bit in status register

---

firmware/.vscode/settings.json

Prevent build products from showing up in vscode file browser/search

vscode usability

---

firmware/console/binary/tunerstudio_configuration.h
firmware/console/status_loop.cpp

We already had a field for it - and the math to do it.  There's even a gauge!

hook up rpm acceleration

---

firmware/util/efilib.cpp

fix ltoa_internal: fix #948

---

firmware/controllers/sensors/sensor.cpp
unit_tests/tests/sensor/mock_sensor.cpp

Actually really reset the registry when you ask it to.

Fix sensor mocking bug

---

firmware/controllers/actuators/alternator_controller.cpp
firmware/controllers/engine_controller.cpp
firmware/util/math/pid.cpp
firmware/util/math/pid.h
unit_tests/tests/test_pid.cpp

_A PID with derivative filtering (backward differences) and integrator anti-windup.
See: Wittenmark B., Astrom K., Arzen K. IFAC Professional Brief. Computer Control: An Overview. 
Two additional parameters used: derivativeFilterLoss and antiwindupFreq
(If both are 0, then this controller is identical to PidParallelController)_
Meaningful unit-tests included!

Industrial PID Controller

---

firmware/config/boards/kinetis/chconf.h
firmware/config/stm32f4ems/chconf.h

Fix f4 and kinetis.  We have 3 identical chconf files, which is great.

Fix f4/kinetis

---

firmware/console/binary/tunerstudio.cpp
firmware/development/perf_trace.cpp

- make TS commands work
- fix issue with tracing interrupt entry/exits that can stomp another entry

perf tracing fixes

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/system/dc_motor.cpp
firmware/controllers/system/dc_motor.h

- extract full interface
- forward declarations
- conform names `toThisCasing`

DC motor improvements

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h

Working towards testability of electronic throttle.

inject interfaces to ETB, renaming

---

firmware/controllers/actuators/aux_pid.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/core/fsio_impl.h
firmware/controllers/settings.cpp
firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h
firmware/controllers/system_fsio.h
firmware/controllers/system_fsio.txt
firmware/hw_layer/hardware.cpp
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_logic_expression.cpp

Hardcoded FSIO was tested on Kinetis.

Starter relay + Hardcoded 'FSIO' + simulator fix

---

firmware/console/status_loop.cpp

lcd thread name

---

firmware/controllers/sensors/converters/func_chain.h
firmware/controllers/sensors/converters/resistance_func.cpp
firmware/controllers/sensors/converters/resistance_func.h
firmware/controllers/sensors/converters/thermistor_func.cpp
firmware/controllers/sensors/converters/thermistor_func.h
firmware/controllers/sensors/sensors.mk
unit_tests/tests/sensor/func_chain.cpp
unit_tests/tests/sensor/resist_func.cpp
unit_tests/tests/sensor/therm_func.cpp
unit_tests/tests/tests.mk

Adds:
- Resistance function (converts voltage -> resistance)
- Thermistor function (converts resistance -> temperature)
- Function chain (composites together functions into one function)
- Tests for the above

Add new sensor function types

---

firmware/config/boards/kinetis/config/controllers/algo/rusefi_generated.h
firmware/console/binary/tunerstudio_configuration.h
firmware/console/binary/tunerstudio_debug_struct.h
firmware/console/status_loop.cpp
firmware/controllers/generated/rusefi_generated.h
firmware/hw_layer/drivers/gpio/tle8888.c
firmware/hw_layer/drivers/gpio/tle8888.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
java_console/io/src/com/rusefi/binaryprotocol/BinaryProtocol.java
java_console/models/src/com/rusefi/config/FieldType.java
java_console/models/src/com/rusefi/core/Sensor.java

Second try at #1069 , now with more Java!
~~I'm currently unable to build the console, but I _think_ this is at least close.~~ edit: console now builds, seems to work okay with the new scaling!

DRAFT Shrink output channels, again

---

firmware/gen_config.sh
firmware/gen_config_board.sh
firmware/gen_enum_to_string.sh

scripts: add scripts for linux

---

firmware/hw_layer/stepper.cpp
firmware/hw_layer/stepper.h

also use c++ in-header initialization for its state

Convert stepper to use ThreadController

---

firmware/controllers/sensors/sensors.mk

makefile spelling

---

firmware/tunerstudio/rusefi.input

binary data were correct, ts displayed wrong

fix signed ignition timing

---

firmware/tunerstudio/rusefi.input

percents are signed in the firmware, they should be in TS as well

more signed vs. unsigned ts channels

---

firmware/controllers/actuators/boost_control.cpp

- Fix the formatting mess
- Don't enable controller if boost control pin isn't set
- For some reason it didn't compile for me anyway (fixed now)

boost format & cleanup

---

lgtm.yml

This file allows LGTM to successfully compile and analyze the c/c++ part of the project
Test result can be seen here: https://lgtm.com/projects/g/fpoussin/rusefi-lgtm/?mode=tree
Final result will be here: https://lgtm.com/projects/g/rusefi/rusefi/ (no c/c++ analysis until this is merged)
Badges can be added as well in a following PR: [![Total alerts](https://img.shields.io/lgtm/alerts/g/rusefi/rusefi.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/rusefi/rusefi/alerts/)

LGTM configuration file

---

firmware/hw_layer/ports/stm32/flash.c

add DSB to flash write on Cortex-M7

---

firmware/console/status_loop.cpp
firmware/controllers/sensors/map.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/development/logic_analyzer.cpp
firmware/hw_layer/digital_input_icu.cpp
firmware/hw_layer/digital_input_icu.h
firmware/hw_layer/trigger_input_icu.cpp
firmware/hw_layer/vehicle_speed.cpp

fix icu trigger polarity

---

firmware/tunerstudio/rusefi.input

Part of #1121 / #1088.
Stepper HW page now looks like this:

Improve dual hbridge idle UI

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Multispark configuration

---

firmware/controllers/can/can.h
firmware/controllers/sensors/tps.cpp

Also only return pedal position if we have an ADC channel set.

Grow CAN TX stack

---

firmware/console/binary/tunerstudio_configuration.h
firmware/console/status_loop.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/sensors/converters/linear_func.cpp
firmware/controllers/sensors/converters/linear_func.h
firmware/controllers/sensors/sensor_type.h
firmware/init/sensor/init_tps.cpp
firmware/tunerstudio/rusefi.input

Compute pedal position with new sensors, and consume in TS

Accelerator pedal with new sensors

---

firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/engine_parts.h
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/map_averaging.cpp
firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/development/perf_trace.h
firmware/hw_layer/hip9011.cpp

This is fully replaced by perf tracing.  Added a few new trace events added to cover the ones we didn't have.

Remove old monitoring timestamps

---

firmware/controllers/actuators/aux_pid.cpp
firmware/controllers/actuators/boost_control.cpp
firmware/controllers/actuators/dc_motors.cpp
firmware/controllers/actuators/pwm_tester.cpp
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.h
firmware/hw_layer/pwm_generator.h

This makes no difference to the compiled binary, btw.

Default to applyPinState

---

firmware/controllers/algo/engine_parts.h
firmware/controllers/algo/engine_state.h
firmware/controllers/generated/engine_state_generated.h
firmware/integration/engine_state.txt

un-generate multispark

---

firmware/controllers/algo/advance_map.cpp

only correct timing in dynamic mode

---

firmware/controllers/sensors/redundant_sensor.cpp
firmware/controllers/sensors/redundant_sensor.h
firmware/controllers/sensors/sensor_info_printing.cpp
firmware/controllers/sensors/sensors.mk
unit_tests/tests/sensor/redundant.cpp
unit_tests/tests/tests.mk

Add redundant sensor

---

firmware/controllers/can/can_dash.cpp
firmware/hw_layer/drivers/can/can_hw.cpp
firmware/hw_layer/drivers/can/can_hw.h

Switch dash code over to new CAN stuff, fixes #1183 .
Also saves ~100 bytes of flash, so that's good too.

switch dash to new CAN class

---

firmware/controllers/actuators/electronic_throttle.cpp

https://www.youtube.com/watch?v=9A4M3X57PCI

fix electronic throttle RPM rounding

---

firmware/util/math/deadband.h
unit_tests/tests/test_deadband.cpp
unit_tests/tests/tests.mk

Helper for improved closed loop fueling (coming soon™)

Deadband helper & tests

---

firmware/controllers/actuators/electronic_throttle.cpp

use `copyArray` and struct initialization instead of hand initializing everything

simplify etb defaults

---

firmware/config/boards/kinetis/config/controllers/algo/engine_configuration_generated_structures.h
firmware/config/boards/microrusefi/board_configuration.cpp
firmware/config/boards/proteus/board_configuration.cpp
firmware/config/engines/custom_engine.cpp
firmware/config/engines/me7pnp.cpp
firmware/controllers/actuators/dc_motors.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/generated/engine_configuration_generated_structures.h
firmware/controllers/system/dc_motor.cpp
firmware/controllers/system/dc_motor.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

all the ETB driver chips we currently use have a DIS pin - let's support it natively

support ETB disable pin

---

firmware/hw_layer/mc33816.cpp

mc33816 driven to high, and a few additional checks

---

firmware/config/boards/kinetis/config/controllers/algo/auto_generated_enums.cpp
firmware/controllers/algo/auto_generated_enums.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/controllers/can/can_dash.cpp
firmware/controllers/can/can_dash.h
firmware/controllers/can/can_tx.cpp

added CanDash support for w202

Add w202 canDash support

---

firmware/integration/rusefi_config.txt

Only requires 24 bytes of config.

Add config for new closed loop

---

firmware/hw_layer/mc33816.cpp

mc33 flash check, tested against incorrect data code ram in both channels

mc33 flash check

---

firmware/hw_layer/mc33816.cpp
firmware/hw_layer/mc33816_memory_map.h

includes read+write into dram, with initial offsets, and an update Vboost function

MC33816 dram update

---

firmware/hw_layer/mc33816.cpp

verified to work w/ console commands on setting and rebooting hte MC33 chip

DI HV sanity checks

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

The first step in adding Auxilary Serial sensor support. Mainly for Innovate LC-2 wideband controller, at least for now.

Aux Serial config files

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h
firmware/controllers/actuators/idle_thread.cpp
unit_tests/mocks.h
unit_tests/tests/test_etb.cpp

- Move mocks to their own header
- Inject idle position to ETB
- Test ETB idle control math

Inject idle to ETB

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/can/can_rx.cpp
firmware/controllers/can/can_vss.cpp
firmware/controllers/can/can_vss.h
firmware/controllers/controllers.mk
firmware/controllers/settings.cpp
firmware/hw_layer/drivers/can/can_hw.h
firmware/hw_layer/hardware.cpp
firmware/hw_layer/vehicle_speed.cpp

Working for BMW e46.
Can i get a review?

Vss over Can implementation proposal

---

firmware/controllers/algo/obd_error_codes.h
firmware/controllers/can/can_vss.cpp
firmware/hw_layer/vehicle_speed.cpp

small fixes + w202 implementation.
Fixes #1344

Can vss updates

---

firmware/controllers/can/can_dash.cpp
firmware/integration/rusefi_config.txt

- corrected RPM sandiness
- corrected TS enum since no name was shown there

can_dash fix for w202 + TS enum

---

firmware/tunerstudio/rusefi.input

improve etb & pedal dialogs

---

firmware/config/engines/custom_engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/bench_test.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/settings.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Fixes #897.  Now a button instead of a setting.

don't store self stim in config

---

unit_tests/tests/test_etb.cpp

Confirm PID is functioning properly

Test ETB closed loop

---

firmware/config/stm32f4ems/efifeatures.h
firmware/controllers/engine_controller.cpp

turn off unused features

---

firmware/config/boards/kinetis/chconf.h
firmware/config/chconf_common.h
firmware/config/stm32f4ems/chconf.h
firmware/config/stm32f7ems/chconf.h
firmware/controllers/engine_controller_misc.cpp

move hooks in to common chconf.h

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Add raw gauges to sensor config pages

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
unit_tests/tests/test_fuel_math.cpp
unit_tests/tests/tests.mk

progress toward #1299 
@OrchardPerformance fyi

pull out std air charge math

---

firmware/controllers/system/thread_controller.h

don't fail on multiple start calls

---

firmware/controllers/math/closed_loop_fuel.cpp
firmware/controllers/math/closed_loop_fuel.h
firmware/controllers/math/math.mk
firmware/integration/rusefi_config.txt
firmware/util/math/deadband.h
unit_tests/tests/test_stft.cpp

short term fuel trim: part 2

---

firmware/hw_layer/drivers/gpio/core.c
firmware/hw_layer/drivers/gpio/gpio_ext.h
firmware/hw_layer/drivers/gpio/tle8888.c

PP code is hidden inder #if 0, so it should not creak anything.
Diagnostic code tested.
Looks safe.

Tle8888 stage 1

---

firmware/hw_layer/drivers/gpio/tle8888.c
firmware/hw_layer/drivers/gpio/tle8888.h
firmware/hw_layer/smart_gpio.cpp

tle8888: on MRE 0.5.0 we can drive ING_EN and INJ_EN from STM

---

firmware/console/status_loop.cpp
firmware/controllers/system/efi_gpio.cpp
firmware/util/datalogging.cpp
firmware/util/datalogging.h

dead datalog code

---

firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/rtc_helper.cpp

now formats like this:
`rusefi_yymmdd_hhmmss.mlv`

improve SD log file naming

---

firmware/config/stm32f4ems/mcuconf.h
firmware/config/stm32f7ems/mcuconf.h
firmware/hw_layer/digital_input_icu.cpp

free up timers for hardware PWM

---

firmware/controllers/engine_cycle/main_trigger_callback.cpp

as suggested by the comment, this doesn't need a warning

---

firmware/console/status_loop.cpp

redundant TPS & pedal broke a few gauges, this fixes them

fix raw channels

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

- remove unused config fields
- correct stft gauge units

Post-stft cleanup

---

firmware/clean.bat
firmware/clean.sh
firmware/clean_compile_two_versions.bat
firmware/clean_compile_two_versions.sh
firmware/update_version.bat
firmware/update_version.sh

Converting scripts from the firmware directory. (not sub-directories yet)

Convert scripts firmware

---

firmware/update_version.sh

fix git command

---

firmware/config/boards/kinetis/config/!gen_config.bat
firmware/config/boards/kinetis/config/gen_config.sh
firmware/gen_config.sh
firmware/gen_config_board.sh
java_tools/configuration_definition/src/com/rusefi/ConfigDefinition.java

This is a workaround for the gen_config timestamp issue.
Please recompile the ConfigDefinition.jar.

gen_config cache

---

firmware/gen_live_documentation.sh
firmware/tunerstudio/cache/engine_state.txt
firmware/tunerstudio/cache/pid_state.txt
firmware/tunerstudio/cache/trigger_central.txt
firmware/tunerstudio/cache/trigger_state.txt
firmware/tunerstudio/cache/wall_fuel_state.txt
java_tools/configuration_definition/src/com/rusefi/ConfigDefinition.java

Please rebuild ConfigDefinition.jar

gen_live_documentation cache

---

firmware/gen_signature.sh

I don't know if github's bash supports this fix...
So if it fails on github, please revert it.

gen_signature fix attempt

---

firmware/gen_signature.sh

https://github.com/rusefi/rusefi/issues/1549

fix signature

---

firmware/console/status_loop.cpp
firmware/controllers/algo/engine_state.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/math/engine_math.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

hook up the new load fields for split fuel/ignition loads, progress on #1299

plumb new load channels

---

firmware/controllers/core/error_handling.cpp

guard perf track lock hooks

---

firmware/controllers/math/engine_math.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

correct batch fuel cylinder pairing

---

misc/jenkins/compile_other_versions/prepare_bundle.sh

Fix Bundles

---

firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/system/efi_gpio.h

encapsulate injector logic

---

unit_tests/tests/sensor/func_sensor.cpp
unit_tests/tests/sensor/mock/mock_sensor.h
unit_tests/tests/tests.mk

fix test ordering issues

---

.github/workflows/build-firmware.yaml

Upload build artifacts

---

firmware/console/binary/tunerstudio.cpp
firmware/console/status_loop.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/event_registry.h
firmware/controllers/engine_controller.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
unit_tests/tests/test_fuel_wall_wetting.cpp

minor refactor.  fewer "parallel arrays" with the same length = better

put wall wetting inside InjectionEvent

---

unit_tests/tests/ignition_injection/injection_mode_transition.cpp

actually test for stuck injector

improve 1592 test

---

unit_tests/engine_test_helper.cpp
unit_tests/engine_test_helper.h
unit_tests/tests/ignition_injection/injection_mode_transition.cpp
unit_tests/tests/ignition_injection/test_dwell_corner_case_issue_796.cpp

automagically export logicdata file for every test

Export logicdata on all tests

---

firmware/controllers/actuators/idle_thread.cpp

This patch was tested **unsuccessfully** on the real car.
And this is the same patch (hopefully) but for the [older firmware version](https://github.com/rusefi/rusefi/commit/7735758ec5c18c4ff6ddcecef87db241d0e55953), which was reportedly successful:
[older_firmware_successful_patch.patch.zip](https://github.com/rusefi/rusefi/files/4960966/older_firmware_successful_patch.patch.zip)

[DRAFT] Idle PID improvements

---

firmware/console/status_loop.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_state.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
firmware/util/containers/table_helper.h

Use ignition load for ignition

---

firmware/console/status_loop.cpp
firmware/controllers/algo/airmass/speed_density_base.cpp
firmware/controllers/algo/airmass/speed_density_base.h
firmware/controllers/algo/algo.mk
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/math/speed_density.cpp
firmware/controllers/math/speed_density.h
unit_tests/tests/test_engine_math.cpp
unit_tests/tests/test_fuel_map.cpp
unit_tests/tests/test_fuel_math.cpp
unit_tests/tests/test_speed_density.cpp

yet more #1299 progress
Pulls out a base for speed density to be used by both real SD and alpha-n

start refactor for airmass-based alpha-n

---

firmware/config/boards/kinetis/config/controllers/algo/auto_generated_enums.cpp
firmware/controllers/actuators/gppwm/gppwm_channel.cpp
firmware/controllers/algo/auto_generated_enums.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

as suggested in #1490, good idea @stefanst!

Add fuel/ign load as gppwm axes

---

firmware/controllers/bench_test.cpp

fix @Abricosvw's issue with stuck gain after running ETB auto calibrate

clear cal mode upon leaving ETB autocal

---

firmware/tunerstudio/rusefi.input

split out CAN and SD from the gigantic connection dialog

break up connection TS dialog

---

.github/workflows/gen-diffs.yaml
hardware/generate_diffs.sh

Kicad diff action

---

hardware/generate_diffs.sh

Are there any other details I'm missing?

Add documentation to kicad diffs script

---

firmware/tunerstudio/rusefi.input

"enable injection" was impossible to reach if you disabled injection

fix injection enable

---

firmware/console/binary/tunerstudio_outputs.h
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/bench_test.cpp
firmware/tunerstudio/rusefi.input

Auto cal dual etb

---

firmware/controllers/sensors/converters/linear_func.cpp
firmware/controllers/sensors/converters/resistance_func.cpp
firmware/controllers/sensors/converters/thermistor_func.cpp
firmware/controllers/sensors/sensor_info_printing.cpp

consolidate sensor info printing to one place

---

firmware/console/status_loop.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/engine_controller.cpp
firmware/controllers/engine_controller_misc.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/engine_cycle/rpm_calculator.h
firmware/controllers/math/closed_loop_fuel.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/sensors/sensor_info_printing.cpp
firmware/controllers/sensors/stored_value_sensor.h
firmware/hw_layer/sensors/cj125.cpp
firmware/hw_layer/stepper.cpp
unit_tests/tests/test_accel_enrichment.cpp
unit_tests/tests/test_fuel_wall_wetting.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

- Don't register sensors over and over again
- Implement sensor info print for RPM sensor
- Inject engine/config in to RpmCalculator

fix broken master, inject engine ptr to rpmcalculator

---

firmware/controllers/algo/rusefi_types.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

- allow higher knock frequency (now 20khz max)
- Boost table scaling & names

minor TS changes

---

firmware/integration/rusefi_config.txt

remove ign tps bins

---

firmware/config/boards/hellen/cypress/!compile-cypress.bat
firmware/config/boards/hellen/cypress/compile-cypress.sh

The build is failing at this point, but I don't think it's the fault of the script.

Cypress script

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor_type.h
firmware/hw_layer/adc/adc_inputs.cpp
firmware/init/sensor/init_tps.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

progress on #1784, moving away from the TPS2 hack currently in place for idle control

Dedicated sensors for wastegate + idle position

---

firmware/controllers/can/can_vss.cpp

update vss reading from can, small update to read it correctly, now  vss is spot on :D

Update can_vss.cpp for w202

---

firmware/controllers/core/error_handling.cpp

print firmware errors in unit tests in red

---

firmware/controllers/core/fsio_impl.cpp

missing iat from fsio

---

firmware/controllers/system/timer/event_queue.cpp
firmware/controllers/system/timer/event_queue.h
firmware/controllers/system/timer/single_timer_executor.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/hw_layer/microsecond_timer.cpp
unit_tests/tests/test_signal_executor.cpp

Compilers are bad at optimizing around magic numbers.

use expected for event queue next event

---

firmware/controllers/algo/engine.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/controllers/trigger/trigger_emulator_algo.h
firmware/controllers/trigger/trigger_simulator.cpp
firmware/controllers/trigger/trigger_simulator.h
unit_tests/tests/trigger/test_trigger_decoder.cpp

almost entirely a find-replace of pointer -> ref, `const` as appropriate

const ref-ify trigger

---

firmware/controllers/algo/fuel/fuel_computer.cpp
firmware/controllers/algo/fuel/fuel_computer.h
firmware/controllers/algo/fuel_math.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

ign load axis override

---

firmware/console/status_loop.cpp
firmware/console/status_loop.h
firmware/controllers/engine_controller.cpp
firmware/hw_layer/mmc_card.cpp
firmware/hw_layer/mmc_card.h

on the quest to use less memory for SD card

start using BufferedWriter

---

firmware/controllers/actuators/electronic_throttle.cpp
unit_tests/tests/test_etb.cpp

progress on #1784, hopefully, if hardware CI is happy about it...

etb function config 1

---

firmware/console/binary_log/binary_logging.cpp
firmware/console/binary_log/binary_logging.h
firmware/console/binary_log/log_field.cpp
firmware/console/binary_log/log_field.h
firmware/console/status_loop.cpp
firmware/controllers/engine_controller.cpp
unit_tests/tests/test_binary_log.cpp

write SD header using new Writer class

---

firmware/controllers/actuators/electronic_throttle.cpp

more safe parts probably

---

firmware/controllers/actuators/boost_control.cpp
firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h
firmware/controllers/algo/engine.h
unit_tests/mocks.h
unit_tests/tests/test_boost.cpp
unit_tests/tests/test_etb.cpp

plumbing up ETB wastegate control, should be pretty close to working...
#1784 to make Nik happy so he fixes Andrey's BMW v12

Etb wastegate hookup

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor_type.h
firmware/init/sensor/init_fluid_pressure.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Mux either the HP or LP sensor, selectable which one the injectors are located on.  GDI cars pick high, everybody else pick low.

add Injector pressure sensor

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/fuel/injector_model.cpp
firmware/controllers/algo/fuel/injector_model.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
firmware/controllers/gauges/lcd_controller.cpp
unit_tests/tests/test_fuel_map.cpp

Fuel model was implemented, but not actually called. Progress for #1448, as the `InjectorModel` will handle variable fuel pressure.

use fuel model

---

firmware/controllers/algo/fuel_math.cpp
unit_tests/tests/test_fuel_math.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp

temporary fix for #1903 until the correct structural changes can happen

fix double deadtime

---

firmware/hw_layer/hardware.cpp

chibios already has a mutex, no reason to add our own.

use per-device SPI mutex

---

firmware/config/boards/microrusefi/mapping.yaml

fix MRE digital input mapping

---

firmware/controllers/algo/fuel_math.cpp

I removed this check because I thought I'd covered this case, but evidently not

probably fix hardware ci

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/binary_log/binary_logging.cpp
firmware/console/status_loop.cpp
firmware/controllers/algo/engine_state.h
firmware/controllers/algo/fuel/fuel_computer.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

log both, because recalibrating the brain is hard

log afr in addition to lambda

---

java_tools/configuration_definition/src/com/rusefi/ConfigField.java
java_tools/configuration_definition/src/com/rusefi/ConfigStructure.java
java_tools/configuration_definition/src/com/rusefi/ReaderState.java
java_tools/configuration_definition/src/com/rusefi/output/JavaFieldsConsumer.java
java_tools/configuration_definition/src/com/rusefi/output/TSProjectConsumer.java

Please rebuild ConfigDefinition.jar

Add #if/#else/#endif support to gen_config

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Make AFR great again!

---

java_console/inifile/src/main/java/com/opensr5/ini/IniFileModel.java
java_console/inifile/src/main/java/com/opensr5/ini/RawIniFile.java
java_console/inifile/src/test/java/com/opensr5/ini/test/IniFileReaderTest.java

Add directives support to Console .INI parser

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_io.cpp
firmware/console/binary/tunerstudio_io.h

fix large response packets

---

firmware/CHANGELOG.md
firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_io.cpp
unit_tests/tests/test_tunerstudio.cpp

fix the mess from #1944 and #1947

Fix crc again, for real this time

---

firmware/controllers/actuators/dc_motors.cpp
firmware/controllers/actuators/idle_hardware.cpp
firmware/controllers/engine_controller_misc.cpp
firmware/controllers/engine_cycle/spark_logic.cpp

- only start DC motor and idle PWM if actually needed
- do time-sensitive stuff (ign, inj) before associated logging whose jitter/delay matters less

minor perf tweaks

---

.github/workflows/build-firmware.yaml

new way of setting env vars per: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

fix actions

---

.github/workflows/build-firmware.yaml
.github/workflows/gen-configs.yaml
.github/workflows/gen-diffs.yaml
.github/workflows/gen-docs.yaml

more gh action fixing

---

firmware/controllers/system/timer/single_timer_executor.cpp
firmware/hw_layer/hw_layer.mk
firmware/hw_layer/microsecond_timer.h
firmware/hw_layer/microsecond_timer_gpt.cpp

adjust the api to enable the magic in https://rusefi.com/forum/viewtopic.php?p=38501#p38501

adjust microsecond_timer api

---

firmware/controllers/actuators/dc_motors.cpp

broke ETB PWM.
will PR this properly later, just reverting for now

partial undo 1946

---

firmware/controllers/algo/launch_control.cpp
firmware/controllers/algo/launch_control.h
unit_tests/tests/test_launch.cpp
unit_tests/tests/tests.mk

Launch control testable

---

firmware/config/boards/hellen/cypress/rusefi_hw_enums.h
firmware/config/boards/kinetis/rusefi_hw_enums.h
firmware/controllers/algo/rusefi_hw_enums.h
firmware/hw_layer/adc/AdcConfiguration.h
firmware/hw_layer/adc/adc_inputs.cpp

-use enums
-internalAdcIndexByHardwareIndex array should be adc_channel_e size
-add sanity checks
-save few bytes of RAM

ADC: fixes:

---

firmware/controllers/actuators/boost_control.cpp

improve boost control defaults, improve boost init sequence

---

firmware/console/console_io.cpp
firmware/console/status_loop.cpp
firmware/controllers/engine_controller_misc.cpp
firmware/controllers/gauges/lcd_controller.cpp
firmware/controllers/sensors/function_pointer_sensor.h
firmware/controllers/sensors/sensor_info_printing.cpp
firmware/controllers/sensors/software_knock.cpp
firmware/controllers/simple_tcu.cpp
firmware/hw_layer/hardware.cpp
firmware/hw_layer/lcd/lcd_HD44780.cpp
firmware/hw_layer/mc33816.cpp

mostly unused parameters and variables

squash warnings

---

firmware/controllers/actuators/boost_control.cpp
unit_tests/tests/test_boost.cpp

was using duty [0, 1], should've used percent [0, 100]

fix etb wastegate percent output

---

firmware/tunerstudio/rusefi.input

disable legacy temp units

---

firmware/tunerstudio/rusefi.input

vssacceleration should be signed 16bit value

fix vssAcceleration sign

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/tunerstudio/rusefi.input

add indicator for tps2 failure

---

firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor.h
firmware/init/sensor/init_sensors.cpp

go the other direction from #2013: encapsulate more logic instead of semi-dangerous setters

encapsulate sensor entry logic

---

unit_tests/tests/test_etb.cpp

Everybody loves test coverage!

more ETB test coverage

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.h
firmware/console/binary/tunerstudio_impl.h
firmware/console/binary/tunerstudio_io.h

start pulling stuff up in to a class so we can mock out hardware-dependent behaviors

start making TS protocol testable

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle.h
firmware/controllers/actuators/electronic_throttle_impl.h
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor.h
unit_tests/mocks.h
unit_tests/tests/test_etb.cpp

require redundant TPS for ETB

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

- Configurations needed for base noise
- TS usability for base noise definition

Prepare configurations for SW knock detection

---

firmware/console/binary/tunerstudio_outputs.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

config for second lambda

---

firmware/controllers/engine_controller_misc.cpp
firmware/hw_layer/io_pins.cpp
firmware/hw_layer/io_pins.h
unit_tests/engine_test_helper.cpp
unit_tests/engine_test_helper.h

fix mock pins array

---

firmware/CHANGELOG.md
firmware/controllers/algo/engine.h
firmware/controllers/algo/nmea.c
firmware/controllers/engine_cycle/spark_logic.h
firmware/controllers/global_shared.h
firmware/controllers/sensors/sensor.h
firmware/controllers/trigger/trigger_central.cpp
firmware/global.h
firmware/util/os_util.c
firmware/util/os_util.h
unit_tests/Makefile
unit_tests/engine_test_helper.cpp
unit_tests/mocks.h

clang warnings again

---

firmware/controllers/gear_controller.cpp
firmware/controllers/gear_controller.h

add param sig

---

firmware/hw_layer/drivers/can/can_msg_tx.cpp
firmware/hw_layer/drivers/can/can_msg_tx.h

@shadowm60 might need this too for Haltech dash work

add support for extended CAN ids

---

.github/workflows/build-unit-tests.yaml
unit_tests/.gitignore

Trigger action

---

firmware/controllers/core/fsio_core.cpp
unit_tests/tests/test_logic_expression.cpp

test for invalid fsio

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine.h
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/engine_configuration.h
unit_tests/tests/test_idle_controller.cpp

100% idle test coverage would be great, so here we are

testable idle controller part 1

---

firmware/controllers/actuators/aux_pid.cpp
firmware/controllers/algo/engine.h
firmware/controllers/engine_controller.h
firmware/controllers/engine_controller_misc.cpp
firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/hw_layer/io_pins.cpp
firmware/hw_layer/io_pins.h
firmware/hw_layer/sensors/hip9011.cpp
unit_tests/engine_test_helper.cpp
unit_tests/tests/test_gpio.cpp
unit_tests/tests/tests.mk

gpio unit tests

---

firmware/controllers/algo/engine.h
firmware/controllers/math/engine_math.cpp
firmware/controllers/settings.cpp

fix changing ignition modes without reboot

---

java_console/autotest/src/com/rusefi/FunctionalTest.java

HW CI test switching ignition modes

---

firmware/hw_layer/debounce.cpp
firmware/hw_layer/debounce.h

don't name all buttons `button`, use the passed name

actually use button name

---

unit_tests/tests/test_tacho.cpp

fix tach test 2130

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
unit_tests/tests/test_idle_controller.cpp

logic to detect driver intent about whether we're idling or not
progress on #1263

more testable idle logic

---

java_console/autotest/src/com/rusefi/FunctionalTest.java

explicitly test the rev limiter in hardware CI

HW CI: rev limiter

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
unit_tests/tests/test_idle_controller.cpp

more progress on testable idle, will start integration soon

Idle refactor open loop

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Roughly sort the idle UI in priority order, clarifying some labels:

update idle UI

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

config for multiple fuel corr banks

---

.github/workflows/build-unit-tests.yaml

Unit tests on mac with clang

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/binary_log/binary_logging.cpp
firmware/console/status_loop.cpp
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor_type.h
firmware/init/init.h
firmware/init/init.mk
firmware/init/sensor/init_flex.cpp
firmware/init/sensor/init_sensors.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

- add sensor type
- add input pin config
- add TS output channel & logging
- log flex % to SD
progress on #540

Flex fuel stubs

---

firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/fuel/fuel_computer.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/ignition_injection/test_fuel_computer.cpp

interpolate stoichiometric ratio as flex % changes
#540 and #1299

flex fuel AFR interpolation

---

firmware/controllers/bench_test.cpp
firmware/integration/rusefi_config.txt

also complain with a fatal if we get a bench test request we didn't understand
fix #2196

Fix fan bench

---

firmware/controllers/sensors/converters/thermistor_func.cpp
firmware/init/sensor/init_thermistors.cpp

- check that thermistor config is actually valid (decreasing order resistance, increasing order temperature)
- check that resolved temperature is reasonable

better error checking of thermistor config

---

firmware/init/sensor/init_thermistors.cpp
java_console/autotest/src/com/rusefi/functional_tests/TestHelper.java

- fix the fatal error caused by #2199 
- print out the fatal error in the exception assertion message for HW CI

Fix master fatal error

---

.vscode/settings.json

ignore chibios demos folder in searches

adjust vscode settings

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Prep work to introduce biquad filter on vss input to reduce noise on logs and for dynoview as well

Vss filter configuration field and param

---

java_console/autotest/src/com/rusefi/FunctionalTest.java

maybe fix protege HW CI

---

firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h

save memory in trigger structure

---

.github/workflows/gen-docs.yaml
firmware/config/boards/hellen/hellen128/connectors/main.yaml
misc/jenkins/generate_doxygen/gen_upload_docs.sh
misc/pinout-gen/script.js
misc/pinout-gen/style.css

1. It was broken, now it works (I think)
2. Now it automatically finds connectors/*.yaml files, so gen_upload_docs.sh won't have to be edited every time a new connector/board is added.
3. Table rows can now be clicked on to select the row
4. Cursor is changed to pointer for clickable things
5. Row hover highlight issue fixed
6. Works on  first load, as it should

Pinouts Improvements

---

firmware/controllers/algo/rusefi_enums.h
firmware/controllers/sensors/map.cpp
firmware/integration/rusefi_config.txt

GM Map Sensors 
Data from http://www.robietherobot.com/storm/mapsensor.htm

Gm map sensors

---

java_console/autotest/src/com/rusefi/RealHardwareTestLauncher.java
java_console/autotest/src/com/rusefi/RusefiTestBase.java
java_console/autotest/src/com/rusefi/common/CommonFunctionalTest.java
java_console/autotest/src/com/rusefi/common/MiscTest.java
java_console/autotest/src/com/rusefi/f4discovery/HighRevTest.java
java_console/autotest/src/com/rusefi/f4discovery/PwmHardwareTest.java
java_console/autotest/src/com/rusefi/f4discovery/VssHardwareLoopTest.java
java_console/autotest/src/com/rusefi/proteus/ProteusAnalogTest.java
java_console/build.xml

partition HW tests per-board
adds ant target for `hardware_ci_proteus`

Partition hw tests

---

misc/jenkins/generate_doxygen/gen_upload_docs.sh

Adding the -m flag to ncftpput to create directories if necessary
Also replaced -v which is completely pointless for our uses

Fix pinouts maybe

---

.github/workflows/gen-docs.yaml
misc/jenkins/generate_doxygen/gen_upload_docs.sh

Because this is run in cron, I think that the event will never be 'push'.

Remove Push requirement from gen docs

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/idle_hardware.cpp
firmware/controllers/trigger/trigger_central.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

add option to disable ETB if engine not spinning

---

.github/workflows/gen-docs.yaml
firmware/Doxyfile

1: exclude ChibiOS and Cypress dirs
2: install graphviz

Fix doxygen

---

firmware/config/boards/skeleton/efifeatures.h
firmware/console/status_loop.cpp
firmware/controllers/core/error_handling.cpp
firmware/controllers/system/efi_gpio.cpp
firmware/hw_layer/adc/AdcConfiguration.h
firmware/hw_layer/drivers/gpio/mc33810.c
firmware/hw_layer/ports/stm32/stm32f4/mpu_util.cpp
firmware/hw_layer/ports/stm32/stm32f7/mpu_util.cpp

This is set of patches for common code that I need before adding my board support.

Some fixes prior to board pull request

---

.github/workflows/gen-docs.yaml
.github/workflows/gen-ibom.yaml
.github/workflows/gen-pinouts.yaml
misc/jenkins/generate_doxygen/gen_upload_docs.sh
misc/jenkins/generate_ibom/gen_upload_ibom.bat
misc/jenkins/generate_ibom/gen_upload_ibom.sh
misc/jenkins/generate_pinouts/gen_upload_pinouts.bat
misc/jenkins/generate_pinouts/gen_upload_pinouts.sh
misc/jenkins/setup/jobs/ibom/config.xml
misc/jenkins/setup/jobs/pinouts/config.xml

Notes:
- Jobs are set to run on push to master right now. Once it has run once I'll/We'll switch it back to once per day
- Split into 3 Jenkins jobs as well as 3 GHA workflows. I haven't tested the Jenkins jobs yet

Decouple Doxygen, IBOMs, and Pinouts

---

firmware/config/boards/hellen/hellen72/connectors/main.yaml

add info to Hellen Pin 4S

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

add cfg for lps25

---

.github/workflows/hardware-ci-proteus.yaml

Now there's a machine for this to run on!

add proteus hw ci yaml

---

java_console/autotest/src/com/rusefi/common/MiscTest.java
java_console/models/src/main/java/com/rusefi/core/Sensor.java

check that MCU temperature reading works

Hw ci mcu temperature

---

firmware/config/boards/hellen/cypress/OS/os/hal/ports/Cypress/S6E2CxAH/cypress_stm32.h
firmware/config/boards/kinetis/OS/os/hal/ports/KINETIS/KE1xF/kinetis_stm32.h
firmware/config/boards/subaru_eg33/config/controllers/algo/auto_generated_enums.cpp
firmware/config/boards/subaru_eg33/rusefi_hw_enums.h
firmware/controllers/algo/auto_generated_enums.cpp
firmware/controllers/algo/rusefi_hw_enums.h
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/ports/cypress/mpu_util.cpp
firmware/hw_layer/ports/kinetis/mpu_util.cpp
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp
firmware/hw_layer/ports/stm32/stm32_common.mk
firmware/hw_layer/ports/stm32/stm32f4/hw_ports.mk
firmware/hw_layer/ports/stm32/stm32f7/hw_ports.mk

get mcu temperature within port

---

misc/jenkins/generate_doxygen/gen_upload_docs.sh
misc/jenkins/generate_pinouts/gen_upload_pinouts.sh
misc/pinout-gen/append.sh
misc/pinout-gen/gen.sh
misc/pinout-gen/pinout.html
misc/pinout-gen/script.js
misc/pinout-gen/style.css

example: https://chuckwagoncomputing.com/pinouts/proteus/

Pinouts pages merged

---

.github/workflows/build-unit-tests.yaml

I'm not sure why this became necessary suddenly.

Check for different message as well

---

firmware/config/boards/microrusefi/board.mk
firmware/hw_layer/ports/stm32/stm32f4/cfg/chconf.h
firmware/hw_layer/ports/stm32/stm32f7/cfg/chconf.h
firmware/hw_layer/ports/stm32/stm32h7/cfg/chconf.h

For MRE:
This drops consumption from 0.18A@12V to 0.17A@12V.
Sorry, my lab DC power supply has 0.01A resolution.

RusEFI is green: put cpu in standby in idle

---

firmware/integration/rusefi_config.txt

added definitions for calibration table CLT x RPM limit

[WIP] RPM hard limit depending on CLT #455

---

firmware/bootloader/src/dfu.cpp
firmware/console/binary/bluetooth.cpp
firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_io.cpp
firmware/console/binary/tunerstudio_io.h

TS is madness, what if we used C++?

start making tunerstudio more sane: part 1

---

firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp

mayyyybe related to #2390 but a good thing to do anyway

don't cache mcu temp samples at all

---

.vscode/launch.json
.vscode/tasks.json

add build/debug configs for:
- Proteus/MRE F7
- Proteus H7
- hellen72

Vscode build/debug configs

---

firmware/config/boards/subaru_eg33/efifeatures.h
firmware/hw_layer/sensors/hip9011.cpp
firmware/hw_layer/sensors/hip9011.h
firmware/hw_layer/sensors/hip9011_logic.cpp
firmware/hw_layer/sensors/hip9011_logic.h
unit_tests/tests/test_hip9011.cpp

Looks like no one have been using this driver for a while.

hip9011 compilation fix, cosmetic clean-ups

---

firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h
firmware/util/timer.cpp
firmware/util/timer.h

#2025 is broken, trying smaller bites

virtual zero timer

---

firmware/controllers/trigger/trigger_decoder.cpp
firmware/controllers/trigger/trigger_decoder.h

#2025 is broken, trying smaller bites

trigger decoder timer

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h

use existing function getTimeSinceTriggerEvent

remove lastTriggerToothEventTimeNt

---

firmware/hw_layer/ports/stm32/stm32_adc_v4.cpp

H7 ADC was wrong by a ratio of 17/16, see code comment

fix h7 adc

---

.github/workflows/gen-configs.yaml

Checkout ramdisk images

---

.github/workflows/build-unit-tests.yaml

I *think* this should fix #2446. On the other hand I understand git poorly, so I don't have a good understanding of what issues doing it this way could cause.

Try pulling first

---

firmware/controllers/actuators/vvt.cpp
firmware/controllers/actuators/vvt.h
firmware/controllers/actuators/vvt_pid.cpp
firmware/controllers/actuators/vvt_pid.h
firmware/controllers/controllers.mk
firmware/controllers/engine_controller.cpp
firmware/hw_layer/hardware.cpp
unit_tests/tests/test_vvt.cpp
unit_tests/tests/tests.mk

Use common framework already used by ETB, boost, etc.

VVT uses closed loop controller framework

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/controllers/actuators/electronic_throttle_impl.h

makes ETB autotune a little easier to use

set 50% target for ETB autotune

---

firmware/controllers/actuators/vvt.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/sensors/sensor_info_printing.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/mass_storage/compressed_block_device.cpp
firmware/hw_layer/ports/stm32/stm32_adc_v2.cpp
firmware/hw_layer/sensors/cj125.cpp

dead code and warnings cleanup

minor dead code, warnings

---

firmware/console/binary/ts_can_channel.cpp
firmware/console/binary/tunerstudio.mk
firmware/console/binary/tunerstudio_io.cpp
firmware/console/binary/tunerstudio_io.h

extract the [unfinished] CAN channel implementation out in to its own TsChannelBase

extract CAN TS channel

---

firmware/console/status_loop.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/engine_parts.h
firmware/controllers/can/can_verbose.cpp
firmware/controllers/sensors/converters/table_func.h
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor_type.h
firmware/init/init.h
firmware/init/init.mk
firmware/init/sensor/init_fuel_level.cpp
firmware/init/sensor/init_sensors.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
firmware/util/datalogging.h
firmware/util/math/efi_ratio.h
unit_tests/tests/sensor/table_func.cpp
unit_tests/tests/tests.mk

Implement nonlinear fuel level sender

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/binary_log/binary_logging.cpp
firmware/console/status_loop.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_parts.h
firmware/controllers/algo/fuel_math.cpp
firmware/controllers/algo/fuel_math.h
firmware/controllers/can/obd2.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

#45
Adds gauges for "fuel flow rate" and "total fuel consumed"

Usable fuel consumption data/gauges

---

firmware/controllers/algo/engine.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/controllers/trigger/decoders/trigger_misc.cpp
firmware/controllers/trigger/decoders/trigger_misc.h
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/integration/rusefi_config.txt

barra vvt cam pattern

---

firmware/integration/rusefi_config.txt

looks like #2240 accidentally removed these lines, whoops!

fix afr table

---

firmware/console/status_loop.cpp
firmware/controllers/actuators/vvt.cpp
firmware/controllers/actuators/vvt.h
firmware/controllers/can/can_verbose.cpp
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h
unit_tests/tests/test_vvt.cpp
unit_tests/tests/trigger/test_cam_vvt_input.cpp
unit_tests/tests/trigger/test_quad_cam.cpp

VVT controller `N` reads the position from VVT sensor `N`.  This might actually enable the use of multiple VVT.

plumbing for multiple vvt

---

firmware/rusefi.cpp

init MMC a little later so H7 works properly, fixes #2494

Init order h7

---

.github/workflows/sync-wiki.yaml

I assume this works for "gollum", but I'm not actually sure.

Only run if actor is not actions-user

---

firmware/config/engines/dodge_neon.cpp
firmware/config/engines/ford_1995_inline_6.cpp
firmware/config/engines/ford_aspire.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt
unit_tests/tests/trigger/test_trigger_decoder.cpp

goodbye ignitionOffset

---

firmware/init/sensor/init_fuel_level.cpp

slow down fuel level sensor

---

firmware/hw_layer/microsecond_timer/microsecond_timer.cpp

we don't need to wait for 2*30 ms, just wait for a little over 10ms.

speed up boot by 48 ms

---

firmware/controllers/can/can.h
firmware/controllers/can/can_listener.h
firmware/controllers/can/can_rx.cpp
firmware/controllers/can/can_tx.cpp
firmware/controllers/sensors/can_sensor.h

helping make @OrchardPerformance's job easier implementing EGT-over-CAN

separate out "can listener" from "can sensor"

---

firmware/controllers/flash_main.cpp

maybe we can detect #2541 at erase time, since the normal failure mode of flash is that you can't erase it

check if flash erase failed

---

misc/pinout-gen/script.js
misc/pinout-gen/style.css

1. Hide the info table until a pin is clicked
2. Fix clicking on a table row (it was broken)
3. Scroll to the image when a table row is clicked

Fix pinout table

---

firmware/console/binary_log/binary_logging.cpp

remove duplicate SD log fields

---

firmware/hw_layer/mmc_card.cpp

flush SD log 10x faster

---

java_console/models/src/main/java/com/rusefi/composite/CompositeParser.java

Timestamp is an integer type for now, and sadly, but it overflows...
This is an attempt of temporary workaround for #1563

Workaround for logicdata timestamp overflow #1563

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio_commands.cpp
firmware/console/binary/tunerstudio_impl.h
firmware/util/loggingcentral.h

start killing LoggingWithStorage

logging cleanup 1

---

firmware/hw_layer/lcd/lcd_HD44780.cpp

This fixes bug introduced in 7803968621327af5fee34a4ceb4247c9d3ea4e1c
Sorry!

HD44780: start pins on init

---

firmware/controllers/can/can.h
firmware/controllers/can/can_dash.cpp
firmware/controllers/can/can_dash.h
firmware/controllers/can/can_tx.cpp
firmware/hw_layer/drivers/can/can_hw.cpp

update of canDash to support different cyclicity of messages
Breaking down and replacing #2570

Handle can message cyclicity

---

firmware/config/boards/microrusefi/connectors/main.yaml

Well it was simpler and stupider than I thought.
This should fix #2513

MRE reuse pins

---

.github/workflows/gen-pinouts.yaml

add option for manually running workflow

---

firmware/controllers/thread_priority.h

higher priority for log buffer flush

---

firmware/init/sensor/init_baro.cpp

obvious baro typo

---

firmware/controllers/lua/lua.cpp

With a destructor, we don't have to explicitly call `lua_close` whenever we think we're done.

encapsulate lua handle in smart pointer

---

firmware/controllers/lua/lua.cpp

Script can set how fast its own callback gets called.

Lua tick rate hook

---

firmware/console/status_loop.cpp
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h

-plus output messages re-formated

ADC: internalIndex should be used as getAvgAdcValue argument

---

firmware/config/engines/honda_600.cpp
firmware/controllers/algo/engine_configuration.cpp
firmware/controllers/algo/engine_configuration.h
firmware/controllers/settings.cpp

use setTable function

---

firmware/config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml

- all options have pin number
- no underscores in names
- normalize/harmonize names
- spelling

hellen na6 yaml tweaks

---

firmware/config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml

intMAP fix

---

firmware/hw_layer/sensors/hip9011.cpp
firmware/hw_layer/sensors/hip9011_logic.cpp
firmware/hw_layer/sensors/hip9011_logic.h

hip9011: add check for SPI reply in advanced mode
hip9011: read value over SPI in advanced mode

hip9011 update

---

firmware/CHANGELOG.md
firmware/controllers/algo/event_registry.h
firmware/controllers/engine_cycle/fuel_schedule.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp

use cylinder number instead of cylinder index
changelog addition of multi-closed-loop-fuel

Fix multi bank fueling

---

misc/www/s/wiki/index.shtml

rusefi.com/s/wiki
used by #2665

short link to wiki

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/binary_log/binary_logging.cpp
firmware/console/status_loop.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/math/engine_math.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

remove deprecated getEngineLoadT

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/controllers/actuators/idle_thread.cpp
firmware/tunerstudio/rusefi.input

#2585
Now there are two indicators:
- one for "coasting" vs "not coasting"
- one for "idling" vs "not idling"

idle indicators

---

firmware/hw_layer/sensors/lps25.h
firmware/hw_layer/smart_gpio.cpp
firmware/init/sensor/init_baro.cpp

also fixes broken TLE8888 master

don't expose private state

---

firmware/controllers/lua/lua.mk

fixes #2698 by not even compiling that file

don't build OS lib

---

firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_configuration.cpp

- sensible defaults
- bounds check

Post cranking fuel tweaks

---

firmware/hw_layer/ports/stm32/flash_int.c
firmware/hw_layer/ports/stm32/stm32f7/mpu_util.cpp

actually fix F7 flash this time

---

firmware/controllers/actuators/gppwm/gppwm_channel.cpp
firmware/controllers/algo/rusefi_enums.h
firmware/integration/rusefi_config.txt

@OrchardPerformance had a good idea

add pedal to gppwm

---

firmware/controllers/lua/lua_hooks.cpp

engine stop lua hook

---

firmware/controllers/algo/engine_configuration.h
firmware/hw_layer/drivers/can/can_hw.cpp

address "remove me" todo for old config override define

remove old config override

---

firmware/controllers/actuators/boost_control.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Add a config field for what to do in case of a sensor problem.

safe boost duty

---

firmware/controllers/actuators/electronic_throttle.cpp
unit_tests/tests/test_etb.cpp

require redundant pedal

---

firmware/controllers/actuators/idle_thread.cpp

this is just a code style change

most boring parts of idle stuff

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
unit_tests/tests/test_idle_controller.cpp

This test fails.
This test should pass.
#2745 probably fixes this test.

Idle test that fails

---

misc/pinout-gen/gen.sh
misc/pinout-gen/pinout.html
misc/pinout-gen/script.js

- Hide table columns that have no info
- Fix a generation error that I missed from last PR
- minor JS refactor

Hide empty pinout columns

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
unit_tests/tests/test_idle_controller.cpp

carve off a safe part part of #2745

iac coast table from IdleController::getOpenLoop

---

simulator/Makefile

don't include simulator debug info

---

firmware/controllers/actuators/fan_control.cpp
firmware/controllers/actuators/fan_control.h
firmware/controllers/algo/engine.cpp
firmware/controllers/controllers.mk
firmware/controllers/core/fsio_impl.cpp
firmware/controllers/system_fsio.h
firmware/controllers/system_fsio.txt
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_fan_control.cpp
unit_tests/tests/test_logic_expression.cpp
unit_tests/tests/tests.mk

Move logic for fans out of fsio, in to hard coded logic.  Simpler to instance, and simpler to manage as the fan logic is now more complex (enable fan with AC).

hard coded fan logic

---

firmware/config/boards/hellen/cypress/board_configuration.cpp
firmware/config/boards/kinetis/board_configuration.cpp
firmware/config/boards/prometheus/board_configuration.cpp
firmware/config/engines/dodge_neon.cpp
firmware/config/engines/dodge_ram.cpp
firmware/config/engines/ford_aspire.cpp
firmware/config/engines/ford_festiva.cpp
firmware/config/engines/honda_accord.cpp
firmware/config/engines/mazda_626.cpp
firmware/config/engines/mazda_miata_custom_hunchback.cpp
firmware/config/engines/mazda_miata_vvt.cpp
firmware/config/engines/mitsubishi.cpp
firmware/config/engines/subaru.cpp
firmware/controllers/algo/defaults/default_cranking.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/settings.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/trigger/test_trigger_decoder.cpp

this "feature" was the coil-burner 9000
goodbye, coil burner 9000

remove cranking dwell angle

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_etb.cpp

Rev limiter with electronic throttle.
implement #1535

Etb rev limit

---

misc/pinout-gen/script.js

1. Pin markers had some overlap in some cases
2. I accidentally removed the colored list fields when printed
3. I think I finally figured out a way to properly size the marker text when printed. fingers crossed.

Overdue pinouts fixes

---

firmware/config/boards/hellen/hellen121vag/connectors/main.yaml

to match the pattern used everywhere else

change digital_input to digital_inputs

---

unit_tests/test_basic_math/test_interpolation_3d.cpp

clean up 3d interpolation test

---

firmware/integration/rusefi_config.txt

more config cleanup: get rid of extra spaces

---

firmware/console/binary/tunerstudio_outputs.h
firmware/controllers/actuators/electronic_throttle_impl.h
firmware/controllers/gauges/malfunction_central.h
firmware/controllers/serial/serial_sensor.cpp
firmware/controllers/settings.cpp
firmware/hw_layer/digital_input/digital_input.h

typedef struct -> struct

---

firmware/rusefi.cpp
firmware/util/math/interpolation.cpp
firmware/util/math/interpolation.h

fix #440
fix #2865 
fix the underlying problem causing #2828

Check that table axes are ascending

---

firmware/controllers/actuators/dc_motors.cpp
firmware/controllers/system/dc_motor.cpp
firmware/controllers/system/dc_motor.h
firmware/controllers/system/timer/pwm_generator_logic.h

dc motor api

---

firmware/controllers/lua/lua.cpp
firmware/controllers/lua/lua_hooks.cpp
firmware/controllers/lua/lua_hooks.h

deinit lua pins when not used

---

firmware/controllers/algo/airmass/airmass.h
firmware/controllers/algo/airmass/alphan_airmass.cpp
firmware/controllers/algo/airmass/alphan_airmass.h
firmware/controllers/algo/airmass/maf_airmass.cpp
firmware/controllers/algo/airmass/maf_airmass.h
firmware/controllers/algo/airmass/speed_density_airmass.cpp
firmware/controllers/algo/airmass/speed_density_airmass.h
unit_tests/mocks.h
unit_tests/tests/ignition_injection/test_fuel_math.cpp

working on a new airmass mode that needs this to be not-const

not const getAirmass

---

firmware/controllers/actuators/boost_control.cpp
firmware/controllers/actuators/boost_control.h
firmware/controllers/actuators/gppwm/gppwm_channel.cpp
firmware/controllers/actuators/gppwm/gppwm_channel.h
firmware/controllers/system/dc_motor.h
unit_tests/mocks.h
unit_tests/tests/test_dc_motor.cpp
unit_tests/tests/test_gppwm.cpp
unit_tests/tests/tests.mk

should test dc_motor.cpp before #2870

test dc_motor.cpp

---

firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/actuators/idle_thread.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_idle_controller.cpp

Prevents problems on cars that can cruise at near idle speed.
fix #2812

Gate closed loop idle on road speed

---

unit_tests/tests/test_idle_controller.cpp

explicitly set mock vss to test

---

firmware/Makefile
firmware/hw_layer/ports/stm32/cfg/halconf_community.h
firmware/hw_layer/ports/stm32/cfg/mcuconf_community.h
firmware/hw_layer/ports/stm32/stm32f4/cfg/halconf.h
firmware/hw_layer/ports/stm32/stm32f4/cfg/mcuconf.h
firmware/hw_layer/ports/stm32/stm32f7/cfg/halconf.h
firmware/hw_layer/ports/stm32/stm32f7/cfg/mcuconf.h
firmware/hw_layer/ports/stm32/stm32h7/cfg/halconf.h
firmware/hw_layer/ports/stm32/stm32h7/cfg/mcuconf.h
firmware/rusefi.mk

Chibios-Contrib contains some useful stuff. Like HW CRC calculator driver for STM32.
Include it into build and add configs for STM32 chips

Chibios-Contrib for stm32

---

firmware/console/status_loop.cpp
firmware/controllers/algo/engine2.cpp
firmware/controllers/system/efi_gpio.cpp

- more plumbing
- read the config field to set offset

trailing coils

---

firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h
firmware/hw_layer/hardware.cpp
unit_tests/engine_test_helper.cpp

re: https://github.com/rusefi/rusefi/commit/70fd2337408b42754a95bafd70489f79ad6495bd#commitcomment-53285119

inject engine

---

firmware/controllers/engine_controller.cpp
firmware/controllers/sensors/sensor.cpp
firmware/controllers/system/efi_gpio.cpp

These were using precious RAM!

put names in flash

---

firmware/config/boards/hellen/hellen121nissan/board_configuration.cpp
firmware/config/boards/hellen/hellen121vag/board_configuration.cpp
firmware/config/boards/hellen/hellen128/board_configuration.cpp
firmware/config/boards/hellen/hellen72/board_configuration.cpp

fix hellen WBO override

---

firmware/controllers/can/rusefi_wideband.cpp

https://github.com/mck1117/wideband/issues/13

send wbo heater enable bit, read it on wb

---

firmware/config/boards/hellen/hellen128/connectors/main.yaml

Sensor pins

---

firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/trigger_decoder.cpp
unit_tests/tests/trigger/test_symmetrical_crank.cpp

fixes #2980
probably also fixes #2958

Fix prepareEventAngles for symmetrical crank triggers

---

.github/workflows/build-firmware.yaml
firmware/gen_config.sh
firmware/tunerstudio/rusefi.input

I missed the call to gen_config_board.sh in gen_config.sh, so when the gen configs workflow ran, it broke things.

Fix hellen128mercedes

---

firmware/hw_layer/ports/stm32/osc_detector.cpp
firmware/hw_layer/ports/stm32/stm32h7/cfg/mcuconf.h

osc detector on H7

---

firmware/rusefi.cpp

fix led init order

---

firmware/console/status_loop.cpp
firmware/controllers/system/efi_gpio.cpp
firmware/controllers/system/efi_gpio.h

force init LEDs even with fatal

---

firmware/hw_layer/ports/stm32/stm32_common.cpp

H7 turn off USB before reset

---

firmware/config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml

Rev B STM pin changes

---

firmware/config/boards/microrusefi/connectors/main.yaml
misc/pinout-gen/script.js

For this to work, a new 'id' field has been added to the yaml.

Pinout links

---

firmware/development/perf_trace.h
firmware/hw_layer/adc/adc_inputs.cpp
firmware/hw_layer/adc/adc_inputs.h
firmware/hw_layer/hardware.cpp

prep for making map sampling work on H7

fast adc callback

---

firmware/controllers/trigger/decoders/trigger_mazda.cpp
unit_tests/tests/trigger/test_real_nb2_cranking.cpp
unit_tests/tests/trigger/test_symmetrical_crank.cpp

A safer version of https://github.com/rusefi/rusefi/pull/3024

safer NB2 progress

---

.github/workflows/build-android.yaml
.github/workflows/build-firmware.yaml
.github/workflows/build-simulator.yaml
.github/workflows/build-tsplugin-body.yaml
.github/workflows/build-unit-tests.yaml
.github/workflows/gen-configs.yaml
.github/workflows/hardware-ci.yaml

so that maybe they fit in the UI, instead of being cut off so bad:

shorter CI names

---

.github/workflows/hardware-ci.yaml

maybe will help diagnose #3049 if/when it happens again

check for stlink with lsusb

---

.github/workflows/build-firmware.yaml
.github/workflows/build-simulator.yaml
.github/workflows/build-unit-tests.yaml
.github/workflows/hardware-ci.yaml

Please let CI finish on this PR before merging.

Try installing software explicitly

---

firmware/config/boards/hellen/cypress/chconf.h
firmware/config/boards/kinetis/chconf.h
firmware/config/boards/skeleton/efifeatures.h
firmware/config/stm32f4ems/efifeatures.h
firmware/hw_layer/ports/stm32/stm32f4/cfg/chconf.h
firmware/hw_layer/ports/stm32/stm32f7/cfg/chconf.h

Remove outdated option CH_DBG_ENABLE_TRACE

---

firmware/controllers/flash_main.cpp
firmware/hw_layer/flash_int.h
firmware/hw_layer/ports/stm32/flash_int.c

Still does not fix STM32F765 flash issue...

Int flash fixes

---

unit_tests/tests/sensor/test_flex_sensor.cpp
unit_tests/tests/tests.mk

Unit test for flex sensor.cpp by #3091 ticket

Unit test for flex sensor.cpp #3091

---

firmware/hw_layer/ports/stm32/stm32_common.cpp

dead weird define

---

firmware/config/engines/ford_1995_inline_6.cpp
firmware/hw_layer/digital_input/digital_input_icu.cpp
firmware/hw_layer/vehicle_speed.cpp

fix vss crash

---

firmware/controllers/actuators/electronic_throttle.cpp
unit_tests/tests/test_etb.cpp

skip etb init if no primary sensor

---

firmware/config/boards/hellen/hellen128/board_configuration.cpp
firmware/config/boards/hellen/hellen128/connectors/main.yaml

Updated battery sense and SD card configuration to comply with schematic.

Hellen128 default

---

firmware/hw_layer/ports/stm32/stm32f4/board.h
firmware/hw_layer/ports/stm32/stm32h7/board.h

everybody is pulldown

---

firmware/controllers/actuators/electronic_throttle.cpp

don't print the wrong number

---

firmware/controllers/flash_main.cpp
firmware/controllers/sensors/sensor.cpp
firmware/controllers/sensors/sensor.h
firmware/controllers/sensors/stored_value_sensor.h

inhibit sensor timeout during flash

---

firmware/config/boards/subaru_eg33/halconf.h
firmware/config/boards/subaru_eg33/mcuconf.h
firmware/controllers/flash_main.cpp
firmware/hw_layer/drivers/flash/hal_flash_device.c
firmware/hw_layer/drivers/flash/hal_flash_device.h

- ChibiOS updates related to QSPI
- Driver update
- Configuration update

qspi flash updates

---

firmware/controllers/core/fsio_impl.cpp
firmware/controllers/lua/lua.cpp

progress to #3174
- minor cleanup in lua.cpp
- save some fsio memory

lua & fsio cleanup

---

firmware/controllers/lua/lua.cpp

lua pass alloc and script

---

firmware/controllers/sensors/frequency_sensor.cpp
firmware/controllers/sensors/frequency_sensor.h
firmware/init/init.h
firmware/init/sensor/init_flex.cpp
firmware/init/sensor/init_sensors.cpp

#3152 
also will be helpful for #3148

change flex sensor at runtime

---

firmware/config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml

flex class change to event_inputs

flex input

---

firmware/hw_layer/adc/adc_inputs.cpp

missed a little bit

---

firmware/controllers/lua/lua.cpp

one allocator per heap, one heap per VM

multiple lua heaps

---

firmware/controllers/lua/lua_hooks.cpp
firmware/util/timer.cpp
firmware/util/timer.h
unit_tests/tests/lua/test_lua_hooks.cpp

depends on https://github.com/rusefi/luaaa/pull/1
#3159

lua timer is happy

---

firmware/controllers/lua/lua.cpp

Spin up a second VM for system lua functions.  It's pretty fast!

start system lua VM

---

unit_tests/unit_test_rules.mk

no asan on windows

---

firmware/controllers/can/can_verbose.cpp

add fuel flow rate
add total fuel consumed
add fuel trims 1/2
also replaces spaces -> tabs

more fuel info in verbose CAN

---

firmware/CHANGELOG.md
firmware/controllers/math/engine_math.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Dwell voltage correction

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/binary_log/binary_logging.cpp

per cylinder knock level in SD log

---

firmware/console/binary/tunerstudio_outputs.h
firmware/controllers/algo/engine2.cpp
firmware/controllers/algo/engine_state.h
firmware/controllers/sensors/software_knock.cpp
firmware/tunerstudio/rusefi.input
firmware/util/scaled_channel.h

count knock events over the knock threshold

Knock count

---

firmware/controllers/trigger/decoders/trigger_subaru.cpp

- sync on 3 gaps
- correct polarity (rising edges are the good VR edges)

fix 36-2-2-2

---

firmware/controllers/algo/engine.h
firmware/controllers/engine_cycle/knock_logic.cpp
firmware/controllers/engine_cycle/knock_logic.h
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/sensors/software_knock.cpp
firmware/hw_layer/sensors/hip9011.cpp

more knock sense unification

---

firmware/config/engines/sachs.cpp
firmware/controllers/engine_cycle/map_averaging.cpp
firmware/controllers/sensors/map.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

Unclear if anybody ever actually used this.

bye frequency map

---

firmware/tunerstudio/rusefi.input

use ego correction in VE analyze live

---

firmware/init/init.h
firmware/init/sensor/init_fluid_pressure.cpp
firmware/init/sensor/init_map.cpp
firmware/init/sensor/init_sensors.cpp

Reinit pressure sensors

---

firmware/controllers/engine_cycle/spark_logic.cpp
unit_tests/tests/ignition_injection/test_ignition_scheduling.cpp

Overdwell is urgently needed

---

.github/workflows/build-unit-tests.yaml

Fix GCOV upload

---

firmware/config/boards/proteus/connectors/black23.yaml

Is this what we're looking for in #3291?

Make Proteus B23P14 ground

---

firmware/console/eficonsole.cpp
java_console/autotest/src/main/java/com/rusefi/f4discovery/CommonFunctionalTest.java

check for overflow in HW CI

---

firmware/console/status_loop.cpp
firmware/controllers/engine_cycle/map_averaging.cpp
firmware/controllers/gauges/lcd_controller.cpp
firmware/controllers/sensors/map.cpp
firmware/controllers/sensors/map.h
firmware/integration/rusefi_config.txt
simulator/simulator/rusEfiFunctionalTest.cpp

code that's now dead due to #3292

dead code from MAP

---

firmware/tunerstudio/rusefi.input

Add clt/iat presets

---

firmware/tunerstudio/rusefi.input

Split boost dialogs

---

firmware/hw_layer/ports/stm32/stm32f7/STM32F7.ld

Linker file typo fix

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/engine.cpp
firmware/controllers/algo/engine.h
firmware/controllers/engine_cycle/knock_logic.cpp
firmware/controllers/engine_cycle/knock_logic.h
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/sensors/software_knock.cpp
firmware/hw_layer/sensors/hip9011.cpp
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_knock.cpp
unit_tests/tests/test_util.cpp
unit_tests/tests/tests.mk

finally actual progress on #202

Knock retard

---

firmware/controllers/algo/accel_enrichment.h
firmware/controllers/algo/airmass/speed_density_airmass.cpp
firmware/controllers/core/fsio_impl.h
firmware/controllers/sensors/converters/table_func.h
firmware/init/sensor/init_fuel_level.cpp
firmware/init/sensor/init_maf.cpp
firmware/integration/rusefi_config.txt
firmware/util/containers/table_helper.h
firmware/util/math/interpolation.h
firmware/util/scaled_channel.h
unit_tests/test_basic_math/test_interpolation_3d.cpp
unit_tests/tests/sensor/table_func.cpp

- Support mismatched row/column types
- Support row/column as `scaled_channel`
- Same change to interpolate2d
- Switch a few axes to autoscale

support autoscale on table axes

---

firmware/controllers/algo/engine.cpp
firmware/controllers/engine_cycle/rpm_calculator.cpp
firmware/controllers/trigger/trigger_central.cpp
firmware/controllers/trigger/trigger_central.h

extract engine phase function

---

firmware/util/containers/table_helper.h
firmware/util/math/interpolation.h

Remove some implicit C array to pointer conversions in Map3D by adding
(), *, and & where appropriate.  This allows us to remove getBinPtr.
Call interpolate3d from Map3d so there's no code duplication.

Create an interpolate3d function to match the interpolate2d, but for 3d tables.

---

firmware/hw_layer/mass_storage/create_ini_image.sh
firmware/hw_layer/mass_storage/create_ini_image_compressed.sh

I was getting disk full errors because I had two inis in a single zip.  Oops.

Remove correct file in create_ini_image.sh

---

firmware/controllers/trigger/decoders/trigger_structure.cpp

make master happy

---

firmware/controllers/actuators/electronic_throttle.cpp
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input
unit_tests/tests/test_etb.cpp

configurable etb maximum

---

firmware/console/binary/tunerstudio_outputs.h
firmware/console/status_loop.cpp
firmware/console/status_loop.h
firmware/controllers/trigger/trigger_central.cpp
firmware/tunerstudio/rusefi.input

log current engine phase on trigger teeth

---

firmware/tunerstudio/rusefi.input

Fix capitalization of subMenu for TS

---

firmware/config/boards/proteus/compile_proteus_f4.sh
firmware/config/boards/proteus/compile_proteus_f7.sh

disable openblt on proteus

---

java_tools/gcc_map_reader/src/main/java/rusefi/GccMapReader.java

I don't know why I'm having trouble compiling this, but I think gradle itself is crashing.

Track ram4 sections too.

---

firmware/console/binary/tunerstudio.cpp
firmware/console/binary/tunerstudio.h
unit_tests/mocks.cpp
unit_tests/mocks.h
unit_tests/tests/test_tunerstudio.cpp

test TS writes

---

firmware/controllers/core/state_sequence.cpp
firmware/controllers/core/state_sequence.h
firmware/controllers/system/timer/pwm_generator_logic.cpp
firmware/controllers/system/timer/pwm_generator_logic.h
firmware/controllers/trigger/decoders/trigger_structure.cpp
firmware/controllers/trigger/decoders/trigger_structure.h
firmware/controllers/trigger/trigger_emulator_algo.cpp
firmware/controllers/trigger/trigger_emulator_algo.h
firmware/controllers/trigger/trigger_simulator.cpp
unit_tests/tests/ignition_injection/test_fuel_map.cpp
unit_tests/tests/trigger/test_miata_na_tdc.cpp

We can them drop the field from a bunch of callers, simplifying the code.

Move phaseCount into MultiChannelStateSequence

---

firmware/controllers/lua/lua.cpp
unit_tests/tests/lua/test_lua_basic.cpp

load lua libs correctly

---

.github/workflows/build-unit-tests.yaml
.github/workflows/gen-configs.yaml
unit_tests/tests/sensor/test_turbocharger_speed_converter.cpp
unit_tests/tests/sensor/test_vehicle_speed_converter.cpp

Fix two cases that didn't affect the product, but did affect our ability to test.

Test for stack use after free in ASAN.

---

.github/workflows/build-unit-tests.yaml
firmware/controllers/actuators/idle_thread.cpp
firmware/controllers/system/efi_gpio.cpp
unit_tests/logicdata_csv_reader.h
unit_tests/tests/ignition_injection/test_fuel_map.cpp
unit_tests/tests/trigger/test_trigger_decoder.cpp
unit_tests/tests/trigger/test_trigger_multi_sync.cpp
unit_tests/unit_test_rules.mk

Fix the edge cases that pop up.

Use Valgrind to detect unitialized variable references.

---

firmware/controllers/core/engine_ptr.h
unit_tests/global.h

Remove a bunch of macros from engine_ptr.h

---

firmware/controllers/engine_cycle/spark_logic.cpp

Ignition callers are all tooth based, but aux valves calls it from both the microsecond timer and
the main initialization thread.  HPFP will also soon call it from both those places too.

Add a lock for scheduleOrQueue events.

---

firmware/controllers/algo/engine.h
firmware/controllers/engine_cycle/aux_valves.cpp
firmware/controllers/engine_cycle/main_trigger_callback.cpp
firmware/controllers/engine_cycle/spark_logic.cpp
firmware/controllers/engine_cycle/spark_logic.h
firmware/controllers/system/system.mk
firmware/controllers/system/timer/trigger_scheduler.cpp
firmware/controllers/system/timer/trigger_scheduler.h
unit_tests/engine_test_helper.cpp

It's a large enough entity that it shouldn't be buried in ignition logic.

Separate out scheduleOrQueue into it's own standalone scheduler.

---

firmware/controllers/can/can_verbose.cpp
firmware/hw_layer/drivers/can/can_msg_tx.h
firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

verbose CAN bits picker

---

.github/workflows/gen-configs.yaml

workflow adds generated live doc java

---

firmware/hw_layer/digital_input/trigger/trigger_input_adc.cpp
firmware/hw_layer/digital_input/trigger/trigger_input_adc.h

This is a part of PR already commited to the master. I don't understand the workflow... :(

proper trigger_input_adc (already in master)

---

firmware/hw_layer/ports/stm32/port_mpu_util.h
firmware/hw_layer/ports/stm32/stm32f4/mpu_util.cpp
firmware/hw_layer/ports/stm32/stm32f7/mpu_util.cpp
firmware/rusefi.cpp

testing stm32 stop/standby

---

firmware/controllers/algo/accel_enrichment.cpp
firmware/controllers/algo/accel_enrichment.h

Don't need separate `AccelEnrichment` class, since MAP AE is gone.

consolidate tps accel

---

firmware/hw_layer/drivers/can/can_hw.cpp
firmware/hw_layer/drivers/can/can_hw.h
firmware/hw_layer/ports/cypress/mpu_util.cpp
firmware/hw_layer/ports/kinetis/mpu_util.cpp
firmware/hw_layer/ports/mpu_util.h
firmware/hw_layer/ports/stm32/stm32_common.cpp

multi CAN plumbing

---

firmware/controllers/trigger/trigger_central.cpp
unit_tests/tests/trigger/test_map_cam.cpp

we need to check instant MAP, not averaged MAP
#3544

maybe more working MAP sampling

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

charge temperature estimation UI help

---

firmware/config/engines/GY6_139QMB.cpp
firmware/config/engines/ford_aspire.cpp
firmware/config/engines/honda_accord.cpp
firmware/controllers/algo/advance_map.cpp
firmware/controllers/algo/defaults/default_ignition.cpp
firmware/controllers/math/engine_math.cpp
firmware/controllers/settings.cpp
unit_tests/tests/ignition_injection/test_ignition_scheduling.cpp

on no planet are `setTimingLoadBin(1.2, 4.4);` reasonable timing axis defaults
tearing off a small piece of #3704

clean up timing table defaults

---

firmware/util/containers/table_helper.h
unit_tests/test_basic_math/test_interpolation_3d.cpp

tables support non-integer-scaled scaled_channel

---

firmware/console/binary/output_channels.txt
firmware/console/status_loop.cpp
firmware/controllers/sensors/AemXSeriesLambda.cpp
firmware/controllers/sensors/AemXSeriesLambda.h

- Log WB data as normal channels
- Log TPS 1/2 split et al as normal channels
- Convert many channels to SIGNED that should be signed.
#197

log channel improvements

---

firmware/util/containers/table_helper.h
unit_tests/test_basic_math/test_interpolation_3d.cpp

#3708 but for values as well
fix #3707 for real this time

Map3D accepts any scaled_channel type

---

firmware/integration/rusefi_config.txt
firmware/tunerstudio/rusefi.input

With no H-bridge and no special stepper IC

Add settings for Stepper driven by Push-Pull outputs

---

firmware/controllers/can/can_listener.h
firmware/controllers/sensors/AemXSeriesLambda.cpp
firmware/controllers/sensors/AemXSeriesLambda.h

Support both AEM X-Series, older rusEFI wideband firwmare, and newer rusEFI wideband firmware with better data format (more debug info!)
progress on #2953 and #3233

support better wbo format

---

firmware/hw_layer/ports/stm32/stm32f7/mpu_util.cpp

stm32_stop works. used NVIC to trigger wakeup. Will need revisiting for changing to Falling edge, or will require hardware changes for signal inversion.

Stop & wakeup working on rising edge

---

firmware/config/boards/hellen/alphax-2chan/connectors/main.yaml
firmware/config/boards/hellen_meta.h

Probably somehow depends on merging #3756 ? (both modify hellen_meta.h)

Alpha2ch yaml
